### ISSUE TITLE
ionic run android gives Property … does not exist on type ‘{ [key: string]: AbstractControl; }’

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic-app-scripts#100]
#### Short description of the problem:

I am having a form defined as the code below. `ionic serve` does fine, However when I compile my app using `ionic run android` I got the error:

`Property 'email' does not exist on type '{ [key: string]: AbstractControl; }'.`

Code:

```
constructor(

    fb: FormBuilder) {

    // this.recoverPasswordForm = fb.group({
    //     'email': [navParams.get('username') || '', Validators.compose([Validators.required, ValidatorService.email])]
    // });

    this.recoverPasswordForm = new FormGroup({
        email: new FormControl([navParams.get('username') || '', Validators.compose([Validators.required, ValidatorService.email])),
    });

}


recoverPassword() {

    this.account.recoverPassword(this.recoverPasswordForm.get('email').value).subscribe(res => {
```

#### What behavior are you expecting?

The same result when compiling with `ionic serve` and `ionic run android`

**Steps to reproduce:**
Use the code above in an app

**Which @ionic/app-scripts version are you using?**

2.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Also mentioned at: https://forum.ionicframework.com/t/property-does-not-exist-on-type-key-string-abstractcontrol/

**Comment by mhartington** [comment]
This is an actual error with your code and not the build. 
Since you were deploying to a device, we do production builds, which gets an extra layer of compilation. This means that an error will be pointed out, since the the build is much stricter.


You code needs to be fixed and updated.

**Comment by basvdijk** [comment]
Ok, didn't knew about the extra compilation. However I am still unable to release an APK because this error appeared since upgrading to RC0. Any thoughts on what could trigger this error?

**Comment by mhartington** [comment]
it appears to be the way you're trying to access the email property of your form.

A better approach would be to do this 

```
  public term: FormControl = this.formBuilder.control('', Validators.required);
  public form: FormGroup = this.formBuilder.group({
    'term': this.term,
    'filter': ['everything']
  });
```

**Comment by basvdijk** [comment]
Thanks! I've tried this and rewrote to:
```
        let control = fb.control('', Validators.required);

        this.recoverPasswordForm = fb.group({
            'email': control,
            'filter': ['everything']
        });
```

Unfortunately still getting the same error. Yesterday I've tried multiple variants for creating and accessing the form elements including with and without `FormBuilder`. But the error kept appearing.

**Comment by jgw96** [comment]
Hello, thanks for all the info. Since this is an error in your code and not an error on the ionic side of things I am going to close this issue for now, but i will urge that you ask about this on our [forum](https://forum.ionicframework.com/) as im sure someone on there will be able to help you further. Thanks!

**Comment by basvdijk** [comment]
Ok thanks! https://forum.ionicframework.com/t/property-does-not-exist-on-type-key-string-abstractcontrol/65783
