### ISSUE TITLE
version 0.0.29 doesn't generate all source files and components can't be debug

### ISSUE THREAD

**Issue by six006** [driftyco/ionic-app-scripts#101]
I still use ionic-conference-app-master project to test the building scripts .

1.npm uninstall @inoic/app-scripts --save-dev
2.npm install @inoic/app-scripts@latest --save-dev
3.ionic serve
4.the project has many ts files 
![3](https://cloud.githubusercontent.com/assets/5348170/19139107/614262e0-8bb4-11e6-81fd-d63648b7e46a.jpg)

5.but the main.js.map has only 6 source files mapping
![1](https://cloud.githubusercontent.com/assets/5348170/19139127/7792e498-8bb4-11e6-8bc8-46fc7ceb570a.jpg)

![2](https://cloud.githubusercontent.com/assets/5348170/19139133/807ac4d6-8bb4-11e6-9601-f3081cbddb31.jpg)

6.we can debug in  conference-data.ts
![4](https://cloud.githubusercontent.com/assets/5348170/19139166/bad71f08-8bb4-11e6-9093-d1846ce9f1e8.jpg)

7.but we can't set breakpoint and debug the page such as signup.ts
![6](https://cloud.githubusercontent.com/assets/5348170/19139226/4f57ac6a-8bb5-11e6-89a4-bb1ccc0449f4.jpg)

**Comment by six006** [comment]
I'm back to ionic2 beta11.

**Comment by six006** [comment]
npm uninstall -g ionic
npm install -g ionic@2.0.0-beta.37

**Comment by adamdbradley** [comment]
I see the issue and will start fixing it. Thanks

**Comment by jgw96** [comment]
Hello @six006 ! Thanks for all the info! We just released version 0.0.30 that fixes this issue, would you mind giving it a try? To update you can just run `npm install` in your app

**Comment by six006** [comment]
thanks for your hard work!
The file is all generated

**Comment by six006** [comment]
but the page which include @component still can't be dubug

**Comment by jgw96** [comment]
Hello! I am going to close this issue as we do generate source maps for all files now. We can continue to track the breakpoint issue on #110 Thanks!
