### ISSUE TITLE
Improvement : option to append our custom configs to the default one

### ISSUE THREAD

**Issue by TomDemulierChevret** [driftyco/ionic-app-scripts#103]
Currently we can provide our own custom configurations files to build steps like "copy".
The issue is that Ionic default config is completly overriden, which force us include its content in our custom config files.
Therefore our custom configs are dependant of the default ones, forcing us to updates them if Ionic changes the defaults files to copy during the build process.

Currently my package.json looks like this :

```
 "scripts": {
     "build": "ionic-app-scripts build",
     "watch": "ionic-app-scripts watch",
     "serve:before": "watch",
     "emulate:before": "build",
     "deploy:before": "build",
     "build:before": "build",
     "run:before": "build"
   },
   "config" : {
     "ionic_copy": "./config/copy.config.js"
   },
```

and the copy.config.js contains :

```
module.exports = {
  include: [
    {
      src: 'src/assets/',
      dest: 'www/assets/'
    },
    {
      src: 'src/index.html',
      dest: 'www/index.html'
    },
    {
      src: 'src/service-worker.js',
      dest: 'www/service-worker.js'
    },
    {
      src: 'node_modules/ionic-angular/polyfills/polyfills.js',
      dest: 'www/build/polyfills.js'
    },
    {
      src: 'node_modules/ionicons/dist/fonts/',
      dest: 'www/assets/fonts/'
    },
    {
      src: 'node_modules/chart.js/dist/Chart.bundle.js',
      dest: 'www/build/chart.js'
    },
  ]
};

```

Ideally the config file should only include :

```
    {
      src: 'node_modules/chart.js/dist/Chart.bundle.js',
      dest: 'www/build/chart.js'
    },
```

Then, we should add a flag (--copy-config-append ?) to the package.json to inform the copy script about this behaviour :

```
"build": "ionic-app-scripts build --copy-config-append",
"watch": "ionic-app-scripts watch --copy-config-append",
```

Another approach would be to use the "append" behaviour as the default one and instead provide a `--copy-config-force`flag to override entirelly the default config.

**Comment by Chris1308** [comment]
Hey,

this is already possible, just do this:

`const orgCopyConfig = require('@ionic/app-scripts/config/copy.config');


orgCopyConfig.include.push(
  {
    src: 'node_modules/chart.js/dist/Chart.bundle.js',
    dest: 'www/build/chart.js
  }
);

module.exports = orgCopyConfig;`

But a little more documentation on this would be nice. Maybe it comes later.

**Comment by TomDemulierChevret** [comment]
Indeed, should've thought about it.
Guess I need more morning coffee.  :)

One minor issue with this approach thought : you still rely on the path used by ionic-app-scripts for the default config.
If this file moves/disappears/changes (for exemple it could be dynamically populated by ionic during the build process), it will break our config file.

**Comment by royipressburger** [comment]
I think a better solution will be thats the script itself  will add the users changes. And not the other way around

**Comment by danbucholtz** [comment]
As @Chris1308 mentioned, you can already do this. We don't intend to support append functionality at this time.

Thanks,
Dan
