### ISSUE TITLE
Barrel stopped working after scripts update.

### ISSUE THREAD

**Issue by kleeb** [driftyco/ionic-app-scripts#105]
We are using Angular barrel for file imports, and as our project is already quite huge, we cannot totally refactor it.
It stopped working after yesterday's Adam's commit: https://github.com/driftyco/ionic-app-scripts/commit/556d2e37dd6b84154b224592751e5f50f9e2a309

and now we are getting:
`Error: Module .../ionic/src/app/index.ts does not export ComponentData (imported by .../src/components/module-components/module-component/module-component.ts)
    at Module.trace (.../node_modules/rollup/dist/rollup.js:7706:29)`

when I am switching back to the rollup conf, that contained ngTemplate() plugin, it works again.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you provide an example of the line that is causing this error?

**Comment by brettatoms** [comment]
@kleeb  s `ComponentData` an interface?  I had the same problem with interfaces that are never implemented getting stripped where I depended on them for type checking.

**Comment by kleeb** [comment]
Yes, ComponentData is an interface, that is put in the barrel.
However when I tried importing it straight, rollup was saying that it hasn't been exported.

**Comment by jgw96** [comment]
@kleeb Would you mind sharing a repo that we can use to reproduce this issue?

**Comment by kleeb** [comment]
@jgw96 will do my best to reproduce on some smaller piece of code and share it, will get back asap

**Comment by Manduro** [comment]
This is the same problem as mentioned by others in #64: interfaces that are used for type checking and are never implemented are removed, throwing an error. This is unrelated to barrels and also happens when importing directly.

**Comment by kleeb** [comment]
I cannot reproduce it on smaller project. 

From around 100 interfaces only 1 was causing problem.
I just changed it to become a class, and it fixed the issue.

Probably some inheritance and usage of those interfaces in some special way inside template is causing problems.

**Comment by anrip** [comment]
I had the same problem with interfaces that are never implemented getting stripped where I depended on them for type checking.

**Comment by Manduro** [comment]
Interesting update: @masatada mentions in the issue referenced above that it only occurs when using the interface to type an `@Input`. I can confirm that this is also the case with me.

So @jgw96 you should be able to reproduce this problem now. 

I'm setting the erroring `@Input` types to `any` for now.

**Comment by scunningham777** [comment]
I'm also seeing this with `@Inject`, so it's probably related to annotations in general.

**Comment by kleeb** [comment]
Look like its fixed with Ionic RC1 + Angular 2.1.0.

**Comment by Manduro** [comment]
Same here!
