### ISSUE TITLE
v.0.0.30 copy failed

### ISSUE THREAD

**Issue by six006** [driftyco/ionic-app-scripts#108]
I reinstalled the latest version 0.0.30 and run the command ionic serve it return the copy error:
```
 copy failed:  Error copying "src/assets/" to "www/assets/": Error: EPERM: operation not permitted, open 'h:\Javascript\Ionicframework\ionic-conference-app-master\www\assets\fonts\ionicons.eot',Error: EPERM: operation not permitted, open 'h:\Javascript\Ionicframework\ionic-conference-app-master\www\assets\fonts\ionicons.svg',Error: EPERM: operation not permitted, open 'h:\Javascript\Ionicframework\ionic-conference-app-master\www\assets\fonts\ionicons.ttf',Error: EPERM: operation not permitted, open 'h:\Javascript\Ionicframework\ionic-conference-app-master\www\assets\fonts\ionicons.woff',Error: EPERM: operation not permitted, open 'h:\Javascript\Ionicframework\ionic-conference-app-master\www\assets\fonts\ionicons.woff2'
```

![1](https://cloud.githubusercontent.com/assets/5348170/19162251/b35c5f34-8c29-11e6-9350-fdc060760be1.jpg)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! If im seeing correctly this is on a windows machine correct? Does this happen with a plain starter?

**Comment by six006** [comment]
1.update build script to 0.0.30 and run the command ```ionic serve``` the error happen
2 then use ```ionic build```  and the error is not disappear,
3.last run ``` ionic serve``` the service is start,but the page is show nothing
![1](https://cloud.githubusercontent.com/assets/5348170/19162609/1efb74a4-8c2b-11e6-8d2a-716cb491be04.jpg)

**Comment by jgw96** [comment]
Awesome, thanks for the repro steps. Is this happening on a windows machine or a linux/osx machine?  Also, does this happen with a plain starter?

**Comment by six006** [comment]
windows 10

**Comment by six006** [comment]
still using ionic-conference-app project for testing

**Comment by six006** [comment]
I download the latest  ionic-conference-app project from https://github.com/driftyco/ionic-conference-app and then run ```ionic serve``` the error is not happened,and can be displayed .
![1](https://cloud.githubusercontent.com/assets/5348170/19163265/dcf8662c-8c2d-11e6-8d9a-3a33c273d2ab.jpg)

Thank you for your help!

But the page is still can't debug such as signup.ts

**Comment by jgw96** [comment]
Thanks for testing. I am going to close this issue and track the debug issue in https://github.com/driftyco/ionic-app-scripts/issues/110. Thanks!
