### ISSUE TITLE
Version 0.0.30 components can't be debug bug 

### ISSUE THREAD

**Issue by six006** [driftyco/ionic-app-scripts#110]
The page can't be debug,
![1](https://cloud.githubusercontent.com/assets/5348170/19163457/9b5c204a-8c2e-11e6-851c-e5b5ac8f6ea6.jpg)

**Comment by mhartington** [comment]
@six006 please do not delete the issue template.  Update your issue with the issue template and the info for it.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind giving a little more info on what exactly is happening here? I was able to put in breakpoints fine in my testing apps.

**Comment by Kobzol** [comment]
Putting breakpoints in [Php|Web]Storm for typescript files doesn't work out of the box (at least I wasn't able to get it working through the whole Ionic 2 beta - if it can be done, please let me know :-)) - it doesn't synchronize with Chrome by itself. Try putting the breakpoints directly in the Chrome sources.

**Comment by six006** [comment]
![1](https://cloud.githubusercontent.com/assets/5348170/19164326/1172d168-8c32-11e6-9b26-3faf1a2ce6ab.gif)

**Comment by six006** [comment]
Thanks ,It can be debug all *.ts files by chrome debugger plugin for vscode,but can't be debug in chrome browser !
![1](https://cloud.githubusercontent.com/assets/5348170/19165274/c00de4c6-8c35-11e6-8553-8d7bb41002f0.jpg)

**Comment by jgw96** [comment]
Thanks! So im getting closer to figuring out what is going on here, breakpoints are working, but the line numbers seem to be "wonky". If i put a breakpoint on two different methods in my test project, click a button to call that method the breakpoint, the debugger stops on a breakpoint, but seems to be stopping on the wrong one.

**Comment by Kobzol** [comment]
I recently noticed that ts sourcemaps were behaving weirdly in Chrome. It's a long shot, but try it with `Disable cache: on` in Developer Network panel.

**Comment by cleever** [comment]
@Kobzol Disable cache is always on in my environment. So, isn't that. 
In the previous ionic (2.0.0-beta.11) in the same Chrome version, sourcemaps debugging is working very well.

**Comment by marcocarosi** [comment]
I guess this is the right thread concerning the issue with sourcemaps causing typescript breakpoints working weirdly, and step-by-step sometimes jumping to the js bundle.

I am experiencing the same, and this is the setup I am using:
- app-scripts upgraded to the latest ( `@ionic/app-scripts@0.0.30` )
- visual studio code, (using Cordova Tools extension)
- emulated iOS over Mac OS X (Xcode 7.3.1)

Various folks have posted this issue in other threads (https://github.com/driftyco/ionic-app-scripts/issues/32 and https://github.com/driftyco/ionic/issues/8292).

Again, with ionic framework beta breakpoints were working flawlessly using the same setup.

**Comment by jmesa-sistel** [comment]
I have tested pull request [126](https://github.com/driftyco/ionic-app-scripts/pull/126/) and now I can debug properly.

Please merge it for the next version

**Comment by jmesa-sistel** [comment]
To be able to debug on device we need that 
- Merge pull request [126](https://github.com/driftyco/ionic-app-scripts/pull/126/)
- "ionic run android -l" generate a dev build , start the live reload server and start the watch process.

Thanks

At now I have to do to much tricks to get it working:
ionic run android -l
In another console:
ionic serve -p 1234 -r 1235

Close android app and restart the app
Now I can debug and when I change the code the live reload works fine.

**Comment by jgw96** [comment]
With the latest master i can happily report that this has been fixed! Breakpoint line numbers now line up exactly like they should. Thanks everyone!

**Comment by jmesa-sistel** [comment]
Are you sure?
I have created a new project: ionic start MyIonic2Project tutorial --v2
Then I download and compiled the last master ionic-app-scripts
Copy folders bin, config & dist from compiled last ionic-app-scripts to C:\Web\MyIonic2Project\node_modules\@ionic\app-scripts
Execute: ionic serve
I have the next error:
```
unable to find C:\Web\MyIonic2Project\src\app\main.dev.ts
(node:5372) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not resolve './app.module' from C:\Web\MyIonic2Project\src\app\main.dev.ts
```

**Comment by jmesa-sistel** [comment]
Finally I can debug with latest version!!!
