### ISSUE TITLE
Convert everything from CommonJS to ES

### ISSUE THREAD

**Issue by DeeM297** [driftyco/ionic-app-scripts#111]
#### Short description of the problem:
I have a project where I've configured angularfire2, redux, redux-thunk and font-awesome. At the moment, I'm able to run with ionic serve but cannot build on device. I'm having different type of build errors. 

The error changes according to the _rollup.config.js_

#### What behavior are you expecting?
Is it the right thing to do to insert this line in _rollup.config_ in order to convert all CommonJS to ES?

```
commonjs({
        include: ['node_modules/**']
})
```

I don't know which build errors I should be dealing with.

**Which @ionic/app-scripts version are you using?**
"@ionic/app-scripts": "^0.0.23"

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
[stackoverflow: Rollup and Redux: “index.js does not export default”](http://stackoverflow.com/questions/39820455/rollup-and-redux-index-js-does-not-export-default/39832029?)

**Comment by danbucholtz** [comment]
What is the error output when you run `npm run build`?

Thanks,
Dan

**Comment by DeeM297** [comment]
Thanks for your quick reply Dan. So, here I'm using _rollup.config.js_ with this config:

> commonjs({
>         include: ['node_modules/**']
> })

> [21:14:29]  lint finished in 6.97 s
> [21:14:37]  ngc error: TypeError: Cannot read property 'kind' of undefined
>     at maybeGetSimpleFunction (c:\XXX\node_modules\@angular\tsc-wrapped\src\collector.js:34:41)
>     at c:\XXX\node_modules\@angular\tsc-wrapped\src\collector.js:242:41
>     at visitEachNode (c:\XXX\node_modules\typescript\lib\typescript.js:8251:30)
>     at Object.forEachChild (c:\XXX\node_modules\typescript\lib\typescript.js:8411:24)
>     at MetadataCollector.getMetadata (c:\XXX\node_modules\@angular\tsc-wrapped\src\collector.js:204:12)
>     at ReflectorHost.getMetadataFor (c:\XXX\node_modules\@angular\compiler-cli\src\reflector_host.js:224:43)
>     at StaticReflector.getModuleMetadata (c:\XXX\node_modules\@angular\compiler-cli\src\static_reflector.js:484:40)
>     at CodeGenerator.readFileMetadata (c:\XXX\node_modules\@angular\compiler-cli\src\codegen.js:36:51)
>     at c:\XXX\node_modules\@angular\compiler-cli\src\codegen.js:100:74
>     at Array.map (native)
> 
> [21:14:37]  ngc error: Compilation failed
> 
> [21:14:37]
> [21:14:37]  bundle prod started ...
> [21:14:38]  Error: Could not resolve entry (.tmp/app/main.prod.js)
>     at c:\XXX\node_modules\rollup\dist\rollup.js:8602:28
>     at process._tickCallback (node.js:368:9)
> [21:14:38]  sass started ...
> [21:14:43]  sass finished in 4.43 s
> [21:14:43]  minify started ...
> [21:14:43]  cleancss started ...
> [21:14:43]  uglifyjs started ...
> [21:14:43]  Error: ENOENT: no such file or directory, open 'c:\XXX\www\build\main.js'
>     at Error (native)
>     at Object.fs.openSync (fs.js:549:18)
>     at Object.fs.readFileSync (fs.js:397:15)
>     at addFile (c:\XXX\node_modules\uglify-js\tools\node.js:68:22)
>     at c:\XXX\node_modules\uglify-js\tools\node.js:79:17
>     at Array.forEach (native)
>     at Object.exports.minify (c:\XXX\node_modules\uglify-js\tools\node.js:77:26)
>     at runUglifyInternal (c:\XXX\node_modules\@ionic\app-scripts\dist\uglifyjs.js:34:19)
>     at runUglify (c:\XXX\node_modules\@ionic\app-scripts\dist\uglifyjs.js:23:28)
>     at Object.uglifyjs (c:\XXX\node_modules\@ionic\app-scripts\dist\uglifyjs.js:9:12)
> [21:14:44]  cleancss finished in 1.56 s
> [21:14:44]  minify finished in 1.56 s
> [21:14:44]  build prod finished in 22.38 s

**Comment by danbucholtz** [comment]
We need to update your `@ionic/app-scripts` to the latest.

Please run:
```
npm install @ionic/app-scripts@latest
```

Then run `npm run build` again.

Please post the output again.

Thanks,
Dan

**Comment by DeeM297** [comment]
This is the new output I'm getting. Do you need the npm-debug.log?

> [00:04:05]  lint finished in 1.64 s
> [00:04:07]  ngc: TypeError: Cannot read property 'kind' of undefined
>     at maybeGetSimpleFunction (c:\XXX\node_modules\@angular\tsc-wrapped\src\collector.js:34:41)
>     at c:\XXX\node_modules\@angular\tsc-wrapped\src\collector.js:242:41
>     at visitEachNode (c:\XXX\node_modules\typescript\lib\typescript.js:8251:30)
>     at Object.forEachChild (c:\XXX\node_modules\typescript\lib\typescript.js:8411:24)
>     at MetadataCollector.getMetadata (c:\XXX\node_modules\@angular\tsc-wrapped\src\collector.js:204:12)
>     at ReflectorHost.getMetadataFor (c:\XXX\node_modules\@angular\compiler-cli\src\reflector_host.js:224:43)
>     at StaticReflector.getModuleMetadata (c:\XXX\node_modules\@angular\compiler-cli\src\static_reflector.js:484:40)
>     at CodeGenerator.readFileMetadata (c:\XXX\node_modules\@angular\compiler-cli\src\codegen.js:36:51)
>     at c:\XXX\node_modules\@angular\compiler-cli\src\codegen.js:100:74
>     at Array.map (native)
> 
> [00:04:07]  ngc: Compilation failed
> 
> [00:04:07]  ngc failed:  NGC encountered an error
> [00:04:07]  Error: NGC encountered an error
>     at ChildProcess.<anonymous> (c:\XXX\node_modules\@ionic\app-scripts\dist\ngc.js:62:24)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at ChildProcess.cp.emit (c:\XXX\node_modules\cross-spawn\lib\enoent.js:40:29)
>     at maybeClose (internal/child_process.js:821:16)
>     at Socket.<anonymous> (internal/child_process.js:319:11)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at Pipe._onclose (net.js:469:12)
> Error running ionic app script "build": Error: NGC encountered an error
> 
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.8.2
> npm ERR! code ELIFECYCLE
> npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ionic-app-scripts build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs ionic-hello-world
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls ionic-hello-world
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     c:\XXX\npm-debug.log

**Comment by danbucholtz** [comment]
Are you providing a custom rollup config? Go ahead and remove the line importing the `ng-template` module. It's in the changelog but we didn't do a good job of socializing that.

```
Cannot find module '../dist/plugi
ns/ng-template'
```

Thanks,
Dan

**Comment by DeeM297** [comment]
I've tried to reproduce the error in a minimum project with redux and redux-thunk. Should I push the project on git?
These are the steps I'm taking from a new tab starter project:

**Here are the steps I'm doing to install _redux_ & _redux-thunk_ in the starter tab project.**
`npm i redux redux-thunk --save`
`npm install @types/request@0.0.30 --save-dev --save-exact` (I'm using 0.0.30 because of AngularFire2)
`npm i @types/redux @types/redux-thunk --save`

**Changes to the starter project**
1) In **app.module.ts**, just before @NgModule
```
//Redux - ReduxThunk - rootReducer
import { createStore, applyMiddleware } from 'redux';
import ReduxThunk  from 'redux-thunk';
import rootReducer from '../modules/rootReducer';

const appStore = createStore(
    rootReducer,
    applyMiddleware(ReduxThunk)
);
```
And adding this in the providers array:
```
providers: [
    { provide: 'AppStore', useValue: appStore }
]
```

2) I'm creating a module folder with two files: increment-reducer.ts and rootReducer.ts
**In increment-reducer.ts** 
```
import { Action } from 'redux'

const initialState = {
	counter: 0
}

export default function (state = initialState, action: Action) {
	switch (action.type) { 
		case 'INCREMENT':
			let newState = Object.assign({}, state);
			newState.counter++;
			return newState;
		default:
			break;		
	}
	return state;
}
```
**In rootReducer.ts**
```
import { combineReducers, Reducer } from 'redux'
import increment from './increment-reducer'

export default combineReducers({
  increment
})
```
3) Final changes in home.ts and home.html
**In home.html**
```
<!-- TEST FOR REDUX -->
<button ion-button (click)="testRedux()">
	Increment
</button>
```
**In home.ts**
```
constructor(
    public navCtrl: NavController,
    @Inject('AppStore') public appStore: any
    ) { }

  testRedux(){
        console.log(this.appStore.getState().increment.counter);
        this.appStore.dispatch((dispatch)=> {
            dispatch({type: 'INCREMENT'});});
        console.log(this.appStore.getState().increment.counter);
    }
```
And import _inject_ in home.ts
`import { Inject, Component } from '@angular/core';`

**Comment by DeeM297** [comment]
I can run the project with ionic serve but it fails with `npm run build`. This is the error log.

> [15:12:08]  lint finished in 1.17 s
> [15:12:11]  ngc: TypeError: Cannot read property 'kind' of undefined
>     at maybeGetSimpleFunction (c:\Ionic\Redux Test rc0\node_modules\@angular\tsc-wrapped\src\collector.js:34:41)
>     at c:\Ionic\Redux Test rc0\node_modules\@angular\tsc-wrapped\src\collector.js:242:41
>     at visitEachNode (c:\Ionic\Redux Test rc0\node_modules\typescript\lib\typescript.js:8251:30)
>     at Object.forEachChild (c:\Ionic\Redux Test rc0\node_modules\typescript\lib\typescript.js:8411:24)
>     at MetadataCollector.getMetadata (c:\Ionic\Redux Test rc0\node_modules\@angular\tsc-wrapped\src\collector.js:204:12)
>     at ReflectorHost.getMetadataFor (c:\Ionic\Redux Test rc0\node_modules\@angular\compiler-cli\src\reflector_host.js:224:43)
>     at StaticReflector.getModuleMetadata (c:\Ionic\Redux Test rc0\node_modules\@angular\compiler-cli\src\static_reflector.js:484:40)
>     at CodeGenerator.readFileMetadata (c:\Ionic\Redux Test rc0\node_modules\@angular\compiler-cli\src\codegen.js:36:51)
>     at c:\Ionic\Redux Test rc0\node_modules\@angular\compiler-cli\src\codegen.js:100:74
>     at Array.map (native)
> 
> [15:12:11]  ngc: Compilation failed
> 
> [15:12:11]  ngc failed:  NGC encountered an error
> [15:12:11]  Error: NGC encountered an error
>     at ChildProcess.<anonymous> (c:\Ionic\Redux Test rc0\node_modules\@ionic\app-scripts\dist\ngc.js:62:24)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at ChildProcess.cp.emit (c:\Ionic\Redux Test rc0\node_modules\cross-spawn\lib\enoent.js:40:29)
>     at maybeClose (internal/child_process.js:821:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> Error running ionic app script "build": Error: NGC encountered an error
> 
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.8.2
> npm ERR! code ELIFECYCLE
> npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ionic-app-scripts build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs ionic-hello-world
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls ionic-hello-world
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     c:\Ionic\Redux Test rc0\npm-debug.log

**Comment by danbucholtz** [comment]
@DeeM297, That is an `ngc` error, I'm not sure what's going on. If you make a very simple repo to reproduce it I'll run it and verify.

Thanks,
Dan

**Comment by DeeM297** [comment]
I've just pushed the starter project with redux/redux-thunk to git. 
`git clone https://github.com/DeeM297/ionic-redux-test.git`

Does that help?

**Comment by danbucholtz** [comment]
I helped @DeeM297 offline on slack. It's an issue with calling a Redux function to initialize something than trying to make it injectable. I advised to look into how Rob is doing it with ngrx.

I'm going to close this now.

Thanks,
Dan
