### ISSUE TITLE
Multiple Components in same file

### ISSUE THREAD

**Issue by herbzi** [driftyco/ionic-app-scripts#115]
Hi, I have several small Modal components defined in the same .ts file, this works fine in 0.0.23. but when I upgraded to 0.0.30 I noticed that any components after the first one are not getting template inlined etc. The src remains templateUrl: "home-modal.html" and the app fails to load the template. 

I was just wondering if this is expected behaviour. I can just separate these into individual files if need be.

**Comment by adamdbradley** [comment]
No this is a bug, we'll get it fixed up in the next release. Thanks for creating the issue.
