### ISSUE TITLE
Can't use custom config file with v0.0.29 and newer

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic-app-scripts#116]
#### Short description of the problem:
I use a custom config file for PouchDB compatibility. It works in `0.0.27` and `0.0.28`. When in `0.0.29` or newer this error is printed : 
> Config file "/Users/******/Documents/IonicProjects/Metho/config/rollup.config.js" not found. Using defaults instead.
(replace the * with my username)
But the config file is there as it's working for older versions.
#### What behavior are you expecting?
The config file to be used

**Steps to reproduce:**
1. Provide a config file to `@ionic/app-scripts@0.0.29`
2. `ionic serve`

**Which @ionic/app-scripts version are you using?**
0.0.28 (working), newer (broken)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! You should be getting a warning message in the output that tells you the small change that 0.0.29 and up requires to custom rollup.config files. The `entry` property of the rollup.config file should now be `'src/app/main.dev.ts'`. Can you give that change a try and see if it fixes it for you? Thanks!

**Comment by OnnoGeorg** [comment]
I got the same error. The change in `entry` was not enough, so I restarted with a fresh  file from `node_modules/@ionic/app-scripts/config/rollup.config.js` (as proposed in the [docs](http://ionicframework.com/docs/v2/resources/app-scripts/)) and just inserted the PouchDB namedExports:

My `rollup.config.js`:

`var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var globals = require('rollup-plugin-node-globals');
var builtins = require('rollup-plugin-node-builtins');
var json = require('rollup-plugin-json');

var rollupConfig = {
  entry: 'src/app/main.dev.ts',
  sourceMap: true,
  format: 'iife',
  dest: 'main.js',
  plugins: [
    builtins(),
    commonjs({
      namedExports: {
        // pouchdb
        'node_modules/js-extend/extend.js': ['extend'],
      }
    }),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    }),
    globals(),
    json()
  ]
};

if (process.env.IONIC_ENV == 'prod') {
  // production mode
  rollupConfig.entry = '{{TMP}}/app/main.prod.ts';
  rollupConfig.sourceMap = false;
}

module.exports = rollupConfig;`

**Comment by rapropos** [comment]
That error is somewhat misleading, but rollup treats any syntax errors triggered by attempting to evaluate the config file as if the file was not found, so look up for earlier root causes.

**Comment by Bouzmine** [comment]
@jgw96 I found the cause. My Rollup script was importing `ngTemplate` and it isn't available in `0.0.29` and newer. Once I fixed that issue, it prompted me with the error saying to use `src/app/main.dev.ts`
