### ISSUE TITLE
Build is not outputting HTML files

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic-app-scripts#117]
#### Short description of the problem:
Running any of the build commands does not output HTML files. This issue occurred to me before but then somehow it got fixed. Now I'm getting the same issue again after updating to latest version of `ionic-app-scripts`. I tried downgrading back to `0.0.27` but that's not helping.

Creating a fresh project results in the same problem.

I also tried spinning up a fresh Ubuntu container and I had the same problem there.

`www/build` contains only the following files:
```
main.css  main.js  main.js.map  polyfills.js
```

**Steps to reproduce:**
1. Create a new project
2. Run `npm run build` or `npm run build --dev`

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0-beta.3 (tried with latest stable and beta, no difference)
Ionic App Lib Version: 2.1.0-beta.1 (tried with latest stable and beta, no difference)
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v6.7.0
```

**Comment by DominikTrenz** [comment]
I'm having the same Problem. Only inline templates are in the main.js and no html files are copied.
For example:
`LoginPage = __decorate$114([
        Component({
            templateUrl: 'login.html',
        }), 
        __metadata$8('design:paramtypes', [(typeof (_a = typeof TranslateService !== 'undefined' && TranslateService) === 'function' && _a) || Object, (typeof (_b = typeof NavParams !== 'undefined' && NavParams) === 'function' && _b) || Object])
    ], LoginPage);
    return LoginPage;`

But login.html is not copied and not inlined

**Comment by jgw96** [comment]
Hello all! Thanks for using Ionic! @DominikTrenz Do you have multiple components in the same file? If so then we are addressing this issue here #115 .

**Comment by ihadeed** [comment]
@danbucholtz yeah that was it.. didn't realise the templates were inlined. Thanks!
