### ISSUE TITLE
rollup@0.36.1 

### ISSUE THREAD

**Issue by tmvnk** [driftyco/ionic-app-scripts#118]
0.0.23 and higher 

[16:38:16]  lint finished in 616 ms
[16:38:20]  bundle dev failed:  Unexpected character '@' (8:0) in /Users/Tom/dev/MyApp/src/pages/login/login.js

[16:38:20]  SyntaxError: Unexpected character '@' (8:0) in /Users/Tom/dev/MyApp/src/pages/login/login.js
    at Parser.pp$4.raise (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:4070:13)
    at Parser.pp$7.getTokenFromCode (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:4609:8)
    at Parser.pp$7.readToken (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:4330:15)
    at Parser.pp$7.nextToken (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:4321:13)
    at Parser.pp$7.next (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:4266:8)
    at Parser.pp.eat (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:2200:10)
    at Parser.pp.semicolon (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:2245:13)
    at Parser.pp$1.parseImport (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:2996:8)
    at Parser.pp$1.parseStatement (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:2409:44)
    at Parser.pp$1.parseTopLevel (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:2313:23)

  "devDependencies": {
    "@ionic/app-scripts": "0.0.23",
    "typescript": "^2.0.3"
  },

{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowJs": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": true,
  "atom": {
    "rewriteTsconfig": false
  }
}

**Comment by danbucholtz** [comment]
Can you paste your login.ts and corresponding template here?

Thanks,
Dan

**Comment by tmvnk** [comment]
It's a JS file. 
I'm using TS but also JS files.

import {NavController,AlertController,ToastController} from 'ionic-angular';
import {Component} from '@angular/core';
import {TabsPage} from '../tabs/tabs';
import {SignupPage} from '../signup/signup';
import {UserData} from '../../providers/user-data';


@Component({
  selector: 'page-login',
  templateUrl: 'login.html'
})
export class LoginPage {
  static get parameters() {
    return [[NavController], [UserData],[AlertController],[ToastController]];
  }

  constructor(nav, userData, alertCtrl, toastCtrl) {
    this.nav = nav;
    this.userData = userData;
    this.alertCtrl = alertCtrl;
    this.toastCtrl = toastCtrl;

    this.login = {
      password: '',
      email: '',
      username: ''
    };

    this.submitted = false;
  }

  onLogin(form) {
    console.log(form.value.email);
    console.log(form);
    this.submitted = true;

    if (form.valid) {
      this.userData.login(form.value).then((resp)=>{
       if(resp.status == 'ok' || resp.status == 'success'){
        // toast message is send via app.js
        this.nav.setRoot(TabsPage);
      }else if(resp.status == 'error'){
        this.messageToast('A error has occured. Please check your login credentials and try again.')
      }else{
        this.messageToast('A error has occured. Please try again later.')
      }
    });

    }
  }

  onSignup() {
    this.nav.push(SignupPage);
  }

  onForgotPassword() {
    let alert = this.alertCtrl.create({
    title: 'Reset Password',
    subTitle: 'We will send instructions to your email address.',
    inputs: [
    {
      name: 'email',
      placeholder: 'your email address',
      value: ''
    }
    ],
    buttons: [
    {
      text: 'Cancel',
      role: 'cancel',
      handler: data => {
        console.log('Cancel clicked');
      }
    },
    {
      text: 'Send',
      handler: data => {
        let email = data.email;

        if(this.emailValidator(email)){
          this.requestReset(email);
          console.log('email ok')
          return true
        }else{
          this.messageToast('Please enter a valid email.');
          console.log('email invalid')
          return false
        }
      }
    },
    ]
  });
    //open alert
    alert.present();

  }

  emailValidator(value) {
    var EMAIL_REGEXP = /^[a-z0-9!#$%&'*+\/=?^_`{|}~.-]+@[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/i;
    if (!EMAIL_REGEXP.test(value)) {
      return false;
    }else{
      return true;
    }
  }

  requestReset(email){
   this.login = {};
   // send request and handle response
   this.userData.forgot(email).then((resp) => {
    if(resp.status == 'ok'){
      this.messageToast('A reset link is send to ' + email)
    }else if(resp.status == 'error'){
      this.messageToast('A error has occured. Please check your email and try again.')
    }else{
      this.messageToast('A error has occured. Please try again later.')
    }
  });
 };

 messageToast(message,duration,timeout){

  if(duration === undefined){
    var duration = 5000;
  }

  let toast = this.toastCtrl.create({
    message: message,
    duration: duration
  });

  toast.onDidDismiss(() => {
    console.log('Dismissed toast');
  });

  if(timeout){
    setTimeout(() => {
      toast.present();
    }, 300);
  }else{
    toast.present();
  };

}


// class end
}

**Comment by danbucholtz** [comment]
Can you install the latest `@ionic/app-scripts`?

```
npm install @ionic/app-scripts@latest
```

Thanks,
Dan

**Comment by tmvnk** [comment]
Sorry. I actually get this error with latest. 
It worked up to 0.0.27

**Comment by adamdbradley** [comment]
I think this is because of the update to use typescripts `ts.transpileModule` method. However, I'm rewriting it right now to use `ts.createProgram` instead which will take into account all TS files.

**Comment by tmvnk** [comment]
It would be nice if I could use login.js instead of login.ts. Especially when using typescript support in Atom, to avoid ts checking in js code.

**Comment by tmvnk** [comment]
https://github.com/tmvnk/ionic2/tree/ionic_script_unexpected-character
hereby an example where I have changed the login.js to Javascript.

**Comment by adamdbradley** [comment]
In the most recent versions, typescript bundling takes into account the entire app, rather than just one file. Can you update to the latest and see if it fixes your issue? `npm install @ionic/app-scripts@latest --save-dev` Thanks

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
