### ISSUE TITLE
Misleading error message that config file is not found

### ISSUE THREAD

**Issue by dmastag** [driftyco/ionic-app-scripts#120]
#### Short description of the problem:

If using custom configs like rollup and the script has a bug the error log will say 

```
[10:51:02]  Config file "C:\project\config\rollup.config.js" not found. Using defaults instead.
```

Event though the error itself is showing afterwards, ex:

```
[10:51:02]  Error: Cannot find module '../dist/plugins/ng-template'
```
#### What behavior are you expecting?

Remove the config not found message and show the error only instead.

**Steps to reproduce:**
1. copy the default rollup into config/rollup.config.js
2. add rollup into package.json

```
var ngTemplate = require('../dist/plugins/ng-template').ngTemplate;
```

should trigger an error

**Which @ionic/app-scripts version are you using?**
0.0.27

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

https://github.com/driftyco/ionic-app-scripts/issues/58#issuecomment-250956624
https://github.com/driftyco/ionic-app-scripts/issues/58#issuecomment-252400938

**Comment by danbucholtz** [comment]
This should be resolved.

Thanks,
Dan
