### ISSUE TITLE
A way for using custom build arguments

### ISSUE THREAD

**Issue by cmaart** [driftyco/ionic-app-scripts#124]
Hi all, 

is there a way to pass command line parameters to ionic serve or ionic build?
In my case I have the following setup:
- In package.json I have this script
  `"build": ionic build`

and i want to pass in parameters that I can use in my configs, like custom rollup config.
Example for planned usage from command line:

`npm run build --stage=prod`

Any help would be greatly appreciated!

**Comment by jthoms1** [comment]
We have not concept of custom parameters within the CLI.  @danbucholtz I believe this is something that is more about how configs are used within app-scripts.

**Comment by danbucholtz** [comment]
@cmaart,

Let me give this some thought and I'll get back to you in the coming days. This is lower priority for us so it may be a bit. You could certainly use Node environment variables in the interim.

Thanks,
Dan

**Comment by cmaart** [comment]
@danbucholtz: Okay. What I currently do is, in the npm script i run a initializeBuildEnvironment.js that takes some parameters, I store them as a json file and read the parameters from the json again later in the build process.

My Use-Case if this is interesting for you why I even do need it: We build for multiple stages. The build on the build agent should be able to pass in settings (like the stage) as a parameter to the npm script. In the custom webpack config I need the stage to replace endpoints according to the stage specified.

**Comment by danbucholtz** [comment]
More than likely, we aren't going to have time to get to this in the next few months. With that in mind, I'm going to close this issue.

Thanks,
Dan

**Comment by alan-agius4** [comment]
I used "yargs" for some like that

**Comment by alan-agius4** [comment]
Or try to re the custom argv with.


process.env.npm_config_argv

Or

process.env.argv

**Comment by cmaart** [comment]
@alan-agius4: Thx! That's pretty much what I ended up doing. I just set env variables according to my stage that i'm building for
