### ISSUE TITLE
white screen after templateUpdate or sass finished in v2 rc.0

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#128]
_From @lwz7512 on October 10, 2016 8:30_

while made some changes in template or .ts, a few seconds later, the chrome browser auto refresh then display WHITE screen... 
this happen in active 'device toolbar' (blue state), but everything ok in deactive device toolbar!(gray state)

_Copied from original issue: driftyco/ionic#8602_

**Comment by jgw96** [comment]
_From @lwz7512 on October 10, 2016 12:17_

this happen often, and sometimes page mis-layout or looks like lost all the styles...
very frustrating...
I can make sure that I did not make any mistakes, for manually refresh the browser(cmd+r), it comes back...

I use chrome 53.0.2785.143 (64-bit) and Mac.
Nevertheless, 2.0 beta.11 does NOT have this problem!

**Comment by devarg** [comment]
Experiencing the same after upgrading to RC.

**Comment by Manduro** [comment]
Same here! There seem to be two separate issues to me:

1. With a css update, the live reload fails and all css that was loaded is discarded. This results in a completely unstyled page. This seems to be random. A next css save could work again, applying the new styles.

2. With a template update, the live reload works, but the javascript fails to load. The `<ion-app></ion-app>` can be found in the dom: empty.

**Comment by jgw96** [comment]
Hello all! After some testing today I have confirmed this issue. Note to team: i will work on doing some debugging and narrowing this issue down.

**Comment by jgw96** [comment]
Hello all! This seems to be fixed in 0.0.33. Because of this i will be closing this issue for now.

**Comment by Manduro** [comment]
@jgw96 This is definitely still occurring in 0.0.35, for both the sass and bundle updates I mentioned.

**Comment by lwz7512** [comment]
@Manduro update your package.json to the latest:
```
https://github.com/driftyco/ionic2-app-base/blob/master/package.json
```
the situation is better...in my case...

**Comment by Manduro** [comment]
@lwz7512 My dependencies are up to date, and I'm still seeing this.

**Comment by lwz7512** [comment]
Yes, @Manduro @jgw96 the bug is still exist! I can confirm this...but fewer than before...

**Comment by devarg** [comment]
I confirm too. And also agree that is less frequent in rc1 with 0.0.36 than with rc0 with 0.0.30
