### ISSUE TITLE
[Bug] Cli or Rollup error to import pollyfils

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic-app-scripts#129]
#### Short description of the problem:
Ionic-app-scripts or Rollup doesn't play nice with `Intl` and `web-animation-js`.

#### What behavior are you expecting?
No errors from the pollyfils.

**Steps to reproduce:**
1. Just import the pollyfils in the `app.module.ts` file.
2. The errors are well reported in this Ionic forum thread: [how-to-rollup-pollyfils](https://forum.ionicframework.com/t/how-to-rollup-pollyfils/66108/9)

**Which @ionic/app-scripts version are you using?**
`Ionic info` output.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
All in thread.

**Comment by danbucholtz** [comment]
Can you link me to the polyfills on `npm`? I'll try to get something working.

Thanks,
Dan

**Comment by Luchillo** [comment]
Sure:
* [Intl](https://www.npmjs.com/package/intl)
* [web-animations-js](https://www.npmjs.com/package/web-animations-js)

**Comment by danbucholtz** [comment]
@Luchillo,

web-animations-js should just be imported like this. I didn't need to change anything to get it to work.

```
import * as webAnimation from 'web-animations-js'
```

`intl` is giving me a little bit of grief. I am sure it can be done but I think the best bet for now is to just use it via a `script` tag as described [here](https://github.com/andyearnshaw/Intl.js/#intljs-and-ft-polyfill-service).

Let me know what you think or if you have any additional questions. I will re-open if necessary.

Thanks,
Dan

**Comment by Luchillo** [comment]
I tough that way of importing puts everithing in the variable named `webAnimation` and wouldn't be a pollyfil any more, like a scope or something like that, also tslint will complain about unused variable.

**Comment by danbucholtz** [comment]
Try just

```
import 'web-animation-js'
```

That should fix tslint.  As far as the scope thing, generally polyfills provide a replacement for browser-level functionality, so they are operating on top-level items like window, etc. I think it will probably work. I have imported polyfills like this in the past.

Give it a shot and let me know how it goes.

Thanks,
Dan

**Comment by Luchillo** [comment]
I did, tslint doesn't complains with that import, but then the library does in the browser and i think it's because minification, i think Rollup complains about the lib using `eval` (as stated in the forum thread).

**Comment by Luchillo** [comment]
I've tested again the `web-animation-js` pollyfil and it seems the same error pops up in both ways of the import, both with direct import and with the default one, the difference is the file from which the error happens in browser.

**With direct import:**
```ts
import 'web-animations-js';
```
error:
![image](https://cloud.githubusercontent.com/assets/9698639/19286300/c15c237a-8fc2-11e6-8301-2be94a0e9e39.png)

**With default import:**
```ts
import * as webAnimations from 'web-animations-js';

webAnimations;
```

error:

![image](https://cloud.githubusercontent.com/assets/9698639/19286358/fbc48854-8fc2-11e6-9738-51c4fa65f670.png)

**And in both the same Rollup complain:**
```sh
[14:56:15]  rollup: Use of `eval` (in 
/home/carlos/Carlos/OSGroup/startApp/node_modules/web-animations-js/web-animations.min.js)
is strongly discouraged, as it poses security risks and may cause issues with minification.
See https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details
```

**Comment by danbucholtz** [comment]
Sorry Luchillo, just include them via `script` tags then.

Thanks,
Dan

**Comment by Luchillo** [comment]
I guess the rollup copy plugin it is then.

**Comment by Luchillo** [comment]
Actually i don't see any plugin for copying the files on build time, will i have to copy the files by hand into assets?

**Comment by danbucholtz** [comment]
You can do it either way. For now, just copy them by hand to assets.

Thanks,
Dan

**Comment by Luchillo** [comment]
I'm seriously missing Webpack right now.

**Comment by Luchillo** [comment]
If so do i have to make the same with font awesome?
