### ISSUE TITLE
Only delete relevant files/directories in the www directory

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-app-scripts#134]
#### Short description of the problem:

Currently the build is deleting everything in the `www/` directory. If I have a file in my `www/` directory it gets erased on build. I could put the file in another directory and add a custom config but this seems like overkill for one file.

#### What behavior are you expecting?

Either be able to add specific files to ignore from deletion in the `www/` directory or only have the relevant files in `www/` deleted for a build. 

**Steps to reproduce:**
1. Clone the conference app: https://github.com/driftyco/ionic-conference-app
2. Run `ionic serve`
3. See that the `.gitignore` file is deleted inside of `www/` and all other files in `www/` are showing up to add to git

**Which @ionic/app-scripts version are you using?**

0.0.30

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Related to: https://github.com/driftyco/ionic-app-scripts/issues/127

**Comment by brandyscarney** [comment]
@adamdbradley @danbucholtz Thoughts on how this should be handled?

**Comment by danbucholtz** [comment]
It sounds like we should only delete the `www/build` directory going forward.

What does this mean for the `assets` directory, though?

Thanks,
Dan

**Comment by adamdbradley** [comment]
The recent updates has it so only `www/build` gets deleted.

**Comment by marcoturi** [comment]
i still get all the folder cleaned (app-scripts 0.34)

**Comment by marcoturi** [comment]
my bad, i didn't run npm install after updating package.json, was using app-scripts 0.30.
