### ISSUE TITLE
SASS module traversal creates a deadlock

### ISSUE THREAD

**Issue by shlomiassaf** [driftyco/ionic-app-scripts#14]
@adamdbradley, when the sass process is looking for sass files inside modules it might freeze the build process.

In my scenario the `lodash` module caused it.

The freeze/deadlock happens [here](https://github.com/driftyco/ionic-app-scripts/blob/master/src/sass.ts#L154)

I guess the directory or a file in it get's locked and the instruction is waiting for it to get released.

Now, I know that I can add this module to the `excludeModules` in `sass.config.js` but this solution requires some understanding and deep debugging capabilities, developers shouldn't break their mind about it.

There was no error, the process just froze on `sass started ...` log message and nothing happen from there on... 
Users might add a lot of modules, if there's no error or no handling for this issue most of them will not be able to use it.

**Comment by adamdbradley** [comment]
Yeah understandable, it should be rewritten in more of an async nature. Would you be able to help rewrite it?

**Comment by danbucholtz** [comment]
I haven't heard of anyone else experiencing this issue. I don't think we'll be changing this for the foreseeable future unless this is still an issue affecting developers. Please let me know if the issue still is causing problems.

Thanks,
Dan
