### ISSUE TITLE
Could not resolve './app.module.ngfactory'

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#147]
_From @rkyleg on October 12, 2016 17:4_

I got this error when running ionic build ios

[12:33:30]  bundle prod started ...
[12:33:32]  bundle prod failed:  Could not resolve './app.module.ngfactory'

I had to change the import path for AppModuleNgFactory in main.prod.ts to 

import { AppModuleNgFactory } from '../compiled/app/app.module.ngfactory';

Does that make any sense?

node version: 6.7.0
npm version: 3.10.3

_Copied from original issue: driftyco/ionic#8653_

**Comment by jgw96** [comment]
_From @okonon on October 12, 2016 20:22_

is your `ionic serve` working normally?

**Comment by danbucholtz** [comment]
Did you change your directory structure? There isn't a `compiled` directory in the project.

Thanks,
Dan

**Comment by rkyleg** [comment]
Dan, 

Yea, I had genDir: "compiled" in the angularCompiler section of tsconfig from trying to get PrimeNG working with ionic. I removed that section and the compiled directory and the error goes away. All good now.
