### ISSUE TITLE
ionic serve not working

### ISSUE THREAD

**Issue by shlomiassaf** [driftyco/ionic-app-scripts#15]
With the new change the `server:before` npm script is executing the `watch` process.
The `watch` never ends so the server never start.

The logic should be something like build -> serve -> watch

**Comment by shlomiassaf** [comment]
Also, when you don't `build' the 'copy' command is not invoked...

**Comment by brandyscarney** [comment]
Can you try updating your CLI to the latest beta? `npm install -g ionic@beta`. We released a new version for this case. :smile:

**Comment by shlomiassaf** [comment]
Working after the update.
