### ISSUE TITLE
Ionic 2 rc0, npm run build, Error: Could not resolve entry (.tmp/app/main.prod.js)

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#153]
_From @tomgallagher on October 13, 2016 10:17_

Hi,

I'm trying to build for production using `npm run build`

When I run the command in the terminal, I'm getting this message:

```
Error: Could not resolve entry (.tmp/app/main.prod.js)
    at /home/ubuntu/workspace/pathfinder/node_modules/rollup/dist/rollup.js:8602:28
    at process._tickCallback (node.js:369:9)
```

Closely followed by this one:

`Error: ENOENT: no such file or directory, open '/home/ubuntu/workspace/pathfinder/www/build/main.js'`

What am I doing wrong? Seems a bit weird that a typescript build in a typescript project would be looking for a js file. I have a file called main.prod.ts in that location.

Thanks.

Tom

_Copied from original issue: driftyco/ionic#8674_

**Comment by danbucholtz** [comment]
@tomgallagher,

I see the original issue is closed so I'm going to close this too.

The reason the `bundle` step is looking for a `.js` file is because bundling operates on `javascript` after the `typescript` compilation.  So, Typescript gets compiled, THEN we bundle.

Thanks,
Dan

**Comment by tomgallagher** [comment]
OK, that makes sense. Thanks for explaining. If I have errors in the typescript compilation then the bundler won't be able to find the file.
