### ISSUE TITLE
ionic serve includes *.spec.ts files in compilation

### ISSUE THREAD

**Issue by kesozjura** [driftyco/ionic-app-scripts#157]
#### Short description of the problem:
ionic serve started to throw errors in *.spec.ts files, that cannot find name 'it' and 'describe'...
@ionic/app-scripts 0.0.30 were fine.
In our source files structure we have .spec.ts files in same directory as tested .ts file. We use mocha as testing framework.

#### What behavior are you expecting?
serve should not include *.spec.ts files

**Steps to reproduce:**
1. create some ts file.
2. in same directory create .spec.ts file 
3. run ionic serve

**Which @ionic/app-scripts version are you using?**
0.0.31, 0.0.32, 0.0.33

**Comment by danbucholtz** [comment]
Should be an easy fix.

Thanks,
Dan

**Comment by JustinPierce** [comment]
I believe this may not apply only to `.spec.ts` files, but any `.ts` files that sit outside of the usual project directories. We have some supplementary files in a folder next to `src` that are also causing `npm run build --dev` and `ionic serve` to fail.

**Comment by danbucholtz** [comment]
@JustinPierce,

Thanks, I will look into it.

Thanks,
Dan

**Comment by mbakker96** [comment]
I've the same problem. I have my `*.spec.ts` files in the same directory as in my `*.ts` files. it aways ignored the spec files becease they were not included in de `*.ts` files.

But since the last update to 0.0.33 it does not ignore the `*.spec.ts` files anymore. 

I can't add the spec files to `exclude` becease then i can't test the files anymore. 

here my `tsconfig.ts`:
```JSON
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by danbucholtz** [comment]
Did you modify your `tsconfig.json` at all? It does not match what I see here:

https://github.com/driftyco/ionic-app-scripts/blob/master/tsconfig.json

**Comment by mbakker96** [comment]
No I've not modify it. It is the standard when you create a Ionic project.

Fresh from a blank ionic project:
```JSON
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by danbucholtz** [comment]
You guys are right, I linked to the wrong thing. Okay, hmmm.  I will investigate and come up with a solution.

Thanks,
Dan

**Comment by JustinPierce** [comment]
@danbucholtz Your "wrong thing" that you linked to gave me a (temporary?) workaround. I changed the default `tsconfig.json` to look like this:

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "typeRoots": [
      "./node_modules/@types"
    ],
    "types": [
      "jasmine",
      "googlemaps"
    ]
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

This allows me to run a dev build on 0.0.33. The only changes were the additions of the `typeRoots` and `types` properties.

**Comment by danbucholtz** [comment]
@kesozjura,

Add `Mocha` or `Jasmine` to the global types in TSConfig as @JustinPierce mentioned. We are now being more strict in how we're compiling Typescript. We were getting complaints using the `transpile only` solution where it didn't actually validate types, etc.

Thanks,
Dan
