### ISSUE TITLE
Exclude files from the linter

### ISSUE THREAD

**Issue by duydao** [driftyco/ionic-app-scripts#161]
ngc generates declaration files that are getting linted.

Could you provide a config option that we could use to exclude those files by setting a glob pattern or is there another way to exclude those files?

**Comment by danbucholtz** [comment]
Good idea, we'll add it to our backlog. Thanks!

Thanks,
Dan

**Comment by DenisVuyka** [comment]
@danbucholtz It seems everything in the `node_modules` get linted. Is it possible excluding entire `node_modules` folder from the check?

**Comment by danbucholtz** [comment]
@DenisVuyka, it shouldn't be, but we'll look into it when we do this.

Thanks,
Dan

**Comment by danbucholtz** [comment]
I believe this is resolved now. Please let me know if it's not.

Thanks,
Dan
