### ISSUE TITLE
[RC1] Cannot exclude files from serve/watch process

### ISSUE THREAD

**Issue by cmhand** [driftyco/ionic-app-scripts#169]
#### Short description of the problem:

When running ionic serve, there doesn't seem to be a way to exclude files (such as .spec.ts files).

#### What behavior are you expecting?

I should be able to exclude files by pattern or some other way.

**Steps to reproduce:**
1. Attempt to ignore via ionic.config.json (this won't work because the transpiling to JS fails).
2. Attempt to provide custom watch.config.js file with an "ignore statement". No effect.

watch.config.js attempt:
```
watchers: [

    {
      paths: [
        '{{SRC}}/**/*.ts'
      ],
      options: { ignored: "{{SRC}}/**/*.spec.ts" },
      callback: buildUpdate
    },

    {
      paths: [
        '../src/**/*.html'
      ],
      options: { ignored: /(index.html$)/ },
      callback: templateUpdate
    },

    {
      paths: [
        '{{SRC}}/**/*.scss'
      ],
      callback: sassUpdate
    },

    {
      paths: [
        '{{SRC}}/assets'
      ],
      callback: copyUpdate
    },

  ]
```

**Which @ionic/app-scripts version are you using?**
0.0.34

`Cannot find name 'describe'. ` 

Around 100 times.

**Comment by cmhand** [comment]
Thanks @danbucholtz for the quick reply. I will do that for now. I realize I could also just move all the spec files out of the src directory, but attempt to follow the angular 2 style guide. 

I assumed (maybe incorrectly) that specifying a custom watch file would be supported.

**Comment by danbucholtz** [comment]
It is. Documentation forthcoming on this topic.

Thanks,
Dan

**Comment by marcoturi** [comment]
I made a [working example here](https://github.com/marcoturi/ionic2-boilerplate). See  https://github.com/marcoturi/ionic2-boilerplate/blob/master/config/watch.config.js for specific configuration.

**Comment by cmhand** [comment]
I don't know if others have seen the same thing, but spec files are still built for me on ionic serve. I have the latest app-scripts as well.

**Comment by cmhand** [comment]
As of the latest app-scripts 0.0.36, spec files are still built on ionic serve.
