### ISSUE TITLE
AppModuleNgFactory unavailable in app.module.ngfactory

### ISSUE THREAD

**Issue by Purus** [driftyco/ionic-app-scripts#171]
#### Short description of the problem:
Ionic Serve command works fine. But Ionic Build fails with the below error.

I don't see the file app.module.ngfactory in the path too.
```
[15:09:30]  Error: Error at F:/Project/Ionic/captions/.tmp/app/main.prod.ts:4:10

[15:09:30]  Module '"F:/Project/Ionic/myapp/.tmp/app/app.module.ngfactory"' has no exported member 'AppModuleNgFactory'.
[15:09:30]  ngc failed
```

#### What behavior are you expecting?

I would expect the build process to create the apk file at the end.

My package information is provided below:

```
  "dependencies": {
    "@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/compiler-cli": "2.1.0",
    "@angular/core": "^2.0.0",
    "@angular/forms": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "@angular/platform-browser-dynamic": "^2.0.0",
    "@angular/platform-server": "^2.1.0",
    "@ionic/app-scripts": "0.0.34",
    "@ionic/storage": "^1.0.3",
    "angular2-moment": "^1.0.0-beta.5",
    "ionic-angular": "2.0.0-rc.1",
    "ionic-native": "^2.0.3",
    "ionicons": "^3.0.0",
    "rxjs": "^5.0.0-rc.1",
    "zone.js": "^0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.30",
    "typescript": "^2.0.3"
  },
```

Node:  v4.2.6
NPM : V3.10.8
Ioinc CLI: 2.1.0
OS: Windows 10

"Cordova build android -device" command builds the apk file successfully.

If the error is due to some issues in  my own app code, how do I find the root cause?

**Other information:** 
https://github.com/driftyco/ionic/issues/8312

**Comment by adamdbradley** [comment]
Can you try updating to the latest app-scripts? `npm install @ionic/app-scripts@latest --save-dev`

**Comment by helderdiin** [comment]
I  made that steps: https://javebratt.com/ionic2rc0-firebase-angularfire2/

But now, the `var ngTemplate = require('@ionic/app-scripts/dist/plugins/ng-template').ngTemplate;` doesn't work =/

`Error: Cannot find module '@ionic/app-scripts/dist/plugins/ng-template'`

now my app crashes...

`"@ionic/app-scripts": "0.0.36"`

Thanks for any help... trying for long 6 hours :disappointed:

**Comment by Purus** [comment]
The app-script is now at 0.0.36. I still have the same issue.

I could not find where the actual issue.. whether in CLI or in the code..

**Comment by Purus** [comment]
@jgw96  @adamdbradley I have created a repo so that you can quickly review.

https://github.com/Purus/Test-App

**Comment by danbucholtz** [comment]
@purus,

In your test app, your `AppModule` is named `MyApp` instead of `AppModule`. That's the issue and why the export can't be resolved.

I'm going to close this since Ionic and NGC are behaving as expected. Please let me know if there is anything else you're having trouble with.

Thanks,
Dan

**Comment by Purus** [comment]
Would it be possible for Ionic to report such things? It would be helpful to know in CLI outputs.

**Comment by danbucholtz** [comment]
Possible, yes. We are going to investigate better error reporting out of `ngc`. We are seeing a lot of users having problems with `ngc` since it's so strict.

Thanks,
Dan

**Comment by nottinhill** [comment]
Its good that its strict. Better than crashes when you have a nav.push of a buggy component in JIT on a real device. In our case it came down to many own bugs due to nature of JavaScript in combination of lack of unit tests (b/c of beta nature), but also due to incompatibilities with ng-2 final and ionic rc0.

**Comment by danbucholtz** [comment]
@nottinhill, this is very common. It is pretty jarring to most apps when they start using AoT. NGC is super strict. I would argue too strict. It is them way it is because it works off of typescript type metadata, so it needs to be explicit.

Thanks,
Dan

**Comment by Purus** [comment]
In a way it's good to be very strict. It would be better if ngc or Ionic
reports the exact reason for the failure. It was hard for me to debug even
a simple issue.

**Comment by nottinhill** [comment]
@danbucholtz Like I said, I like that it is strikt, it help us debug our app. Nothing wrong with that at all.
