### ISSUE TITLE
issue: Colors not working

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-app-scripts#172]
#### Short description of the problem:
As per 0.33 there are meant to be colors output for sass and ts errors. 

I have tried on normal Mac terminal and iterm2 and there are no colors. See screenshots below.

![image](https://cloud.githubusercontent.com/assets/2852839/19409298/35f82b32-92d1-11e6-8f08-f6cf2c7f44f8.png)

**Which @ionic/app-scripts version are you using?**
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.34
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.8.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by dylanvdmerwe** [comment]
After a while in `ionic serve` colors do eventually show when files change due to watch...?

![image](https://cloud.githubusercontent.com/assets/2852839/19409552/4991e9da-92d6-11e6-9217-a9b51a051907.png)

**Comment by danbucholtz** [comment]
@dylanvdmerwe,

To see the colors, you have to have the latest CLI.

```
npm install ionic@latest -g
```

Thanks,
Dan
