### ISSUE TITLE
RC1 watch hangs very often

### ISSUE THREAD

**Issue by Bubelbub** [driftyco/ionic-app-scripts#174]
#### Short description of the problem:
After starting the IONIC Watch process it hangs very long after some changes.

#### What behavior are you expecting?
That it not hangs as before 👍 

**Steps to reproduce:**
1. $ ionic serve
2. Change html template
3. Wait for watch ready or if its come fast then restart from 2.

	[16:38:53]  template update started ...
	JS changed:   C:\xampp\htdocs\ionic-conference-app\www\build\main.js
	[16:38:53]  template update finished in 312 ms
	[16:38:53]  watch ready
	[16:38:53]  template update started ...
	q

Q meens that I canceled because it takes too long 👎 

**Which @ionic/app-scripts version are you using?**
0.0.34

**Comment by adamdbradley** [comment]
Thanks for the report, we'll get it fixed
