### ISSUE TITLE
The application in production mode does not find some plugins

### ISSUE THREAD

**Issue by konrin** [driftyco/ionic-app-scripts#177]
#### Short description of the problem:
Compiled applications in production mode gives an error:

> Storage: SQLite plugin not installed, falling back to WebSQL Make sure to install cordova-sqlite-storage in production.!

> Install the t plugin: 'ionic plugin add cordova-plugin-calendar'

although these plug-ins are available at `window.plugins.calendar` and `window.sqlitePlugin`. If you build your application in development mode by putting the flag `ionic-app-scripts build --dev`, then the plug-ins found.

#### What behavior are you expecting?
Compiled applications in production mode should work with all the plug-ins included.

@ionic/app-scripts 0.0.36

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A219b

**Comment by mlynch** [comment]
Thanks, we're tracking this over at ionic-native. If you're able to, I'd love to see your project. If you could zip up your app directory or put it on github for me, my email is max@ionic.io. I've had trouble reproducing this locally so a real live project would be immensely helpful (in that case, the .zip method would be preferable so I can get a snapshot of the app). Thanks!

**Comment by mlynch** [comment]
Can you check this comment and see if this fixes it for you? https://github.com/driftyco/ionic-native/issues/602#issuecomment-254024940

**Comment by konrin** [comment]
Guys - this is my big mistake! I found that I start to work with plug-ins to confirm the readiness of the platform. Yet, why is this code was working in design mode!
