### ISSUE TITLE
fs-extra/readJsonSync breaks comments in tsconfig.json

### ISSUE THREAD

**Issue by rob3c** [driftyco/ionic-app-scripts#18]
TypeScript has allowed comments in tsconfig.json files for almost a year now (see https://github.com/Microsoft/TypeScript/issues/4987), but the current use of `readJsonSync()` in `fs-extra` to parse tsconfig.json files doesn't seem to like them.

Maybe switching to a tsconfig-aware library like https://github.com/TypeStrong/tsconfig would better support the full format?

**Comment by adamdbradley** [comment]
Good call, I'll look into it, thanks!

**Comment by danbucholtz** [comment]
PR welcome here. Otherwise this is off our radar for now.

Thanks,
Dan
