### ISSUE TITLE
Transpile error with app-scripts v0.0.31 and up

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#184]
_From @morious on October 17, 2016 1:24_

Hi,
I have been using the following package in my ionic project:
https://www.npmjs.com/package/tinycolor2
https://www.npmjs.com/package/@types/tinycolor

and I noticed transpiling errors when upgrading to RC1.
```
Cannot find module 'tinycolor2'.
...and...
Cannot find name 'tinycolorInstance'.
```

Moving one version back at a time I traced the issue to a change in v0.0.31.
I am not sure what is causing this issue though.

Any idea is welcome.
Thanks!

_Copied from original issue: driftyco/ionic#8745_

**Comment by jgw96** [comment]
Hello @morious, would you be able to provide some more info on this issue? Are you using a custom rollup config?

**Comment by morious** [comment]
Hi @jgw96,
I am not using any custom config for rollup.
I have tried to compare the type definition for tinycolor to other @types modules i am using and could not find a significant difference either.

Thx!

**Comment by danbucholtz** [comment]
@morious, can you update to latest app-scripts?

```
npm install @ionic/app-scripts@latest
```

And try again? This should be resolved.

Thanks,
Dan

**Comment by morious** [comment]
@danbucholtz - resolved! thanks a bunch!
This issue can be closed now.

**Comment by morious** [comment]
@danbucholtz ,
I am sorry but I may have jumped the gun on this one.
I could not see the error on my mac, but later today running from my windows machine this error shows app with the latest app-scripts as well.
I would like to ask you to re-open the issue please.

Thx.

**Comment by danbucholtz** [comment]
@morious,

There isn't a `types` definition for `tinycolor2`. I was unable to recreate this.

I did do a separate test with the library `lodash` and the `@types/lodash` package, and ran `ionic serve` without issue.

Thanks,
Dan

**Comment by morious** [comment]
@danbucholtz , Thanks.
I used this: https://www.npmjs.com/package/@types/tinycolor type definition.
I'll try your approach instead.

**Comment by morious** [comment]
@danbucholtz ,
I removed the type dependency and use the declaration you suggested.
It seems that the compiler is not complaining about 'tinycolor' any more ....
but there is another type definition called ''tinycolorInstance' that is now not recognized.
```
Cannot find name 'tinycolorInstance'.
```
Moreover, since I removed the typedefinition for this library the IDE typescript compiler is complaining as well.
Is there a way to get the transpiler to work using the type definition I referenced?

Thanks!

**Comment by morious** [comment]
@danbucholtz,
ok so I was able to overcome the compiler errors by copying lots of the type definitions for this module into the declarations.d.ts file.
So the big question is why this type definition:
https://www.npmjs.com/package/@types/tinycolor
is not doing its job?
