### ISSUE TITLE
www directory not found problem (Ionic 2 RC1)

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#186]
_From @azakusilo on October 17, 2016 10:6_

Hello.
In my project www directory was in folder with name of project. But for my needs I replace it from this folder to another. 
When I try to execute "ionic serve" command. It says me that www directory not found.
I fix the /node_modules/@ionic/app-scripts/config/dist/util/config.js to:
```
var BUILD_DIR = 'build';
var SRC_DIR = '../view/app/src';
var TMP_DIR = '.tmp';
var WWW_DIR = '../view/app/www';
```
And it's work fine, but when ionic serve starts it says me 
`"www" directory not found.`
I create a empty www folder in folder of project. But I don't need it. How to fix it?

_Copied from original issue: driftyco/ionic#8752_

**Comment by jgw96** [comment]
@azakusilo Would you mind taking a look at [this section](https://github.com/driftyco/ionic-app-scripts#custom-config-files) of our docs and trying a custom copy.config? Thanks!

**Comment by jgw96** [comment]
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by azakusilo** [comment]
I tryed to add custom config. But it have no effect. May be you have any example?
