### ISSUE TITLE
How disable templateUrl precompiller. (ionic 2 RC1)

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#187]
_From @azakusilo on October 17, 2016 10:9_

I need for my needs to disable templateUrl precompiler which is situated in:
`/node_modules/@ionic/app-scripts/dist/template.js`
I stopped it in 2 ways. But do you have any native solutions?

_Copied from original issue: driftyco/ionic#8753_

**Comment by adamdbradley** [comment]
Do you want to prevent all of them from being inlined, or individually select which ones shouldn't be inlined? Also, would you be able to explain what is it about the inlining that doesn't work in your case? Thanks

**Comment by azakusilo** [comment]
I need to prevent all. Because in my case the "templateUrl" option get html content from url. 
```
....
templateUrl: '/mobilesiteapp/template?path=app/app'
....
```
The url it is a server with php which gets template from Ionic template folder and compile it. I need it because I use php variables in html templates. Example:
```
{literal}
<ion-header>
  <ion-toolbar>
    <ion-navbar>
      <ion-buttons start>
        <button ion-button>
          <ion-icon name="search"></ion-icon>
        </button>
      </ion-buttons>
      <ion-title>{{product.title}}</ion-title>
      <ion-buttons end>
        <button ion-button>
          <ion-icon name="more"></ion-icon>
        </button>
      </ion-buttons>
    </ion-navbar>
  </ion-toolbar>
</ion-header>
{/literal}

{$page_urls=[ /* PHP variable usage */
  'offers' => $router->getUrl('externalapi-front-apigate', ['method'=>'product.getofferslist'])
]}
<ion-content>
  <blocks-catalog-product [config_private]="{ offers_url: '{$page_urls.offers}'}" [slideOptions]="{ loop: false, pager: true, observe: true}"></blocks-catalog-product>
</ion-content>
```
After PHP compile it returns to my usual html with ready strings.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! After reviewing this issue this seems like it is outside of the scope of app-scripts. Because of this I am going to close this issue for now.
