### ISSUE TITLE
Ionic 2: www/index.html not updated on updating src/index.html

### ISSUE THREAD

**Issue by shikharls** [driftyco/ionic-app-scripts#194]
#### Short description of the problem:

I added one script tag in src/index.html
`<script src="https://code.createjs.com/createjs-2015.11.26.min.js"></script>`

Then I ran `ionic serve`. www/index.html was not updated.

#### What behavior are you expecting?
www/index.html to be updated with the new script tag.

**Which @ionic/app-scripts version are you using?**
Ionic RC2 after Max's Weekend Update changes.

**Comment by jourdan-jobox** [comment]
I have the same exact problem :)

**Comment by jourdan-jobox** [comment]
For now I'm going to manually update my `www/index.html` file which isn't a big deal at all, but I hope to see the fix soon.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has been fixed in the latest beta build of app-scripts which you can install by running `npm install @ionic/app-scripts@beta`.

**Comment by jourdan-jobox** [comment]
Hi @jgw96, thanks! 

I tried installing it, it looked to be fine in the console except for an invalid issue. I retried it a second time and it gave me the following output below, any idea what this issue is? 

```
$ npm install @ionic/app-scripts@beta
jobox-front-end@ /Users/Jourdan/Desktop/jobox/jobox-front-end
└── @ionic/app-scripts@0.0.37-2  invalid

npm WARN jobox-front-end@ No repository field.
npm WARN jobox-front-end@ No license field.
Shravyas-MacBook-Pro:jobox-front-end Jourdan$ 
```

As you can see, it says `invalid` next to app-scripts
