### ISSUE TITLE
Build fails with custom js file

### ISSUE THREAD

**Issue by shikharls** [driftyco/ionic-app-scripts#195]
#### Short description of the problem:

I have a JavaScript file which exports a function `init()`. I have defined d.ts file for the same and using the function in a ts file.

`ionic serve` runs fine.
But `ionic build` fails:

bundle failed: Could not resolve './demo' from /Users/..../app/.tmp/pages/books/demo/demo.component.js

I checked the .tmp/ folder. It doesn't have the JavaScript file copied here.

**Steps to reproduce:**
1. Create 3 files:

demo.js
```
function init() {}
module.exports = init;
```

demo.d.ts
```
declare function init(): void;
export = init;
```

demo.component.ts
```
import { Component, AfterViewInit } from '@angular/core';

import init from './demo';

@Component({
  templateUrl: 'demo.html'
})
export class DemoBookComponent implements AfterViewInit {
  public show: boolean = false;
  ngAfterViewInit() {
    init();
  }
}
```

2. On the CLI:
`ionic build` gives error whereas `ionic serve` succeeds.

**Which @ionic/app-scripts version are you using?**
Ionic 2 after Max's 14th Oct blog update.

**Comment by shikharls** [comment]
I tried moving the JS and .d.ts file to assets/ folder. Again, ionic serve runs fine but ionic build fails with same error. I checked the .tmp/ directory - it does not have assets/ folder, so build is expected to fail. So I believe we should be copying the assets/ folder as well?

**Comment by shikharls** [comment]
Thanks @jgw96 for the mail. So this is the flow:
I have a 3rd party software which outputs the following HTML:
```
<head>
<script>....</script>
<script>....</script>
</head>
<body>
<div ...>...</div>
</body>
```

I tried making this HTML as component template, but then realized that Ionic 2 RC removes all `<script>` tags from the template (BTW, I wish I could control this...).
So what I know do is take the JS inside `<script>` tags and put in JS file. And export methods to use in TS component file.
It is not possible to convert the JS file to TS as this is 3rd party generated and is fairly complex. Also changing it is not scalable as we move forward. We want that to remain as black box.

**Comment by shikharls** [comment]
@jgw96 Is there any alternative work around as of now? I am not very familiar with webpacks, but would that solve this issue when that CL is merged?

**Comment by jgw96** [comment]
Thanks for the info @shikharls ! So just to be clear, you are trying to put `<script />` tags in your component templates?

**Comment by shikharls** [comment]
@jgw96 Sorry for being ambiguous. What I have from a 3rd party is a self-sufficient HTML file which script tags. Now there are two ways to integrate this:

1. Take the entire HTML file and make it as `templateUrl` of a `@Component`. The problem here: Ionic removes `script` tags from the template.

2. Separate the `script` tags from the HTML and make 2 files: 1 pure HTML which would be `templateUrl` of a `@Component`, second, a JS file which would have JS from the `script` tags and expose the methods using exports and .d.ts file. The problem here: This JS files is not copied over when building and build fails. Also, I would not like to put these JS files in `index.html` as this is not scalable for us.

I think Ionic should address both of these. As of now, any workaround would be great.

**Comment by jgw96** [comment]
@shikharls Does this work in a normal Angular app? Such as one generated by the [angular cli](https://github.com/angular/angular-cli)

**Comment by shikharls** [comment]
@jgw96 To be very frank, I have never used angular cli. These work well with Ionic 1. But given Angular does not remove the `script` tags, and also has no custom script like `@app-scripts`, I think it should work fine.

**Comment by jgw96** [comment]
Hello! After further review I am going to be closing this issue for now. Angular 2 components are not designed to have `script` tags in the templates. Also, not only are they not designed to have `script` tags in them, but this will also cause other issues with things like AoT compile. While this may have worked in Ionic 1 / Angular 1, Ionic 2 is built on Angular 2 which is an entirely different architecture.
