### ISSUE TITLE
Custom scripts

### ISSUE THREAD

**Issue by marsanla** [driftyco/ionic-app-scripts#196]
#### Short description of the problem:
I would like to have the possibility to create my own custom scripts using the base of the app-scripts. 

#### Example
For example i would like to create a image forlder in each component and later copy all of them in the `dist/folder/assets/images`, and from now its not possible to do this.

**Which @ionic/app-scripts version are you using?**
0.0.36

**Comment by royipressburger** [comment]
http://ionicframework.com/docs/v2/resources/app-scripts/

**Comment by marsanla** [comment]
I was reading the documentation, but i don't understand how to add new tasks to the app-scripts

Thans :)

**Comment by marcoturi** [comment]
you should hook the copy task -> https://github.com/driftyco/ionic-app-scripts/blob/master/config/copy.config.js inside you package.json. [See here](https://github.com/marcoturi/ionic2-boilerplate/blob/master/package.json#L188) for an example with the watch task.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Also, the link @marcoturi gave above should help too. Thanks for using Ionic!
