### ISSUE TITLE
Ionic serve issues

### ISSUE THREAD

**Issue by sveinl** [driftyco/ionic-app-scripts#198]
#### Short description of the problem:
When editing and saving files - sometimes `ionic serve` are using file from an older save of the file. Looks like there are som caching that are used.

Also when adding pages with `ionic g pageName` i have to restart serve to make that page work.

#### What behavior are you expecting?
No cached files used and new pages are recognized after adding with `ionic g pageName`

**Which @ionic/app-scripts version are you using?**
0.0.37

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.37
OS: Windows 10
Node Version: v6.7.0

**Comment by danbucholtz** [comment]
@sveinl,

This is resolved now. Tomorrow (Friday) we are releasing `0.0.37` which will fix the issue. You could also install `@ionic/app-scripts@beta` which will fix it too. It is the second beta release that fixed this.

Thanks,
Dan
