### ISSUE TITLE
ionic 2 watch typescript not working

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#199]
_From @balicekt on October 19, 2016 10:39_

I wanted to try new ionic 2. I made this steps:

```
ionic start HelloWorld --v2
cd HelloWorld
ionic serve
```

until now is everything OK. BUT when I go to folder src/pages/home and adjust file home.ts nothing is hapening watcher is not working but when I adjust file home.html watcher is working well console show changes and browser automatically refresh page.

Does anyone know why in ionic 2 watcher does not working with typescript files? Or is there something I did wrong? Also in Ionic project is no gulpfile.js anymore.

I will be glad for any help.

Thank you

_Copied from original issue: driftyco/ionic#8799_

**Comment by pierrepastre** [comment]
Same issue her, since last update, ts does not compile anymore.

**Comment by glaucocustodio** [comment]
Since I've updated to beta version (`npm install @ionic/app-scripts@beta`) the `ionic serve` is not creating a server at `localhost:8100`.

**Comment by GITHuHo** [comment]
Same issue here. With beta `@ionic/app-scripts@0.0.37` the `ionic serve` command  just hangs after build, and livereload is never started:
```
[16:46:03]  ionic-app-scripts 0.0.37
[16:46:03]  watch started ...
[16:46:03]  build dev started ...
[16:46:03]  clean started ...
[16:46:03]  clean finished in 12 ms
[16:46:03]  copy started ...
[16:46:03]  transpile started ...
[16:46:03]  lint started ...
[16:46:09]  lint finished in 5.83 s
[16:46:10]  transpile finished in 7.09 s
[16:46:10]  webpack started ...
[16:46:10]  copy finished in 7.30 s
[16:46:24]  webpack finished in 13.97 s
[16:46:24]  sass started ...
[16:46:26]  sass finished in 2.38 s
[16:46:26]  build dev finished in 23.47 s
```

This issue only occurs on my Windows 7 machine. On Mac OS X the same project serves fine with live reload. 

My system information on Windows:
```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.37
OS: Windows 7 SP1
Node Version: v5.10.0
```

My system info on Mac OS X:
```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.37
ios-deploy version: 1.8.6
ios-sim version: 4.1.1
OS: Mac OS X El Capitan
Node Version: v6.4.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by jgw96** [comment]
@pierrepastre and @glaucocustodio are you all also on windows?

**Comment by glaucocustodio** [comment]
I am on OS X Yosemite and Ionic RC.1.

**Comment by balicekt** [comment]
OS X Sierra RC1 - now I updated npm, ionic, cordova and it started working but not everything typoscript is working now but src/assets is not working when I mage new file for example src/assets/i18n/en.json it also make new file in www/assets/i18n... but when I make update in this json it won't appear in www file.

**Comment by pierrepastre** [comment]
OSX sierra here, ionic 2.1.1, cordova 6.3.1

**Comment by danbucholtz** [comment]
We'll look into it. Glad to hear it's not just Windows.

Thanks,
Dan

**Comment by Chris1308** [comment]
I have the same issue on Windows 10, but OS X Sierra works fine.

**Comment by morrisonbrett** [comment]
I'm also seeing it on Ubuntu. See output here: https://github.com/driftyco/ionic/issues/8920#issuecomment-256492785

**Comment by danbucholtz** [comment]
This issue is fixed [here](https://github.com/driftyco/ionic-app-scripts/commit/af98397e7a7030c051807187777db4b790b5bf59). We are going to release `@ionic/app-scripts@0.0.37` tomorrow and it will be in that.

Thanks,
Dan

**Comment by morrisonbrett** [comment]
Great. Wow - Been using .37-2 all day. Webpack - **so much** faster on watch/build/refresh cycle.

**Comment by glaucocustodio** [comment]
After I update to  `"@ionic/app-scripts": "0.0.37-3"` `ionic serve` was not working because the `manifest.json` file was missing.

**Comment by morrisonbrett** [comment]
I recommend you put manifest.json in the root of /src.  I had it somewhere else (and referred to it in index.html), but it seems to be safer if you leave it at root (where I guess some code is assuming it will be).
