### ISSUE TITLE
typescript version is inconsistent between dev and prod builds

### ISSUE THREAD

**Issue by rob3c** [driftyco/ionic-app-scripts#200]
#### Short description of the problem:
The version of typescript used for transpiling can be different between `dev` and `prod` builds.

#### What behavior are you expecting?
I expect `dev` and `prod` builds to both use the same version of typescript under all circumstances.

**Steps to reproduce:**
1. install a 2.1.0 typescript version, e.g. `npm install --save-dev typescript@2.1.0-dev.20161019`
2. run a `prod` build and check the typescript version used
3. run a `dev` build and check the typescript version used

**Which @ionic/app-scripts version are you using?**
0.0.36

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

This problem is due to `app-scripts` declaring typescript in `dependencies` instead of `peerDependencies` in `package.json`, which is where angular 2 declares it in the `tsc-wrapped` module. Therefore, it can get out of sync with its own copy of typescript in its nested `node_modules` folder at times when angular 2 defers to a project's installed version.

I suggest moving typescript to `peerDependencies` to mirror the angular 2 declaration.

Additionally, I think you need to change the semver carat-based declaration to `^2.0.3 || 2.1.0-dev` if you want to allow `@next` versions of typescript.

Finally, I suggest logging the version of typescript used for the build to the console, since this was very hard to detect when I was getting `async/await` working. I kept installing different local typescript versions under the assumption that they were being used for the build, but nothing was changing, of course! For details, see https://github.com/driftyco/ionic-app-scripts/issues/197#issuecomment-254953042

**Comment by danbucholtz** [comment]
Good to know, thanks. We'll update this. In general, we won't provide detailed technical support for those who wish to diverge off the happy path we provide, but we'll try to do our best.

Thanks,
Dan

**Comment by rob3c** [comment]
Thanks! I didn't realize that a progressively-diverging typescript version between dev and prod over the lifetime of an ionic project was a happy path, but I appreciate you're addressing it nonetheless ;-)

**Comment by danbucholtz** [comment]
@rob3c,

We will keep the Typescript version up to date. We'll also provide a hook into the build and bundle tasks for users to do whatever they need to do. However, once once get into weird transpilation states, it is nearly impossible to keep tools in sync and working. Especially with most tools barely support ES2015 so far. I am a huge fan of async/await so we will get it in ASAP.

Thanks,
Dan
