### ISSUE TITLE
Add  gzip compression in webpack dev server

### ISSUE THREAD

**Issue by jmesa-sistel** [driftyco/ionic-app-scripts#202]
Hi @danbucholtz

I've seen that you are adding webpack support, please enable gzip compression in webpack dev server, so when we are developing/debugging in a device using livereload will speed up the load files from the server to the device. [compression-webpack-plugin](https://github.com/webpack/compression-webpack-plugin)

I guess adding the next code do the trick but I'm not sure 

In webpack.config.js add 

`var CompressionPlugin = require("compression-webpack-plugin");`

And add the next code after **module:** section

```
,
  plugins: [
        new CompressionPlugin({
            asset: "[path].gz[query]",
            algorithm: "gzip",
            test: /\.js$|\.html$|\.css$|\.map$/,
            threshold: 10240,
            minRatio: 0.8
        })
    ]

```

Do you know if it is posible to do it in rollup ?

**Comment by bobrosoft** [comment]
Is this solved in some other way?

**Comment by jmesa-sistel** [comment]
This is not the right github repo.
The right repo is https://github.com/driftyco/ionic
Anyway I've modified it to enable gzip and the improvement is not noticeable.

**Comment by bobrosoft** [comment]
Is it really started to serve with gzip? I'm trying to tunnel local env with ngork and there loading speed is very noticeable in comparison to local env.

**Comment by boadude** [comment]
When i try this option nothing happent... no gzip files found when i serve
