### ISSUE TITLE
Internet Explorer 11 click-block div prevents clicking

### ISSUE THREAD

**Issue by alfabetagama** [driftyco/ionic-app-scripts#203]
#### Short description of the problem:
When building for release Internet Explorer displays click-block div element in front of application content. This element prevents any interaction with application. This DOES NOT happen in development mode.

#### What behavior are you expecting?
I expect buttons to be clickable and inputs to be able to accept input.

**Steps to reproduce:**
1. Create app with menu and page
2. Place button on a page
3. Build with --release switch
4. Run in IE 11
5. try to click the buitton

**Which @ionic/app-scripts version are you using?**
ionic-app-scripts 0.0.36

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Fix: 
```
//IE
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
    .click-block {
        display:none;
    }
}
```

**Comment by patrickmcd** [comment]
IE isn't supported.

**Comment by alfabetagama** [comment]
@patrickmcd I didn't find any official documentation regarding the IE non-support, however apart from some minor styling bugs it works just fine. And of course the click-block div.

**Comment by patrickmcd** [comment]
It might not be in the official docs, but there are some comments scattered throughout the issues about it.

https://github.com/driftyco/ionic/issues/8669#issuecomment-253623266
https://github.com/driftyco/ionic/issues/6386#issuecomment-220648407

etc...

**Comment by danbucholtz** [comment]
@jgw96 can you move this.

Thanks,
Dan

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic#8828

**Comment by jgw96** [comment]
Hello @alfabetagama , thanks for opening an issue with us! Since this issue is an issue with the framework and not app-scripts i have moved this issue to the appropriate repo. Thanks!
