### ISSUE TITLE
ionic serve occasionally breaks upon Memory issue

### ISSUE THREAD

**Issue by jourdan-jobox** [driftyco/ionic-app-scripts#209]
#### Short description of the problem:

Basically, I see a `FATAL ERROR CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` error really randomly during development (seems to occur when new coding changes I make are compiled, but there doesn't seem to be a pattern of when it happens)

#### What behavior are you expecting?

An `ionic serve` command that runs smoothly 100% without crashing.

**Steps to reproduce:**
1. Run `$ ionic serve`
2. Make a bunch of HTML and/or TS changes
3. Wait until the console shows a fatal error.

Here's the stacktrace:
```
[14:14:15]  transpile update started ... 
[14:14:18]  transpile update finished in 3.06 s 
[14:14:18]  bundle update started ... 
JS changed:   www/build/main.js
[14:14:42]  bundle update finished in 24.63 s 
[14:14:42]  watch ready 
[14:15:08]  transpile update started ... 
[14:15:11]  transpile update finished in 3.68 s 
[14:15:11]  bundle update started ... 
<--- Last few GCs --->
 6672427 ms: Mark-sweep 1277.0 (1435.0) -> 1267.0 (1435.0) MB, 1067.6 / 0 ms [allocation failure] [GC in old space requested].
 6673520 ms: Mark-sweep 1267.0 (1435.0) -> 1266.8 (1435.0) MB, 1092.8 / 0 ms [allocation failure] [GC in old space requested].
 6674647 ms: Mark-sweep 1266.8 (1435.0) -> 1266.8 (1435.0) MB, 1126.9 / 0 ms [last resort gc].
 6675768 ms: Mark-sweep 1266.8 (1435.0) -> 1266.8 (1435.0) MB, 1121.8 / 0 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x263928ac9e31 <JS Object>
    2: /* anonymous */(aka /* anonymous */) [/Users/Jourdan/Desktop/jobox/jobox-front-end/node_modules/rollup/dist/rollup.js:~8684] [pc=0x32be616cad09] (this=0x263928a04189 <undefined>,entryModule=0x3cd68c9e31b1 <a Module with map 0x114fc68a2bf1>)
    3: PromiseHandle(aka PromiseHandle) [native promise.js:90] [pc=0x32be5b060f86] (this=0x263928a04189 <undefined>,y=0x3cd68c9e31b1 <a Module with m...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 
node::Abort() [/usr/local/Cellar/node/6.3.1/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/Cellar/node/6.3.1/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/Cellar/node/6.3.1/bin/node]
 4: 
v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/Cellar/node/6.3.1/bin/node]
 5: 
v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/Cellar/node/6.3.1/bin/node]
 6: 
v8::internal::FullCodeGenerator::PopulateDeoptimizationData(v8::internal::Handle<v8::internal::Code>) [/usr/local/Cellar/node/6.3.1/bin/node]
 7: 
v8::internal::FullCodeGenerator::MakeCode(v8::internal::CompilationInfo*) [/usr/local/Cellar/node/6.3.1/bin/node]
 8: 
v8::internal::Compiler::EnsureDeoptimizationSupport(v8::internal::CompilationInfo*) [/usr/local/Cellar/node/6.3.1/bin/node]
 9: 
v8::internal::OptimizedCompileJob::CreateGraph()
 [/usr/local/Cellar/node/6.3.1/bin/node]
10: 
v8::internal::GetOptimizedCodeNow(v8::internal::CompilationInfo*) [/usr/local/Cellar/node/6.3.1/bin/node]
11: 
v8::internal::Compiler::GetOptimizedCode(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ConcurrencyMode, v8::internal::BailoutId, v8::internal::JavaScriptFrame*) [/usr/local/Cellar/node/6.3.1/bin/node]
12: 
v8::internal::Runtime_CompileForOnStackReplacement(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/Cellar/node/6.3.1/bin/node]
13: 
0x32be5700961b
14: 0x32be570394f6
15: 0x32be616cad09
16: 0x32be5b060f86
17: 0x32be5b060bf7
18: 0x32be57038004

^CShravyas-MacBook-Pro:jobox-front-end Jourdan$
```

**Which @ionic/app-scripts version are you using?**

Here's what my `package.json` says:
```
"dependencies": {
    "@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "^2.0.0",
    "@angular/forms": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "@angular/platform-browser-dynamic": "^2.0.0",
    "@angular/platform-server": "^2.0.0",
    "@ionic/storage": "1.1.2",
    "angular2-signaturepad": "^1.1.1",
    "ionic-angular": "^2.0.0-rc.1",
    "ionic-native": "^2.2.3",
    "ionicons": "^3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.21"
  },
"devDependencies": {
    "@ionic/app-scripts": "^0.0.34",
    "typescript": "^2.0.3"
  },
```

**Comment by jourdan-jobox** [comment]
Just realized I'm behind in the app-scripts version (looks like it's up to 0.0.36, maybe I should update my version first and see if I ever come across this issue again!

**Comment by fenglanzhan** [comment]
@jourdan-jobox Maybe same  error.Npm log is above.
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch',
1 verbose cli   '--color' ]
2 info using npm@3.10.8
3 info using node@v6.9.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle ionic-hello-world@~prewatch: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~prewatch: no script for prewatch, continuing
7 info lifecycle ionic-hello-world@~watch: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~watch: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~watch: PATH: D:\Program Files\nodejs\node_global\node_modules\npm\bin\node-gyp-bin;D:\test\myIonic2Project3\node_modules\.bin;C:\Python35-32\Scripts\;C:\Python35-32\;C:\Program Files\Java\jdk1.8.0_51\\bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;D:\**\TortoiseGit\bin;D:\**\Git\Git\cmd;C:\Program Files\Skype\Phone\;C:\Program Files\nodejs\;C:\Ruby22\bin;D:\**\sdk\tools;D:\**\sdk\platform-tools;D:\Program Files\nodejs\node_global\;C:\Program Files\Sublime Text 3;C:\xampp\mysql\bin;C:\Users\win7\AppData\Roaming\npm
10 verbose lifecycle ionic-hello-world@~watch: CWD: D:\test\myIonic2Project3
11 silly lifecycle ionic-hello-world@~watch: Args: [ '/d /s /c', 'ionic-app-scripts watch' ]
12 silly lifecycle ionic-hello-world@~watch: Returned: code: 3  signal: null
13 info lifecycle ionic-hello-world@~watch: Failed to exec watch script
14 verbose stack Error: ionic-hello-world@ watch: `ionic-app-scripts watch`
14 verbose stack Exit status 3
14 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_global\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_global\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd D:\test\myIonic2Project3
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch" "--color"
19 error node v6.9.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error ionic-hello-world@ watch: `ionic-app-scripts watch`
22 error Exit status 3
23 error Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

My ionic info:
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS: Windows 7 SP1
Node Version: v6.9.0
And here's my package.json:
"scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@ionic/storage": "1.0.3",
    "ionic-angular": "2.0.0-rc.1",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "ts-md5": "^1.2.0",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.36",
    "typescript": "^2.0.3"
  },

**Comment by jgw96** [comment]
Hello all! This has been fixed in the latest version of app-scripts. To update you can run `npm install @ionic/app-scripts@latest --save-dev` in your project. Thanks!

**Comment by jourdan-jobox** [comment]
@jgw96 Thanks Justin! I haven't seen any issues yet since updating yesterday, so it looks to be good!

**Comment by jourdan-jobox** [comment]
Hi @jgw96, actually just came across a memory issue, though this was the first time it's happened since I've commented 2 days ago. Not sure how to reproduce but I'll print the stack trace here:

```
[22:17:05]  bundle update finished in 51.12 s 
[22:17:05]  watch ready 
[22:17:05]  transpile update started ... 
[22:17:17]  transpile update finished in 12.17 s 
[22:17:17]  bundle update started ... 
[22:17:34]  template update started ... 
[22:17:34]  template update finished in 96 ms 
[22:17:34]  watch ready 
JS changed:   www/build/main.js
<--- Last few GCs --->
24747831 ms: Mark-sweep 1268.5 (1435.0) -> 1268.5 (1435.0) MB, 1052.6 / 0 ms [allocation failure] [GC in old space requested].
24748907 ms: Mark-sweep 1268.5 (1435.0) -> 1268.5 (1435.0) MB, 1076.3 / 0 ms [allocation failure] [GC in old space requested].
24750186 ms: Mark-sweep 1268.5 (1435.0) -> 1268.5 (1435.0) MB, 1278.9 / 0 ms [last resort gc].
24751574 ms: Mark-sweep 1268.5 (1435.0) -> 1268.5 (1435.0) MB, 1387.6 / 0 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x321f10fc9e31 <JS Object>
    1: forEach [native array.js:~956] [pc=0x1ce656cb8fa5] (this=0x25685b0ebc79 <JS Array[2]>,br=0x17aaa30b6d49 <JS Function processDependency (SharedFunctionInfo 0x380605e9a731)>,bs=0x321f10f04189 <undefined>)
    2: arguments adaptor frame: 1->2
    3: processDependency(aka processDependency) [/Users/Jourdan/Desktop/jobox/jobox-front-end/node_modules/rollup/dist/rollup.js:~9056] [pc=0x1ce656de...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/Cellar/node/6.3.1/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/Cellar/node/6.3.1/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/Cellar/node/6.3.1/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/Cellar/node/6.3.1/bin/node]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/Cellar/node/6.3.1/bin/node]
 6: v8::internal::LCodeGenBase::PopulateDeoptimizationData(v8::internal::Handle<v8::internal::Code>) [/usr/local/Cellar/node/6.3.1/bin/node]
 7: v8::internal::LChunk::Codegen() [/usr/local/Cellar/node/6.3.1/bin/node]
 8: v8::internal::OptimizedCompileJob::GenerateCode() [/usr/local/Cellar/node/6.3.1/bin/node]
 9: 
v8::internal::Compiler::GetConcurrentlyOptimizedCode(v8::internal::OptimizedCompileJob*) [/usr/local/Cellar/node/6.3.1/bin/node]
10: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [/usr/local/Cellar/node/6.3.1/bin/node]
11: v8::internal::StackGuard::HandleInterrupts() [/usr/local/Cellar/node/6.3.1/bin/node]
12: v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/Cellar/node/6.3.1/bin/node]
13: 0x1ce64bc0961b
```
