### ISSUE TITLE
Adding more environment flags?

### ISSUE THREAD

**Issue by hw101** [driftyco/ionic-app-scripts#211]
It's nice to have dev and prod flags for building, but for some it's useful to have more than these two. We use dev, test and production for our app, and used `NODE_ENV` to inject different config variables for each environment since we have test and production API servers.

Would it be possible to add a `--test` flag or the ability to add custom build flags to a config file?

**Comment by marcoturi** [comment]
Meanwhile you can use [a method like this to stub them] (https://github.com/marcoturi/ionic2-boilerplate/blob/master/config/rollup.config.js).

**Comment by danbucholtz** [comment]
@hw101, Rollup supports this and so does Webpack, so I am going to close this issue.

Thanks @marcoturi!

Thanks,
Dan
