### ISSUE TITLE
Error: Metadata version mismatch for module

### ISSUE THREAD

**Issue by astelilani** [driftyco/ionic-app-scripts#212]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Error on _ionic build ios_

> [03:32:06]  Error: Metadata version mismatch for module /Users/Ast-837/Documents/Ionic/myDemoApp/node_modules/angular2/src/http/base_response_options.d.ts

#### What behavior are you expecting?
Expecting successful build

**Which @ionic/app-scripts version are you using?**
ionic build ios

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

[npm-debug.log.txt](https://github.com/driftyco/ionic-app-scripts/files/543892/npm-debug.log.txt)

**Comment by astelilani** [comment]
Attempted to resolve the issue by re-installing npm modules -
rm -rf node_modules
npm install

However, build still results in an error
[04:05:49]  ionic-app-scripts 0.0.36 
[04:05:49]  build prod started ... 
[04:05:49]  clean started ... 
[04:05:49]  clean finished in 5 ms 
[04:05:49]  copy started ... 
[04:05:49]  ngc started ... 
[04:05:49]  copy finished in 129 ms 
[04:05:50]  lint started ... 
[04:05:51]  /Users/Ast-837/Documents/Ionic/myDemoApp/node_modules/@angular/compiler-cli/src/private_import_compiler.js:10 

[04:05:51]  exports.AssetUrl = compiler_1.__compiler_private__.AssetUrl; 
[04:05:51]  TypeError: Cannot read property 'AssetUrl' of undefined 

[04:05:51]  ngc failed 

[04:05:51]  ionic-app-script task: "build" 

[04:05:51]  Error: Error 
[npm-debug.log.txt](https://github.com/driftyco/ionic-app-scripts/files/543934/npm-debug.log.txt)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue with any of my test apps. Could you provide a repo that i could use to reproduce this issue?

**Comment by pmurpmur** [comment]
I just started getting this same error: I first got it today when I tried downloading my project off github and then building it after a successful `npm install`. Next I went back to my project that has been working just fine, deleted `node_modules` and then tried building that project and got the same error there

**Comment by pmurpmur** [comment]
This error can be replicated in the latest version of the ionic-conference-app. Do the following steps:

1. `rm -rf node_modules`
2. `ionic build`

**Comment by jgw96** [comment]
Thanks for the info! Can you make sure that your package.json matches the one [here](https://github.com/driftyco/ionic2-app-base/blob/master/package.json) and then remove node_modules and run npm install? Thanks!

**Comment by pmurpmur** [comment]
Everything works! Thanks

**Comment by astelilani** [comment]
I replaced the package.json, removed node_modules and ran npm install. I am facing the original error again.

[18:57:10]  Error: Metadata version mismatch for module /Users/Ast-837/Documents/Ionic/myDemoApp/node_modules/angular2/src/http/base_response_options.d.ts, 

            found version undefined, expected 1 
[npm-debug.log.txt](https://github.com/driftyco/ionic-app-scripts/files/545447/npm-debug.log.txt)

**Comment by kleeb** [comment]
@jgw96 I do confirm that with the change of ionic2-app-base package.json everything works
would be good to post an update in https://github.com/driftyco/ionic/blob/master/CHANGELOG.md RC1 Package.json Updates

**Comment by astelilani** [comment]
I am unable to access GitHub due to the current cyber attack. Could you please let me know why this was closed?

Ektaa Lilani
AST Corporation
1755 Park Street, Naperville, IL. 60563
Cell: +1 630-880-7646
elilani@astcorporation.com<mailto:elilani@astcorporation.com> | www.astcorporation.com<http://www.astcorporation.com/>

Please consider the environment before printing this email

On Oct 21, 2016, at 3:20 PM, Justin Willis <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #212<https://github.com/driftyco/ionic-app-scripts/issues/212>.
