### ISSUE TITLE
[Bug] Tslint and webpack processing non specified files

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic-app-scripts#216]
#### Short description of the problem:

I have a folder called `src.1`, when using `ionic serve` both tslint and webpack start linting and transpiling even when they aren't part of the build process.

So i think they are configured to transpile and lint all ts files in any `/src/` regexp? with webpack i would do both lint and transpile and it will only do that with the ones imported by the root file.
#### What behavior are you expecting?

I expect the pipeline to only process files referenced by the root file, not all files in folder, in dev case is `main.dev.ts`, in prod case is `main.prod.ts`.

**Steps to reproduce:**
1. Create new project and update to `ionic-app-scripts` beta.
2. Duplicate the `src` folder and name the copy `src.1` or something.
3. Make a few changes to any file in `src.1` that triggers both a ts transpile error as well as tslint lint error.
4. Hit `ionic serve` in console and watch it complain in files not referenced in the `src/app/main.dev.ts`.

**Which @ionic/app-scripts version are you using?**
Ionic info output:

``` ts
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.37
OS: Distributor ID: Ubuntu Description: Ubuntu 16.10 
Node Version: v6.6.0
```

**Other information:**
This is an example of how it looks in places not referenced, note the paths:
![image](https://cloud.githubusercontent.com/assets/9698639/19621148/28c7b72c-9851-11e6-8f63-dc26a8877bb1.png)

**Comment by Luchillo** [comment]
New test, change folder name:
![image](https://cloud.githubusercontent.com/assets/9698639/19621167/8732b8de-9851-11e6-8201-0c45897e981f.png)

**Comment by Luchillo** [comment]
Ok this is just plain wrong, it's hitting each ts file of project inside subdirectories, including inside www, config and any other folder:
![image](https://cloud.githubusercontent.com/assets/9698639/19621215/9379d0fe-9852-11e6-85c1-e62914dbaeda.png)

It should just lint and transpile the imported/required files by the main file, not each ts file in the projects subfolder.

**Comment by jgw96** [comment]
Thanks for all the testing @Luchillo , we will look into this asap.

**Comment by Luchillo** [comment]
@jgw96 Is that expected behavior or just unexpected?

**Comment by jgw96** [comment]
This is unexpected behavior for sure 😄

**Comment by danbucholtz** [comment]
This is fixed now. Make sure the tsconfig matches the [one we provide](https://github.com/driftyco/ionic2-app-base/blob/master/tsconfig.json).

Thanks,
Dan

**Comment by Luchillo** [comment]
Well, i'm not using `ionic-app-scripts` any more, but at least it's one issue less to fix 😄 .
