### ISSUE TITLE
[Bug][Webpack] Error output not verbose enough

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic-app-scripts#217]
#### Short description of the problem:
The output of the errors are not verbose enough, idk why is it showing me this kind of error all over the app:

![image](https://cloud.githubusercontent.com/assets/9698639/19620739/efee800a-9848-11e6-821c-42cca362cfec.png)

#### What behavior are you expecting?
I would expect the issue to tell me if it is because it can't find the module, type definition or anything like that.

**Which @ionic/app-scripts version are you using?** `@ionic/app-scripts@0.0.37`

**Other information:** 
Here's the end of the terminal output, again not very descriptive as  why the error:
![image](https://cloud.githubusercontent.com/assets/9698639/19620768/5cf993f6-9849-11e6-893a-5f11105c3def.png)

**Comment by danbucholtz** [comment]
@Luchillo,

What more are you expecting to see? It gives you a line number, and tells you exactly what it cannot find.

Thanks,
Dan

**Comment by Luchillo** [comment]
So it is indeed about not finding the class, i can suppose that since i know my project needs aliases and idk how to tell ngc about those aliases, webpack is easy to do that.

I think i hurry too much to make this issue, however with [this](https://forum.ionicframework.com/t/help-us-test-webpack-support-in-ionic-2-app-scripts/67507/33?u=luchillo17) comment i think i'll opt out of ngc and work all with webpack, is there a way to tell the build process to avoid ngc and tslint?

**Comment by danbucholtz** [comment]
@Luchillo,

Not at this time no. The build process is defined the way it is to make things easy for most people. If you need a customized set-up, it may be best to roll your own build.

Thanks,
Dan

**Comment by Luchillo** [comment]
Yeah i thought so, and i'm trying, i have one with webpack however the styles look weird since i updated to RC.0, tomorrow i'll try and copy the src folder to a new project and see how it works.
