### ISSUE TITLE
rollup resolved templateURL for --dev builds with non-standard src path

### ISSUE THREAD

**Issue by strictd** [driftyco/ionic-app-scripts#22]
first my ionic src path has changed from src/app to src/mobile/app, src/pages to src/mobile/pages, etc..

using the relative path of
```typescript
@Component({
  templateUrl: './about.html'
})
```
works on `ionic-app-scripts build`,
does not work on `ionic-app-scripts build --dev` 
which produces and error of

```
Error reading template file, "./about.html": Error: ENOENT: no such file or directory, open '/Users/StrictDev/Documents/update/starter/src/pages/about/about.html'
```

when I use the templateUrl relative like
```typescript
@Component({
  templateUrl: '../../../src/mobile/pages/about/about.html'
})
```
this templateURL works on both prod and dev ionic-app-scripts builds

https://github.com/strictd/angular2-ionic2-webpack to use as a demo.

**Comment by strictd** [comment]
also to note, in my package.json I have included
```
  "config": {
    "ionic_copy": "ionic-copy.config.js",
    "ionic_src_dir": "src/mobile/"
  },
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Can you try this again with the latest app-scripts (just run `npm install` in your app) and by changing the `templateUrl` to `about.html`. Thanks!

**Comment by strictd** [comment]
same issue. i've updated to @2.0.0-rc.0 and @latest both produce the same results

```
[18:23:58]  bundle dev started ...
Error reading template file, "tabs.html": Error: ENOENT: no such file or directory, open '/Users/StrictDev/Documents/update/starter/src/pages/tabs/tabs.html'
Error reading template file, "home.html": Error: ENOENT: no such file or directory, open '/Users/StrictDev/Documents/update/starter/src/pages/home/home.html'
Error reading template file, "about.html": Error: ENOENT: no such file or directory, open '/Users/StrictDev/Documents/update/starter/src/pages/about/about.html'
Error reading template file, "contact.html": Error: ENOENT: no such file or directory, open '/Users/StrictDev/Documents/update/starter/src/pages/contact/contact.html'
[18:24:06]  bundle dev finished in 7.63 s
```

The path should be, /Users/StrictDev/Documents/update/starter/src/mobile/pages/tabs/tabs.html

**Comment by jgw96** [comment]
@strictd sorry for the delay on this one! Is there any reason you are not just using `templateUrl: 'about.html'` ?

**Comment by strictd** [comment]
it was actually me who has the late reply. The path issue has been resolved.

**Comment by jgw96** [comment]
Awesome, great to hear that! Thanks for using Ionic!

**Comment by Ingosmar89219** [comment]
I have same issue. Error: ENOENT: no such file or directory, open 'C:\Users\osmarvirux\Documents\ionic-app-facilito\MoneyMap\www\index.html'

my cmd.. C:\Users\osmarvirux\Documents\ionic-app-facilito\MoneyMap>ionic serve
Running live reload server: http://192.168.0.7:35729
Watching: www/**/*, !www/lib/**/*
V Running dev server:  http://192.168.0.7:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $

MY package.json
{
  "name": "moneymap",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "config": {
    "ionic_copy": "ionic-copy.config.js",
    "ionic_src_dir": "src/mobile/"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.45",
    "typescript": "2.0.6"
  },
  "description": "MoneyMap: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": []
}

Help me please. im noob in Ionic but i love to program with google's frameworks. they are fantastic...! someone can help me?
