### ISSUE TITLE
0.0.37 webpack source code is null

### ISSUE THREAD

**Issue by frankpolkm** [driftyco/ionic-app-scripts#220]
Hi, tried npm install @ionic/app-scripts@beta --save-dev. It works fine, compare to 0.0.36, application start up is much fast especially integrated with firebase which is good! But all ts source files under webpack:// are null (chrome debug mode).

**Comment by Luchillo** [comment]
More specifically the sourcemaps aren't working.

**Comment by konrin** [comment]
In version 0.0.37 the problem persists

**Comment by konrin** [comment]
Who knows how this can be a quick fix?

**Comment by konrin** [comment]
@danbucholtz, any ideas? Because of this bug impossible to debug the project.

**Comment by danbucholtz** [comment]
We'll publish out a `beta` in the next day or so. In the mean time install `@ionic/app-scripts@nightly`. The source maps aren't perfect their but they are at least useable.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Please run `npm install @ionic/app-scripts@beta` to install the latest. Source map support is there. We are working on getting *better* source map support in place. I am going to close this issue for now.

Thanks,
Dan

**Comment by frankpolkm** [comment]
Hi Dan, tried your suggestion, but the source code is compiled js not original ts file. Here is the screen shot: [http://prnt.sc/czrslg](http://prnt.sc/czrslg)

**Comment by cleever** [comment]
@frankpolkm @danbucholtz same here.

0.0.37 => Sourcemaps null.
0.0.37-2 => SourceMaps in js format.

**Comment by danbucholtz** [comment]
@frankpolkm, @cleever, yes, we are well aware of the issue 😄 . We're calling it good enough for now. You can get work done with it. We're working on it.

Thanks,
Dan

**Comment by cleever** [comment]
thanks @danbucholtz you guys are doing a great job. I agree with you that is good enough for now! It's better than nothing. =)
