### ISSUE TITLE
Rollup bundler even when Webpack is specified?

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic-app-scripts#222]
#### Short description of the problem:
I noticed that rollup is always used for bundling even when I specify to use Webpack.

#### What behavior are you expecting?
Webpack to be used.

**Steps to reproduce:**
1. Change the output filename of rollup and webpack through configs.

The following error is show
```
  "config": {
    "ionic_webpack": "./build/config/webpack.config.js",
    "ionic_rollup": "./build/config/rollup.config.js",
    "ionic_bundler": "webpack"
  },
  "scripts": {
    "ngc": "ionic-app-scripts ngc",
    "bundle": "ionic-app-scripts bundle --webpack"
  },
```

**Which @ionic/app-scripts version are you using?**
0.0.36

**Comment by Chris1308** [comment]
I think Webpack only works on 0.0.37.

**Comment by alan-agius4** [comment]
So I guess it's still to come!

**Comment by jgw96** [comment]
Hello, thanks! Our webpack build is in the beta release of app-scripts (v0.0.37) right now, although it will be in a stable release soon. To install the beta you can run `npm install @ionic/app-scripts@beta --save-dev`.

**Comment by alan-agius4** [comment]
Tried to the use the 0.0.37 but for some reason NGC files are not
generated.
