### ISSUE TITLE
Optionally Exit with Error Code 1 when TSLint finds errors

### ISSUE THREAD

**Issue by KyleMcNutt** [driftyco/ionic-app-scripts#223]
I think it would be nice to have the option that fails the build with an error if tslint finds any problems. Personally I would love to see in my CI process a build go red if I happen to miss any tslint print outs in the console.

**Comment by danbucholtz** [comment]
@KyleMcNutt,

I agree. This is a future enhancement that we'll make configurable.

Thanks,
Dan

**Comment by alan-agius4** [comment]
+1

**Comment by danbucholtz** [comment]
This is in master and configurable now. Please see the README for more info.

Thanks,
Dan

**Comment by rolandjitsu** [comment]
@KyleMcNutt you can find the option to fail properly at [Tips](https://github.com/driftyco/ionic-app-scripts#tips).

**Comment by KyleMcNutt** [comment]
Yay!! Thank you guys so much! This is significantly helpful!
