### ISSUE TITLE
ionic serve freezes if manifest.json is missing

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic-app-scripts#224]
#### Short description of the problem:
If you delete the `src/manifest.json` file, `ionic serve` freezes after `build dev finished in ...` line.

#### What behavior are you expecting?
`ionic serve` not freezing

**Steps to reproduce:**
1. Create a new Ionic v2 starter project.
2. delete `src/manifest.json`.
3. install `@ionic/app-scripts@0.0.37` (the bug doesn't seem to happen with 0.0.36)
4. run `ionic serve`

**Which @ionic/app-scripts version are you using?**
`@ionic/app-scripts@0.0.37`

**Comment by Chris1308** [comment]
Maybe this is related? I have no manifest.json, and on Windows i have the same problem:
https://github.com/driftyco/ionic-app-scripts/issues/199

**Comment by imgx64** [comment]
Possibly, I'm also on Windows.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind sharing the reason you are deleting the manifest.json?

**Comment by imgx64** [comment]
I don't remember why I removed it, it was weeks ago. Most likely because it's a hybrid app and it wasn't going to be deployed as a PWA. I've added it back now, but it took me a while to find out why ionic serve was freezing after updating to 0.0.37.

**Comment by jgw96** [comment]
Hello all! So after some debugging this morning this has exposed where we need some better error handling in our copy script. The copy script fails (silently) and then breaks the watch task from ever fully starting. I am looking into making sure that when the copy script runs into a file that is not their that it A: throws a warning and then continues to the next path in the array, B: does not break things in the build down the line.

**Comment by danbucholtz** [comment]
I am tracking this is issue here so I am going to close this.

https://github.com/driftyco/ionic-app-scripts/issues/246

Thanks,
Dan

**Comment by morrisonbrett** [comment]
I moved manifest.json from where I had it to the root of src and can confirm no `ionic serve` is no longer hanging on 0.0.37-2 on Windows 10.

**Comment by macdasi** [comment]
Why did you close this issue ? it's still an error at 0.0.38

**Comment by danbucholtz** [comment]
@macdasi,

What is the error that you're seeing?

Thanks,
Dan

**Comment by macdasi** [comment]
I've just added 2 files to src , the manifest and service worker .js and now build is working , before the build process is stack with error on "can't find files" ... I wonder since which version it is a must to add the files into src ?

**Comment by danbucholtz** [comment]
@macdasi, It shouldn't prevent the build from going through either way. That is a bug on our end if that is the case. It should just report the issue and continue on.

Thanks,
Dan

**Comment by macdasi** [comment]
It prevents

**Comment by danbucholtz** [comment]
@macdasi, are you on windows? I just tested this on my Mac and Node 4.x LTS and it works as expected.

Thanks,
Dan

**Comment by macdasi** [comment]
windows 7

**Comment by danbucholtz** [comment]
@macdasi, cool, I think this is a Windows only issue. I'll fire up my Windows instance and test it out.

Thanks,
Dan
