### ISSUE TITLE
Cannot find module '../../package.json'

### ISSUE THREAD

**Issue by masimakopoulos** [driftyco/ionic-app-scripts#225]
Trying to import package.json using latest version of ionic-app-scripts (0.0.36) gives a compile error.
```
[12:56:05]  transpile started ...
[12:56:06]  lint started ...
[12:56:14]  typescript: src/app/app.config.ts, line: 2
            Cannot find module '../../package.json'.
[12:56:14]  transpile failed

       L1:  import { Injectable } from '@angular/core';
       L2:  import p from '../../package.json';
```

Couldn't find an example in @danbucholtz [mega test](https://github.com/danbucholtz/ionic-third-party-lib-mega-test/blob/master/src/app/app.module.ts) project that imports a json file. 
Also adding .json to rollup.config.json nodeResolve extensions does not help.
```
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js', '.json']
    }),
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind installing the latest beta release of app-scripts by running `npm install @ionic/app-scripts@beta --save-dev` and trying this again? That release uses webpack by default which should handle this better out of the box than rollup.

**Comment by masimakopoulos** [comment]
Hi @jgw96, I have no problem trying out app-scripts beta, but it is my understanding that you will not drop rollup for webpack, but offer it as an alternative. Is that not the case? 
If so I would think solving rollup issues is still important. If you are dropping rollup for webpack, then it makes sense to stop trying to work around issues.

**Comment by masimakopoulos** [comment]
I can confirm that using latest app scripts 0.0.37 I can use require imports to include package.json.

```
const p = require('../../package.json');
```

not really ES6, but I guess will have to do for now.

**Comment by jgw96** [comment]
Hello @masimakopoulos You are correct that we still offer rollup as the alternative and will continue to develop both the rollup part of app-scripts and the webpack part of app-scripts. The reason I mentioned trying webpack is because importing JSON files is not supported by the ES6 module spec, which rollup follows strictly. Webpack however does allow things like importing json files as it follows the non-standard commonjs spec instead. If you would like to continue using rollup (which does provide slightly smaller/faster bundles than webpack) i would recommend loading json files with the `http` module in Angular 2 instead of importing them. Thanks!

**Comment by masimakopoulos** [comment]
@jgw96 just to clear things up a bit, I am now using webpack and the import works using require instead of import. Also I believe what you are stating about rollup not being able to load json files through imports is incorrect.

The rollup documentation on the section about plugins actually has an [example](http://rollupjs.org/guide/) that uses the rollup-plugin-json plugin to load package.json using es6 syntax. 

```
import { version } from '../package.json';
export default function () {
  console.log('current version is ' + version);
}
```

as long as you enable the plugin
```
import json from 'rollup-plugin-json';

export default {
  entry: 'src/main.js',
  format: 'cjs',
  plugins: [ json() ],
  dest: 'bundle.js'
};
```

And in this projects package.json I see you are actually listing this plugin in [dependencies](https://github.com/driftyco/ionic-app-scripts/blob/master/package.json#L41) and you are actually enabling it in the [default config](https://github.com/driftyco/ionic-app-scripts/blob/master/config/rollup.config.js#L49) so this should work out of the box, but it doesn't.

Is there something I am missing?
