### ISSUE TITLE
watch mode bundle update is not working

### ISSUE THREAD

**Issue by shlomiassaf** [driftyco/ionic-app-scripts#23]
When in `watch` mode the first compilation works fine.

After an update the new rollup bundle is not updating in the browser, while code changes the browser still see's the "old" version.

The bundle is indeed updated but the destination is not right, for every update calling `bundleUpdate` it will call `runBundle`.

`runBundle` does this:
```
    rollupConfig.dest = join(context.buildDir, rollupConfig.dest);
```

so this will concat the directory path on itself on every call.

I have created a pull request, it is valid as long as `context.buildDir` is absolute.

**Comment by mixersoft** [comment]
FYI - until the fix is out, it seems that `watch` works correctly with `ionic serve --lab`

**Comment by fifafu** [comment]
Can confirm that the fix from @shlomiassaf solves the issue. Thank you!

**Comment by jamesgroat** [comment]
#24 fixes this for me also. Thanks.

**Comment by mlynch** [comment]
I can confirm this works as well, going to merge the PR. Thanks so much @shlomiassaf!

**Comment by cmaart** [comment]
Same issue as in #59 
Basically it's solved twice now :-)
