### ISSUE TITLE
ngc doesn't allow components in source that aren't being used

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-app-scripts#233]
If you have a `@Component` defined somewhere, but the component isn't being declared in `NgModule`, `ngc` complains with

`Error: cannot determine the module for component MyComponent`

This means you can't really work on partial components without immediately including them in `NgModule`.

**Comment by jgw96** [comment]
@mlynch I am working on updating the framework to the latest NGC and Angular which may include a fix for this [here](https://github.com/driftyco/ionic/pull/8921).

**Comment by danbucholtz** [comment]
Pretty sure we have a fix for this that will go live with the app-scripts release. It will involve adding an `include` statement to `tsconfig`.

I'll verify and update at some point.

Thanks,
Dan

**Comment by danbucholtz** [comment]
@mlynch,

This is fixed as long as the module isn't imported anywhere. I think that's a reasonable behavior.

Thanks,
Dan
