### ISSUE TITLE
Clean task not working

### ISSUE THREAD

**Issue by jcviau** [driftyco/ionic-app-scripts#235]
#### Short description of the problem:

Calling ionic-app-script clean fail because clean.js file doesnt return an object that has a property catch. index.js expect all task to have a catch property because it calls this :  
`require("../dist/" + task)[task]().catch(function (err) {`

**Log information:**
[17:34:04]  ionic-app-script task: "clean" 
[17:34:04]  TypeError: Cannot read property 'catch' of undefined 
#### What behavior are you expecting?

Should be able to call ionic-app-script clean without errors or the task should removed from the documentation here: see https://github.com/driftyco/ionic-app-scripts/blob/master/README.md.

**Steps to reproduce:**
1. Run this command ionic-app-script clean

**Which @ionic/app-scripts version are you using?**
0.0.37

**Comment by nottinhill** [comment]
We are seeing same issue.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Does this issue also happen when running `npm run watch` which also calls clean? Or does it only happen when calling the clean script separately?

**Comment by jcviau** [comment]
Only when calling the clean script separately. It works when called from build or watch.

**Comment by rolandjitsu** [comment]
Has this been released, I just tried to clean today and I still get the same error.

**Comment by danbucholtz** [comment]
@rolandjitsu,

Not yet. Should be coming in `0.0.40` in the coming day(s).

Thanks,
Dan

**Comment by withinsight** [comment]
I'm on 0.0.43 and running clean or copy independent of the build or serve processes doesn't seem to work. Here are the lines I added to the scripts block in package.json:

"ionic:clean": "ionic-app-scripts clean",
"ionic:copy": "ionic-app-scripts copy"
