### ISSUE TITLE
ionic build does not update already present files of assets folder

### ISSUE THREAD

**Issue by nottinhill** [driftyco/ionic-app-scripts#236]
#### Short description of the problem:

Best-Practice in GitHub Ionic 2 RC0 Changelog is to use the `src/assets` folder. This is should then be copied over by ionic-app-scripts to `www/assets`. But, when the folder already exists, this is not happening. My team, and the whole community, is at the moment manually deleting the `www/assets` folder, on each and every build when we changed files in `src/assets` folder.

#### What behavior are you expecting?

`www/assets` folder needs to be cleaned out before copy in order for legacy files to be overridden. 

**Steps to reproduce:**
1. touch `www/assets/foo`  
2. echo "bar" >`src/assets/foo`
3. ionic build
4. cat `www/assets/foo` // no bar

**Which @ionic/app-scripts version are you using?**

0.0.36

**Comment by nottinhill** [comment]
4. must be: www/assets/foo,  witch no bar in it.

**Comment by nottinhill** [comment]
4 not 1

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has been fixed in the master branch and will be in the next release.

**Comment by nottinhill** [comment]
Thanks a million Justin! Could you kindly post/link the code in order patch our current version already?

**Comment by ehorodyski** [comment]
I'm having this issue running `"@ionic/app-scripts": "3.1.8"`
