### ISSUE TITLE
bug: [Bug] Ionic build android broken, ionic serve ok

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#241]
_From @Luchillo on October 25, 2016 16:35_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm using `ionic build android` to see the actual output of the compilation process, however it shows errors without any file line number, not very explicit, while the `ionic serve` command works ok:

![image](https://cloud.githubusercontent.com/assets/9698639/19695049/4ae0c97c-9aa7-11e6-9fd5-02ad1db7a990.png)

</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#8904_

**Comment by mhartington** [comment]
The build is not broken. It is saying that you have a type error.

When you build for the native platform, it does a production build, so it goes through stricter type checking. We don't do that for serve. So you need to fix the type error.

**Comment by Luchillo** [comment]
Ok, it says type error but doesn't say where, it only says that cannot find 'map' property.

Where am i supposed to look? also this project was working in beta.11, i would expect that if I've been developing with `serve` command it would work the same when i hit `build` command.

**Comment by mhartington** [comment]
>this project was working in beta.11

Beta 11 vs RC is a big difference. Considering the build changes were quite different and ngc/AoT were not a thing then. 

Anyways, back to the main point....

Can you provide the app-scripts version in the package.json?

**Comment by Luchillo** [comment]
Its 0.0.37 for webpack support.

**Comment by mhartington** [comment]
can you run `npm install @ionic/app-scripts@beta` again to get the latest.

**Comment by Luchillo** [comment]
Yes it's very big difference, the thing that took me by surprise was the fact that AoT makes stricter type checking.

Also i think `0.0.37` is the actual beta version, right?

**Comment by Luchillo** [comment]
Same result, `ionic build` outputs error, while `ionic serve` works ok, here's the new info after updating `app-scripts`:

```ts
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.37
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.10 
Node Version: v6.6.0
```

**Comment by Luchillo** [comment]
All ionic parts (cli, framework and app-scripts) are at most recent version or beta and the error still says the same thing, no clue where that type error is pointing.

**Comment by mhartington** [comment]
Yes, as I said, thats to be expected, since serve *does not* run ngc.

In your app, are you using `array.map` anywhere in your app? 

Also, in the `build` entry of your package.json, can your add `--debug`

so it should read.

```
  "scripts": {
    "build": "ionic-app-scripts build --debug",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
```

**Comment by Luchillo** [comment]
I'm mostly using `lodash-es map`, i tried earlier with `ionic build android --debug` and only saw a few memory sizes, now it shows this:

![image](https://cloud.githubusercontent.com/assets/9698639/19701456/1c807ae0-9ac1-11e6-89e2-9bd8c3c7ce0a.png)

**Comment by Luchillo** [comment]
I've searched for '.map' and some come from the `service-worker.js` that the new project brings by default, the only other one i'm using is the `.map` from an observable after a `.delay`, however i don't think it is because i'm using this on top of that file:

```ts
import 'rxjs/add/operator/retry';
import 'rxjs/add/operator/timeout';
import 'rxjs/add/operator/delay';
import 'rxjs/add/operator/map';
```

**Comment by Luchillo** [comment]
When it says `Cannot read propery 'map' of undefined` most likely it's a call like `someVar.map(...)` and in some point that `someVar` is undefined according to typecheck, right?

I've commented all `.map(...)` function calls in my source code, so i think it's not my code that generates this issue.

**Comment by danbucholtz** [comment]
@Luchillo,

Sorry, the error messages from the Angular compiler are not great. There isn't a whole lot we can do about that beyond lobby the team to improve them (which we are doing). If you don't want to use `ngc`, through a `--dev` at the end of `npm script` for `build`.

Thanks,
Dan

**Comment by Luchillo** [comment]
Will still compile for an apk?
