### ISSUE TITLE
Cannot build after adding new page to project

### ISSUE THREAD

**Issue by janfreymann** [driftyco/ionic-app-scripts#242]
After adding a new page to the project using

ionic g page map2

I can use the page with ionic serve, but ionic build gives the following error:

bundle failed: Unexpected character '@' (10:0) in /Users/raumklang_spare/Desktop/JF/klangerfinder/lubu_tourist2016/ionic2/LBGuide2016/.tmp/pages/lubu-map/lubu-map.ts 
[22:37:52]  ionic-app-script task: "build" 
[22:37:52]  SyntaxError: Unexpected character '@' (10:0) in /Users/raumklang_spare/Desktop/JF/klangerfinder/lubu_tourist2016/ionic2/LBGuide2016/.tmp/pages/lubu-map/lubu-map.ts 

**Steps to reproduce:**
1. start new ionic v2 project
2. ionic g page LubuMap
3. add LubuMap to app.module.ts
4. ionic build

```
//new page:

import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

/*
  Generated class for the LubuMap page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Component({      //unexpected character @
  selector: 'page-lubu-map',
  templateUrl: 'lubu-map.html'
})
export class LubuMap {

  constructor(public navCtrl: NavController) {}

  ionViewDidLoad() {
    console.log('Hello LubuMap Page');
  }

}


//app.module.ts:
import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';

import { HomePage } from '../pages/home/home';

import { LubuMap } from '../pages/lubu-map/lubu-map';

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    LubuMap
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    LubuMap
  ],
  providers: []
})
export class AppModule {}
```

**Which @ionic/app-scripts version are you using?**

Your system information:

Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.36
ios-deploy version: Not installed
ios-sim version: 5.0.9 
OS: Mac OS X Yosemite
Node Version: v6.0.0
Xcode version: Xcode 6.4 Build version 6E35b

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue. Would you mind installing the latest beta release of app-scripts by running `npm install @ionic/app-scripts@beta` and trying again?

**Comment by janfreymann** [comment]
Thank you, installing the latest beta of the app-scripts let the ionic build run without errors. However, when I emulate the iOS version, the error is back again:

ionic $ 0     735371   error    Error: Module parse failed: /Users/raumklang_spare/Desktop/JF/klangerfinder/lubu_tourist2016/ionic2/LBGuide2016/node_modules/@ionic/app-scripts/dist/loaders/ionic-loader.js!/Users/raumklang_spare/Desktop/JF/klangerfinder/lubu_tourist2016/ionic2/LBGuide2016/.tmp/pages/lubu-map/lubu-map.ts **Unexpected character '@' (10:0)
You may need an appropriate loader to handle this file type.**
|   Ionic pages and navigation.
| */
| @Component({
|   selector: 'page-lubu-map',
|   templateUrl: 'lubu-map.html', http://192.168.1.19:8100/build/main.js, Line: 28

**Comment by janfreymann** [comment]
Thank you, installing the latest beta of the app-scripts let the ionic build run without errors.  It is working now.
