### ISSUE TITLE
custom config files not working for PROD 

### ISSUE THREAD

**Issue by shlomiassaf** [driftyco/ionic-app-scripts#25]
Hi,

When setting the path to a config file in the package.json or using arguments in **PROD** mode the resolved file is always the default version of the config.

in `runBundle`:
```
  const taskInfo = (options.isProd) ? ROLLUP_PROD_TASK_INFO : ROLLUP_TASK_INFO;
  rollupConfig = fillConfigDefaults(context, rollupConfig, taskInfo);
```
The task is identified as PROD and sent to **fillConfigDefaults**.

**fillConfigDefaults** will load the configuration files using **getConfigFileData** (util.ts)
```
getConfigFileData(task.fullArgConfig, task.shortArgConfig, task.envConfig, null, context) || {};
```

Now, let's assume using config values from `package.json` (env). There is not way to distinguish between prod / dev in the `config` section so the end result is always loading `xxx.config.js` and not `xxx.prod.config.js`. **getConfigFileData** does not implement prod/dev file selection.

Since `config` inside `package.json` is not aware of prod/dev modes you probably need to decide on a convention to load files based on configuration preset. Something like add `.prod` for prod etc...

**Comment by strictd** [comment]
You could pass your production config file in with command line arguments
`--rollup ionic-rollup-prod.config.js`

the other option would be to update src/bundle.ts line 159 to something like `envConfig: 'ionic_rollup_prod',`

**Comment by shlomiassaf** [comment]
@strictd the 1st option, using arguments, will probably work but I prefer using the `config` object.

Yes, explicitly looking for `ionic_rollup_prod` can be added to the code but then a user will need to do that for every config file, this is not ideal.

I think a convention should take place and having 1 config file with added convention name.

**Comment by strictd** [comment]
are you looking for prod configs for all ionic-app-script configs or just the rollup config? There is a rollup.prod.config.js file that the bundler defaults to on production builds.

**Comment by shlomiassaf** [comment]
@strictd I know the is a `rollup.prod.config` in the package, that's the point of this issue - being able to override it.

**Comment by strictd** [comment]
I see your point.. Originally my thought was you wanted a complete second set of config files for prod. Which could be useful past the rollup configs for reasons nobody has thought of yet.

**Comment by adamdbradley** [comment]
We're not using a single rollup config file: https://github.com/driftyco/ionic-app-scripts/blob/master/config/rollup.config.js#L56

Within the configs you can now check for: `process.env.IONIC_ENV == 'prod'`

**Comment by kleeb** [comment]
doing npm run build or ionic build goes production
