### ISSUE TITLE
ionic build copies www/assets to platforms and not src/assets 

### ISSUE THREAD

**Issue by nottinhill** [driftyco/ionic-app-scripts#250]
#### Short description of the problem:

`ionic build` copies to platforms folder from www/assets and not from src/assets. Same for index.html. So in order run to develop on device we need to:

`rm -rf www`
`ionic build` 
`ionic run`

#### What behavior are you expecting?

All for the run on device folder should be taken from src. 
aka ionic run should perform ionic build first. 

**Steps to reproduce:**
1. create unique file in your src/assets folder
2. look at assets folder
3. ionic run
4. watch the unique file in src/assets folder not being copied over to platforms folder.

**Which @ionic/app-scripts version are you using?**

0.0.36

This whole topic needs some more testing on Ionic teams side in my opinion.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1599

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is a cli issue and not an app-scripts repo I have moved this issue to the cli repo. Thanks!
