### ISSUE TITLE
Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.

### ISSUE THREAD

**Issue by jthoms1** [driftyco/ionic-app-scripts#256]
_From @tlambrou on October 20, 2016 5:55_

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:
Cannot type `ionic serve` without getting the following error

#### What behavior are you expecting?
Seeing my code run in a browser

**Steps to reproduce:**
1. Installed node 6
2. Installed ionic and cordova
3. Verified that repository works on other machines

```
ionic serve

Running 'serve:before' npm script before serve

> ionic-hello-world@ watch /Users/Tassos/Dropbox/Code/LittleBrother
> ionic-app-scripts watch

sh: ionic-app-scripts: command not found

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch" "--color"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ionic-hello-world@ watch: `ionic-app-scripts watch`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Tassos/Dropbox/Code/LittleBrother/npm-debug.log
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Post the output of `ionic info` below please**

```
ionic info
--------------------------------
--------------------------------

Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.0 Build version 8A218a 


--------------------------------
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

_Copied from original issue: driftyco/ionic-cli#1564_

**Comment by jthoms1** [comment]
_From @MiriKabrt on October 20, 2016 7:15_

I have similar issue. When i run "ionic serve" then everythink is ok. But when i run "ionic run android" it show me this error:

[09:09:28]  Error: Error at /Users/Miri/Prace/Level/Mobile/apprc1/.tmp/pages/summary/summary.ngfactory.ts:1091:72
[09:09:28]  Supplied parameters do not match any signature of call target.
[09:09:28]  ngc failed
[09:09:28]  ionic-app-script task: "build"
[09:09:28]  Error: Error

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.8.1/bin/node" "/usr/local/bin/npm" "run" "build" "--color"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Miri/Prace/Level/Mobile/apprc1/npm-debug.log
Caught exception:
 undefined



Problem is in pipe "... | momentdt: 'LT'"

**Comment by jthoms1** [comment]
_From @rodrigograca31 on October 20, 2016 10:28_

Same issue as #1562 please close it or mark it as duplicate....

**Comment by jthoms1** [comment]
_From @cimenx on October 22, 2016 6:18_

@tlambrou i solve this by adding ionic-app-scripts to the project
`npm install @ionic/app-scripts@latest --save-dev`

**Comment by jthoms1** [comment]
_From @rodrigograca31 on October 24, 2016 11:51_

Didn't solve the problem in my case....
It was `@ionic/app-scripts@0.0.36` and stayed the same...

**Comment by jthoms1** [comment]
_From @tlambrou on October 25, 2016 3:3_

In my case it appears that the problem was related to having my ionic app running in a folder that was synced to cloud services (Dropbox, iCloud). After moving the directory to a non-synced folder, things began working again. # #

**Comment by jthoms1** [comment]
_From @rodrigograca31 on October 25, 2016 10:25_

@tlambrou That doesn't make sense.... Can you confirm that?
I have my project on a "non-synced folder" and tried to move it to another folder and didn't help...

**Comment by danbucholtz** [comment]
@tlambrou,

Glad you were able to get it resolved. @rodrigograca31, any updates on this? This is unexpected and we need more info to troubleshoot.

For now, I am going to close this. Will re-open if needed.

Thanks,
Dan

**Comment by rodrigograca31** [comment]
@danbucholtz No, I've not solved the problem.... What info do you need?

Since you guys move this issue I nee to add again that this is the same problem as #253 

Running these commands again still creates the same problem:
```
ionic start app4 --v2
cd app4
ionic run android
cordova platform add android
ionic run android
```

`ionic info` report:
```
--------------------------------

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS: Distributor ID:     LinuxMint Description:  Linux Mint 17.3 Rosa 
Node Version: v0.12.7

--------------------------------
```

I tough we could already create apps using Ionic 2 but apparently not....

**Comment by danbucholtz** [comment]
@rodrigograca31,

Please give me some output or error information. Right now I have literally nothing to work off of.

Thanks,
Dan

**Comment by rodrigograca31** [comment]
@danbucholtz `" I have literally nothing to work off of."` What? If you scroll up there's the error information.... On the issue it self.... and as I mentioned before it's the same problem as #253 so my own output is on #253 this was a duplicated issue..... but....

**Comment by danbucholtz** [comment]
@rodrigograca31, See my comment [here](https://github.com/driftyco/ionic-app-scripts/issues/253#issuecomment-257069823).

Thanks,
Dan

**Comment by brucecantarim** [comment]
Hi!

Just to let you guys know, I was facing the same problem (sh: ionic-app-scripts: command not found) in my macbook, and I managed to solve this problem running yarn instead of npm install. You might have to use sudo.

Cheers!

**Comment by elimsuhendra** [comment]
i have problem when ionic serve for ionic start --v2 ionic-todo blank

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed

Ionic serve:

> ionic-hello-world@ ionic:serve D:\bootcamp_ionic\ionic-todo
> ionic-app-scripts serve

[16:20:04]  ionic-app-scripts 0.0.45
[16:20:04]  watch started ...
[16:20:04]  build dev started ...
[16:20:04]  clean started ...
[16:20:04]  clean finished in less than 1 ms
[16:20:04]  copy started ...
[16:20:04]  transpile started ...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen ENOTSOCK 0.0.0.0:53703
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1244:19)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts
serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\bootcamp_ionic\ionic-todo\npm-debug.log
There was an error serving your Ionic application: There was an error with the s
pawned command: serve


Help me please ?

**Comment by danbucholtz** [comment]
@jthoms1,

What do you think of the above issue?

Thanks,
Dan

**Comment by ngrealish** [comment]
I had this same issue.  I found that when I initialized my app, I did so in terminal.  So I had already run Ionic serve.  The server was running but I could only tell in the terminal app.  I then went into my IDEA (IntelliJ) and tried to run ionic serve in the terminal there.  I then go the same error you showed above.  

After fiddling, I noticed it was already running... silly me.

**Comment by MadhavBitra** [comment]
@ionic/app-scripts@latest --save-dev has worked for me

**Comment by nanomo** [comment]
Had similar issue:

Windows 7 64 bits

node -v
v6.10.1
npm -v
4.4.4
Your system information:

Cordova CLI: 6.4.0
Gulp version: CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 1.2.5
OS: Windows 7 SP1
Node Version: v6.10.1

````
C:\apps\someapp>npm run meteor-client:bundle

ionic-hello-world@ meteor-client:bundle C:\apps\someapp
meteor-client bundle -s api
Created a new Meteor app in
'C:\Users\MALDIT~1\AppData\Local\Temp\tmp-20527S7sUIvnECrM'.

To run your new app:
cd C:\Users\MALDIT~1\AppData\Local\Temp\tmp-20527S7sUIvnECrM
meteor

If you are new to Meteor, try some of the learning resources here:
https://www.meteor.com/learn

meteor create --bare to create an empty app.
meteor create --full to create a scaffolded app.

Changes to your project's package version selections:

barbatus:typescript added, version 0.6.5_1
barbatus:typescript-compiler added, version 0.9.5
barbatus:typescript-runtime added, version 1.0.0

WARNING: The output directory is under your source tree.
Your generated files may get interpreted as source code!
Consider building into a different directory instead
meteor build ../output

C:\Users\malditowindows\AppData\Local.meteor\packages\meteor-tool\1.4.3_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190

  throw error;
  ^
RangeError: Maximum call stack size exceeded
C:\Users\malditowindows\AppData\Roaming\npm\node_modules\meteor-client-bundler\n
ode_modules\execa\index.js:277
throw (result.error || new Error(result.stderr === '' ? result.s
tdout : result.stderr));
^

Error: null
at Function.module.exports.sync (C:\Users\malditowindows\AppData\Roaming\npm
\node_modules\meteor-client-bundler\node_modules\execa\index.js:277:26)
at Object.bundle (C:\Users\malditowindows\AppData\Roaming\npm\node_modules\m
eteor-client-bundler\lib\bundler.js:72:9)
at Command. (C:\Users\malditowindows\AppData\Roaming\npm\node_mod
ules\meteor-client-bundler\cli:37:13)
at Command.listener (C:\Users\malditowindows\AppData\Roaming\npm\node_module
s\meteor-client-bundler\node_modules\commander\index.js:301:8)
at emitTwo (events.js:106:13)
at Command.emit (events.js:191:7)
at Command.parseArgs (C:\Users\malditowindows\AppData\Roaming\npm\node_modul
es\meteor-client-bundler\node_modules\commander\index.js:615:12)
at Command.parse (C:\Users\malditowindows\AppData\Roaming\npm\node_modules\m
eteor-client-bundler\node_modules\commander\index.js:458:21)
at Object. (C:\Users\malditowindows\AppData\Roaming\npm\node_modu
les\meteor-client-bundler\cli:45:9)
at Module._compile (module.js:570:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-hello-world@ meteor-client:bundle: meteor-client bundle -s api
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ meteor-client:bundle script 'meteor-cl
ient bundle -s api'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! meteor-client bundle -s api
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.`
```
