### ISSUE TITLE
Not able to build in android

### ISSUE THREAD

**Issue by jthoms1** [driftyco/ionic-app-scripts#259]
_From @jayeshanandani on October 21, 2016 7:5_

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:
When I try to build in android I encounter the below-mentioned error in the image. Same works in ionic ios build.

#### What behavior are you expecting?
Build should pass.

**Steps to reproduce:**
1. Clone ionic-conference-app
2. Run ionic build android
3. See error in console.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**
![capture](https://cloud.githubusercontent.com/assets/3860787/19589602/cbad17e2-978a-11e6-884b-c3c0d88535b9.PNG)

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

_Copied from original issue: driftyco/ionic-cli#1571_

**Comment by jthoms1** [comment]
_From @sfraga94 on October 21, 2016 10:50_

Same problem

**Comment by jthoms1** [comment]
_From @vintage on October 21, 2016 11:37_

You can try temporary solution which I've put in https://github.com/driftyco/ionic-cli/issues/1574

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by jayeshanandani** [comment]
@jthoms1 : Below is the attached screenshot for ```ionic info```

![image](https://cloud.githubusercontent.com/assets/3860787/19795438/3805cfb0-9c90-11e6-8987-2f0e98b14fbd.png)

**Comment by danbucholtz** [comment]
@jayeshanandani,

Please remove the `^` character for your package.json file. Angular ahead-of-time compiler broke something on us so we had to stop relying on their wildcard for now.

Go to `2.0.0` and everything should work.

Thanks,
Dan

**Comment by jayeshanandani** [comment]
@danbucholtz : Yes that works fine if we remove that ```^``` character.
