### ISSUE TITLE
Changes of templates are ignored during buildUpdate

### ISSUE THREAD

**Issue by jthoms1** [driftyco/ionic-app-scripts#260]
_From @jgw96 on September 26, 2016 16:51_

_From @olostan on September 26, 2016 16:16_

ionic 2.1.0-beta.2

When I run `ionic serve`, everything works ok until i change templates - app reloads, but templates are without my changes. Only stopping `ionic serve` and run again helps… making development process extremely slow

Seems `ng-template` plugin is not re-run or does not receive changes of templates.

_Copied from original issue: driftyco/ionic#8216_

_Copied from original issue: driftyco/ionic-cli#1413_

**Comment by jthoms1** [comment]
_From @olostan on September 26, 2016 16:57_

The only workaround I've found is to disable `rollup` cache in `@ionic/app-scripts/dist/bundle.js` (bundleApp function) by commenting:
```
bundleCache = bundle;
```

**Comment by jthoms1** [comment]
_From @cozzbie on September 27, 2016 16:13_

This issue still presents. +1

**Comment by danbucholtz** [comment]
@olostan, @cozzbie,

This issue is resolved. Please install `@ionic/app-scripts@latest`. We're releasing `@ionic/app-scripts@0.0.37` tomorrow with a load of bug fixes so it would be a good idea to check that out.

Thanks,
Dan
