### ISSUE TITLE
No source mappings for providers

### ISSUE THREAD

**Issue by jthoms1** [driftyco/ionic-app-scripts#262]
_From @golear91 on October 13, 2016 1:47_

When debugging my Ionic2 application on an android device and connected via the Chrome Debugger, I see that the source mapping has nicely made my .ts files available for everything in the /pages folder however all of my services in the /providers folder are not available.

[![enter image description here][1]][1]
What gives?

when I debug using `ionic serve` i can see the /providers files in another form:
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/HVxs7.png
  [2]: https://i.stack.imgur.com/j6Znb.png

_Copied from original issue: driftyco/ionic-cli#1529_

**Comment by danbucholtz** [comment]
Hi @golear91,

This issue was long since resolved. Please run `npm install @ionic/app-scripts@latest`. We're releasing `@ionic/app-scripts@0.0.37` tomorrow it has a ton of fixes, so go ahead and install that.

Thanks,
Dan

**Comment by golear91** [comment]
thanks!
