### ISSUE TITLE
Failed optional dependency /chokidar/fsevents

### ISSUE THREAD

**Issue by jthoms1** [driftyco/ionic-app-scripts#263]
_From @rashid-softordi on October 12, 2016 18:22_

I am installing "cordova-plugin-geolocation" via npm but "cordova-plugin-geolocation" is unable to intsall. Getting the Warnings

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

Any possible solution?

_Copied from original issue: driftyco/ionic-cli#1528_

**Comment by danbucholtz** [comment]
@rashid-softordi,

Have you resolved this issue? Sorry, the best place to look for Ionic help is the Ionic [forum](https://forum.ionicframework.com/). If there is an issue with the framework or the build process itself, I'll re-open this issue.

Thanks,
Dan
