### ISSUE TITLE
JavaScript out of heap memory

### ISSUE THREAD

**Issue by jthoms1** [driftyco/ionic-app-scripts#266]
_From @Bandito11 on October 6, 2016 17:45_

Version: @ionic/app-scripts version 0.0.28

Issue:

After running it for awhile the message appeared and the cli just stopped compiling and running the livereload. 

It was fixed in the 0.0.29 of the @ionic/app-scripts.  

_Copied from original issue: driftyco/ionic-cli#1482_

**Comment by danbucholtz** [comment]
@Bandito11,

Today (Friday) we are releasing `@ionic/app-scripts@0.0.37`. This issue has been resolved for awhile, but you may want to install the latest tomorrow.

Thanks,
Dan
