### ISSUE TITLE
Adding a new method/function need restart of ionic serve

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#267]
Hello,

I'm using version 0.0.36 (rollup). While my ionic serve is running, if I add a new method/function in a typescript class and the call in the html page, even after the automatic compilation is triggered, the new method/function not gonna be exposed for the runtime.

If I reload my app in my browser and try to access the page where I just did a change, I gonna end up on an error telling me that the new function/method doesn't exists, like:

    error_handler.js:53 TypeError: self.context.isNotFirstSlide is not a function

To solve such cases, I have to shutdown and restart my server each time.

Best regards

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you install the latest beta of app-scripts (`npm install @ionic/app-scripts@beta --save`) and try again? The latest beta has a ton of bug fixes.

**Comment by peterpeterparker** [comment]
thx@jgw96 the beta solve that issue, coolio!

**Comment by jgw96** [comment]
Glad to hear! We are hoping to release this beta as a stable release asap today.
