### ISSUE TITLE
Webpack dev config

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic-app-scripts#269]
#### Short description of the problem:
The dev entry point config of webpack should point to TS and not JS
https://github.com/driftyco/ionic-app-scripts/blob/master/config/webpack.config.js#L16

**Which @ionic/app-scripts version are you using?** 0.0.37

**Comment by jgw96** [comment]
Hello, thanks for the PR! I am going to close this for now after the conversation on that PR.
