### ISSUE TITLE
Can't debug in chrome with 0.0.37-2

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#275]
Hey,

With version 0.0.36 I was able to debug in chrome.

Yesterday I install 0.0.37-2 (following https://github.com/driftyco/ionic-app-scripts/issues/267) and now I notice that I'm not able anymore to debug in chrome.

Is that a bug or is there any new configuration required to enable that functionality?

Thx in advance for your feedback

**Comment by lordgreg** [comment]
Exactly the same issue here. I've updated `app-scripts` using `latest` flag because I was tired of waiting 10 seconds every time I've changed a file, so currently, I'm using 0.0.38, but... joy...

NO SOURCEMAPS.

👎

**Comment by danbucholtz** [comment]
@lordgreg, @peterpeterparker,

Hmm. That is not the expected result. I'll investigate and publish a fix asap.

Thanks,
Dan

**Comment by peterpeterparker** [comment]
Thx a lot in advance @danbucholtz 

Just installed 0.0.38 same...but also won't be surprised if I missed something...again

**Comment by danbucholtz** [comment]
This is fixed in `0.0.39`. I have another issue tracking the `Typescript` sourcemaps which will be out in `0.0.40`.

Thanks,
Dan

**Comment by lordgreg** [comment]
Thank you for the fix @danbucholtz.

So should the sources now be really visible under opening 232 sub-folders? :)

![image](https://cloud.githubusercontent.com/assets/480546/19881586/634e40b0-a007-11e6-94cc-cf639620f9bd.png)
