### ISSUE TITLE
VERSION_DOWNGRADE error after moving to V2

### ISSUE THREAD

**Issue by loursbourg** [driftyco/ionic-app-scripts#278]
#### Short description of the problem:

My app was working just fine before i decided to migrate to V2. But when i tried to **ionic run** the new  version that is made with ionic 2, i got a **version downgrade** error even though i incremented the version from '1.2.4' to '2.0.0'.
#### What behavior are you expecting?

Umm, **LAUNCH SUCCESS**?

```
Error: Failed to install apk to device: pkg: /data/local/tmp/android-debug.apk
Failure [INSTALL_FAILED_VERSION_DOWNGRADE]

You're trying to install apk with a lower versionCode that is already installed.
Either uninstall an app or increment the versionCode.
```

**Note:**
The app works very normally when i remove the old version and install the newer one. However, **Google Play** doesn't allow me to publish that new version as it has the thingy downgrade error.
**Ionic info:**
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 8.1
Node Version: v6.7.0

**Comment by loursbourg** [comment]
The version that is currently on the google play 1.0.4 with Version code 100048. Which i think is the cause of error as when i ionic run the new version, adb thinks i'm tryina downgrade, thus throws the error.
I changed the version number in the Config.xml file to 20.0.0 and it worked. However i don't want to jump all the numbers between.

**Comment by loursbourg** [comment]
The version that is on the google play is 100048

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! So to fix this issue on your device you just need to completely uninstall the old version before installing the new version, or bump the version code in the package.json. This warning has nothing to do with the version of ionic your project is using, but simply is a warning coming from android about trying to install an apk that has a lower version number than the one previously installed. The correct version to bump your app to be if its currently at `100048` would be `100058`. Since this is not an Ionic issue I am going to close this issue for now. Thanks!

**Comment by loursbourg** [comment]
I knew that reinstalling the app fixes the issue. But this is not what i opened the issue for.
The thing i forgot to tell is that when i git pushed the repo from a desktop computer, then cloned it to a laptop. i was unable to ionic run the app. Though i incremented the version number in the config.xml file.
So i have the same project in a computer and a laptop. The ionic build works very normally in the desktop. But when i build on the laptop, the error occurs.

**Comment by bigtourist** [comment]
loursbourg, did you ever figure this out?

I am having the same issue trying to go from version 2.0 to 3.0, I get the INSTALL_FAILED_VERSION_DOWNGRADE error, but if I bump it to version 21.0, it does not get the error and installs successfully (attempting with version 10.0 and 20.0 did NOT work).
