### ISSUE TITLE
strange behavior when run android

### ISSUE THREAD

**Issue by st1s** [driftyco/ionic-app-scripts#280]
#### Short description of the problem:

screen-splash and icon are not being loaded on device. also build is creating strange folders: _res_ and _usersst1sdevnewapp_, as in the pic below

![screen shot 2016-10-30 at 00 51 13](https://cloud.githubusercontent.com/assets/719763/19834326/34050d56-9e41-11e6-97f7-ffa949fe9f51.png)
#### What behavior are you expecting?

icon and splash when `ionic run android`

**Steps to reproduce:**
1. ionic start newApp --v2
2. ionic resources
3. ionic run android
4. repository to test: https://github.com/st1s/ionic-demo

**Which @ionic/app-scripts version are you using?**
0.0.36

**Other information:**

```

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.36
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.1 Build version 8B62 

```

**Comment by danbucholtz** [comment]
This is really quite strange. Hmmmm. Can you try installing the latest version of app-scripts? `0.0.38`?

`npm install @ionic/app-scripts@latest --save-dev`

Thanks,
Dan

**Comment by st1s** [comment]
@danbucholtz even so =(

**Comment by st1s** [comment]
I think I found the source of one problem, it seems that node is not able to get my OS temp folder in https://github.com/driftyco/ionic-app-scripts/blob/27b506983d245d79ae58032c7d1108a77418179f/src/util/helpers.ts#L77

to workaround I've installed the gulp and did a downgrade to

```

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Sierra
Node Version: v6.5.0
Xcode version: Xcode 8.1 Build version 8B62 
```

**Comment by danbucholtz** [comment]
@st1s, any thoughts on why it we couldn't access your OS temp folder? It works on Mac OS Sierra for me.

Thanks,
Dan

**Comment by st1s** [comment]
Hi @danbucholtz 

I didnt figured out yet but I guess it is some thing related with permissions or node version. not sure about

**Comment by danbucholtz** [comment]
@st1s,

Are you still able to run the app? I'll re-open if needed, but this is the intended behavior now that I look at it further.

I'm going to close for now, but will re-open if you can't run the app as a result.

Thanks,
Dan

**Comment by st1s** [comment]
@danbucholtz 

are you using node 7?

**Comment by danbucholtz** [comment]
@st1s, I am running Node 4.5 LTS and occasionally Node 6 LTS. Is there anything else you can think of with your environment that is different? Hmm... thinking!

Thanks,
Dan
