### ISSUE TITLE
@ionic/app-scripts@0.0.38  invalid

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#285]
Hey,

Just wanted to inform you that when I just installed the last version of the script, npm told me that the package is invalid respectively got the msg:

> @ionic/app-scripts@0.0.38  invalid

BR

**Comment by peterpeterparker** [comment]
I ran

> sudo npm install @ionic/app-scripts@latest --save-dev

I get

myapp@ /Users/me/Documents/projects/myproject
└─┬ @ionic/app-scripts@0.0.38  invalid
  ├─┬ autoprefixer@6.4.1
  │ └── caniuse-db@1.0.30000572 
  ├─┬ node-sass@3.9.3
  │ └─┬ sass-graph@2.1.2
  │   └── lodash@4.16.5 
  └─┬ rollup@0.36.3
    └── source-map-support@0.4.6

When I run again

> sudo npm install @ionic/app-scripts@latest --save-dev

I get

myapp@ /Users/me/Documents/projects/myproject
└── @ionic/app-scripts@0.0.38  invalid

**Comment by lleevvyy** [comment]
@peterpeterparker  Please update package.json and set @ionic/app-scripts to 0.0.38 :-) That fix "invalid" message".

**Comment by mhartington** [comment]
1) never use `sudo` for local package installs, it is not the correct way to install local packages. You should be running `npm install <package>` for local.

2) run `npm  @ionic/app-scripts@latest --save-dev` and did not run into any issues.

**Comment by peterpeterparker** [comment]
@lleevvyy nope, it's already 0.0.38 in my package.json

@mhartington I never had that error before, even while always using sudo. Furthermore all my folders and files have the right privileges user:group aka me. Anyway I just run the command "npm install @ionic/app-scripts@latest --save-dev" again without npm, same warning

**Comment by mhartington** [comment]
Can you delete node_modules, and run npm install again? 

So far we are not able to replicate this at all in our test.

**Comment by peterpeterparker** [comment]
Same.

> sudo rm -r node_modules/
...
> npm install
...
myapp@ /Users/me/Documents/projects/myproject
├── @angular/common@2.1.2 
├── @angular/compiler@2.1.2 
├─┬ @angular/compiler-cli@0.6.2 
│ ├─┬ @angular/tsc-wrapped@0.3.0 
│ │ └─┬ tsickle@0.1.7 
│ │   └─┬ source-map-support@0.3.3 
│ │     └── source-map@0.1.32 
│ ├── minimist@1.2.0 
│ ├── parse5@1.3.2 
│ └── reflect-metadata@0.1.8 
├── @angular/core@2.1.2 
├── @angular/forms@2.1.2 
├── @angular/http@2.1.2 
├── @angular/platform-browser@2.1.2 
├── @angular/platform-browser-dynamic@2.1.2 
├─┬ @angular/platform-server@2.1.2 
│ └── parse5@2.2.3 
├─┬ @ionic/app-scripts@0.0.37-2  invalid
│ ├─┬ autoprefixer@6.4.1 
│ │ ├── browserslist@1.3.6 
...

**Comment by peterpeterparker** [comment]
Wait why 0.0.37-2 ... let me check

**Comment by peterpeterparker** [comment]
Freak ... a-hole dumb user here. Above in my package.json was still an occurence of 0.0.37-2 written down. All my apologies and thx a lot for quick support @mhartington and @lleevvyy  

All good now
