### ISSUE TITLE
Disable TSlint

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic-app-scripts#287]
it's more of a question rather than an issue, even though it would be nice to have since of my workflow,  I need to fail CI builds when linting fails, and for the time being its not supported from your end. 

Thus, is there any flag or option to disable TSlint?

Thanks

**Comment by danbucholtz** [comment]
We intend to make it configurable whether A) it runs at all, and B) whether it "fails" a build or not.

Thanks,
Dan
