### ISSUE TITLE
Missing exports for custom watch config 

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic-app-scripts#295]
I am trying to do a custom watch config however there are some methods which are not exported such as `templateUpdate` and `fullBuildUpdate`

**Comment by danbucholtz** [comment]
We made some updates here.

Thanks,
Dan

**Comment by alan-agius4** [comment]
@danbucholtz  now watch.buildUpdate is not exported but build.buildUpdate is exported, which is not working properly when I run my custom watch as webpack is not triggering

**Comment by alan-agius4** [comment]
https://github.com/driftyco/ionic-app-scripts/issues/366

**Comment by danbucholtz** [comment]
Let's track this issue there @alan-agius4.

Thanks,
Dan
