### ISSUE TITLE
Using OpenLayers 3 with Ionic 2 RC1

### ISSUE THREAD

**Issue by blackskymedia** [driftyco/ionic-app-scripts#297]
#### Short description of the problem:
Cannot use OpenLayers 3 with Ionic 2 RC1. 

#### What behavior are you expecting?
Being to able to include OL into Angular Service. 

**Steps to reproduce:**
Here's how I include OL to my project: 

1. "openlayers": "^3.19.1",
2. "@types/openlayers": "^3.18.39"
3. declare module 'openlayers';

And use it like this in my Angular service:

```
import ol from 'openlayers';
```

**Which @ionic/app-scripts version are you using?**
3.10.3 

And here is what I get when I run "ionic serve":
```
Uncaught SyntaxError: Unexpected identifier
```

Although it works when I replace the minified version of Ol "ol.js" with non-minified "ol-debug.js" in "node_modules". I just switch the names. So the reason seems to be the build process where OL can't access DOM objects.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
