### ISSUE TITLE
Error occured during initialization of VM Could not reserve enough space for object heap

### ISSUE THREAD

**Issue by pantonis** [driftyco/ionic-app-scripts#298]
#### Short description of the problem:
Error while running ionic run android --device
Error occured during initialization of VM Could not reserve enough space for object heap

#### What behavior are you expecting?
Successful app deployment on my device

**Steps to reproduce:**
1. ionic run android --device

insert any relevant code between the above and below backticks

**Which @ionic/app-scripts version are you using?**
@ionic/app-scripts": "0.0.37",

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
![capture](https://cloud.githubusercontent.com/assets/3295086/19931530/7af636c8-a115-11e6-8a11-a05dac272ee2.PNG)

I have about 4GB free RAM at the moment I run it

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1616
