### ISSUE TITLE
Create Notion of Production/Release Build

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-app-scripts#299]
1. Discuss removing minificaction from development build to device
2. Include sourcemap for development build to device
3. Create a `--release` or `--prod` argument that does minification, etc.

Questions:
Should we always do AoT when deploying to device?

**Comment by rathgeber2** [comment]
Is AoT always necessary on debug / dev build, if we had a switch, this would be nice. 

i mean you will definitely have the ability to test it, but for faster development, i would like to skip this compiling stuff.

is this related to the issue with the 0.39 app-script Version issue that emulate builds are always Production

```
ionic emulate android --debug --dev
--------------------------------

Running 'emulate:before' npm script before emulate

> ionic-hello-world@ build /Volumes/DATEN/repositorys/tmp/httpGettest/httpGetTest
> ionic-app-scripts build

[09:15:35]  ionic-app-scripts 0.0.39 
[09:15:35]  build prod started ... 
```

**Comment by danbucholtz** [comment]
@rathgeber2, you can pass the `--dev` option to skip AoT which will speed things up. We are working with Angular on getting an incremental AoT build in place. Google internally has sub-second AoT builds so some members of the Angular team are going to be working on better tooling to make this possible for the broader community. Fingers crossed that is happens soon!

Thanks,
Dan

**Comment by NoNameProvided** [comment]
> Google internally has sub-second AoT builds so some members of the Angular team are going to be working on better tooling to make this possible for the broader community.

Wow! that incremental sub-second AoT builds is a must! Excited to have this!

> Questions:
Should we always do AoT when deploying to device?

Yes, I think it's a good idea to default to that. The difference between an AoT compiled app and a normal one is *huge* on older devices which can make testing really painful.

Our current process is to test with AoT (I mean clicking around and using features) and when we find a bug we simply fix it in the browser environment and verify that fix when a few other bug was fixed as well. This approach is a way more faster for us than reloading the app all the time.

**Comment by danbucholtz** [comment]
This is resolved.

Thanks,
Dan

**Comment by NoNameProvided** [comment]
Does app-scripts supports incremental builds now?

**Comment by danbucholtz** [comment]
No, `ngc` does not support incremental builds and there is no timeline for that. Production builds are going to be slow for awhile so the best bet is to just use development builds as much as possible.

Thanks,
Dan
