### ISSUE TITLE
ES 6 and babel support

### ISSUE THREAD

**Issue by Kobzol** [driftyco/ionic-app-scripts#30]
Hello, will you add support for ES6 code generation and Babel transpiling (similar to the old `ionic-gulp-browserify-typescript-babel` package)?
It would be nice to have it in the scripts "core" support, async/await support is a killer feature for many people IMO.

**Comment by danbucholtz** [comment]
At this time we have no plans of formally supporting anything other than Typescript.  Async/Await is coming to `es5` code in [Typescript 2.1](https://github.com/Microsoft/TypeScript/milestone/20), so not too far off.



Thanks,
Dan

**Comment by Kobzol** [comment]
Okay, I'll use the babel post-process step manually and wait for Typescript 2.1 :-) Thanks.

**Comment by bytenik** [comment]
I tried using Rollup's babel plugin with no success. I can do a post-process step, but it breaks `watch`.

**Comment by pensacola1989** [comment]
@danbucholtz  typescript 2.1 is rc now, when will app-script surpport comping to es5? I'm new to ionic 2.and use a lot of "async/await" in my code, so I can build my app now,but "ionic serve" works fine with "target: 'es6'", can wait "async/await"

**Comment by danbucholtz** [comment]
@pensacola1989, hopefully soon! We are going to make the changes to make it easy for users to specify this soon. I think (I'm not 100% sure) Angular has some issues right now with version 2.1. Not entirely sure though.

Thanks,
Dan

**Comment by pensacola1989** [comment]
@danbucholtz thanks for you all hard working, but for my current situation: I need to remove a lot of await/async in my code...any other solution?like "modify webpack.config"? I know you don't recomand that ,

**Comment by pensacola1989** [comment]
@Kobzol ,Could you show some webpack sample code with app-script to make  async/await avalible?I'm very new to webpack,thanks

**Comment by Kobzol** [comment]
@pensacola1989 Take a look at this issue #197, there's a detailed explanation how to use async/await for ES5 with in the current Ionic 2 version :-)
