### ISSUE TITLE
ionic build ios in windows does not update the files in the platforms/ios folder.

### ISSUE THREAD

**Issue by mflmartin** [driftyco/ionic-app-scripts#303]
#### Short description of the problem:
When Building for IOS with ionic build ios, the modified files of the build are not copied again into platforms/ios, in Windows 10

#### What behavior are you expecting?
That they are updated.

**Steps to reproduce:**
1. ionic start myapp --v2
2. ionic platform add ios
3. ionic build ios
4. Test the platform (with a Mac). Ok. It works.
5. Modify something in your project
6. ionic build ios
7. Boom. No files updated.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS: WINDOWS 10
Node Version: v6.4.0

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1626
