### ISSUE TITLE
default use  "browser-sync"  and "proxy-middleware" ,

### ISSUE THREAD

**Issue by 791060555** [driftyco/ionic-app-scripts#310]
![image](https://cloud.githubusercontent.com/assets/1204319/19992859/3ddd5a7e-a27c-11e6-96b2-96de7f3017ed.png)
![image](https://cloud.githubusercontent.com/assets/1204319/19992874/5381d030-a27c-11e6-9410-29c44f380599.png)
![image](https://cloud.githubusercontent.com/assets/1204319/19992949/f04aceb2-a27c-11e6-8568-7c7c719831b5.png)
no used,I dont know why 
,but I can do it that "browser-sync"  and "proxy-middleware" ,
I hope default that use  "browser-sync"  and "proxy-middleware" ,

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
