### ISSUE TITLE
ionic resources command problems

### ISSUE THREAD

**Issue by mflmartin** [driftyco/ionic-app-scripts#312]
#### Short description of the problem:
`ionic resources` does not generate ios and android icons & splash screens in any way
`ionic resources --icons` generates icons for ios but NOT android. They are generated into the resources/android folder, BUT not copied and propertly renamed to platform/android/res, which means that when you compile the app, you get the cordova robot. 

`ionic resources --splash` generates splash for ios but NOT android They are generated into the resources/android/splash folder, BUT not copied and propertly renamed to platform/android/res, which means that when you compile the app, you get the cordova robot. 

#### What behavior are you expecting?
That it works correctly. 

**Steps to reproduce:**
1. place icon.png and splash.png in the resources folder
2. Execute `ionic resources`
3. They are not created propertly.
4. Execute `ionic resources --icons`
5. Android icons in platform/res, are not propertly updated
6. Execute `ionic resources --splash`
7. Android splash in platform/res, are not propertly updated

**Which @ionic/app-scripts version are you using?**
Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS:
Node Version: v6.4.0

**Comment by mflmartin** [comment]
I found a res folder at the ROOT of my project containing android resources. It might be that it creates it in the ROOT folder of the project, instead of placing it inside the platforms/android folder. If this helps you narrow it down more.

**Comment by ferranvila** [comment]
@mflmartin Me too. I think this happens after the new [cordova-android version](https://github.com/apache/cordova-android/releases): 6.X.X. If you downgrade to 5.2.2 the icon is displayed but the splash screen don't.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1638
