### ISSUE TITLE
Barrel error with webpack (0.0.39)

### ISSUE THREAD

**Issue by maxkunitsa** [driftyco/ionic-app-scripts#315]
#### Short description of the problem:
In version 0.0.39 rollup bundler works correct, but with webpack bundler i have error in browser console: 'Error: Cannot find module "../../common/services/index/"(…)'. This file is barrel.

#### What behaviour are you expecting?
Correct build both with rollup or webpack without any error's in console.

**Steps to reproduce:**
1. Create 'barrel' file in ionic project
2. Run 'ionic serve' with ionic-app-scripts@0.0.39 and webpack as bundler 
3. Browser started with white screen and error in console: 'Error: Cannot find module "../../common/services/index/"(…)'

**Example of barrel (https://angular.io/docs/ts/latest/guide/glossary.html#!#sts=Barrel)**

```
//common/services/index.ts
export * from './utils/color.utils';
export * from './utils/localstorage.utils';
export * from './utils/math.utils';
export * from './utils/uuid.utils';
```

**Which @ionic/app-scripts version are you using?**
0.0.39

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Dont have any ideas

**Comment by ValterSantosMatos** [comment]
+1, same issue here

**Comment by alan-agius4** [comment]
Had an issue with barrels and webpack sometime ago.
Had it solve with https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs

**Comment by maxkunitsa** [comment]
@alan-agius4 u use it as plugin in webpack config or ...?

**Comment by alan-agius4** [comment]
@maxkunitsa Yes.

**Comment by alan-agius4** [comment]
@maxkunitsa I used it as a loader. 
```bash
npm i babel-loader babel-plugin-transform-es2015-modules-commonjs --save-dev
```

Add the below to the webpack config

```ts
module: {
  loaders: [
    {
      test: "/\.js$/",
      exclude: "node_modules",
      loader: "babel-loader",
      query: {
        presets: ["transform-es2015-modules-commonjs"]
      }
    }
  ]
}
```

I can't remember if you need `babel-core` as well as a dependency.

If this doesn't work I'll re-post an update tomorrow, as right now I don't have access to my code base.

**Comment by maxkunitsa** [comment]
@alan-agius4 big tnx for helping, but suggested solution didnt help.

**Comment by alan-agius4** [comment]
Do you have a link for the repo that I can have a look at?

**Comment by maxkunitsa** [comment]
@alan-agius4 sorry, but no, because project is private...

**Comment by mbakker96** [comment]
I've the same problem.

@maxkunitsa did you try the fix from @ValterSantosMatos?

**Comment by alan-agius4** [comment]
Hi, all I updated my above snippet. Can you have a look and see if it works now?

**Comment by mbakker96** [comment]
Hi @alan-agius4,

I see in your snippet that you use ` test: "/\.js$/"` but I quest that it is not working with `*.ts` files. or am I wrong?

**Comment by alan-agius4** [comment]
@mbakker96 no it must be `.js` as at that stage the `ts` files are already transpiled

**Comment by maxkunitsa** [comment]
@alan-agius4 hello. I tried your snipper and still got error in console. I shared my webpack config, could u please take a look? Maybe something else should be changed https://www.dropbox.com/s/klmhtase7c1670x/webpack.config.js?dl=0

**Comment by mbakker96** [comment]
I think i've a different error. I created a different issue

**Comment by ValterSantosMatos** [comment]
@maxkunitsa  and @alan-agius4 I also tried the snipped and didn't work, just changing it to rollup.

**Comment by maxkunitsa** [comment]
@ValterSantosMatos me too, but rollup if very-very-very slow.

**Comment by ValterSantosMatos** [comment]
@maxkunitsa yha :( thats why I am also waiting for some solution with webpack and barrels...

**Comment by danbucholtz** [comment]
All,

Webpack 2 has known issues with Barrels. Can you not use them if possible? They cannot be tree shaken as far as I know, in addition to other challenges.

Thanks,
Dan

**Comment by maxkunitsa** [comment]
@danbucholtz what about solution in first answer here http://stackoverflow.com/questions/37082601/how-to-import-a-barrel-by-folder-name-only? Do we have place in app-scripts configs where we could try to add path to barrel?

**Comment by Quocnamit** [comment]
I have one question : Why is Webpack applied in new version of ionic-app-scripts ?

**Comment by alexmgrant** [comment]
@Quocnamit explained [here](http://blog.ionic.io/ionic-build-process-updates/)

**Comment by alan-agius4** [comment]
I updated my snippet again

**Comment by maxkunitsa** [comment]
@alan-agius4 tnx, but not work for me with app-scripts 0.0.43, same problem.

**Comment by danbucholtz** [comment]
Since this is a Webpack issue, we are going to close this. We do *not* recommend the barrel pattern. Explicit import/export FTW. There are many valid reasons for it, namely barrels cause grief for every tree shaker except Rollup.

Thanks,
Dan
