### ISSUE TITLE
Black screen while running in ios10

### ISSUE THREAD

**Issue by lwz7512** [driftyco/ionic-app-scripts#316]
Hi, does anyone meet this problem? this situation occur very often...
we are developing ionic app with 2.0.0-rc.1, but when run into this problem I have nothing to do with...

below is screen shot:
![mmexport1478442047848](https://cloud.githubusercontent.com/assets/920778/20038587/4b6cc930-a471-11e6-89a9-da16b6210d47.jpg)

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
