### ISSUE TITLE
Ionic rc.2 build issue with angular2-google-maps

### ISSUE THREAD

**Issue by loet** [driftyco/ionic-app-scripts#319]
#### Short description of the problem:
I can not build my ionic rc.2 project with angular2-google-maps included.
In development mode (executing `ionic serve`) everything works fine. But when executing `ionic build`, I get the following error message:
`Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function [...]`

#### What behavior are you expecting?
Correct building

**Steps to reproduce:**
1. Include angular2-google-maps (version 0.15.0) in a ionic project
2. Load it in the AppModule: 
`AgmCoreModule.forRoot({
      apiKey: 'mykey'
    })`
3. Execute ionic build

**Which @ionic/app-scripts version are you using?**
latest (0.0.39)

**Other information:** 
build with --dev arg seems to work (at least regarding the angular2-google-maps library)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is an NGC error that points to an issue in your code. NGC is extremely strict about types in your code and unfortunately the errors it throws are not always perfectly clear. Unfortunately this is not something we control at the moment but we are working with the Angular team to get better error messages from NGC. I would recommend asking around on the [forum](https://ionicframework.forum.com) to get some help with fixing this error. Thanks!
