### ISSUE TITLE
Increased build size (300%) with 0.0.40 compared to 0.0.39

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic-app-scripts#323]
#### Short description of the problem:
Build size increased 300% building with 0.0.40 compared to 0.0.39

Any idea what's going on?

Left side: build by 0.0.40
Right side: build by 0.0.39
![image](https://cloud.githubusercontent.com/assets/230182/20077876/81c40ee4-a53e-11e6-826e-7305fbf202f2.png)

**Comment by danbucholtz** [comment]
@biesbjerg,

Super weird. I will look into it.

Thanks,
Dan

**Comment by danbucholtz** [comment]
@biesbjerg,

I'm not seeing that. Can you blow away `.tmp` and `www` directory and try again?

Thanks,
Dan

**Comment by biesbjerg** [comment]
Just reproduced it after deleting .tmp and clearing www.

Let me try and downgrade to 0.0.39 and try again.

**Comment by danbucholtz** [comment]
@biesbjerg,

I see it now. It's for the prod build. Okay, we will fix in `0.0.41` or `0.0.42`. It has to do with using `eval` sourcemaps I think. We are going to have a better story here soon.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Fixed in `0.0.41` @biesbjerg. We still intend to make some changes around this soon.

Thanks,
Dan

**Comment by jgw96** [comment]
Thanks for catching this @biesbjerg !

**Comment by biesbjerg** [comment]
Thank *you* for creating Ionic! ;-)
