### ISSUE TITLE
Cannot debug with ionic serve and app-scripts 0.0.41

### ISSUE THREAD

**Issue by jmesa-sistel** [driftyco/ionic-app-scripts#330]
In windows 10 I have config VSCode to debug a simple ionic app.
Steps:
Create app:  ionic start cutePuppyPics --v2
In home.html add a button:  
`<button (click)="OnClick()">Test</button>`
In home.ts add a function: 
` OnClick() {
    console.log('test clicked!');
  }`

Run ionic serve

In VSCode select debug with chrome, open debug config (launch.json).
In 'Launch Chrome against localhost, with sourcemaps' configuration change url to:  http://yourip:8100
Add "userDataDir": "${workspaceRoot}\\chromeDummyDir", to launch a new chrome navigator.
Add a breakpoint in 'console.log('test clicked!');' line.
Press F5 to debug
You will see that the breakpoint is misplaced, press the Test button, you will notice that the breakpoint does not work.

**Comment by danbucholtz** [comment]
This is resolved now.

Thanks,
Dan
