### ISSUE TITLE
Watch fires when no files have changed

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-app-scripts#331]
#### Short description of the problem:
I am busy browsing through my assets in Finder, and while moving through the folder the watch fires continuously even though nothing has been changed. 

This is extremely problematic from a dev point of view as the app effectively restarts for no apparent reason. 

![image](https://cloud.githubusercontent.com/assets/2852839/20110268/6a54fbd4-a5ec-11e6-881d-22af6aadf70a.png)

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.41
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: Mac OS X Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by danbucholtz** [comment]
Fixed in next release.

Thanks,
Dan
