### ISSUE TITLE
Transpile config

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic-app-scripts#333]
Similar to ngc config, transpile or tsc should also have a config.

Reason being is that I have a generic tsconfig.json however when running the transpile from ionic app scripts its being files that shouldn't be picked.

Proving something similar to the ngc config would solve the issue.

**Comment by danbucholtz** [comment]
So you want the ability to override this is what you're saying?

Thanks,
Dan

**Comment by alan-agius4** [comment]
Yeah, provide a sort of custom tsconfig either path or options

**Comment by alan-agius4** [comment]
If it make sense for other people as well that is

**Comment by danbucholtz** [comment]
@alan-agius4,

I don't think we intend on implementing this. You can pass in a custom `tsconfig.json` in some cases that may resolve some challenges that you're experiencing. It's worth a shot.

Thanks,
Dan
