### ISSUE TITLE
[0.0.41] build dev failed: Cannot find module '../util/Logger'

### ISSUE THREAD

**Issue by MathieuNls** [driftyco/ionic-app-scripts#337]
**Note: for support questions, please use one of these channels:**

#### Short description of the problem:

Upon installation of the new ionic-app-scripts, `ionic serve` fails with `build dev failed: Cannot find module '../util/Logger'`.

#### What behavior are you expecting?

**Steps to reproduce:**
1. upgrade to 0.0.41
2. `ionic serve`
3. Watch it fail

```
Running 'serve:before' npm script before serve

> Toolwatch@0.8.0 watch /home/math/www/twapp/tw-mobile-2rc0
> ionic-app-scripts watch

[13:32:35]  ionic-app-scripts 0.0.41
[13:32:35]  watch started ...
[13:32:35]  build dev started ...
[13:32:35]  clean started ...
[13:32:35]  clean finished in 3 ms
[13:32:35]  copy started ...
[13:32:35]  transpile started ...
[13:32:35]  lint started ...
[13:32:37]  lint finished in 2.08 s
[13:32:38]  transpile finished in 3.73 s
[13:32:38]  webpack started ...
[13:32:38]  build dev failed: Cannot find module '../util/Logger'
[13:32:39]  copy finished in 4.00 s
[13:32:39]  watch ready in 4.30 s
Proxy added: /api/ => https://toolwatch.io/api/
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*, !www/**/*.map
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $
```

**Which @ionic/app-scripts version are you using?**

0.0.41

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

It seems that every `console.log` in the application are replaced by `logger_1.Logger(..)` when transpiled. If ionic-app-script depends on a `Logger` lib, then, it's missing.

M.

**Comment by rapropos** [comment]
I think this is a dupe of [#326](https://github.com/driftyco/ionic-app-scripts/issues/326).

**Comment by MathieuNls** [comment]
Indeed, duplicate of #326 . Still a problem as reported in #353 .
