### ISSUE TITLE
Versioned JS and CSS bundles like main-1.0.2,js

### ISSUE THREAD

**Issue by JoeKool** [driftyco/ionic-app-scripts#34]
Given a version number like 1.0.2, the script should create main-1.0.2.js, main-1.0.2,css and include the same in index.html. I know how to do this in gulp but prefer to use ionic-app-scripts. One option I can think of is to customise uglify script. Any suggestions?

**Comment by adamdbradley** [comment]
Can you set the dest property? https://github.com/driftyco/ionic-app-scripts/blob/master/config/rollup.config.js#L32

**Comment by JoeKool** [comment]
Lot of config files need to be customised as many of them refer to main.js, etc. For the time being I am using ionic_build_dir in package.son to achieve versioned build.

  "config": {
    "ionic_build_dir": "www/build-1.0.2"
  },

**Comment by jgw96** [comment]
Thanks! We have reviewed this and i am going to close it for now as it is not something we want to include in our build process. I would advise that you continue to use the `ionic_build_dir` option to get this in your project. Thanks!
