### ISSUE TITLE
typescript: Cannot find name 'EventStaffLogService'.

### ISSUE THREAD

**Issue by karlpatrickespiritu** [driftyco/ionic-app-scripts#344]
I'm having this error. I've installed the latest app scripts. I don't know much about typescript but this used to work before I ran the update scripts.

````cli
$ ionic serve

Running 'serve:before' npm script before serve

> ionic-hello-world@ watch C:\Users\cmadmin\Development\mobile\sportsinfocus-mobile-app
> ionic-app-scripts watch

[14:01:26]  ionic-app-scripts 0.0.42
[14:01:26]  watch started ...
[14:01:26]  build dev started ...
[14:01:26]  clean started ...
[14:01:26]  clean finished in 6 ms
[14:01:26]  copy started ...
[14:01:26]  transpile started ...
[14:01:32]  typescript: ...sportsinfocus-mobile-app/src/app/events/event-sign-in/event-sign-in.component.ts, line: 18
            Cannot find name 'EventStaffLogService'.
````

event-sign-in.component.ts
````typescript
import { Component } from '@angular/core';
import { NavController, NavParams, ToastController } from 'ionic-angular';
import { EventStaffLogService, EventStaff } from '../shared/';

@Component({
  templateUrl: 'event-sign-in.component.html',
   providers: [EventStaffLogService]
})
export class EventSignInComponent {
  eventStaff: any;
  eventStaffLogs: Object = { data: [] };
  fetchingLogs: Boolean = true;
  isSignIn: Boolean = false;

  constructor(
    private navCtrl: NavController,
    private navParams: NavParams,
    private eventStaffLogService: EventStaffLogService,
    public toastController: ToastController
  ) {
    this.eventStaff = navParams.get('eventStaff');
    this.getEventStaffLogs();
  }
````

And BTW, great update for the build scripts! And the error reporting rocks. 👍

**Comment by savanvadalia** [comment]
I have reported similar issue here https://github.com/driftyco/ionic-app-scripts/issues/325
I am assuming you are using angular 2 barrels. I think issue is related to barrels or webpack. 

As temporary fix try importing the service from the file location.

Regards,
Savan

**Comment by karlpatrickespiritu** [comment]
Hmm. How do I import the service from the file location @savanvadalia?

**Comment by karlpatrickespiritu** [comment]
Just found the issue. Seems that importing from an `index.ts` file causes this error.

changed my code from:
````js
import { EventStaffLogService, EventStaff } from '../shared/';
````

to
````js
import { EventStaffLogService } from '../shared/event-staff-log.service';
import { EventStaff } from '../shared/event-staff.model';
````

and it worked.

**Comment by savanvadalia** [comment]
Correct that's what I meant. Ideally it should worked for your original code to as per barrel concepts.
import { EventStaffLogService, EventStaff } from '../shared/';

 I use barrels heavily in my project to organize my imports but this issue defeats the purpose of using barrels.
Hope this is fixed soon as its hard to keep track of this type of temporary fixes.

**Comment by karlpatrickespiritu** [comment]
Yeah. I hope it'll be fixed soon. Thanks @savanvadalia

**Comment by jaymcguinness** [comment]
Possibly related : https://forum.ionicframework.com/t/barrels-did-latest-rc0-or-ng2-final-release-break-them/66972

FWIW I'm using barells just fine if I explicitly reference them with a /index at the end. Obviously my index.ts file lists all of my exports.

**Comment by karlpatrickespiritu** [comment]
I tried reverting back my barrels and now it doesn't throw any errors. Probably because I updated my ionic app scripts. Well, now it works.

Probably one of the breaking changes of ng2 rc. Thanks @jaymcguinness.
