### ISSUE TITLE
v0.0.42 Sourcefile in Editor needs to be saved twice to reflect changes in sourcemaps

### ISSUE THREAD

**Issue by waybackrider** [driftyco/ionic-app-scripts#349]
Steps to reproduce:
Create a new Project: ionic start MyApp --v2
start it: ionic serve
Now open a file, eg. home.ts, in Editor and add some Code to it, eg. declare a var in constructor and save the file. You see see watch in firing up. Now look a the sourcemap, im using Chrome, you won't see the changed code. Save the unchanged Sourcefile a second time in Editor, watch is firing up, now the codechange is in sourcemaps.
Change the Statemant you added in the constructor, save the file, no Code change in Sourcemaps, save it a second time, code change is there.

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.42
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

**Comment by waybackrider** [comment]
After some Tests, saving twice doesn't work in existing upgraded Projects. It seems that several lines of Code (maybe 4-5) need to be changed before saving to update the sourcemap correctly, really weird.....

**Comment by Kobzol** [comment]
What editor are you using? Some IDEs (for example Phpstorm/webstorm) don't save the file to the disk after every change.

**Comment by danbucholtz** [comment]
@waybackrider,

I cannot recreate this. What editor are you using? I'm on a Mac fwiw.

Thanks @Kobzol!

Thanks,
Dan

**Comment by waybackrider** [comment]
I'm using VSCode on Win10. Also tried Notepad++, same Problem. I cannot see a scheme, sometimes is works, but most times not. Seems to be same Problem as Issue #363

**Comment by danbucholtz** [comment]
This should be fixed in our nightly release. Can you please test and validate. This will go out in a release on Monday if everything is good to go. I'll reopen if needed.

```
npm install @ionic/app-scripts@nightly
```

Thanks,
Dan
