### ISSUE TITLE
`ionic serve` doesn't work with Edge

### ISSUE THREAD

**Issue by berchik** [driftyco/ionic-app-scripts#356]
#### Short description of the problem:

1. I could update only after removing node_module folder and running npm install
2. App serve ok in Chrome but only white screen on Edge.
3. /ionic-lab is not functional and actually was useful

version: 0.0.42

"scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.2",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.42",
    "typescript": "2.0.3"
  },

**Comment by MELAS007** [comment]
it is still not working!!!!!

**Comment by danbucholtz** [comment]
@berchik,

Please provide more info about what isn't working on some actionable item. We are working on getting `ionic serve --lab` working again.

Thanks,
Dan

**Comment by berchik** [comment]
@danbucholtz, as I wrote, ‘ionic serve’ doesn’t seem to work on edge (w10) only on chrome, and ‘localhost:8100/ionic-lab’ doesn’t work. The “not working!!!!!” message above is not mine and I have no idea what it means.
 
Thanks.

**Comment by MELAS007** [comment]
@danbucholtz - It is not working i mean:

1. ionic serve --l or --lab is not open with 3 os (localhost:8100/ionic-lab) 
2.on gist bash i don't see the little menu was: r or restart, -consolelogs, etc

**Comment by danbucholtz** [comment]
@berchik,

When you say `it doesn't work with edge`, do you mean that if you run `ionic serve` and open Edge and go to `http://localhost:8100/` in Edge *after* chrome opens, it doesn't render?

I am trying in IE10 right now (Windows 7) and it is working as expected.

Thanks,
Dan

**Comment by MELAS007** [comment]
@danbucholtz - Thank you for the update!

I am on windows 7, it is not fix !!

I write ionic serve --lab, it gives me only localhost:8100 and not with 3
platforms.
Also where is the little menu (r or restart, .... q or quit)???

I can't work without theses things (3 platforms + little menu)

regards,

**Comment by berchik** [comment]
@danbucholtz 
I'm testing Edge 38.14393.0.0 on Win10 64. I get blank page when I run `ionic serve` directly on Edge _before_ testing Chrome. 

Thanks.

**Comment by danbucholtz** [comment]
This works with edge now.

Thanks,
Dan
