### ISSUE TITLE
[0.0.43] Dev build with Rollup cannot find app.module.

### ISSUE THREAD

**Issue by JustinPierce** [driftyco/ionic-app-scripts#359]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When running `npm run ionic:build --dev` and, by extension, `ionic serve`, the build fails with the following message:

```
rollup failed: Could not resolve './app.module' from C:\Source\GitHub\test\src\app\main.dev.ts
```

Running a production build succeeds.

#### What behavior are you expecting?
I expect the build to succeed. 😁

**Steps to reproduce:**
1. Start a new project (`npm start test --v2 --ts`)
2. Install the latest app scripts (`npm install @ionic/app-scripts@latest`)
3. Configure the project to build with Rollup (add `"ionic_bundler": "rollup"` to the `"config"` section in `package.json`)
4. Run a dev build (`npm run ionic:build --dev`)

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
`0.0.43`

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
`0.0.39` is the last version of `@ionic/app-scripts` that could perform a dev build with Rollup for me. The failures start with `0.0.40`.

**Comment by danbucholtz** [comment]
This is working for me on my Mac. I just tested. I think this may be a windows issue.

Thanks,
Dan

**Comment by JustinPierce** [comment]
The error I pasted probably made it obvious, but I will confirm that I am on Windows. 😛

**Comment by rapropos** [comment]
New scratch project builds fine with rollup under Debian sid as well, if that is relevant.

**Comment by MELAS007** [comment]
@danbucholtz - I am on windows too

**Comment by Quocnamit** [comment]
Me too . I am on windows

**Comment by savanvadalia** [comment]
Same error for me on windows

**Comment by danbucholtz** [comment]
@JustinPierce, @Quocnamit, @MELAS007, @savanvadalia, what versions of Windows? I am testing on Win 7 and it's going pretty well.

Thanks,
Dan

**Comment by danbucholtz** [comment]
I have fixed this issue. Can you run `npm install @ionic/app-scripts@nightly` and test it out to validate.

Thanks,
Dan

**Comment by JustinPierce** [comment]
@danbucholtz Can confirm that things are working as expected on my Windows 10 machine. Thanks!

**Comment by MELAS007** [comment]
@danbucholtz - Thank you for the update!

I am on windows 7, it is not fix !!

I write ionic serve --lab, it gives me only localhost:8100 and not with 3
platforms.
Also where is the little menu (r or restart, .... q or quit)???

I can't work without theses things (3 platforms + little menu)

regards,

**Comment by MELAS007** [comment]
@danbucholtz - Any news?

**Comment by danbucholtz** [comment]
@MELAS007,

The issue in this thread is resolved in the latest nightly and will probably be published today. The other issues you reported are known issues and aren't relevant to this thread. They probably won't be published today. We are aware of them and are working on them.

Thanks,
Dan
