### ISSUE TITLE
ie css limit

### ISSUE THREAD

**Issue by tienne** [driftyco/ionic-app-scripts#360]
#### Short description of the problem:
theme/variables.scss $colors length >47
ie11 css not working

#### What behavior are you expecting?
my theme/variables.scss $colors length > 47
my ionic app ie11 not working
because ie css selector/size limit one css file

how css output file multiple bundle?

**Which @ionic/app-scripts version are you using?**

```
"dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.2",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.42",
    "typescript": "2.0.6"
  }
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

http://spaceninja.com/2015/03/31/ie-css-limits/

**Comment by danbucholtz** [comment]
@tienne,

Sorry, there is nothing we can do about this. I suggest using fewer colors. There isn't an easy fix here.

Thanks,
Dan
