### ISSUE TITLE
watch.BuildUpdate is not exported

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic-app-scripts#366]
Noticed that the watches.config have changed. 
I have custom watches and I am using `require("@ionic/app-scripts").buildUpdate`  which is exported from build rather than `watch`, which is resulting in triggering build without doing anything else.

![image](https://cloud.githubusercontent.com/assets/17563226/20218147/651742b0-a823-11e6-9e2e-aa41364d5958.png)

Ionic App Scripts Version: 0.0.43

**Comment by alan-agius4** [comment]
I can do a quick PR if you confirm that the buildUpdate should be exported from the watch rather than build file.

**Comment by alan-agius4** [comment]
Also, notice that "js" files are not handled within the function. For my project its mandatory to handle this.

**Comment by alan-agius4** [comment]
Any update re this please? I really want to use the the debounce functionality in 0.0.43

**Comment by danbucholtz** [comment]
@alan-agius4,

Can you do a PR with what you need?

Thanks,
Dan
