### ISSUE TITLE
[0.0.43] prod build fails, too

### ISSUE THREAD

**Issue by michael-brade** [driftyco/ionic-app-scripts#367]
With the new version 0.0.43, the serve goal is broken, as in https://github.com/driftyco/ionic-app-scripts/issues/361, but so is the `build` :(

```
[15:28:04]  copy finished in 102 ms 
[15:28:12]  Error: Error at .../.tmp/app/main.prod.ts:4:36 
[15:28:12]  Cannot find module './app.module.ngfactory'. 
[15:28:12]  ngc failed 
[15:28:12]  ionic-app-script task: "build" 
[15:28:12]  Error: Error 
```

I thought `ngc` would create the ngfactory, but there is none in `.tmp`.

**Comment by alan-agius4** [comment]
Do you have the `declarations.d.ts` file?
Should contain

`declare module '*';`

**Comment by michael-brade** [comment]
Wow, that was quick!! :) Where should that file be?

**Comment by alan-agius4** [comment]
You can place it directly under `src`

**Comment by michael-brade** [comment]
Yeah, that changes things! Now I get
```
Error: Metadata emit requires the sourceFiles are passed to WriteFileCallback. Update to TypeScript 
            ^1.9.0-dev
```
I guess my TypeScript is too new for some feature... I'll try to downgrade to 1.9.

**Comment by alan-agius4** [comment]
You can downgrade to "2.0.9"

**Comment by michael-brade** [comment]
Yay, lovely! Thank you very much, with TypeScript 2.0.x and `src/declarations.d.ts` it now builds again! :)
I'll close this issue again.
