### ISSUE TITLE
Documentation update for "scripts":{} in package.json with version 0.0.43

### ISSUE THREAD

**Issue by devnigelwheeler** [driftyco/ionic-app-scripts#372]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

readme.md says scripts section of package.json should read:

 "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch"
  },

#### What behavior are you expecting?

ionic blog post on app-scripts release 0.0.43 states scripts should read:

"scripts" : {
"ionic:build": "ionic-app-scripts build",
"ionic:serve": "ionic-app-scripts serve"
}

(current scripts version 0.0.43 working with this.)

**Steps to reproduce:**
1. read driftyco/ionic-app-scripts readme.md
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
0.0.43

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.8
Node Version: v6.8.0
Xcode version: Not installed

{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "@types/underscore": "^1.7.33",
    "angular2-swing": "^0.10.0",
    "firebase": "^3.6.0",
    "ionic-angular": "2.0.0-rc.2",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "underscore": "^1.8.3",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.43",
    "typescript": "2.0.6"
  },
  "description": "rbf-shop-ionic: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": []
}

**Comment by masimplo** [comment]
I opened pull request https://github.com/driftyco/ionic-app-scripts/pull/382 for this

**Comment by jgw96** [comment]
Hello all! I am going to close this issue for now as the above PR was merged to fix this. Thanks!
