### ISSUE TITLE
ionic serve --lab fails with error Cannot GET //__ion-dev-server/ionic_lab.html

### ISSUE THREAD

**Issue by faraazc** [driftyco/ionic-app-scripts#374]
#### Short description of the problem:
ionic serve --lab fails with error Cannot GET //__ion-dev-server/ionic_lab.html
However ionic serve works (i.e. without lab option)
This is happening after upgrading ionic cli to 2.1.8 and ionic framework to 2.0.0-rc.2 and App scripts to 0.0.43

http://localhost:8100//__ion-dev-server/ionic_lab.html Failed to load resource: the server responded with a status of 404 (Not Found)

#### What behavior are you expecting?
i am expecting ios, android and windows previews

**Steps to reproduce:**
1. upgrade app to use ionic cli to 2.1.8 and ionic framework to 2.0.0-rc.2 and App scripts to 0.0.43
2. run command sudo ionic serve --lab on terminal
3. see the output on  browser window

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.7.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by fagnerdireito** [comment]
I have a same problem, this is work for group of ionic.

**Comment by CarlRyds** [comment]
Same issue :(

You can just go to http://localhost:8100/

However, you don't get the side by side iOS, Android, Windows page

**Comment by danbucholtz** [comment]
This should be resolved now.

Thanks,
Dan
