### ISSUE TITLE
sass build triggering webpack build norm or bug?

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic-app-scripts#376]
When I do npm run sass which is mapped to `ionic-app-scripts sass` webpack is being called as well. Is this the norm behavior?

![image](https://cloud.githubusercontent.com/assets/17563226/20236691/b67f8948-a8bc-11e6-8374-071dc1562a95.png)

**Comment by danbucholtz** [comment]
Yes, because we only bundle the sass of the components included in the bundle. It is designed this way to have the smallest possible css bundle.

Thanks,
Dan
