### ISSUE TITLE
How to include third party css and scss?

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#38]
Hey,

In Ionic Beta 11, I was overriding the sass task in gulp file to have the possibility to include third party libraries css or scss. I used to have following code in my gulpfile.js

    gulp.task('sass', function(){
        return buildSass({
            sassOptions: {
                includePaths: [
                    'node_modules/ionic-angular',
                    'node_modules/ionicons/dist/scss',
                    'node_modules/cropperjs/dist',
                    'node_modules/bourbon/app/assets/stylesheets',
                    'node_modules/sass-mediaqueries'
                ]
            }
        });
    });

Is there a way to achieve that in ionic-app-scripts aka how do I include third libraries css and scss in the build process?

Thx in advance for your help

**Comment by pskhodad** [comment]
https://github.com/driftyco/ionic-app-scripts/blob/master/config/sass.config.js
This file might help you.

**Comment by peterpeterparker** [comment]
Thx, that helped. I did the following then

1. Add a config in package.json

  "config": {
    "ionic_sass": "./scripts/sass.config.js"
  }

2. Write the script

module.exports = {
  includePaths: [
    'node_modules/ionic-angular/themes',
    'node_modules/ionicons/dist/scss',
    'node_modules/cropperjs/dist',
    'node_modules/bourbon/app/assets/stylesheets',
    'node_modules/sass-mediaqueries'
  ],
  includeFiles: [
    /\.(scss|css)$/i
  ]
};

I still have got some import error, but I'm guessing it's because every scss are now separated, therefor I should probably add my needed import in each file. Gonna try that and when all solve, close that task.

**Comment by peterpeterparker** [comment]
Doesn't seems to work with "css" files. Someone have any ideas?

**Comment by iooK** [comment]
Sorry to reopen it.

I have exactly the same problem.
In addition, I have some backgrounds with url paths from the css file (with relative path of course).
The css file is imported correctly.

But, are there a solution to import images in my www directory and to correct the relative paths  ?

The module concerned by this issue is Leaflet.
Thx in advance.
