### ISSUE TITLE
Changes in linked modules not triggering changes

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic-app-scripts#380]
#### Short description of the problem:
When you link npm module you still need to listen for changes on them. The file extension in would mainly be `js` which at the time being is not handled.

Used to work in 0.0.41

#### What behavior are you expecting?
Bundles again

**Steps to reproduce:**
1. npm link a library
2. Do a change in the library and build
3. Change is detected but nothing else happens
```
module.exports = {
  watchers: [
    {
      paths: [
        'node_modules/mylib/dist/**/*.(js|scss)',
        '{{SRC}}/**/*.(ts|html|scss)'
      ],
      options: { ignored: ['{{SRC}}/**/*.spec.ts', '**/*.DS_Store'] },
      callback: watch.buildUpdate
    }
  ]
};
```

Note: I had to change the `index.js` of `ionic-app-scripts` to export `buildUpdate` from `watch` rather than `build`.

**Which @ionic/app-scripts version are you using?** 0.0.43

**Comment by danbucholtz** [comment]
We merged the PR, so closing this.

Thanks @alan-agius4.

Thanks,
Dan
