### ISSUE TITLE
Error copying assets folder

### ISSUE THREAD

**Issue by Artfloriani** [driftyco/ionic-app-scripts#384]
#### Short description of the problem:
When compiling the app, the assets folder is not being copied to the build. I need to manually copy and paste the assets folder to the build folder. Error on console:

```
 copy: Error copying "PATH\node_modules\ionicons\dist\fonts" to "PATH\www\assets\fonts"
```

This also happens to the default assets folder. This was not on app-scripts 0.3.6.

#### What behavior are you expecting?
Assets folder should be copied automaticaly on compile.

**Which @ionic/app-scripts version are you using?** 0.4.2

I also tried running the bash as admin if there was any issue with permissions but it still did not work. If I delete the `www/assets` folder, it will work as expected, but then I need to do it everytime I compile.

**Comment by appdezign** [comment]
Same here

**Comment by ataraxus** [comment]
Getting same here with app scripts 44 on Win7 
```

[12:35:19]  ionic-app-scripts 0.0.44
[12:35:19]  watch started ...
[12:35:19]  build dev started ...
[12:35:19]  clean started ...
[12:35:19]  clean finished in 2 ms
[12:35:19]  copy started ...
[12:35:19]  transpile started ...
[12:35:26]  transpile finished in 7.23 s
[12:35:26]  webpack started ...
[12:35:28]  copy: Error copying "C:\git\mobile\projects\xxx\src\assets"
            to "C:\git\mobile\projects\xxx\www\assets"
[12:35:28]  copy finished in 9.03 s
[12:35:38]  webpack finished in 11.89 s
[12:35:38]  sass started ...
[12:35:41]  sass finished in 2.70 s
[12:35:41]  build dev finished in 21.85 s
[12:35:42]  watch ready in 22.57 s
[12:35:42]  dev server running: http://localhost:8100/
```

**Comment by marcoturi** [comment]
delete the content of www (expect .gitignore/.gitkeep) should fix the error.

**Comment by jsayol** [comment]
FYI, I just started seeing this after updating to 0.0.46.
In case it's relevant, I used yarn instead of npm to install dependencies.

```
$ ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v7.2.0
Xcode version: Not installed


$ yarn --version
0.17.8

$ npm --version
4.0.2

$ uname -a
Linux archpc 4.8.8-1-ARCH #1 SMP PREEMPT Tue Nov 15 08:25:24 CET 2016 x86_64 GNU/Linux
```

**Comment by ZiFFeL1992** [comment]
Also here: 

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v6.8.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by Artfloriani** [comment]
I found out that this bug is caused if you have ionic fonts on your src/assets folder. I removed all the ionicons font files that were on src/assets/fonts and now I'm only seeing the error bellow which does not break anything.

```
[10:01:16] copy: Error copying "/path/to/project/node_modules/ionic-angular/fonts" to "/path/to/project/www/assets/fonts"
```

**Comment by thiboot** [comment]
@Artfloriani : it even seems to be when src\fonts exist and is full because i have some other font files than ionicons in it

**Comment by Artfloriani** [comment]
@thiboot The error I mentioned on the previous post is present even if I don't have a `fonts` folder in `src\assets`. But having other custom fonts on that folder does not throw any other error IF those fonts are not a duplicate of ionicons fonts or roboto fonts. 

Are you experiencing something similar?

**Comment by thiboot** [comment]
@Artfloriani : really weird, i just removed all fonts in src/assets/fonts and other assets subfolders. After delete www/ folder and launch ionic serve the error is still persisting...

**Comment by Artfloriani** [comment]
@thiboot Haha, I did the same test a few moments ago. Which of the errors are you getting?

The first one is always present, no matter what I do. The second one is solved by removing ionicons fonts from my assets font folder.

```
copy: Error copying "/path/to/project/node_modules/ionic-angular/fonts" to "/path/to/project/www/assets/fonts"
```
OR

```
 copy: Error copying "PATH\node_modules\ionicons\dist\fonts" to "PATH\www\assets\fonts"
```

**Comment by thiboot** [comment]
@Artfloriani : you're right ! It is definitely the first one which persists !

**Comment by ascorbic** [comment]
I have no fonts in my assets folder and I'm getting the same error. This does seem to be down to 69f89a8, as @jsayol suggested. The script is trying to copy two different fonts folders to the same destination (ionic-angular/fonts and ionicons/dist/fonts). Unless I'm missing something, this doesn't merge the folders, so the second one fails. Can @jgw96 take a look, as it was his commit?

**Comment by RezaRahmati** [comment]
Same issue here, any solutions?

**Comment by danbucholtz** [comment]
This should be resolved.

Thanks,
Dan
