### ISSUE TITLE
ionic serve

### ISSUE THREAD

**Issue by mflmartin** [driftyco/ionic-app-scripts#385]
#### Short description of the problem:
ionic serve --platform ios 

yields Error opening the Browser

#### What behavior are you expecting?

That it serves my app

**Steps to reproduce:**
It's tricky because sometimes it works, others it doesn't. 
1. Create a project
2. ionic serve --platform ios 
3. it hangs there and we can see that it is writing to ionic.config.json the line: "defaultBrowser": true
Even if you remove it before executint the command.

Also if you force chrome, it doesn't work either sometimes.

**Which @ionic/app-scripts version are you using?**
Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS: WINDOWS 10 x64 (By the way, not reported by ionic info)
Node Version: v6.4.0

**Comment by jthoms1** [comment]
@mflmartin Is this issue still occurring for you. I believe that it was likely an issue with livereload that has been resolved in the latest CLI release.
