### ISSUE TITLE
moment-timezone problem:  Cannot find module "./data/packed/latest.json"

### ISSUE THREAD

**Issue by tinquang** [driftyco/ionic-app-scripts#398]
I just upgraded to app-scripts version 0.0.44 from 0.0.39 and I got those 2 errors:

`Failed to load resource: http://0.0.0.0:35729/livereload.js?snipver=1 net::ERR_ADDRESS_INVALID `

`Uncaught Error: node_modules\moment-timezone\index.js:2  Cannot find module "./data/packed/latest.json"`

**Comment by danbucholtz** [comment]
Closing since it's a dupe.

Thanks,
Dan
