### ISSUE TITLE
How to use debug menu in iOS simulator ?

### ISSUE THREAD

**Issue by jigarsdev** [driftyco/ionic-app-scripts#399]
In the latest version 0.0.44  we have option to show debug menu using cmd+shift+8.

But I have tried it but not showing any option. Is there anything to update for this? 
Tried in browser its working fine (Great work !!)

**Which @ionic/app-scripts version are you using?**
0.0.44

**Comment by danbucholtz** [comment]
I don't think it will be possible. It's not actually enabled yet. I'm going to close this for now.

Thanks,
Dan
