### ISSUE TITLE
Do not copy declarations.d.ts

### ISSUE THREAD

**Issue by iron9light** [driftyco/ionic-app-scripts#4]
I'm using pouchdb. Since @types/pouchdb sucks, I wrote my declarations.d.ts with `declare module 'pouchdb';`. But *.d.ts will not copy to .tmp folder.
How can I include 3rd party js lib which has no type define, just like pouchdb.

**Comment by ramonornela** [comment]
I think that @danbucholtz fix this in #29 

Thanks

**Comment by danbucholtz** [comment]
Yep, this is fixed. Thanks all!

Thanks,
Dan
