### ISSUE TITLE
`ionic build` does not build all installed platforms, just iOS

### ISSUE THREAD

**Issue by kelvindart** [driftyco/ionic-app-scripts#402]
#### Short description of the problem:
When running `ionic build` on macOS when you have two platforms installed (iOS and Android), the build process seems to not build every platform, just iOS in this instance.

#### What behavior are you expecting?
When `ionic build` is run, it builds every platform. I am basing this behaviour on `cordova build` which, I am aware, does not have the Angular 2 specific build steps, but it then builds both the Xcode project, and Gradle Project one after the other.

I am expecting `ionic build` to build all platforms enabled.

**Steps to reproduce:**
1. After you have initiated a new repository, add both Android and iOS platforms: `ionic platform add ios && ionic platform add android`
2. Issue a build command: `ionic build`
3. Observe just iOS is built.

**Which @ionic/app-scripts version are you using?**
0.0.43

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
N/A

**Comment by kelvindart** [comment]
Just seen, this is an ionic-cli issue: https://github.com/driftyco/ionic-cli/blob/master/lib/ionic/build.js#L35-L39.

I thought Ionic just passes the arguments through to `cordova build` but the script above confirms it does not.

Cordova build script: https://github.com/apache/cordova-cli/blob/master/src/cli.js#L346-L351

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1691
