### ISSUE TITLE
Updating src/assets should update browser in serve

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-app-scripts#403]
#### Short description of the problem:
Updating an image, or any file in the src/assets folder or subfolder should update the browser when running `ionic serve`. Similar to when a SASS change is detected. 

#### What behavior are you expecting?
The scenario is I am trying to, for example, design a background. I have an app open through `ionic serve` on the specific page. I am making constant changes to a file called background.png and putting this in src/assets/images/. 

I would expect, similar to when a sass change happens, that the browser would notice there is a changed asset and pull in the new background image updated immediately in the browser window. Second prize would be for the app to restart and load any updated assets. 

Currently I have to update the asset. Close ionic serve. Close the browser window. Rerun ionic serve and then navigate to the page I am trying to design. 

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.44
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by danbucholtz** [comment]
@dylanvdmerwe,

Is this still an issue? I don't remember where we left off with this stuff.

Thanks,
Dan

**Comment by dylanvdmerwe** [comment]
Hi Dan. I don't think this is an issue anymore. At least I haven't experienced any situations where this is not happening.
