### ISSUE TITLE
cloud-angular has no exported member provideCloud

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic-app-scripts#404]
#### Short description of the problem:

I just setup a blank app.  Install cloud-angular and init ionic io.
When i try to import provideCloud i get the following error:

`cloud-angular has no exported member provideCloud`

![screen shot 2016-11-16 at 14 30 47](https://cloud.githubusercontent.com/assets/5312907/20349140/51ba7130-ac09-11e6-825a-9dbe064309bd.png)

(I have a similar error with ionicBootrap)

#### What behavior are you expecting?

I expect to properly import `provideCloud` from `@ionic/cloud-angular`

**Steps to reproduce:**
1. ionic start whateva blank --v2
2. npm install @ionic/cloud-angular --save
3. ionic io init
4. Import the following:

```
import { provideCloud, CloudSettings } from '@ionic/cloud-angular';
import { ionicBootstrap, Platform } from 'ionic-angular';
```

**Which @ionic/app-scripts version are you using?**
0.0.44

**Comment by dwieeb** [comment]
@FrancescoMussi What documentation are you following? The `provideCloud` function is a relic from pre Angular 2.0.0 days.

I recommend following our current docs for Ionic 2 setup: http://docs.ionic.io/setup.html

**Comment by jgw96** [comment]
Hello @FrancescoMussi ! I am going to close this one for now as it is not an app-scripts issue. The docs linked to above should fix your issue. Thanks!
