### ISSUE TITLE
Regression: 0.0.44 lost source mapping

### ISSUE THREAD

**Issue by ataraxus** [driftyco/ionic-app-scripts#405]
#### Short description of the problem:
Prior to `0.0.44` one was able to use at least the js code for debugging in `serve` mode, besides they were somewhat hidden. 

#### What behavior are you expecting?
Mapping of the original code, at least in transpiled form. 

**Steps to reproduce:**
1. use `ionic serve` with `0.0.44`

**Which @ionic/app-scripts version are you using?**
```
$ ionic info

Your system information:

 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.2-201611110153
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed

```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

`0.0.44`
![as44](https://cloud.githubusercontent.com/assets/1838191/20350184/24d36294-ac0e-11e6-95d1-f6e9936650dc.PNG)
`0.0.43`
![as43](https://cloud.githubusercontent.com/assets/1838191/20350195/2e5e5954-ac0e-11e6-910f-0573324041c4.PNG)

**Comment by danbucholtz** [comment]
@ataraxus,

The source maps should be there. Please check out file://Path/To/My/Project.

See an example here:

<img width="513" alt="screen shot 2016-11-16 at 2 52 34 pm" src="https://cloud.githubusercontent.com/assets/4680488/20365456/8c465712-ac0c-11e6-895c-074e1b3f6648.png">

Thanks,
Dan
