### ISSUE TITLE
ionic run android --device --livereload no longer recompiles code on change

### ISSUE THREAD

**Issue by rolandjitsu** [driftyco/ionic-app-scripts#406]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
It seems that after I updated to latest (`0.0.44`) and updated the `package.json` to what the changelog indicated, the `ionic run android --device --livereload` command no longer recompiles code on change, neither it builds (ideally it should run a dev build since the device I'm deploying to is connected to my machine).
So in order to have the app running on a device, I have to run `npm run ionic:serve` before I run the described command in another terminal window.

#### What behavior are you expecting?
The command should make a dev build before it deploys to device and then recompile code every time there is a change in source code.

**Steps to reproduce:**
1.
2.
3.

Here is the relevant part of my `package.json`:
```
"scripts": {
	"ionic:build": "ionic-app-scripts build",
	"ionic:serve": "ionic-app-scripts serve",
	"ionic:clean": "ionic-app-scripts clean",
	"ionic:lint": "ionic-app-scripts lint"
},
"config": {
	"ionic_webpack": "./config/webpack.config.js",
	"ionic_copy": "./config/copy.config.js"
}
```

**Which @ionic/app-scripts version are you using?**
`0.0.44`

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by mfdeveloper** [comment]
+1 a have the same problem :disappointed:

**Comment by kodeine** [comment]
i have the same issue and its really hard to code/debug when we have to recompile everything and run it again.

**Comment by rolandjitsu** [comment]
Actually, after updating everything (including ionic-cli), it seems like everything is working now.
```js
{
	"name": "test",
	"version": "0.0.0",
	"description": "",
	"keywords": [],
	"homepage": "",
	"license": "MIT",
	"scripts": {
		"ionic:build": "ionic-app-scripts build",
		"ionic:serve": "ionic-app-scripts serve",
		"ionic:clean": "ionic-app-scripts clean",
		"ionic:lint": "ionic-app-scripts lint"
	},
	"config": {
		"ionic_bundler": "rollup",
		"ionic_rollup": "./config/rollup.config.js",
		"ionic_copy": "./config/copy.config.js"
	},
	"dependencies": {
		"@angular/common": "2.1.1",
		"@angular/compiler": "2.1.1",
		"@angular/compiler-cli": "2.1.1",
		"@angular/core": "2.1.1",
		"@angular/forms": "2.1.1",
		"@angular/http": "2.1.1",
		"@angular/platform-browser": "2.1.1",
		"@angular/platform-browser-dynamic": "2.1.1",
		"@angular/platform-server": "2.1.1",
		"@ionic/storage": "1.1.6",
		"core-js": "^2.4.1",
		"ionic-angular": "2.0.0-rc.3",
		"ionic-native": "^2.2.6",
		"ionicons": "3.0.0",
		"potion-client": "^0.21.5",
		"reflect-metadata": "^0.1.3",
		"rxjs": "5.0.0-beta.12",
		"zone.js": "^0.6.26"
	},
	"devDependencies": {
		"@ionic/app-scripts": "0.0.45",
		"@types/node": "^6.0.46",
		"codelyzer": "^1.0.0-beta.4",
		"cordova": "^6.4.0",
		"ionic": "^2.1.12",
		"rollup-plugin-replace": "^1.1.1",
		"tslint-ionic-rules": "^0.0.8",
		"typescript": "2.0.10"
	},
	"engines": {
		"node": ">= 6.4"
	},
	"cordovaPlugins": [
		"cordova-plugin-device",
		"cordova-plugin-console",
		"cordova-plugin-whitelist",
		"cordova-plugin-splashscreen",
		"cordova-plugin-statusbar",
		"ionic-plugin-keyboard",
		"ionic-plugin-deploy",
		"cordova-plugin-image-picker",
		"cordova-plugin-camera",
		"cordova-plugin-compat",
		"phonegap-nfc"
	],
	"cordovaPlatforms": [
	]
}

```
