### ISSUE TITLE
"Ionic build windows" not working correctly, not add tag wp

### ISSUE THREAD

**Issue by edy-ap** [driftyco/ionic-app-scripts#408]
"Ionic build windows" not working correctly, not add tag wp, Therefore looks bad

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
@jgw96,

Can you move this to the cli repo?

Thanks,
Dan

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1892
