### ISSUE TITLE
Source-maps does not retain the folder structure in browser (Chrome)

### ISSUE THREAD

**Issue by savanvadalia** [driftyco/ionic-app-scripts#414]
#### Short description of the problem:
Unable to view source maps in a proper folder structure as per```src``` directory.

#### What behavior are you expecting?
I expect the source maps to be viewed in a proper folder structure for the ease of finding the file I am trying to debug.

**Steps to reproduce:**
1.  Create a blank starter template and do ```ionic serve``` in command prompt.
2.  Do inspect element in chrome and you should see flat structure for all sourcemaps files.

**Screenshot:1**

![image](https://cloud.githubusercontent.com/assets/17091755/20374613/ed1c25be-accd-11e6-9657-1b5ae12b74f6.png)

**Screenshot:2**
![image](https://cloud.githubusercontent.com/assets/17091755/20374697/68fa6eb6-acce-11e6-9a0f-9432e1f46696.png)

**Screenshot:3(Source code Structure)**
![image](https://cloud.githubusercontent.com/assets/17091755/20375011/6c2503a6-acd0-11e6-8108-f696a4a9097c.png)

**Which @ionic/app-scripts version are you using?**
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.44
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. We are going to use this issue https://github.com/driftyco/ionic-app-scripts/issues/431 as a tracking issue for source maps issues.

**Comment by savanvadalia** [comment]
@jgw96, I don't think this issue is about improving/optimising the current source-maps. 

I have seen a youtube video where the source-map folder structure is shown properly on MAC but the same folder structure is not retained on windows.

Here is the video link for the same https://www.youtube.com/watch?v=nCWCGS5hurY, just check the video from 4:30 on-wards.

As you have closed this issue I just want to highlight the problem once again and want to make sure that this issue is not lost thinking it is similar.

**Comment by rajpat** [comment]
Hi @jgw96 
I have the same issue as @savanvadalia . I can see source-map folder for my app on mac but not on windows 7. (I am using "@ionic/app-scripts": "0.0.45"). This is seriously affecting productivity as our Ion9ic 2 development environment is on Windows 7 Enterprise.
Is there a solution yet to get source-maps working on Windows ?
