### ISSUE TITLE
ionic serve not finding typings

### ISSUE THREAD

**Issue by chris-hammons** [driftyco/ionic-app-scripts#415]
#### Short description of the problem:
When using google-maps typings I cannot run ionic serve. I can run the ionic build.

#### What behavior are you expecting?
that I can use ionic serve with typings

**Steps to reproduce:**
1. setup the following project
```
ionic start MyIonic2Project tutorial --v2
cd MyIonic2Project 
npm install @types/google-maps --save-dev
```
2. Edit the file src/pages/hello-ionic/hello-ionic.ts
```
import { Component } from '@angular/core';

@Component({
  templateUrl: 'hello-ionic.html'
})
export class HelloIonicPage {
  constructor() {
    var location = new google.maps.LatLng(-1, -1);
  }
}
```
3. Modify the file src/index.html to include google script in head tag
```
  <script src="http://maps.google.com/maps/api/js"></script>
```

4. Run `ionic serve`

**Which @ionic/app-scripts version are you using?**
Ionic Framework: 2.0.0-rc.2
Ionic Native: 2.2.3
Ionic App Scripts: 0.0.44
Angular Core: 2.1.1
Angular Compiler CLI: 2.1.1
Node: 4.2.2
OS Platform: Windows 7
Navigator Platform: Win32

**Other information:**
Here is what I am getting
```
[21:28:24]  ionic-app-scripts 0.0.44
[21:28:24]  watch started ...
[21:28:24]  build dev started ...
[21:28:24]  clean started ...
[21:28:24]  clean finished in 1 ms
[21:28:24]  copy started ...
[21:28:24]  transpile started ...
[21:28:27]  typescript: C:/Projects/tests/MyIonic2Project/src/pages/hello-ionic/
hello-ionic.ts, line: 9
            Cannot find name 'google'.

       L8:  constructor() {
       L9:    var location = new google.maps.LatLng(-1, -1);

[21:28:27]  transpile failed
[21:28:27]  copy finished in 2.38 s
[21:28:27]  watch ready in 2.40 s
[21:28:27]  dev server running: http://localhost:8100/
```

**Comment by rapropos** [comment]
Are you importing anything from google in your TypeScript? You need to do that, or declare it.

**Comment by danbucholtz** [comment]
I can't recreate this issue. Please let me know if it's still a legitimate issue.

Thanks,
Dan
