### ISSUE TITLE
Unable to quit the build script like before

### ISSUE THREAD

**Issue by savanvadalia** [driftyco/ionic-app-scripts#416]
#### Short description of the problem:
Unable to quit a running build script by pressing `q`.  No longer see the list of commands to quit, restart etc. (See Screenshot:1). Surprisingly changing the scripts in `package.json` as below in Steps to reproduce allows to quit.

#### What behaviour are you expecting?
I expect a way to quit the build scripts. Currently I have to close command prompt and start all over again and then need to browse to project directory again. This is painful.

**Steps to reproduce:**
1. Create a blank starter template and do `ionic serve` in command prompt.
2. Press `q` and try to quit the build as such it will not quit the build script.
3.  Change scripts in `package.json` like below it should allow you to quit but it doesn't show usual logs with the default scripts.

**From**
```
"scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  }
````
**To**
```
"scripts": {
    "build": "ionic-app-scripts build",
    "serve": "ionic-app-scripts serve"
  }
````

**Screenshot:1** 
![image](https://cloud.githubusercontent.com/assets/17091755/20375613/58120806-acd4-11e6-8ba2-6c1b5e5319c8.png)

**Which @ionic/app-scripts version are you using?**

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.44
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed

**Comment by Simpler1** [comment]
I posted a similar issue on Slack yesterday and found that if you press `<ctrl-c>` instead of pressing `q`, it will close all of the node.exe processes (as expected).  

Not a solution, but a workaround in the interim...

**Comment by dylanvdmerwe** [comment]
`Ctrl-c` will cancel the script. I don't think anything more is needed really.

**Comment by CarlRyds** [comment]
I liked the old way of doing it with the Q to Quit, R to Reload, etc. it was easy to understand and work with

**Comment by savanvadalia** [comment]
Thanks you all for the temporary fix. Would be good if they can add quit command to debug tools which from memory is currently available on ctrl+shift+8.

**Comment by danbucholtz** [comment]
For now I don't think we have any plans to add this functionality. `Ctrl-c` and `Command-c` is very common for this sort of thing. We'll reopen if anything changes here.

Thanks,
Dan

**Comment by savanvadalia** [comment]
Thank @danbucholtz  Ctrl+C works and is good enough for me as of now

**Comment by Barryrowe** [comment]
This is not completely fixed. I can ctrl+c ti quit immediately after ionic-serve, but as soon as I change a file and another build is started, I can no longer ctrl+c to quit.

Ionic info:

```
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by danbucholtz** [comment]
@Barryrowe,

You should be able to do a command-c at any time. Please try again and let me know if that's not the case.

Thanks,
Dan

**Comment by Barryrowe** [comment]
I forgot to report back. This looks like sit was an issue with a bad npm install. I am on 0.0.45 and haven't had issues lately.
