### ISSUE TITLE
ionic serve can't get the config value

### ISSUE THREAD

**Issue by jcDu** [driftyco/ionic-app-scripts#418]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
ionic serve can't get the config value(like --lab,-l,-c,-s)

#### What behavior are you expecting?
after I run `ionic serve -lcs`, it should open my browser and output the server and console logs on my terminal.

And I get `false` on console.log(launchLab(context)).

**Steps to reproduce:**
1.just run `ionic serve -lcs`

```
insert any relevant code between the above and below backticks
```

    context = config_1.generateContext(context);
    var config = {
        httpPort: getHttpServerPort(context),
        host: getHttpServerHost(context),
        rootDir: context.rootDir,
        wwwDir: context.wwwDir,
        buildDir: context.buildDir,
        launchBrowser: launchBrowser(context),
        launchLab: launchLab(context),
        browserToLaunch: browserToLaunch(context),
        useLiveReload: useLiveReload(context),
        liveReloadPort: getLiveReloadServerPort(context),
        notificationPort: getNotificationPort(context),
        useServerLogs: useServerLogs(context),
        useProxy: useProxy(context),
        notifyOnConsoleLog: sendClientConsoleLogs(context)
    };

**Which @ionic/app-scripts version are you using?**
0.0.44

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
This should be resolved in 1.0.0. Please let me know if it's not and a simple reproduction case for the issue.

Thanks,
Dan
