### ISSUE TITLE
[0.0.44] build dev failed

### ISSUE THREAD

**Issue by alfredteo36** [driftyco/ionic-app-scripts#419]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
[22:59:08]  build dev failed: Cannot read property 'length' of undefined

#### What behavior are you expecting?
Build Successful

**Steps to reproduce:**
1. Ionic serve 
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
0.044

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.44
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.1.0
Xcode version: Not installed

The resource from “http://localhost:8100/build/main.css” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).
The resource from “http://localhost:8100/build/main.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).

**Comment by fiznool** [comment]
I have this same issue if I use `yarn`, are you using it?

If so, try to use `npm install` instead.

**Comment by alfredteo36** [comment]
Nope I am not using yarn. 
Have perform npm install and update npm to 4.0.2 but still build fail and browser show resource block on console log

**Comment by marcoturi** [comment]
I've just implemented yarn [here](https://github.com/marcoturi/ionic2-boilerplate), just copy the package.json deps. I have also added an example to an integration with gitlab continuous integration. 

The error you are getting came from typescript. Block the version to 2.0.10 without the ^ and probably yarn will not complain. To make it work I have also added tslint to devDep.

**Comment by danbucholtz** [comment]
This should be resolved.

Thanks,
Dan
