### ISSUE TITLE
UglifyJs in Webpack

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic-app-scripts#420]
Webpack has Uglify Js integrated within it, thus there should be needed an uglify task for prod when bundler is webpack. 

This will also solve issues that uglify will run twice on same file when you have multiple entry points in webpack.

https://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin

I see two approaches,

1) run uglify through webpack and disable the uglify task. (Prod only)

2) provide option for users to pass an array or inputs rather than 1 file only. This actually will also be great on Clean Cas

I am sorry for always making requests etc.. but to tell the truth I am fond of this library, and i think you are doing a great job!

**Comment by danbucholtz** [comment]
@alan-agius4,

Right now we are using Webpack exclusively as a bundler so we can support other bundlers like Rollup. For now we don't plan on doing this but I'll re-open if we reconsider this.

Thanks,
Dan
