### ISSUE TITLE
Assets in www not being cleaned

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-app-scripts#426]
#### Short description of the problem:
Old assets are not being removed from the www folder. 

#### What behavior are you expecting?
Assets in the www folder should mimic those from the src folder when running `ionic build ios` or `ionic build android`.

My src/assets folder:
![image](https://cloud.githubusercontent.com/assets/2852839/20423889/a51e216e-ad7b-11e6-8ed2-0487c5410936.png)

My www/assets:
![image](https://cloud.githubusercontent.com/assets/2852839/20424033/590444a6-ad7c-11e6-9cfe-381e9089401f.png)

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by AndreasGassmann** [comment]
This is still an issue in the most recent version (0.0.48).

In the debug log it shows that it is only deleting the build folder, but not the assets folder.

```
[11:26:16]  clean started ... MEM: 115.9MB 
[ DEBUG! ]  [Clean] clean: cleaning /Users/andreas/project/www/build  MEM: 115.9MB 
[11:26:16]  clean finished in 10 ms MEM: 116.1MB
```

**Comment by danbucholtz** [comment]
This should be resolved. It is configurable. It is a super challenging problem with globs, though, so it does not always work reliably in some super edge cases. It will work for the vast majority of cases though.

Thanks,
Dan
