### ISSUE TITLE
Can't debug again in chrome with app-script 0.0.45

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#428]
Hi,

I upgraded from app-script version 0.0.43 to 0.045, didn't changed anything else except that update and I can't debug anymore in Chrome.

    "scripts": {
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
      },
      "config": {
        "ionic_sass": "./scripts/sass.config.js",
        "ionic_copy": "./scripts/copy.config.js"
      }

Did I missed something in the update aka should I had updated some local config files?

If no thx in advance for fixing the issue.

Best regards

<img width="223" alt="capture d ecran 2016-11-18 a 10 57 50" src="https://cloud.githubusercontent.com/assets/16886711/20426157/15702352-ad7e-11e6-8705-136bf3fbd92e.png">

**Comment by neguso** [comment]
Add the following configuration to enable creation of the source map file:

```
"config": {
    "ionic_source_map": "source-map"
  }
```

More information in the [ionic-app-scripts](https://github.com/driftyco/ionic-app-scripts) project.

**Comment by peterpeterparker** [comment]
thx a lot @neguso 

it solved my issue.
