### ISSUE TITLE
build fails with cordova 6.4.0

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic-app-scripts#429]
#### Short description of the problem:
ionic platform add android/ios going into infinite loop of printing dots with cordova 6.4.0. Working with cordova 6.3.1. Latest version of phonegap push plugin requires cordova 6.4.0.
```

ionic2-push-base$ ionic plugin add phonegap-plugin-push
Unmet project requirements for latest version of phonegap-plugin-push:

    cordova (6.3.1 in project, >=6.4.0 required)
Fetching highest version of phonegap-plugin-push that this project supports: 1.8.4 (latest is 1.9.0)


```
#### What behavior are you expecting?
It should work

**Steps to reproduce:**
1. Update cordova to 6.4.0
2. `ionic platform add android` won't work with ionic2-app-base

**Which @ionic/app-scripts version are you using?**
0.0.45

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Your system information:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.1 Build version 8T61a

**Comment by mcornillon87** [comment]
Same issue here... Any news ?

**Comment by jayeshanandani** [comment]
Can you please update cordova to 6.4.0 and ionic cli to 2.1.18 and try again?  I have tried same in MAC but not able to reproduce the issue.

**Comment by aggarwalankush** [comment]
It's working now with ionic cli 2.1.18, still prints lots of dots in terminal which feels like infinite loop but works after a minute or so.

**Comment by jayeshanandani** [comment]
Those dots are due to Gradle being added for latest version. It will happen only once. Once done it won't repeat same thing again.
