### ISSUE TITLE
watch on 0.0.45 fails with A watch configured to watch the following paths failed to start

### ISSUE THREAD

**Issue by andrevcf** [driftyco/ionic-app-scripts#430]
#### What behavior are you expecting?
npm run watch with version 0.0.43 is ok.
with version 0.0.45 i get the error `A watch configured to watch the following paths failed to start. It likely that a file referenced does not exist`

**Steps to reproduce:**
1. npm run watch
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
0.0.45

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Is the app you are experiencing this issue with on Github? If so, could we have the link? Most likely you have deleted or renamed a file, such as our `app.module` file, that our watch task expects to be there.

**Comment by andrevcf** [comment]
I didn't move or deleted or renamed any file from 0.0.43 to 0.0.45.
the list of files from the error: 
`....does not exist: /home/andre/trabalho/projetos/solucioneOnline/app.new/src/assets/, 
            /home/andre/trabalho/projetos/solucioneOnline/app.new/src/index.html, 
            /home/andre/trabalho/projetos/solucioneOnline/app.new/src/manifest.json, 
            /home/andre/trabalho/projetos/solucioneOnline/app.new/src/service-worker.js, 
            node_modules/ionic-angular/polyfills/polyfills.js, node_modules/ionicons/dist/fonts/`

But I never had a file manifest.json on the project like the one on the above list.

**Comment by andrevcf** [comment]
ok. started a new project with `ionic start cutePuppyPics --v2`, copied the manifest.json to my project and now it works. thanks

**Comment by rainmak33r** [comment]
I had the same problem, adding 
"sw-toolbox": "3.4.0"
to the package.json, fixed the problem. Hope it helps somebody.

**Comment by Malkiat-Singh** [comment]
@rainmak33r  Thanks it works

**Comment by erdemildiz** [comment]
@rainmak33r  Thanks man! Its work :+1:
