### ISSUE TITLE
Revisit Source Maps

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-app-scripts#431]
- [x] Not all of ionic-angular has a source map

- [x] Investigate cheaper source map options with original source

- [x] Improve docs and show an example

**Comment by rajpat** [comment]
Hi @jgw96
I have the same issue as @savanvadalia . I can see source-map folder for my app on mac but not on windows 7. (I am using "@ionic/app-scripts": "0.0.45"). This is seriously affecting productivity as our Ionic 2 development environment is on Windows 7 Enterprise.
Is there a solution yet to get source-maps working on Windows ?

**Comment by danbucholtz** [comment]
@rajpat,

Yes, it should work in `0.0.47`.

Thanks,
Dan

**Comment by olivermuc** [comment]
Have you guys got source maps working, finally?
I just downloaded the latest "ionic2-app-base", with the npm modules installed:

├── @angular/common@2.2.1
├── @angular/compiler@2.2.1
├── @angular/compiler-cli@2.2.1
├── @angular/core@2.2.1
├── @angular/forms@2.2.1
├── @angular/http@2.2.1
├── @angular/platform-browser@2.2.1
├── @angular/platform-browser-dynamic@2.2.1
├── @angular/platform-server@2.2.1
├── @ionic/app-scripts@0.0.47
├── @ionic/storage@1.1.6
├── ionic-angular@2.0.0-rc.4
├── ionic-native@2.2.11
├── ionicons@3.0.0
├── rxjs@5.0.0-beta.12
├── typescript@2.0.9
└── zone.js@0.6.26

Still no source maps in Safari (running the app in ios Simulator).
What am I missing?

Thanks!

**Comment by pjc2007** [comment]
I started a new project yesterday (RC4) and source maps are now working, at
least using Chrome with either Ionic serve or the browser emulator (i.e.
debugging from VS Code) on Windows

My components are exactly the same version as yours....

   "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.4",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.47",
    "typescript": "2.0.9"
  },

**Comment by olivermuc** [comment]
Apologies, should have been clearer about the issue.

The source map is generated (main.js.map) in the build/ folder, but apparently not loaded / considered by Safari. I also can't judge whether the created map is legit.

I do see statements in the main.js file:
//# sourceMappingURL=index.js.map

I may know enough about how source maps are loaded and correlated but it strikes me that one JS file can have multiple individual source map directives that essentially point to non existent files.

**Comment by snortblt** [comment]
I've tried everything I can think of and everything I've found here to get source maps working in safari with ionic 3. Should this just work out of the box at this point? Debugging on iOS is very frustrating for me a present.
