### ISSUE TITLE
app-scripts how to compile multiple scss to multiple dir

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-app-scripts#432]
_From @dragonahao on November 17, 2016 13:20_

app-scripts how to compile multiple scss to multiple dir
1.I want to compile ionic v2 scss ( with ionic-components ) to a dir  
2.and I want to compile my component scss file to anthor dir 

3.I want to compile my component typescript files to a dir 

I try to create myself ./config/sass.config.js  file , but my component`s scss always compile together with ionic library 's scss

What should I do ?

_Copied from original issue: driftyco/ionic#9202_

**Comment by brandyscarney** [comment]
_From @dragonahao on November 17, 2016 13:23_

main.css and main.js  is too bigger (fileSize > 6M),so i want to split package 
but i failed

**Comment by danbucholtz** [comment]
Hi @dragonahao,

We're working on the package size to reduce it. We generate one sass output file that is includes only the components from ionic you're using and your sass. 

We probably will not support this use case, but you're welcome to create your own sass script. It wouldn't be too difficult to do I don't think.

Thanks,
Dan

**Comment by Sevenonclick** [comment]
two years passed, any solutions?My main.css was too large, about5.5M, can't split it to other file?
