### ISSUE TITLE
Don't log Websocket errors

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-app-scripts#434]
^

**Comment by adamdbradley** [comment]
Attempt to reconnect X number of times if the connection was dropped.

**Comment by brandyscarney** [comment]
`error sending client ws, Error: not opened`

Adding this comment so it shows up in search

**Comment by DhruvGupta5** [comment]
happens same with me on ionic run android

**Comment by Maziar-Fotouhi** [comment]
I'm still getting **websocket errors** on **0.0.48**.
Here is a sample:

`error opening ws message: {"category":"console","type":"log","data":["DEVICE READY FIRED AFTER",6244,"ms"]}`

**OR**

```
error opening ws message: {"category":"console","type":"log","data":["Cannot retrieve 
            item",{"code":2,"source":"Native","exception":null}]} 
```

**Comment by maxflex** [comment]
Same on **1.0.0**

**Comment by giboow** [comment]
Same error occured 
```
error opening ws message: {"category":"console","type":"log","data":["DEVICE READY FIRED AFTER",4397,"ms"]} 
```
Here is my configuration
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002

```

**Comment by smit26** [comment]
facing the same issue, any solutions for this yet?
