### ISSUE TITLE
TS changes not being bundled in Webpack with ionic serve

### ISSUE THREAD

**Issue by nickwinger** [driftyco/ionic-app-scripts#437]
When i start ionic serve and make a change in a Typescript file the watcher triggers and starts transpilation, after that the webpack triggers but don't "sees" changes in the (generated) js files, so nothing changed in the ouput and also he reload of the brower is not triggered.

If i then make a second (dummy) change in the typescript file, again the transpilation triggers, after that webpack sees the change in the js files and updates the bundle.

It's always just the seconds time the webpack sees the changes.

This is very annoying while working. Maybe it needs a little bit more time between the transpilation and the webpack to see the changes in the filesystem ?

I'm on a Windows7 System

**Comment by danbucholtz** [comment]
Can you try testing this with:

`npm install @ionic/app-scripts@nightly` and see if you can recreate with the latest? I think this issue should be resolved.

Thanks,
Dan

**Comment by alan-agius4** [comment]
@danbucholtz the latest `@nightly` also solves my issues  https://github.com/driftyco/ionic-app-scripts/issues/435

Thanks

**Comment by nickwinger** [comment]
it seems to work with @nightly, thanks

**Comment by nickwinger** [comment]
just another weired thing i encounter is that if i quit "ionic serve" by pressing "q" or "quit"
The node processes in memory still are there taking up some hundred megabytes.
Shouldn't they get discarded ?

**Comment by danbucholtz** [comment]
@nickwinger, it should get cleaned up. Please let me know if it doesn't.

Thanks,
Dan
