### ISSUE TITLE
Tree-shaking not working

### ISSUE THREAD

**Issue by dorgold** [driftyco/ionic-app-scripts#442]
#### Short description of the problem:
Tree-shaking is not working with Webpack bundler

#### What behavior are you expecting?
I would expect main.js bundle to **not** include code from external libraries which was not imported to the app.

**Steps to reproduce:**
1. Create a project from the starter template
2. Run `ionic build`
3. Produced bundle (main.js) includes:
 - All the code from 'ionic-native' (while only StatusBar, Splashscreen are imported).
 - Unused components from 'ionic-angular' (for example Searchbar, Slides, ...).
 - If you import a third party library such as Lodash and import only a few methods, all the library is present in the bundled output.

**Which @ionic/app-scripts version are you using?**
0.0.39-0.0.45

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
@dorgold,

This is a [known issue](https://github.com/webpack/webpack/issues/2867) with Webpack. We are tracking the issue and will resolve as soon as possible.

Thanks,
Dan

**Comment by lordgreg** [comment]
Hi @danbucholtz 

Since the webpack treeshaking isn't working properly, may we switch to rollup to get the treeshaked code? Putting:
```
  "config": {
    "ionic_bundler": "rollup",
    "ionic_source_map": "source-map"
  }
```
in `package.json` doesn't bring much to file sizes at the end. Does that mean the treeshaking also doesn't work?

Thank you for your feedback.

**Comment by danbucholtz** [comment]
@lordgreg,

This is something I am actively working on.

https://github.com/rollup/rollup/issues/1130
https://github.com/rollup/rollup/issues/1128

Are issues filed by the Angular team about tree shaking.

We will have some stuff to share here soon. Reducing bundle size is my number one concern right now.

Thanks,
Dan
