### ISSUE TITLE
allow building despite TS errors

### ISSUE THREAD

**Issue by tycho01** [driftyco/ionic-app-scripts#443]
Currently app-scripts' TS transpiler [cancels](https://github.com/driftyco/ionic-app-scripts/blob/254bb6c3085c37d3018eb855f67fb9e843e297fe/src/transpile.ts#L122-L126) the build on TS errors. I definitely like the pretty screen, but enforcing this behavior as a default setting presumes that the typings of all libraries, and in fact, TypeScript itself, are both infallible. I feel this might not be fully realistic in all cases, especially given even just the TypeScript repo itself has around [1.5k](https://github.com/Microsoft/TypeScript/issues) outstanding issues. Might it be an option to allow overriding this behavior with e.g. a command-line switch?

Related:
- [ng-cli](https://github.com/angular/angular-cli/issues/3034)
- [ionic-gulp-tasks](https://github.com/driftyco/ionic-gulp-tasks/issues/57)

**Comment by danbucholtz** [comment]
We may someday allow this but this behavior does not jive with what we think provides the best experience. I'll keep it open as a low priority issue.

Thanks,
Dan

**Comment by tycho01** [comment]
In the event you'd nevertheless be willing to take a PR on this, I've made one from my fork.

**Comment by danbucholtz** [comment]
@tycho01,

Sorry, this is outside of the scope of what we intend to do. Maybe in the future but in all sincerity probably not.

Thanks,
Dan
