### ISSUE TITLE
type definitions from plugin /www folders not copied to .tmp for aot builds

### ISSUE THREAD

**Issue by rob3c** [driftyco/ionic-app-scripts#446]
#### Short description of the problem:
Type definition files from plugin `/www` folders are not copied to the `/.tmp` folder for Aot production builds. They work fine in dev builds.

#### What behavior are you expecting?
Production builds should see side-by-side type definitions in plugin `/www` folders.

**Steps to reproduce:**
1. Install a cordova plugin with a side-by-side type definition `*.d.ts` file like `cordova-plugin-ms-adal`.
2. Reference a global from the plugin type definition (e.g. `Microsoft.ADAL...` above).
3. Run a dev build and see everything work fine.
4. Run a prod build and see the errors thrown by the AoT compiler about "cannot find namespace xxx" and such (e.g. "Cannot find namespace Microsoft..." in the above example).

```
// put this in device ready or somewhere - dev works fine, but aot won't see `Microsoft` defined
let authContext = new Microsoft.ADAL.AuthenticationContext('https://login.windows.net/common');
```

**Which @ionic/app-scripts version are you using?**
I tried 0.0.39 and the latest 0.0.46

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by rob3c** [comment]
Just wanted to add that my workaround is to manually copy the .d.ts files to the project folder.

Often, plugin type definitions aren't distributed side-by-side with the plugins, so people use ones from `DefinitelyTyped` (or the `@types` npm mirror). That puts them in locations that the ionic prod build will handle correctly. However, those aren't always up-to-date (the DT definition for the Microsoft ADAL plugin mentioned above is waaay out of date). Since typescript itself sees side-by-side plugin definitions just fine - and, by extension, so does the ionic dev build - the ngc copy process needs to be updated to support them.

**Comment by danbucholtz** [comment]
@rob3c,

Sorry, we recommend using @types or `npm` to manage this. Worst case, if that doesn't work, you could add an entry to the `copy.config` and let the copy task handle it for you.

Please let me know if that will work for you.

Thanks,
Dan

**Comment by rob3c** [comment]
@danbucholtz Copying the files over myself isn't the issue (there are plenty of ways for me to manually do that). Such a manual process is exactly what I'm trying to avoid, especially when it makes sense for ionic to take care of it as part of cordova plugin support.

I created this issue because it seems appropriate for ionic to support libraries that actually go to the trouble of distributing their own type definitions in their npm package alongside their code. Since ionic is built on cordova, it seemed reasonable that ionic should support the `/www` distribution folder convention for plugin assets, including type definitions for its contents.

I'm not sure what you mean by letting *npm* manage this, since the plugins I'm talking about are already installed via npm. Also, `@types` on npm is just an auto-generated mirror of the DefinitelyTyped repo, which is really a hack to provide type definitions for those libraries that don't already distribute type definitions along with their js files. It's much better when libraries distribute their own definition files to help keep things in sync. Why discourage plugin writers from distributing their own definitions?

**Comment by danbucholtz** [comment]
If there are definitions in the `npm package`, say... `@angular/core` or `ionic-angular` for example, they'll be resolved and everything will work happily.

We don't actually use the `.tmp` folder anymore, so it is a non-issue either way. Everything should just work.

Thanks,
Dan

**Comment by rob3c** [comment]
Sounds good! I've had to switch away from ionic temporarily, so I missed that welcome change to the build process. I look forward to diving back in in the next few weeks.
