### ISSUE TITLE
unable to see console and server logs with ionic run android @app-scripts .45, .46

### ISSUE THREAD

**Issue by DhruvGupta5** [driftyco/ionic-app-scripts#447]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
upon ionic run android -l -c -s unable to see any console logs or server logs, tried with all app scripts from .40 to .46.

#### What behavior are you expecting?
should show console logs and server logs.

**Steps to reproduce:**
1.  ionic run android -l -c -s
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
.46

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed

**Comment by jigarsdev** [comment]
+1

**Comment by danielabbatt** [comment]
I find they do work (both .45 and .46), but only when using CLI 2.1.8
If I use anything above 2.1.8 (up to 2.1.12 at time of this comment) I lose the console logs.

**Comment by DhruvGupta5** [comment]
@danielabbatt is there a way to downgrade cli ?

**Comment by jigarsdev** [comment]
@DhruvGupta5 You can get 2.1.8 cli by running `npm install -g ionic@2.1.8`

**Comment by danielabbatt** [comment]
Yes that's exactly what I do

**Comment by DhruvGupta5** [comment]
@jigarsdev @danielabbatt thanks

**Comment by jthoms1** [comment]
Updating to the latest version of the CLI will resolve this issue.  Thanks!

`npm install -g ionic@latest`
