### ISSUE TITLE
ionic run android - unable to test native modules on device - @app-scripts .45, .46

### ISSUE THREAD

**Issue by DhruvGupta5** [driftyco/ionic-app-scripts#452]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
upon ionic run android native modules are not working, earlier they used to work, upon build these modules are working , just in the run mode they are not working.

#### What behavior are you expecting?
they should work.

**Steps to reproduce:**
1. ionic run android -l -c -s
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
.46 but tested with all of them

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)]]

**ionic info**

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed

**cordova plugin list**

cordova-plugin-console 1.0.4 "Console"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-plugin-x-socialsharing 5.1.3 "SocialSharing"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by lukasbisdorf** [comment]
I think this one is related: https://github.com/driftyco/ionic-app-scripts/issues/467

**Comment by jayeshanandani** [comment]
Can you please try with `0.0.48` ionic app scripts?

**Comment by danbucholtz** [comment]
I believe this issue is resolved. Please provide a minimal reproduction case repository if it's not and I'll check it out.

Thanks,
Dan
