### ISSUE TITLE
GET http://0.0.0.0:35729/livereload.js?snipver=1 net::ERR_ADDRESS_INVALID

### ISSUE THREAD

**Issue by thiboot** [driftyco/ionic-app-scripts#453]
#### Short description of the problem:
livereload error in console when runing ionic serve

**Steps to reproduce:**
1. run `ionic serve`

```
GET http://0.0.0.0:35729/livereload.js?snipver=1 net::ERR_ADDRESS_INVALID
```

**Which @ionic/app-scripts version are you using?**
0.0.46

**Other information:**
Seems to be resolved with this manipulation in ionic-app source:
https://forum.ionicframework.com/t/err-address-invalid-after-latest-update-0-0-42-ionic-app-scripts/70423/4

**Comment by danbucholtz** [comment]
@thiboot,

This should be resolved now in 1.0.0.

Thanks,
Dan
