### ISSUE TITLE
Error running ionic serve v2 sample app

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#460]
_From @barocsi on November 20, 2016 18:23_

**Ionic version:**  (check one with "x")

[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

Just updated ionic, started v2 sample app
receiving
```
src\pages\tabs\tabs.ts:1Uncaught Error: Module build failed: TypeError: Cannot read property 'content' of

 at Object.typescriptSourcemapLoaderMemory (\node_modules\@ionic\app-scripts\dist\webpack\typescript-sourcemap-loader-memory.js:21:34)
````

_Copied from original issue: driftyco/ionic#9253_

**Comment by jgw96** [comment]
_From @tycho01 on November 21, 2016 11:48_

A similar report [here](https://forum.ionicframework.com/t/uncaught-error-module-build-failed-in-webpack/69977) stated an `npm cache clean` then reinstall of ionic did it.

**Comment by gorancn** [comment]
Cleaning npm cache and reinstalling ionic does not help me to resolve this issue when running **ionic serve**. Unfortunately I was force to revert to older version of ionic(app-script and ionic-angular).

**Comment by Maziar-Fotouhi** [comment]
I did `npm cache clean` -> `sudo npm uninstall ionic -g` -> `sudo npm install ionic@latest`
But it did **NOT** help. I still see the exact same error mentioned here.

I used to have _ionic-cli_ version _2.1.4_. Now it's updated to version _2.1.13_.
Here is the result of running ionic info:
```

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.44
ios-deploy version: 1.9.0 
ios-sim version: 5.0.9 
OS: macOS Sierra
Node Version: v6.2.2
Xcode version: Xcode 8.1 Build version 8B62
```


Here are parts of my _package.json_ which may help you find the root of this problem:

```
"private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "^2.2.6",
    "ionicons": "3.0.0",
    "ng2-translate": "3.1.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.44",
    "typescript": "2.0.9"
  },
```
### 
AND

```
"cordovaPlatforms": [
    "ios",
    "android"
  ],
```

**Comment by Maziar-Fotouhi** [comment]
## Solved my issue

Okay... I finally figured it out. This problem was showing up **after updating** to _version 0.0.40_.
So I added some debug statements to the newly added _typescript-sourcemap-loader-memory.js_ file.
Turns out that I had a misspelling in one of the import statements:

`import {Constants} from "../../lib/Constants";`

instead of:

`import {Constants} from "../../lib/constants";`

This was wrong since the letter 'c' was uppercase. For some unknown reason it was just running fine on version 0.0.39 and below. With the update, webpack was looking for _"/lib/Constants.js"_ and _"/lib/Constants.js.map"_ , which did not exist.


The strange thing is that it was %100 functional before this update!
But anyway, I really expected a **more intuitive error message** than that.

Hope this saves other people some time!

**Comment by dm-grinko** [comment]
I have the same issue
ionic info:                                                                                                 

> Cordova CLI: 6.3.1                                                                             
> Ionic Framework Version: 2.0.0-rc.3                                                            
> Ionic CLI Version: 2.1.14                                                                      
> Ionic App Lib Version: 2.1.7                                                                   
> Ionic App Scripts Version: 0.0.45                                                              
> ios-deploy version: Not installed                                                              
> ios-sim version: Not installed                                                                 
> OS: Windows 10                                                                                 
> Node Version: v6.0.0                                                                           
> Xcode version: Not installed 

@Maziar-Fotouhi I can't find import {Constants} from "../../lib/constants"; in typescript-sourcemap-loader-memory.js 

I can see in my typescript-sourcemap-loader-memory.js  - 
`var context = helpers_1.getContext();`

**Comment by Maziar-Fotouhi** [comment]
@dm-grinko `import {Constants} from "../../lib/constants";` was a custom code from my project.
You might be misspelling another import in one of your files. I can try to help you debug this.
Could you please provide your console error logs from the browser?

**Comment by dm-grinko** [comment]
@Maziar-Fotouhi 
ok, but I haven't any custom code in this project because it is my first app.
I got this issue before I start do something.
I repeat steps from youtube tutorial of Mirko Nasato 
[https://www.youtube.com/watch?v=qdeD9rYlBU4&t=288s](url)

**Comment by Maziar-Fotouhi** [comment]
@dm-grinko You can expand the error log in the console and see the origin. At least in Chrome, you can. Try to open the app in Chrome and paste the whole error log here, please.

**Comment by dm-grinko** [comment]
@Maziar-Fotouhi 
![issue](https://cloud.githubusercontent.com/assets/14158015/21019854/1a74127c-bd83-11e6-8b49-4cbede969efc.png)

**Comment by Maziar-Fotouhi** [comment]
@dm-grinko How did you find this out? What was your previous webpack version? What is your current version after update?
You could have clicked on the small triangle just on the left hand side of the word "Error". This would have expanded the error logs and probably showed the origin.

**Comment by dm-grinko** [comment]
Yes, the small triangle helped me. I didn't have the Webpack before. Thanks

**Comment by danbucholtz** [comment]
This should be resolved now.

Thanks,
Dan
