### ISSUE TITLE
lab only updates Windows on change

### ISSUE THREAD

**Issue by moldstadt** [driftyco/ionic-app-scripts#461]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When running "ionic serve --lab", and making a change, only the Windows view is updated to reflect changes. 

#### What behavior are you expecting?
iOS and Android views should also update.

**Steps to reproduce:**
1.  ionic serve --lab (in any project)
2.  make a change to the code that affects the view and save (e.g. template or sass)
3.  

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
0.0.46

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by eholland7080** [comment]
I am experiencing the same issue.  How in my case stopping and restarting ionic serve --lab and perform template changes and saving, the platform that live reloads changes, but it is always only one that live reloads.  Refreshing the browser does show the changes for the other two, but only one live reloads.  Did you find out anything on this issue?
Thanks
Eric

**Comment by moldstadt** [comment]
Sorry, still having this problem. Just so happened that the first 10 or so times it was always reloading Windows, but like you said, it seems to be random.
