### ISSUE TITLE
Args not being passed to configs due to worker-client

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic-app-scripts#463]
#### Short description of the problem:
In my `cleancss.config.js` and `uglifyjs.config.js`, I am dependent on npm args. However the `worker-client` is being spawned as another process, which is causing the args not to be passed.

#### What behavior are you expecting?
The args are passed, this can be solved by not using the `worker-client` but the `cleanCssWorker` and `uglifyjsWorker`. To make it clear, I am not 100% sure what's the need and scope of the worker-client

```
const args = require("../args");

module.exports = {
	sourceFileName: `${args.output}/styles/app.mobile.css`,
	destFileName: `${args.output}/styles/app.mobile.css`,
};
```
**Which @ionic/app-scripts version are you using?** 0.0.46

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
PR merged.

Thanks,
Dan
