### ISSUE TITLE
All ionic project shows me the same file

### ISSUE THREAD

**Issue by adirzoari** [driftyco/ionic-app-scripts#465]
hey,
weird issue happen me just, i'm trying to run my project and i saw other app with this photo
![ionic 2](https://cloud.githubusercontent.com/assets/20258998/20554034/b66cae60-b161-11e6-9e6d-c886d9d21882.jpg)

i opened a new project and see the same image.
is this any issue with ionic 2??

**Comment by danbucholtz** [comment]
No, this is a user error 😸 

Thanks,
Dan
