### ISSUE TITLE
Bug console.log function does not work on Android device, ionic test 2 RC3

### ISSUE THREAD

**Issue by sebaxtian** [driftyco/ionic-app-scripts#473]
#### Short description of the problem:
This console.log function work with running on 'ionic serve' the browser show console.log.

But running on 'ionic run android -lc' or 'ionic run android' --livereload --consolelogs' not work console logs on android device.

#### What behavior are you expecting?
Using Ionic 2 RC2 the console.log function works from the android device, with the update to RC3 stopped working.

**Steps to reproduce:**
1. run: ionic serve (this will work fine for console.log)
2. run: ionic run android -lc (this will not work fine for console.log)
3. run: ionic run android --livereload --consolelogs (this will not work fine for console.log)
4.

```
constructor(public navCtrl: NavController) {
    /**
     * This console.log function work with running on 'ionic serve'
     * the browser show console.log.
     * 
     * But running on 'ionic run android -lc' or 'ionic run android' --livereload --consolelogs'
     * not work display console logs on android device.
     */
    console.log('Constructor Home Page');
  }

testConsole() {
    /**
     * This console.log function work with running on 'ionic serve'
     * the browser show console.log. Event click button.
     * 
     * But running on 'ionic run android -lc' or 'ionic run android' --livereload --consolelogs'
     * not work display console logs on android device. Event click button.
     */
    console.log('Click on button Test Console Log');
  }
```

**Which @ionic/app-scripts version are you using?**

"@ionic/app-scripts": "0.0.45",

sebaxtian@Satellite [ test ] >> sudo ionic info

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v5.12.0
Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

This is my project, https://github.com/sebaxtian/ionic2-angular2/tree/master/test using the console.log function in the home.ts file

home.ts file: https://github.com/sebaxtian/ionic2-angular2/blob/master/test/src/pages/home/home.ts
home.html file: https://github.com/sebaxtian/ionic2-angular2/blob/master/test/src/pages/home/home.html

package.json file: https://github.com/sebaxtian/ionic2-angular2/blob/master/test/package.json

**1. run: ionic serve (this will work fine for console.log)**
![1d](https://cloud.githubusercontent.com/assets/695945/20607245/a9c59ae4-b244-11e6-9570-c9178f6595c8.png)

**2. run: ionic run android -lc (this will not work fine for console.log)**
![2d](https://cloud.githubusercontent.com/assets/695945/20607246/a9d88820-b244-11e6-942f-56c553b36b38.png)

**Comment by sebaxtian** [comment]
# **[SOLVED]**

Change in the package.json file:
Replace: "ionic:serve": "ionic-app-scripts serve"
With: "ionic:watch": "ionic-app-scripts watch"

`
"scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:watch": "ionic-app-scripts watch"
}
`

**Change in the package.json file**
![1d](https://cloud.githubusercontent.com/assets/695945/20612342/e3193c0a-b286-11e6-91e9-b2c1e3dd15c7.png)

**Comment by mburger81** [comment]
Hi, but with RC.3 the new default configuration is ionic:serve instead of ionic:watch. So with default configuration we are not able to watch console.log on device emulating. So it would be nice to know how we should debug on ionic running on device or emulator?

In the past the docs also removed nearly all info's about running on a device, so I think, for now there are some problems to understand how to run and debug on different devices.

So why did you close the bug your self?

**Comment by sebaxtian** [comment]
Thanks,

Hi, since the update to RC3 I have problems debugging the execution on the Android device.
What other alternative to console.log exists to debug the run from the Android device?

**Comment by mburger81** [comment]
I opened also a request on ionic forum which is also referencing to this bug

https://forum.ionicframework.com/t/debug-on-emulator-and-device/71793

**Comment by mburger81** [comment]
@sebaxtian using ionic cli 2.1.8 the debug console works, so this should be a workaround. I don't know if this is a bug or this is wanted.

See the ionic forum link posted before for more information.

**Comment by Mokto** [comment]
See https://github.com/driftyco/ionic-cli/issues/1695. Still not working but...

**Comment by danbucholtz** [comment]
This should be working now. Please let me know if it's not.

Thanks,
Dan
