### ISSUE TITLE
Update tslint to v4

### ISSUE THREAD

**Issue by rolandjitsu** [driftyco/ionic-app-scripts#479]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Right now linting is stuck at version 3. It would be nice if it could be updated to v4 and/or allow the user to define which version to use.

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
`0.0.46`

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
Done.

**Comment by rolandjitsu** [comment]
Looking forward to the next release, I suppose it will also have this update.
