### ISSUE TITLE
Provide custom rollup.prod.config.js?

### ISSUE THREAD

**Issue by fifafu** [driftyco/ionic-app-scripts#48]
Hi,

I can easily override rollup.config.js, however is it also possible to override the rollup.prod.config.js?

I haven't found a way to do this yet and I think it's needed to allow custom builds that work in prod and devmode.

**Comment by trkoch** [comment]
I'm also looking for a way to do this. Maybe related, I noticed that providing a custom `rollup.config.js` breaks `npm run build` and therefore `ionic build`.

**Comment by fifafu** [comment]
providing a custom rollup.config.js works fine for me, how does yours look like?

**Comment by trkoch** [comment]
What I meant is that if you provide a `rollup.config.js` this works for development, but breaks production.

**Comment by fifafu** [comment]
Ah yes, because it can't find the correct file in the .tmp folder. That is why I'm looking for a way to provide the config.prod.config.js file (all it does is changing the entry file name)

**Comment by trkoch** [comment]
One workaround is to append the `--rollup` parameter to `ionic-app-scripts build`. In your `package.json` replace `"build": "ionic-app-scripts build` with `"build": "ionic-app-scripts build -r ./config/rollup.prod.config.js"` (obviously adjusting paths to your preferences)

**Comment by fifafu** [comment]
or alternatively make the rollup.config.js export a function that takes the build mode as parameter. Then we'd only need one file to handle dev and prod.

**Comment by jgw96** [comment]
Hello all! I am taking a look at this as we speak. Thanks for all the feedback!

**Comment by adamdbradley** [comment]
Thinking we can use the `--environment` flag here: https://github.com/rollup/rollup/wiki/Command-Line-Interface#examples 

Then only have one config which could have if statements in it. Thoughts?
