### ISSUE TITLE
ionic serve reports error in webpage - need flag to turn off that feature

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#480]
_From @mrweiland on November 25, 2016 14:39_

**Ionic version:**  
* Ionic 2 RC3

**I'm submitting a ...** 
[x ] feature request

**Current behavior:**
I run ionic serve then if i get an error it displays over webpage so i need to close it everytime i debug.

**Expected behavior:**
This is expected behavior but its really bad for me when i cannot get rid of exceptions that been thrown - from my case Ionic native googlemaps plugin that is throwing a runtime error and i cannot do anything to catch those Runtime errors when i run in browser....

From my point of view thats ok to have this error message because i dont wanna load emulator each time when i wanna test some other code that is not dependent on googlemaps.

```
Runtime Error
Uncaught (in promise): cordova_not_available
```

**What i would like to have**
I wanna have an option that i can turn on or off gui errors with a flag on ionic serve command.

Example:
ionic serve --noguierrors

Or better.. 
ionic serve --guierror (this turn on this feature with errors in web gui)

This is really annoying behavior that really need to be fixed... i guess this feature works well  for 90% of the cases.... but for us this is really killing our development..

<img width="416" alt="skarmavbild 2016-11-25 kl 15 30 16" src="https://cloud.githubusercontent.com/assets/12168854/20628252/2d1c5eec-b325-11e6-9d20-0c0b4c15e166.png">

_Copied from original issue: driftyco/ionic#9351_

**Comment by beylkhanovdamir** [comment]
![image](https://cloud.githubusercontent.com/assets/7656847/20920989/4056387a-bbb3-11e6-8b57-178344a0c5db.png)

same error with AppVersion module

**Comment by mrweiland** [comment]
Is this still considered? I really think still we need an option to turn off this feature - just to show in console.log error not in webpage.

**Comment by pbreuss** [comment]
To turn error reporting off, I comment out following line in src/app/app.module.ts near the bottom:

    ,{provide: ErrorHandler, useClass: IonicErrorHandler}

-->

/*    ,{provide: ErrorHandler, useClass: IonicErrorHandler} */

Hope this helps.
Philipp

**Comment by danbucholtz** [comment]
Yes, please just turn off the IonicErrorHandler in the NgModule.

Thanks,
Dan

**Comment by mrweiland** [comment]
Ok - then i guess it works like always send error to console? I will try. :)

**Comment by mharishkar** [comment]
![screen shot 2018-04-10 at 11 59 36 am](https://user-images.githubusercontent.com/26592507/38539652-a90cba30-3cb6-11e8-904d-d3ee27d0b72a.png)
while i am running my app, i got this error. anyone can me to solve this

**Comment by pbreuss** [comment]
Are you trying to run the Wikitude Plugin in a browser? That won't work.
You need a mobile device, Android, iOS.

Best,
Philipp

2018-04-10 8:30 GMT+02:00 Harishkar M <notifications@github.com>:

**Comment by mharishkar** [comment]
Actually, I am running the application using ionic serve and debugging the application in the browser.
I am facing this issue (refer my previous comment, which includes the screenshot).

I am a newbie to Ionic, I don't know whether I am debugging is correct or not?

If I am wrong please correct me with the right way.

**Comment by isyel** [comment]
i'm having same error as @mharishkar  can someone help please
