### ISSUE TITLE
Updating the service worker does not reload the app in the browser

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#494]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When making a change to our service worker while running `ionic serve` the changes do get copied over to `www/service-worker.js` as they should, but the app does not reload in the browser. 

#### What behavior are you expecting?
The app to also reload in the browser.

**Steps to reproduce:**
1. run `ionic serve` in your app
2. Make a change to `src/service-worker.js`
3. Notice the issue

**Comment by bitjson** [comment]
It would be extremely helpful if the solution to this issue also allowed for an npm script to run with the watch task for the worker. I'm writing a worker script in typescript, but it's currently somewhat hard to fit it into my development workflow.

Currently, I have a separate directory structure with all the worker-related files (`service`) and a single entry-point called `worker.ts`. It would be great if the watch task could be extensible in some way to allow another folder structure to be watched and a script executed on change.

(Currently I'm running `ionic serve` and another separate watch task with the `concurrently` npm package. A decent solution, though it feels somewhat unnecessary/hacked together.)

**Comment by danbucholtz** [comment]
@jgw96,

Is this still an issue?

Thanks,
Dan

**Comment by jgw96** [comment]
This is no longer an issue, seems to be working great in the latest version of app-scripts (:

**Comment by sadakpramodh** [comment]
Its because service-worker.js in src not importing sw-toolbox,

**solution**

1. npm install --save sw-toolbox
2. copy node_modules\sw-toolbox\sw-toolbox.js to src\build\sw-toolbox.js
3. edit **service-worker.js** find importScripts(’./build/sw-toolbox.js’); to importScripts(‘build/sw-toolbox.js’);
4. ionic serve

That’s it.
