### ISSUE TITLE
Typescript diagnostic parse errors

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic-app-scripts#496]
1) Duplicate definitions causes: 
![image](https://cloud.githubusercontent.com/assets/804331/20766804/77adb81c-b6fd-11e6-8ea3-f622d68ef851.png)

2) Incorrect lib causes: 
![image](https://cloud.githubusercontent.com/assets/804331/20766823/8b0aaa82-b6fd-11e6-8ed2-0856d07d9ec5.png)

Repro for 1) is to add "webworker" to tsconfig's lib option (Worker definition is already in lib.d.ts), for 2) you can add any incorrect lib, I did "worker".

**Comment by danbucholtz** [comment]
I believe both of these should be resolved. Please let me know if they're not.

Thanks,
Dan
