### ISSUE TITLE
resolve config file path relative to root

### ISSUE THREAD

**Issue by shlomiassaf** [driftyco/ionic-app-scripts#5]
Current [behaviour](https://github.com/driftyco/ionic-app-scripts/blob/master/src/util.ts#L61) resolves the path relative to the `dist` folder within `@ionic/app-script` node module.

The relative root should be the project's root, where `package.json` is.

In the current behaviour one must find it's way out by using `../../../../` to get to the root of the project since the actual root is now `node_modules/@ionic/app-scripts/dist`

Since `package.json` is static it's not possible to provide an absolute path without running into issues.

**Comment by brandyscarney** [comment]
Thanks! Fixed in the `0.0.8` release.
