### ISSUE TITLE
RC0 - doesn't build with node LTS versions v4.x but do on v5.x and v6.x

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#50]
_From @vukasin-nikodijevic on September 30, 2016 12:58_

**Short story long:**
works on 5.10.1 & 6.7.0 but not on any LTS e.g 4.6.0.

**All details are in forum thread:**
https://forum.ionicframework.com/t/rc0-production-build-for-starter-projects-fails-serve-works-as-expected/65149/2

_Copied from original issue: driftyco/ionic#8355_

**Comment by mlynch** [comment]
@jgw96 we should say that they should install node 6 for ionic 2 then? We can update our getting started doc

**Comment by vukasin-nikodijevic** [comment]
@mlynch - this is not solution.
Many users / companies (specially enterprises) have policy to use LTS versions over latest.

I believe that you don't have strategy to reduce Ionic2 user base because of node version :)

**Comment by vukasin-nikodijevic** [comment]
Another solution is to update NPM to v3.x

```
$ npm i npm -g 
```

```
$ node --version
v4.4.7
$ npm --version
3.10.8
```

**Comment by jgw96** [comment]
Hello all, thanks for opening an issue with us! We are currently looking into making app-scripts work with npm 2, but for the time being we do require npm 3. If you are not running Node 6 you can update npm by running `npm i npm -g` as @vukasin-nikodijevic points out in the above comment (thanks!). Also, Node 6 is on track to become the LTS release in two weeks as stated by Node [here](https://github.com/nodejs/LTS) which means that NPM 3 will be the default NPM release to use.
