### ISSUE TITLE
Should work with locationStrategy: 'path'

### ISSUE THREAD

**Issue by Mokto** [driftyco/ionic-app-scripts#500]
#### Short description of the problem:
When using locationStrategy to 'path', `http://localhost:8100/any_path` is not found by the script.

#### What behavior are you expecting?
Should work

**Steps to reproduce:**
1. ionic start myApp -t tabs --v2
2. set this in app.module.ts

```javascript
IonicModule.forRoot(MyApp, {
			locationStrategy: 'path'
		}, {
			links: [
				{ component: HomePage, name: 'Home', segment: 'home' },
				{ component: ContactPage, name: 'Contact', segment: 'contact' },
				{ component: AboutPage, name: 'About', segment: 'about' },
			],
		}),
```
3. Go to any route
4. Reload the page

**Which @ionic/app-scripts version are you using?**
0.0.46

** As a workaround, i'm writing locationStrategy: isDevMode() ? 'hash' : 'path'

Thank you !

**Comment by danbucholtz** [comment]
@jgw96,

Can you move this to framework?

Thanks,
Dan

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic#10290
