### ISSUE TITLE
Total error count

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic-app-scripts#503]
#### Short description of the problem:

Sometimes can have many many typescript errors (e.g. when converting something over from JS to TS). By many, I mean more than you would want to scroll or count. 

If you make a few changes, and again have many many errors, its not clear if the most recent change has improved the situation

#### What behavior are you expecting?

Would be great on the error console to have it as Error (74) - i.e. the total error count showing at the top.

Then if it subsequently reads Error (64) you know you have knocked 10 off

**Which @ionic/app-scripts version are you using?**
Ionic App Scripts: 0.0.45

**Comment by danbucholtz** [comment]
Sorry, this is outside of the scope of what we intend to do. We're open to a well-tested PR on it, though.

Thanks,
Dan

**Comment by alexbainbridge** [comment]
Hi Dan
Fair enough :) 
It only came up within the context of moving a largish v2 JS codebase to v2 TypeScript...... and having a lot of errors at the same time (hundreds).... I can see that within the context of regular v2 coding, this solution isn't really necessary
Alex
