### ISSUE TITLE
Can't find variable Firebase with app-scripts0.0.46

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#505]
_From @urm47 on December 2, 2016 10:33_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Using angularfire2 and firebase.
Call to firebase.auth().sendPasswordResetEmail reports error "Can't find variable Firebase"
Build with 0.0.45 was OK

**Expected behavior:**

No error

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

_Copied from original issue: driftyco/ionic#9460_

**Comment by comfortme** [comment]
same issue.
it was fine with 0.0.45
rolling back...

**Comment by vazad28** [comment]
I dont know how you are accessing it. I had this issue too and finally this worked.

import * as firebase from 'firebase';

**Comment by urm47** [comment]
Downgrading to 0.0.45 worked for me. 
import * as firebase from 'firebase' gives me lots of duplicate identifier errors, e.g

Duplicate identifier 'Promise'. 
Error at /.../node_modules/angularfire2/node_modules/firebase/firebase.d.ts:17:9 
Duplicate identifier 'Promise_Instance'. 
Error at /.../node_modules/angularfire2/node_modules/firebase/firebase.d.ts:130:9 

Guess this is because I am using angularfire2.
But I still need to access firebase directly, because angularfire2 does not expose all the firebase functionality.

**Comment by vazad28** [comment]
Perhaps this is like you said, AF2. I did use AF2 but then decided to use bare FB. But, your need may be different but I will suggest considering if it's possible to do without AF2. Hope next version of app-script resolves it.

**Comment by mlynch** [comment]
A case of duplicate or incompatible Promise polyfills?

**Comment by jayeshanandani** [comment]
Can you please try again with 0.0.48?

**Comment by ltaylor0430** [comment]
I'm using 0.0.48 and ran into this issue. @vazad28  solution solved my problem but i also had to add 'firebase' to the types array in tsconfig.json.  the` import * as firebase from 'firebase';` statement seem to be only necessary in my provider class.

**Comment by danbucholtz** [comment]
I believe this is resolved. Please let me know if it's not.

Thanks,
Dan

**Comment by Tyler-Darby** [comment]
@danbucholtz I am still having this issue on 1.0.0.
