### ISSUE TITLE
ionic platform add ios hangs when fetching "plugin.google.maps"

### ISSUE THREAD

**Issue by juanf9224** [driftyco/ionic-app-scripts#508]
whenever i try to add ios platform it hangs on:

> Fetching plugin "https://bitbucket.org/nightstomp/cordova-plugin-googlemaps-sdk.git" via git clone

then i cancel by "Ctrl + c" and if i try to add it again it says that it is already added. i haven't test the app on ios, on android it works fine, but id rather that the ios platform finish its process without issues.

any help would be appreciated.

**Comment by mlynch** [comment]
Hi, looks like a network issue or something with Cordova. I'm closing because this isn't something we can fix through this repo. However, for this, try removing the platform directory `platform/ios` and add the platform back.
