### ISSUE TITLE
Support Typescript 2.1

### ISSUE THREAD

**Issue by wmaurer** [driftyco/ionic-app-scripts#520]
#### Short description of the problem:
`ionic-app-scripts` requires typescript ~2.0.10, which overrides the app's installed version of typescript 2.1.4.

#### What behavior are you expecting?
Typescript 2.1.4 to be used by `ionic-app-scripts`

**Steps to reproduce:**
1. Spin up a new app using `ionic start`
2. `npm i typescript --save-dev`
3. `npm i @ionic/app-scripts@0.0.46 --save-dev`
4. Add `"alwaysStrict": true` to `tsconfig.json` (this is a new option with typescript 2.1)
5. `ionic serve`
6. See error message: "Unknown compiler option 'alwaysStrict'."

**Which @ionic/app-scripts version are you using?**
0.0.46

*Note* a second version of typescript (`2.0.10`) is being installed under `node_modules/@ionic/app-scripts/node_modules/typescript`

*Note* reverting back to version `0.0.45` solves this issue.

**Comment by rapropos** [comment]
[This commit](https://github.com/driftyco/ionic-app-scripts/commit/ef7203bfe41534276abf221e5218d0e5a94d2299) suggests that this is a known issue.

**Comment by danbucholtz** [comment]
Coming soon. Technically app-scripts already does. It is a question of whether Ionic will work it. Not entirely sure yet.

**Comment by mirkonasato** [comment]
Same as #197?

**Comment by wmaurer** [comment]
I raised this issue to highlight that `app-scripts@0.0.46` is specifying `typescript ~2.0.10`, which means that installing `typescript 2.1` results in two versions of typescript being installed which causes a problem when doing an `ionic serve`.

The other issue is about `app-scripts`, specifically the ng compiler, does not work with `typescript 2.1`.
So they're related, but exactly the same.

In my experience, downgrading to `app-scripts@0.45` and upgrading to `typescript 2.1` *does* work for local development, i.e. the application runs correctly in the browser via `ionic serve`. However the ng compilation doesn't seem to work, i.e. the compiled app doesn't work on an Android device.

**Comment by danbucholtz** [comment]
@wmaurer,

Typescript is now a peer dependency of app-scripts so in theory in will just work when you flip the switch.

TypeScript 2.1 does not work with Angular, yet, though. It's a known issue.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Tracking here:
https://github.com/driftyco/ionic-app-scripts/issues/197

Thanks,
Dan
