### ISSUE TITLE
Setting IONIC_ENV via command line doesn't work for dev builds

### ISSUE THREAD

**Issue by dually8** [driftyco/ionic-app-scripts#521]
#### Short description of the problem:
Setting the `IONIC_ENV` variable for dev builds doesn't work. It continues with production build regardless.

#### What behavior are you expecting?
`IONIC_ENV=dev` will trigger dev build.

**Steps to reproduce:**
1. In shell `IONIC_ENV=dev ionic build ios`
2. Notice `build prod started` in terminal.

**Which @ionic/app-scripts version are you using?**
ionic-app-scripts 0.0.38

**Comment by dually8** [comment]
Also, if I manually set the `package.json` file to use dev like this
```
"scripts": {
    "build": "ionic-app-scripts build --dev",
```
the build just freezes at 
```
[10:42:14]  sass finished in 1.52 s 
[10:42:14]  build dev finished in 16.56 s 
```

Any suggestions?

**Comment by dually8** [comment]
Upgraded from RC 1 to RC 3 with the app-scripts version at .45 (instead of .38) and still have the same issue.

**Comment by rolandjitsu** [comment]
@dually8 take a look at this entry [CHANGELOG.md#0047-2016-12-12](https://github.com/driftyco/ionic-app-scripts/blob/master/CHANGELOG.md#0047-2016-12-12). All builds are dev by default, you make a prod build by appending `--prod` flag.

**Comment by dually8** [comment]
`--prod` is literally nowhere in my project directory. I can grep and find nothing. Upgrading to RC3 and manually setting `--dev` in the build script in the package.json works okay. It's just awkward to have inaccurate documentation. Feel free to close this if you like.

**Comment by rolandjitsu** [comment]
@dually8 if you update to the latest app scripts (`0.0.47`) and you run a `npm run ionic:build` (I assume you followed the instructions and setup these scripts in your `package.json`), it will build for dev, if you run `npm run ionic:build --prod` it will build for production. As simple as that. I haven't tried the `ionic build ios` command though, but I am pretty sure it should behave the same way.

**Comment by dually8** [comment]
I mean, I opened this bug 5 days ago and your changelog is for literally a day ago, so I haven't updated yet, but I will try this when I can and get back to you, @rolandjitsu. Thanks.

**Comment by danbucholtz** [comment]
This is not a value to be set, this is a value to be read.

Thanks,
Dan
