### ISSUE TITLE
Built-in HMR support

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic-app-scripts#525]
#### Short description of the problem:
I'd like it if `ionic serve` could use [Angular Hot Module Replacement](https://github.com/angularclass/angular2-hmr). I followed a course on React, and now I want this feature so badly.

**Which @ionic/app-scripts version are you using?**
0.0.45

**Comment by danbucholtz** [comment]
Sorry, we probably won't be able to add this for a decent amount of time. Closing for now.

Thanks,
Dan

**Comment by nicolas-albert** [comment]
Their is a work around to run a ionic application with HMR activated ?
(with some packages.json customization ?)
