### ISSUE TITLE
copy task issue

### ISSUE THREAD

**Issue by agustinhaller** [driftyco/ionic-app-scripts#527]
#### Short description of the problem:
I added a new entry to the copy dictionary to get some node_modules file copied to the build folder. Unfortunately the file doesn't get copied.

#### What behavior are you expecting?
node_modules/file copied to www/build folder

**Steps to reproduce:**
1. Add a custom `copy.config.js` in your ionic 2 app
```
"config": {
    "ionic_copy": "./config/copy.config.js"
  }
```
2. Add a new entry to the copy dictionary in `./config/copy.config.js`
```
copySW_Toolbox: {
    src: ['{{ROOT}}/node_modules/sw-toolbox/sw-toolbox.js'],
    dest: '{{BUILD}}'
  }
```
3. Run `ionic serve`

**Which @ionic/app-scripts version are you using?**
0.0.45

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Maybe this issue is related to https://github.com/driftyco/ionic-app-scripts/issues/448#issuecomment-264735182.

And other people are experiencing the same problem (https://github.com/driftyco/ionic/issues/9035) also.

**Comment by danbucholtz** [comment]
This should be resolved in `0.0.47`.

Thanks,
Dan
