### ISSUE TITLE
Cannot find module './app.module.ngfactory'

### ISSUE THREAD

**Issue by jsanchezgarcia** [driftyco/ionic-app-scripts#529]
I've seen some people having this issue before, but none of their solutions seemed to help in this case. I can run my app with ionic serve and in ionic view, but when try to build or emulate, I get the following error.

```
$ ionic build ios
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

Running 'build:before' npm script before build

> baroapp@ build /Users/juansanchezgarcia/Projects/baro/baroapp-ionic
> ionic-app-scripts build

[16:41:41]  ionic-app-scripts 0.0.46
[16:41:41]  build prod started ...
[16:41:41]  clean started ...
[16:41:41]  clean finished in 4 ms
[16:41:41]  copy started ...
[16:41:41]  ngc started ...
[16:41:42]  copy: Error copying "/Users/juansanchezgarcia/Projects/baro/baroapp-ionic/node_modules/ionic-angular/fonts"
            to "/Users/juansanchezgarcia/Projects/baro/baroapp-ionic/www/assets/fonts"
[16:41:42]  copy finished in 483 ms
[16:42:05]  Error: Error at /Users/juansanchezgarcia/Projects/baro/baroapp-ionic/.tmp/app/main.prod.ts:4:36
[16:42:05]  Cannot find module './app.module.ngfactory'.
[16:42:05]  ngc failed
[16:42:05]  ionic-app-script task: "build"
[16:42:05]  Error: Error

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! baroapp@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
```

This is my package.json
```
{
  "name": "baroapp",
  "author": "Baro Team",
  "homepage": "https://baroapp.com",
  "private": true,
  "scripts": {
    "build-dev": "ionic-app-scripts build --dev",
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "angular2-moment": "^1.0.0",
    "angular2-uuid": "^1.1.0",
    "angularfire2": "^2.0.0-beta.6",
    "bourbon": "^4.2.7",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.46",
    "typescript": "^2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    },
    {
      "platform": "android",
      "version": "",
      "locator": "android"
    }
  ],
  "description": "baroapp",
  "config": {
    "ionic_sass": "./config/sass.config.js"
  }
}

```

thanks!

**Comment by yauros** [comment]
Hello, i am in your exact situation and waiting for a solution, i saw many posts of people talking about it but didnt see the fix.

I saw also you have also an error when copying fonts, this one can be solved as commented FireCoding here: https://github.com/driftyco/ionic-app-scripts/issues/448.

**Comment by realappie** [comment]
This is related to the last commit 0594803, my team is having the same issue after doing a `npm install` and downloading the latest version.

**Comment by jayeshanandani** [comment]
Can you please try with the latest version, there have been many changes and I don't see that issue happening anymore.

**Comment by jsanchezgarcia** [comment]
0.0.47 fixed it! thanks guys

**Comment by cmaart** [comment]
0.0.47 is buggy as hell, can't update to this version (watch does not work, IONIC_ENV variable not set,..)

**Comment by yauros** [comment]
Don't know if it is related to app scripts or no but i am getting this error on "npm run ngc":

`[14:48:35]  ionic-app-scripts 0.0.47
[14:48:35]  ngc started ...
[14:48:35]  ionic-app-script task: "ngc"
[14:48:35]  TypeError: Cannot read property 'fileCache' of undefined

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ngc"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! App-Generator@ ngc: `ionic-app-scripts ngc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the App-Generator@ ngc script 'ionic-app-scripts ngc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the App-Generator package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts ngc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs App-Generator
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls App-Generator
npm ERR! There is likely additional logging output above.`

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47

in other pc with ionic cli 2.1.14 and appscripts in 0.46 works ok
