### ISSUE TITLE
Updating AngularFire/Firebase project to new RC - @types issue

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#53]
_From @sicontis on September 30, 2016 8:33_

Since the new RC uses **@types** now to install typings, I added the types from Firebase and Angularfire to my project using

`npm install @types/firebase --save-dev --save-exact`

It saves the types to a folder inside `node_modules/@types/firebase` and updates the **package.json** file.

Upon running the project with ionic serve, I get a whole bunch of `error TS2503: Cannot find namespace 'firebase'.` errors, which was fixable in the previous release with a `"files": [ "firebase" ]` addition to the **tsconfig.json** file and then running the `typings install` command. 

Just wondering is there a fix for something similar or an extra step after the npm install?  
Do the types for AngularFire/Firebase need to be updated to match the new RC? 

Any ideas?

_Copied from original issue: driftyco/ionic#8343_

**Comment by jgw96** [comment]
_From @tja4472 on September 30, 2016 9:39_

Hi
See https://github.com/tja4472/ionic-angularfire

hth

**Comment by jtushar53** [comment]
this one works for me
https://github.com/angular/angularfire2/issues/565

and also this
https://playcode.org/getting-started-with-ionic-2-rc0-firebase-3-angularfire-2/

**Comment by jgw96** [comment]
Hello all! Since the namespace error is actually an AngularFire issue I am going to be closing this issue for now. Thanks!
