### ISSUE TITLE
Command line params on windows don't work

### ISSUE THREAD

**Issue by jamesgroat** [driftyco/ionic-app-scripts#531]
#### Short description of the problem:

Command line params on windows don't work: ionic serve -debug does not trigger debug mode.

#### What behavior are you expecting?

ionic serve -debug should print debug messages.

```
the config.ts hasArg() function ends up comparing the value '[object object]' to '--lab' etc.
```

**Which @ionic/app-scripts version are you using?**

0.0.47 (also existed in .45, etc)

**Comment by jamesgroat** [comment]
Additonal information:

Running npm run ionic:serve --debug works as expected.

npm 3.10.3
node 6.7.0

**Comment by danbucholtz** [comment]
Did you update your Ionic CLI?

Thanks,
Dan

**Comment by jamesgroat** [comment]
Sorry -- that does fix it.
