### ISSUE TITLE
build dev failed: Each glob entry must be a string

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#540]
I upgraded to 0.0.47 from 0.0.45 and can't compile anymore! Doing ionic serve I get:

    [22:05:11]  webpack started ... 
    (node:12589) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Each glob entry must be a string
    (node:12589) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    (node:12589) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Each glob entry must be a string
    [22:05:26]  webpack finished in 14.62 s 
    [22:05:26]  sass started ... 
    [22:05:26]  build dev failed: Each glob entry must be a string 
    [22:05:26]  dev server running: http://localhost:8100/ 
    (node:12589) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
    [22:05:28]  sass finished in 2.71 s 

Help plz!!!

Tried with node 6.9.1 and 7.2.1 same result

Your system information:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3-201612122136
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by danbucholtz** [comment]
@peterpeterparker ,

Did you override the `copy.config`? Can you provide more info?

Thanks,
Dan

**Comment by peterpeterparker** [comment]
@danbucholtz sure thx for your answer

tsconfig.json:

{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": [
            "dom",
            "es2015"
        ],
        "module": "es2015",
        "moduleResolution": "node",
        "sourceMap": true,
        "target": "es5",
        "removeComments": true
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ],
    "compileOnSave": false,
    "atom": {
        "rewriteTsconfig": false
    }
}


package.json:

{
  "name": "",
  "author": "",
  "homepage": "",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "config": {
    "ionic_sass": "./scripts/sass.config.js",
    "ionic_copy": "./scripts/copy.config.js",
    "ionic_source_map_type": "source-map"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.6",
    "angular2-swing": "^0.10.0",
    "bourbon": "^4.2.7",
    "chart.js": "^2.3.0",
    "cropperjs": "^0.8.1",
    "font-awesome": "^4.7.0",
    "ionic-angular": "^2.0.0-rc.3-201612122136",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "moment": "^2.15.2",
    "ng2-translate": "^3.2.1",
    "rxjs": "5.0.0-beta.12",
    "sass-mediaqueries": "^1.6.1",
    "socket.io-client": "^1.4.8",
    "underscore": "^1.8.3",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.47",
    "@types/cropperjs": "0.0.21",
    "@types/googlemaps": "3.20.34",
    "@types/moment": "2.13.0",
    "@types/socket.io-client": "1.4.27",
    "@types/underscore": "1.7.33",
    "gulp": "^3.9.1",
    "gulp-remove-code": "^1.0.2",
    "ncp": "^2.0.0",
    "plist": "^2.0.1",
    "replace": "^0.3.0",
    "typescript": "2.0.6"
  },
  "cordovaPlugins": [
    
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": ""
}

**Comment by peterpeterparker** [comment]
@danbucholtz my copy.config you are right is overriden, look like following:

    module.exports = {
    include: [
        {
            src: '{{SRC}}/assets/',
            dest: '{{WWW}}/assets/'
        },
        {
            src: '{{SRC}}/index.html',
            dest: '{{WWW}}/index.html'
        },
        {
            src: '{{SRC}}/manifest.json',
            dest: '{{WWW}}/manifest.json'
        },
        {
            src: '{{SRC}}/service-worker.js',
            dest: '{{WWW}}/service-worker.js'
        },
        {
            src: 'node_modules/ionic-angular/polyfills/polyfills.js',
            dest: '{{BUILD}}/polyfills.js'
        },
        {
            src: 'node_modules/ionicons/dist/fonts/',
            dest: '{{WWW}}/assets/fonts/'
        },
        {
            src: 'node_modules/font-awesome/fonts/',
            dest: '{{WWW}}/assets/fonts/font-awesome'
        }
    ]
};

**Comment by peterpeterparker** [comment]
it's all good now, thx @danbucholtz for the quick answer

had to update my copy.config.js 

like following

   module.exports = {
    copyAssets: {
        src: ['{{SRC}}/assets/**/*'],
        dest: '{{WWW}}/assets'
    },
    copyIndexContent: {
        src: ['{{SRC}}/index.html', '{{SRC}}/manifest.json', '{{SRC}}/service-worker.js'],
        dest: '{{WWW}}'
    },
    copyFonts: {
        src: ['{{ROOT}}/node_modules/ionicons/dist/fonts/**/*', '{{ROOT}}/node_modules/ionic-angular/fonts/**/*', '{{ROOT}}/node_modules/font-awesome/fonts/'],
        dest: '{{WWW}}/assets/fonts'
    },
    copyPolyfills: {
        src: ['{{ROOT}}/node_modules/ionic-angular/polyfills/polyfills.js'],
        dest: '{{BUILD}}'
    },
    copyWorkers: {
        src: ['{{ROOT}}/node_modules/ionic-angular/workers/*.js'],
        dest: '{{BUILD}}'
    }
};


sorry for stupid post and thx for the help, so much appreciated!

**Comment by danbucholtz** [comment]
@peterpeterparker,

Glad you got it figured out.

Thanks,
Dan
