### ISSUE TITLE
Ionic 2 RC3 new project does not work

### ISSUE THREAD

**Issue by crystal98** [driftyco/ionic-app-scripts#548]
#### Short description of the problem:
I created a new ionic 2 project using 'ionic start myProj blank --v2'  and I have latest ionic 2, node and npm as below:
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: OS X El Capitan
Node Version: v6.9.2
Xcode version: Xcode 8.2 Build version 8C38

npm version: 4.0.3

#### What behavior are you expecting?
When running 'ionic serve', I got the following errors:

ionic serve

> ionic-hello-world@ ionic:serve /Users/myProj
> ionic-app-scripts serve

[11:31:47]  ionic-app-scripts 0.0.45 
[11:31:48]  watch started ... 
[11:31:48]  build dev started ... 
[11:31:48]  clean started ... 
[11:31:48]  clean finished in 1 ms 
[11:31:48]  copy started ... 
[11:31:48]  transpile started ... 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:53703
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:serve" "--"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/myProj/npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve

**Steps to reproduce:**
1. download lated node v6.9.2
2. update npm to latest v4.0.3
3. npm install -g ionic
4. ionic start myProj blank --v2
5. ionic serve

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
ionic-app-scripts 0.0.45

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
This issue occurs because you have 2 instances of `ionic serve` running.  The following commit should resolve this issue in the future. d6de4132247af41a52e291f15f91cc4930404092
