### ISSUE TITLE
ngc task forces es5 output, can't use third-party transpiler

### ISSUE THREAD

**Issue by bytenik** [driftyco/ionic-app-scripts#55]
Prior to rc0, I was using TypeScript to generate ES2015, and then running the result through babel. I did this because we make extensive use of async functions, which are not supported in TypeScript's compilation of ES5 at this time.

rc0 now forces in the ionic-app-scripts ngc script that the target be set as es5, which breaks this workflow and prevents the introduction of a third-party transpiler.

We rely on the use of async functions heavily in our code.

**Comment by bytenik** [comment]
I originally posted this at https://github.com/driftyco/ionic/issues/8377 before realizing this is the right place, btw.

**Comment by Kobzol** [comment]
A temporary workaround might be to comment out this line in `node_modules/@ionic/app-scripts/dist/ngc.js`:
`tsConfig.compilerOptions.target = 'es5';`
(and also to disable uglify, because it didn't work for me with this).
I hope that ES6 codegen will be supported (even if it didn't work out-of-the-box), because it will take some time before TS 2.1 gets released and async/await is sucha nice feature.
I already asked about ES6 here: #30.

**Comment by bytenik** [comment]
Yea, I forked @ionic/app-scripts on GitHub to comment that line, and I now have my npm pulling that package from there. Its such a hack though.

**Comment by bytenik** [comment]
Would you take a pull request that simply allows target to be overridden in the config?

**Comment by danbucholtz** [comment]
@bytenik,

Truthfully, I doubt we'll merge it if you do it at this time. We know we need to do this, just need time to do it.  We are working on solidifying app-scripts right now. In the next couple weeks, improving minifaction will be a large part of things for us.

The best way to do that, we think, is to start with source of ES2015, run Closure Compiler against it for property renaming), then transpile it to es5.  We would expose configs for all of this stuff.

My goal is to make each step entirely configurable and optional.

Thanks,
Dan

**Comment by danbucholtz** [comment]
@urielhdz asked for a similar request.

Just updating.

**Comment by metzc** [comment]
with the current version of app-scripts (0.0.36) it seems to be possible to set the target to "es2015" in tsconfig.json. It still breaks with uglifyjs, which i have to disable in app-scripts/dist/minify.js. Doing this, i can use async/await and ionic builds it just fine.

I wonder why though. Which part of the build process now miraculously takes over the transpilation to ES5?

Also, does anyone know of a more solid way to disable uglify for now?

On another note: With typescript@next we can also use async/await while having the target set to es5. Unfortunately typescript@next break ionic build. But i have posted that just now as a seperate issue: https://github.com/driftyco/ionic-app-scripts/issues/197

**Comment by danbucholtz** [comment]
@metzc,

There is more work to be done here. I don't recommend changing all of these settings around yet.

In order to get the smallest and fastest booting bundle possible, we _think_ we need to minify es2015 code, then transpile it at the end. Not 100% positive but initial tests from Angular team are positive from what we're hearing.

Thanks,
Dan

**Comment by Kobzol** [comment]
@metzc: I too thought that the build process *somewhere* transpiles to ES5, but it turned out to be the opposite case - my browser (Chrome) supports almost all of ES6. When I tried it on a mobile device, it didn¨t work.

**Comment by metzc** [comment]
@Kobzol i also suspected this, so I tried also in safari desktop as well as iOS, both seem to run just fine. I use es6 heavily, also async/await. I assume those browsers support neither? Or do they now?

**Comment by Kobzol** [comment]
Typescript doesn't leave them as async/await AFAIK (it's not even a part of ES6, async/await will be in ES7). TS converts them to generators, and those are supported in major browsers today. BTW Chrome now has an experimental support for async/await too.

**Comment by metzc** [comment]
ok, i see now there is indeed some ES6 stuff in the build. While we are at it: what can we say about the ES6 support when using ionic / cordova / wkwebview / crosswalk? Maybe this isn't a problem after all?

For a working (temporary) non-ES6 workaround for async/await when using ionic, see this issue: https://github.com/driftyco/ionic-app-scripts/issues/197

**Comment by danbucholtz** [comment]
We no longer force the version, so I am going to close this issue.

Thanks,
Dan
