### ISSUE TITLE
Error on prod build in 0.0.47: UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by FdezRomero** [driftyco/ionic-app-scripts#555]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When I run  `ionic build android --prod` I get the following error, and I have no idea where it comes from. Tried with `--verbose` and `--debug` but neither show a stacktrace. I suspect it's related to `ngc` because there are no errors when I run `ionic serve`.

```
[13:52:48]  ionic-app-scripts 0.0.47
[13:52:48]  build prod started ... MEM: 108.7MB
[13:52:48]  clean started ... MEM: 108.9MB
[ DEBUG! ]  clean /Users/rodrigo/Git/App/www/build  MEM: 108.9MB
[13:52:48]  clean finished in 7 ms MEM: 109.0MB
[13:52:48]  copy started ... MEM: 109.1MB
[13:52:48]  ngc started ... MEM: 109.1MB
[13:53:32]  ngc finished in 43.25 s MEM: 491.0MB
[13:53:32]  webpack started ... MEM: 491.0MB
[ DEBUG! ]  [IonicEnvironmentPlugin] apply: creating environment plugin  MEM: 500.4MB
···
[13:53:32]  copy finished in 43.69 s MEM: 503.5MB
(node:3862) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token u in JSON at position 0
```

#### What behavior are you expecting?
To not show any errors, or show a stacktrace.

**Steps to reproduce:**
1. Run `ionic build android --prod`
2. Check the error in the logs

**Which @ionic/app-scripts version are you using?**
0.0.47

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by FdezRomero** [comment]
Adding that this error seems to stop the Ionic part of the build, as neither `main.js` nor `main.css` are generated. The Cordova part continues but when you run the app you get a 404 error for these 2 files.

**Comment by danbucholtz** [comment]
Can you open `node_modules/@ionic/app-scripts/dist/index.js` and modify the `errorLog` function to include a `console.log('e.stack: ', e.stack);` before the process exits?

This will help me track it down.

Thanks,
Dan

**Comment by FdezRomero** [comment]
Hi Dan,

I added the `console.log` in line 60 like this, but the log is never printed on the console so it must be coming from somewhere else.

```
function errorLog(task, e) {
    logger_1.Logger.error("ionic-app-script task: \"" + task + "\"");
    if (e && e.toString() !== 'Error') {
        logger_1.Logger.error("" + e);
    }
    console.log('e.stack: ', e.stack);
    process.exit(1);
}
```

I'm using 0.0.47, you can see the full info at the end of my first message.

Thanks!

**Comment by danbucholtz** [comment]
@FdezRomero,

Hmm, seems to be having trouble with some JSON. That is strange. Can you try to reproduce it?

Thanks,
Dan

**Comment by FdezRomero** [comment]
@danbucholtz You mean with a fresh project? I haven't been able to find the cause, but it happened since I moved from 0.0.46 to 0.0.47.

**Comment by danbucholtz** [comment]
Are you using any third party libraries? It seems like webpack is having a hard time with it? 

Thanks,
Dan

**Comment by FdezRomero** [comment]
@danbucholtz Nothing fancy: Ionic Storage, Ionic Native, the `Intl` polyfill and `ng2-translate`. But I have them since RC0 and only Ionic Storage has been updated recently. These are my deps:

```
"dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "^1.1.7",
    "intl": "^1.2.5",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "^2.2.11",
    "ionicons": "3.0.0",
    "ng2-translate": "^4.2.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.47",
    "typescript": "2.0.9"
  },
```

Thanks for checking this out.

**Comment by danbucholtz** [comment]
@FdezRomero,

If you want to send me Gitlab stuff, I can take a quick look. Please email me at dan.b at ionic.io.

Thanks,
Dan

**Comment by FdezRomero** [comment]
Hi Dan,

Following the upgrade instructions for RC4 I copied and pasted the `tsconfig.json` for 0.0.47 and found that I was missing the line:

```
"sourceMap": true,
```

It works perfectly now. I'm sorry that I couldn't find this error earlier. I checked everything several times but somehow I missed this. I was actually just going to send you the invite for the repo.

Thanks for all the help! Closing :+1:

**Comment by engrsandeep** [comment]
We are facing this issue in latest ionic cordova and android...

I am trying to install plugins given on ionic website... Getting this issue on 3 plugins
1. imagepicker
2. insomnia
3. http


(node:25244) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token )
