### ISSUE TITLE
0.0.47 aot breaks a running app on 0.0.45

### ISSUE THREAD

**Issue by kodeine** [driftyco/ionic-app-scripts#561]
@danbucholtz 

So aot on 0.0.47 breaks the app and i'm unable to find out where the problem is because of AOT its hard to debug. The app runs fine in non-aot environment. I switched back to 0.0.45 and everything works as it should.

Is it possible to run with AOT and prod mode in `ionic serve`? So its more easy to debug without using emulator.

Thanks

![screenshot from 2016-12-15 15-27-09](https://cloud.githubusercontent.com/assets/8620059/21242664/f9e47198-c2da-11e6-9017-bc3c5e1f58c6.png)

```
Your system information:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3-201612142137
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.2
Node Version: v6.6.0
Xcode version: Not installed
```

**Comment by jayeshanandani** [comment]
@kodeine :  This is a reference from Change Log
`If you wish to run AoT but disable minification, do the following ionic run android --aot ionic emulate ios --aot`

Can you please try this by compiling aot without minification? The error would make more sense if done by this mean.

**Comment by danbucholtz** [comment]
It's not possible to run `AoT` with ionic serve. We probably won't support that until AoT is faster.

Thanks,
Dan
