### ISSUE TITLE
There is also error caused by webpack-sources

### ISSUE THREAD

**Issue by spaha** [driftyco/ionic-app-scripts#562]
![image](https://cloud.githubusercontent.com/assets/7152385/21243316/9e14193e-c318-11e6-9412-6e3413af9c0b.png)

"**webpack**": "^2.1.0-beta.27"

I got this error after i updated dependencies according to framework updates (http://blog.ionic.io/rc3-error-reporting-final-oh-my/)

**Comment by danbucholtz** [comment]
Hi @spaha,

Can you provide some more details or a repo demonstrating the issue?

Thanks,
Dan

**Comment by herbzi** [comment]
+1
I also had this problem and struggled to find any information on what could be causing it. I had to revert to  .46 .

**Comment by spaha** [comment]
Hi @danbucholtz ,

unfortunately do not have repo for this app. Don't know what exactly from details you need, but after upgrading "@ionic/app-scripts" to latest version (0.0.47) there was also update for webpack, webpack-sources, source-map ( screenshot below)
![image](https://cloud.githubusercontent.com/assets/7152385/21254087/4a97a4f6-c363-11e6-9713-c0460f7ceb2a.png)

After that, i try to run "ionic serve" but it resulted with error (screenshot from my previous comment)

Do you need more details ? If yes, be specific please.

Thx, 

Haris

**Comment by st1s** [comment]
https://github.com/driftyco/ionic/issues/9658#issuecomment-267636270

**Comment by parkbytes** [comment]
I was facing the same issue and isolated the problem to multiple components within same .ts file. in my RC3 project.

Applied the single responsibility principle from Angular and separated the components into their respective .ts files to resolve the original issue reported here.

https://angular.io/docs/ts/latest/guide/style-guide.html#!#single-responsibility

I was able to narrow down the issue by manually migrating old rc3 project (part by part) to a freshly created rc4 project.!!!

Maybe the experts can confirm.

**Comment by herbzi** [comment]
Nice work. I also have multiple components in the same file. Thanks for going through the trouble of isolating it. I think i'll just separate them now considering I had another issue in a previous version of ionic related to this. Might as well stick with the crowd because this sort of thing isn't really tested.

**Comment by coreymcmahon** [comment]
I'm slightly confused by the suggested fix here. It seems to be breaking when there are multiple components within the same `.ts` file, but that isn't strictly prohibited by Angular 2, right? So this is still a valid bug. Or am I missing something?

**Comment by herbzi** [comment]
Yes it's still a bug that needs addressing. I was just saying that I have had an issue with exactly multiple components within in a single file in the past. This was later fixed and now another issue is cropping up. I'd rather stick with the style guide rather than facing more issues in the future. 

I'm sure @danbucholtz will come and take a look it at now we have found a way to reproduce it.

**Comment by tkem** [comment]
I think I stumbled upon another workaround, which does not require modification of any source files. As documented [here](https://github.com/driftyco/ionic-app-scripts#overriding-config-values), I added the following to my `packages.json`:
```
  "config": {
    "ionic_source_map_type": "eval"
  }
```
According to the docs, this will change some `webpack` option, which defaults to `source-map`, thus probably triggering the error. Now, I have absolutely no clue what `eval` does (or `webpack` in general, for that matter), but for the moment I'm happy enough that I can run `ionic serve` with app-scripts 0.0.47!

And yes, I (seldomly) *do* put multiple components in one `.ts` file; for example, I like to place popups/context menus, which are only a few lines, in the same file as their "parent" page. You may argue about style here, but a build tool still shouldn't croak on this...

**Comment by murshid1988** [comment]
@tkem This worked for me too. But like you said, this is not a proper fix

**Comment by danbucholtz** [comment]
@tkem,

I think we'll have some problems indefinitely with multiple components, etc in one file. I don't recommend that right now. We'll fix eventually but bigger fish to fry first.

Thanks,
Dan

**Comment by tkem** [comment]
@danbucholtz: If that's *really* been identified as the cause of this issue, that would be fine with me. It's still an RC, after all. I'd just like to see this stated prominently in a list of known bugs/limitations in the release notes.

**Comment by danbucholtz** [comment]
@tkem,

I've never actually seen this issue and it's not a popular one so it probably isn't happening for many people. I need to look into it more.

Thanks,
Dan

**Comment by tkem** [comment]
@danbucholtz: Sure. If you're still looking for a public repo for this: https://github.com/tkem/openlap

The `ionic2-rc.4` branch should be up to date and contains the `ionic_source_map_type: eval` workaround, and `npm run ionic:build` works just fine.

The `ionic2-rc.4-source-map` branch sets `ionic_source_map_type` to `source-map` (the default according to the docs), and `ionic:build` aborts with the `TypeError`.

There's also a Travis CI build for the latter that shows the same behavior:
https://travis-ci.org/tkem/openlap/builds/185582821
It's quite verbose, so it should also give you enough info about the build environment.

Hope that helps somewhat,
Thomas

**Comment by danbucholtz** [comment]
Can someone explain this to me like I'm 5? Sorry, I am not up to speed on this. Is this due to multiple components in the same file? If so, I recommend not doing that for now 😸 

Thanks,
Dan

**Comment by danbucholtz** [comment]
Due to lack of response, I'm going to close this issue. I was never able to recreate or understand what was happening.

Please open another issue if needed.

Thanks,
Dan
