### ISSUE TITLE
(0.0.47) add config > watch ready (x)

### ISSUE THREAD

**Issue by vss0705** [driftyco/ionic-app-scripts#564]
( today test ) Windows 7 , Node 6.9.2 , ionic CLI 2.1.17

> ionic start TEST blank --v2
> cd TEST
> ionic serve
[] build dev finished in 13.54 s
[] watch ready in 13.65 s
[] dev server running: http://localhost:8100/

* Watck ready (OK)

 ./TEST/node_modules/@ionic/app-scripts/config/copy.config.js -(copy)-> ./TEST/config/copy.config.js

package.json add config

"config": {
 "ionic_copy": "./config/copy.config.js"
} 

> ionic serve
[] build dev finished in 13.54 s
[] dev server running: http://localhost:8100/

* Watck ready (X)

**Comment by movibe** [comment]
I'm having the same problem, when I activate the copy setting in the package.json, it copies the defined files, however the live reload stops working

**Comment by danbucholtz** [comment]
This is a known issue. Will be fixed in `0.0.48` today.

Thanks,
Dan

**Comment by movibe** [comment]
Thanks, and we are waiting for the release of the new version!

**Comment by danbucholtz** [comment]
Sorry, I did not get a chance to publish yet but you can get this fix now with `npm install @ionic/app-scripts@nightly`. What's holding the fix up are unit tests of some other stuff.

Thanks,
Dan

**Comment by danielehrhardt** [comment]
Thanks @danbucholtz !!

**Comment by danbucholtz** [comment]
Hi all,

This is resolved in `0.0.48` which was just published.

Please let me know if you have any issues.

Thanks,
Dan
