### ISSUE TITLE
incorrect file size in WOFF header

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic-app-scripts#566]
#### Short description of the problem:
With version 0.0.45 I was able to extend ionicons with no problem (just adding few icons to v3 branch)

now with version 0.0.47, im getting this error for the icons:
```
Failed to decode downloaded font: http://localhost:8100/assets/fonts/ionicons.woff2?v=3.0.0-alpha.3
?ionicplatform=android:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
?ionicplatform=android:1 Failed to decode downloaded font: http://localhost:8100/assets/fonts/ionicons.woff?v=3.0.0-alpha.3
?ionicplatform=android:1 OTS parsing error: incorrect file size in WOFF header
```
#### What behavior are you expecting?
Icons should work normally with this version

**Steps to reproduce:**
1.  user this as ionicons path in package.json `"git@github.com:travessey/ionicons.git#travessey`
2. use one of the new icons and see the result. (big square and not an icon)
3. Use `logo-deals` as icon (this is one of the new icons)

```
<ion-icon name="logo-deals"></ion-icon>
```

**Which @ionic/app-scripts version are you using?**
0.0.47

ionic info:
```

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by royipressburger** [comment]
Hi again.

When trying to narrow down on the problem I see that it looks like a problem with the latest version 0.0.47.

I tried to revert to version 0.0.45 and all worked ok.
Also when trying to work with 0.0.46 All worked ok.

It seems that 0.0.47 is causing this.

**Comment by royipressburger** [comment]
Anyone have an idea how to solve that?

**Comment by danbucholtz** [comment]
@royipressburger,

Sorry, this doesn't seem like an app-scripts issue. I'm not sure there is anything we can do to help you here.

Thanks,
Dan

**Comment by royipressburger** [comment]
@danbucholtz Hello,
Thanks for you answer.

If this is the case, How can you explain that it worked fine on 0.0.46?

**Comment by royipressburger** [comment]
@danbucholtz Hello again.

I found the issue and its behind [this](https://github.com/driftyco/ionic-app-scripts/commit/69f89a8) commit.

I remove the copy of the ionic-angular fonts and all seems to work fine.
I think its because that `ionic-angular/fonts` contains some ionicons files which causes the the conflict.

What do you think?

**Comment by royipressburger** [comment]
@danbucholtz Hi,  Sorry for poping this up again

After some more investigations, I see that both `ionic-app-scripts` and `ionic` ([here](https://github.com/driftyco/ionic/blob/master/scripts/gulp/util.ts#L91))
are copying items from `ionicons`.

Because `ionic` is copying fonts from ionicons, when install ionic you get in the fonts folder `woff` files. And because the current copy script is copying the fonts from `ionic-angular/assets` after the fonts from `ionicons` we get a result that installing `ionicons` in a project is useless since you always get the files from `ionic-angular`.
This causes error when trying to create/add custom icons for `ionicons`.

we need to choose when we want to copy the files from `ionicons` to avoid this.

**Comment by royipressburger** [comment]
@danbucholtz @jgw96 Hi guys,
Can someone open this issue.. I think it is still relevant..

**Comment by royipressburger** [comment]
@danbucholtz Ill be happy for a response. Thanks.

**Comment by danbucholtz** [comment]
Sorry, I don't know too much about this. It seems outside of the scope of what we intend to support.

Customizing our icon set and then seeing issues with the wrong size is not something we can support at scale.

Thanks,
Dan
