### ISSUE TITLE
Periodic hang app-scripts

### ISSUE THREAD

**Issue by konrin** [driftyco/ionic-app-scripts#567]
#### Short description of the problem:
app-scripts periodically freezes when you change the project files. It occurs in about 10-15 of changed files, or if you make several changes to a row in a single file (without laws).

On the client, in a moment of suspension remains inscription "Building ..."

Console output:
> [12:42:14]  webpack update finished in 6.11 s
> [12:42:14]  build finished in 6.22 s
> 
> [12:42:14]  build finished in 14.07 s
> 
> [12:42:25]  build started ...
> [12:42:25]  transpile update started ...
> [12:42:25]  transpile update finished in 50 ms
> [12:42:25]  webpack started ...
> [12:42:31]  build started ...
> [12:42:31]  transpile update started ...
> [12:42:31]  transpile update finished in 72 ms
> [12:42:31]  webpack started ...
> [12:42:37]  build started ...
> [12:42:37]  transpile update started ...
> [12:42:37]  transpile update finished in 27 ms
> [12:42:37]  webpack started ...
> [12:43:07]  build started ...
> [12:43:07]  transpile update started ...
> [12:43:07]  transpile update finished in 32 ms
> [12:43:07]  webpack started ...
> [12:43:34]  build started ...
> [12:43:34]  transpile update started ...
> [12:43:34]  transpile update finished in 29 ms
> [12:43:34]  webpack started ...
> [12:44:03]  build started ...
> [12:44:03]  transpile update started ...
> [12:44:03]  transpile update finished in 35 ms
> [12:44:03]  webpack started ...

#### What behavior are you expecting?
Correct assembly of the project, without the periodical restart app-scripts

**Which @ionic/app-scripts version are you using?**
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.1 Build version 8B62

**Comment by danbucholtz** [comment]
@konrin,

Can you see if you can recreate it with Node 6? I have never seen this and I develop/debug a lot of Ionic stuff 😸 

Thanks,
Dan

**Comment by konrin** [comment]
@danbucholtz Node 6, decided the problem

**Comment by danbucholtz** [comment]
@konrin,

I'm not sure what you mean. Can you recreate with Node 6?

Thanks,
Dan

**Comment by konrin** [comment]
@danbucholtz I replaced Node 7 to 6 version, then app-scrips no longer hang.

**Comment by danbucholtz** [comment]
@konrin, okay, cool! Good to know. We will get it working with Node 7 ASAP but for right now we recommend using Node 6 LTS. We also test on Node 4 LTS.

Thanks,
Dan
