### ISSUE TITLE
Create separate bundles for Angular/Ionic and third party libs

### ISSUE THREAD

**Issue by pskhodad** [driftyco/ionic-app-scripts#57]
Allowing multiple bundles would be useful. With single bundle when number of multiple third party libs increase there will be issue with first view. Allowing multiple bundles can address this issue. Also some of the rollup config/third party libs related issues will be addressed nicely.
1) Angular/Ionic bundle goes through rollup process
2) Third party libs can continue to use browserify or rollup

**Comment by awebdeveloper** [comment]
did u succeed
