### ISSUE TITLE
show nothing long time after splash,about 10s,0.045 is ok.rc4

### ISSUE THREAD

**Issue by wolfljj** [driftyco/ionic-app-scripts#574]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jtushar53** [comment]
Hi @wolfljj check out changelog for app-scripts 0.0.47 https://github.com/driftyco/ionic-app-scripts/blob/master/CHANGELOG.md , AOT and minification  is  not enabled by default so that we can debug our apps.

you can run ionic run android --prod to enable AOT and minification

**Comment by danbucholtz** [comment]
@wolfljj, @jtushar53 is exactly right. Please use the `--prod` flag.

Thanks,
Dan
