### ISSUE TITLE
Suggestion: Be clear whether a build was fully optimised or not (--prod) / AOT

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic-app-scripts#579]
#### Short description of the problem:

Seems that some developers unsure (as evidenced in forums / issues) whether they are running a fully optimised (AOT) build or not.

#### What behavior are you expecting?

Works fine as is.

However, suggestion, howabout on the CLI on ionic build / ionic serve

Currently says "build finished in 21.71s"

New phrasing, adding a word
 "**development** build finished in 21.71s" or "**production** build finished in 21.71s

**Which @ionic/app-scripts version are you using?**

0.0.47

**Comment by duydao** [comment]
Just a heads up: Production builds will have a ngc line in the build step list:

```
ngc started...
ngc finished
```

**Comment by alexbainbridge** [comment]
I know that, you know that, but if you read the forums, seems not everyone knows that :)

**Comment by danbucholtz** [comment]
It says whether it's a prod build or a dev build.

Thanks,
Dan
