### ISSUE TITLE
Ionic Provider code changes not reloading after second save/reload

### ISSUE THREAD

**Issue by paulsutherland** [driftyco/ionic-app-scripts#580]
#### Description of the problem:
Providers reload with changes on the first reload, but they are not reloading with code changes after second save/reload and then subsequent reloads thereafter.  

Page class changes do continue to change and are reloaded in the browser as expected.

#### Expected behaviour?
When the code in a provider is changed and saved, webpack should rebuild and the changes should 
live-reload in the browser.

**Steps to reproduce:**
1. Clone the example repo here: git clone https://github.com/paulsutherland/Ionic-Provider-Not-Reloading.git
2. npm install
3. ionic serve
4. Change console message in providers/database.ts
5. Witness that the console message in browser updates to reflect change
6. Change console message in providers/database.ts again
7. Witness that the console message in browser does not update with change
8. Change console message in pages/home.ts
9. Console message in browser updates to reflect change

**Which @ionic/app-scripts version are you using?**
Tested with:

Chrome Version 55.0.2883.95 (64-bit)

Cordova CLI: 6.4.0                                                                                                                                                                       
Ionic Framework Version: 2.0.0-rc.4                                                                                                                                                      
Ionic CLI Version: 2.1.14                                                                                                                                                                
Ionic App Lib Version: 2.1.7                                                                                                                                                             
Ionic App Scripts Version: 0.0.47                                                                                                                                                        
ios-deploy version: 1.9.0                                                                                                                                                                
ios-sim version: 5.0.12                                                                                                                                                                  
OS: macOS Sierra                                                                                                                                                                         
Node Version: v6.9.1                                                                                                                                                                     
Xcode version: Xcode 8.1 Build version 8T47 

And tested with ionic app scripts nightly:

"@ionic/app-scripts": "0.0.47-201612161753",

**Comment by danbucholtz** [comment]
Try this with `1.0.0`. I believe this is resolved. Please let me know if it still an issue.

Thanks,
Dan

**Comment by paulsutherland** [comment]
HI Dan,

I can confirm using 1.0.0 in a fresh Ionic 2.0.0 works as expected. Provider code changes  reload on every save.

Many Thanks,

Paul
