### ISSUE TITLE
Cannot set property 'sources' of undefined at node_modules/@ionic/app-script/dist/webpack/loader-impl.js:35:37

### ISSUE THREAD

**Issue by rephchunhoong** [driftyco/ionic-app-scripts#583]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Error when building with --prod flag. App is blank after loading screen. However, things just work when building without --prod flag.

#### What behavior are you expecting?
--prod should not trigger any error.

**Steps to reproduce:**
1. ionic build android --prod
2. mfp cordova run -d

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
0.0.48

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
![capture](https://cloud.githubusercontent.com/assets/12269078/21325142/bcce90ee-c65f-11e6-99be-fc7107495c55.JPG)

**Comment by danbucholtz** [comment]
Make sure you have `sourceMap` set to `"true"` in `tsconfig.json` like this file does.
https://github.com/driftyco/ionic2-app-base/blob/master/tsconfig.json#L13
Thanks,
Dan
