### ISSUE TITLE
how to use VsCode  to debug ionic2? the first  step  setting

### ISSUE THREAD

**Issue by WillLeeBebi** [driftyco/ionic-app-scripts#584]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
hi . i am trying debug ionic2  via VS Code  the latest version(ver 1.8.1)  
follow the tutorial . 
http://www.damirscorner.com/blog/posts/20161122-DebuggingIonic2AppsInChromeFromVisualStudioCode.html
and   there is a file  launch.json  which need  config it.
but this ionic2 rc4,  one more  configuration option  as below. how do i  config it ?
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8100",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        },
      **```  {
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 8100,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }```**
    ]
}
 the Bond style is the  problem section,how do i setting it ?  (sourcemaps  already setting it.)

**Comment by tja4472** [comment]
Hi

This is mine.
### Debugger for Chrome extension
Google Chrome shortcut Target (Windows)
```
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222
```
launch.json
```
{
    "name": "Attach to Chrome, with sourcemaps",
    "type": "chrome",
    "request": "attach",
    "port": 9222,
    "sourceMaps": true,
    "webRoot": "${workspaceRoot}/www",
    "url":"http://localhost:8100/"          
}
```

You also need to use @ionic/app-scripts version 47 or greater.

hth
Tim

**Comment by danbucholtz** [comment]
Hi @WillLeeBebi,

Please post this question in the Ionic Framework forum. We don't take questions on Github unfortunately. We use issues as a way to track work.

Thanks,
Dan
