### ISSUE TITLE
problem with ionic build android command

### ISSUE THREAD

**Issue by arvind-fwrk** [driftyco/ionic-app-scripts#586]
I am a beginner in ionic framework 
following is my cmd output:

C:\fifteendec>ionic build android
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
Caught exception:
 Error: spawn C:\Windows\system32\cmd.exe;C:\Program Files\Git ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
*****************************************************************
My ionic info:
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.17
OS: window 7 , 64 bit
Node Version: v6.9.2

How can i get rid of  this error???

**Comment by danbucholtz** [comment]
Please provide more info. Our [support forum](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA) is a good place to go for help.
