### ISSUE TITLE
ionic_copy override doesn't override it 'adds'

### ISSUE THREAD

**Issue by olivermuc** [driftyco/ionic-app-scripts#587]
When defining a copy override config:
```
"ionic_copy": "./config/copy.config.js",
```

the process executes both the default npm app-scripts located 
**node_modules/@ionic/app-scripts/config/copy.config.js**
as well as the newly assigned 
**./config/copy.config.js**

A bug or feature? 
How can this be turned off?

Thanks
O.

**EDIT:**
Got it. It requires the same names to be used and will replace their individual definition, it doesn't replace the entire config file & logic per se.

**Comment by danbucholtz** [comment]
@olivermuc,

This is by design. If you want to remove a key, say `copyPolyfills`, you can provide a blank object for it. IE

```
...
copyPolyfills: {},
...
```

Hopefully this helps you.

Thanks,
Dan

**Comment by wjljack** [comment]
blank object doesn't work,
`module.exports = {
  copyFonts: {}
}`

fonts folder copied as usual

**Comment by masimplo** [comment]
@wjljack  just tried it with the current version and it works. Providing an empty copyFonts keyvalue pair does not copy the default fonts inside www dir.
