### ISSUE TITLE
ionic build android --prod outputs file with name android-debug.apk

### ISSUE THREAD

**Issue by pdrosos** [driftyco/ionic-app-scripts#589]
ionic build android --prod creates a file with wrong name: /platforms/android/build/outputs/apk/android-debug.apk

ionic info:
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v7.1.0
Xcode version: Xcode 8.2 Build version 8C38

**Comment by seed880505** [comment]
Try with --release --prod together

**Comment by pdrosos** [comment]
@seed880505 thanks, my mistake to skip the `--release` flag. Closing.
