### ISSUE TITLE
Custom rollup config breaks file watcher

### ISSUE THREAD

**Issue by cmaart** [driftyco/ionic-app-scripts#59]
When using a custom a custom rollup config, it gets loaded with require in util.fillConfigDefaults and the dest property is set on this config object in bundle.runBundle. This works fine the first time. When bundleUpdate is called from the watcher, the same instance is returned by require and again the dest is set like this in bundle.runBundle: 
`rollupConfig.dest = join(context.buildDir, rollupConfig.dest);`

Because it's always the same instance of `rollupConfig`, this will append to the `dest` with each watch trigger, leading to wrong paths.

See a detailed post about it here with screenshots: [https://forum.ionicframework.com/t/having-a-custom-rollup-config-breaks-the-watcher/65343](https://forum.ionicframework.com/t/having-a-custom-rollup-config-breaks-the-watcher/65343)

**Comment by cmaart** [comment]
Pull request for it ready and waiting

**Comment by cmaart** [comment]
Verified, that the code fixes my issue as mentioned here: https://forum.ionicframework.com/t/having-a-custom-rollup-config-breaks-the-watcher/65343

**Comment by adamdbradley** [comment]
Awesome, thanks for the PR and unit tests too!

**Comment by cmaart** [comment]
@adamdbradley No problem. A publish would be good though :-) 
Maybe this issue is related as well #42

**Comment by cmaart** [comment]
Btw. having the fix and all is fine.. but codewise i'd go for immutable types. This wouldn't have happened if config classes for example are not mutable in the first place. Didn't want to do these changes in a PR now, just need a working version to keep on going with my project for now
