### ISSUE TITLE
ionic serve fails on windows

### ISSUE THREAD

**Issue by shadowzick** [driftyco/ionic-app-scripts#591]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Shadowzeik\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ionic:serve',
1 verbose cli   '--' ]
2 info using npm@4.1.1
3 info using node@v6.9.1
4 verbose run-script [ 'preionic:serve', 'ionic:serve', 'postionic:serve' ]
5 info lifecycle ionic-hello-world@~preionic:serve: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~preionic:serve: no script for preionic:serve, continuing
7 info lifecycle ionic-hello-world@~ionic:serve: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~ionic:serve: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~ionic:serve: PATH: C:\Users\Shadowzeik\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Shadowzeik\Desktop\play\ionic\ionic2-meteor-latest\Ionic2CLI-Meteor-WhatsApp\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Users\Shadowzeik\AppData\Local\.meteor\;C:\Users\Shadowzeik\AppData\Local\atom\bin;C:\Users\Shadowzeik\AppData\Roaming\npm\;C:\Users\Shadowzeik\AppData\Local\.meteor;C:\Users\Shadowzeik\AppData\Local\Android\Sdk\platform-tools; C:\curl;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Shadowzeik\AppData\Roaming\npm
10 verbose lifecycle ionic-hello-world@~ionic:serve: CWD: C:\Users\Shadowzeik\Desktop\play\ionic\ionic2-meteor-latest\Ionic2CLI-Meteor-WhatsApp
11 silly lifecycle ionic-hello-world@~ionic:serve: Args: [ '/d /s /c', 'ionic-app-scripts serve' ]
12 silly lifecycle ionic-hello-world@~ionic:serve: Returned: code: 3221225501  signal: null
13 info lifecycle ionic-hello-world@~ionic:serve: Failed to exec ionic:serve script
14 verbose stack Error: ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
14 verbose stack Exit status 3221225501
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Shadowzeik\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Shadowzeik\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd C:\Users\Shadowzeik\Desktop\play\ionic\ionic2-meteor-latest\Ionic2CLI-Meteor-WhatsApp
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Shadowzeik\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--"
19 error node v6.9.1
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
22 error Exit status 3221225501
23 error Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by shadowzick** [comment]
![image](https://cloud.githubusercontent.com/assets/5059523/21375589/921a6b56-c769-11e6-88fa-87e95fdb45c3.png)

**Comment by tja4472** [comment]
Hi 
Have you tried using the current stable version of npm which is 4.0.5?
[https://github.com/npm/npm/releases/tag/v4.0.5](url)


>  ordova CLI: 6.4.0
> Ionic Framework Version: 2.0.0-rc.4
> Ionic CLI Version: 2.1.17
> Ionic App Lib Version: 2.1.7
> Ionic App Scripts Version: 0.0.48
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Windows 10
> Node Version: v6.9.2
> Xcode version: Not installed

Tim

**Comment by danbucholtz** [comment]
I cannot recreate. I believe this issue is resolved.

Thanks,
Dan
