### ISSUE TITLE
Sourcemaps aren't updated properly after source code changes

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#595]
_From @beylkhanovdamir on December 17, 2016 4:40_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I run my ionic app by **ionic serve** command. after this I want to make a some changes in my source code and then I'm saving my changes, in result, starts the build process of project by ionic-appscripts and page is refreshing. In result, my sourcemaps files doesn't updated or they missing in Source control (in Google chrome dev tools). to fix this issue, I must stop the ionic serving process, and run it again
**Expected behavior:**

after saving any changes in my source code, sourcemaps  in Source control must be updated according with my changes properly

**Ionic info:**

```
Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

app-scripts": "^0.0.46",

_Copied from original issue: driftyco/ionic#9680_

**Comment by jgw96** [comment]
_From @graphefruit on December 17, 2016 10:52_

@beylkhanovdamir Update your appscripts to the latest actually 0.0.47 and have a look if the issue still exists

**Comment by jgw96** [comment]
_From @dylanvdmerwe on December 17, 2016 13:51_

https://github.com/driftyco/ionic-app-scripts/blob/master/CHANGELOG.md

**Comment by jgw96** [comment]
_From @beylkhanovdamir on December 19, 2016 8:34_

@graphefruit @dylanvdmerwe thx, I'll try

**Comment by danbucholtz** [comment]
Does this issue still exist?

Thanks,
Dan

**Comment by beylkhanovdamir** [comment]
@danbucholtz let me check

**Comment by royipressburger** [comment]
@danbucholtz I have a similar issue with `0.0.48`.
Change code on any `.ts` file causes the browser to refresh but on dev tool it doesn't change.

**Comment by beylkhanovdamir** [comment]
@danbucholtz @jgw96 

I updated ionic-app-scripts to latest v1.0 - now everything works fine
thx. close issue

**Comment by beylkhanovdamir** [comment]
@danbucholtz @jgw96 

However on android device sourcemaps are not working and I cannot debugging my app in Chrome from device =/

![image](https://cloud.githubusercontent.com/assets/7656847/22150481/3a8f44c8-df2a-11e6-8466-c0534a7d6a0f.png)


Your system information:

> Cordova CLI: 6.3.1
> Ionic Framework Version: 2.0.0-rc.5
> Ionic CLI Version: 2.2.1
> Ionic App Lib Version: 2.2.0
> Ionic App Scripts Version: 1.0.0
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Windows 10
> Node Version: v6.9.1
> Xcode version: Not installed
