### ISSUE TITLE
build dev failed: Cannot read property 'indexOf' of undefined 

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#597]
_From @stefdelec on December 18, 2016 19:11_

Impossible to "serve".
I got this error only on brand new project but not older ones.
` build dev failed: Cannot read property 'indexOf' of undefined `

**Ionic version:** 
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6 
ios-sim version: 5.0.6 
OS: OS X El Capitan
Node Version: v6.9.2
Xcode version: Xcode 8.1 Build version 8B62

npm 4.0.5

[ ] bug report
```
$ ionic serve

> ionic-hello-world@ ionic:serve /Users/Stephane/Downloads/MyProject
> ionic-app-scripts serve

[20:09:16]  ionic-app-scripts 0.0.47 
[20:09:16]  watch started ... 
[20:09:16]  build dev started ... 
[20:09:16]  clean started ... 
[20:09:16]  clean finished in 4 ms 
[20:09:16]  copy started ... 
[20:09:16]  transpile started ... 
[20:09:20]  build dev failed: Cannot read property 'indexOf' of undefined 
[20:09:20]  dev server running: http://localhost:8100/ 

[20:09:20]  copy finished in 4.32 s 
[20:09:20]  watch ready in 4.34 s 
```

Debug file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'ionic:build',
1 verbose cli   '--' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'preionic:build', 'ionic:build', 'postionic:build' ]
5 info lifecycle ionic-hello-world@~preionic:build: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~preionic:build: no script for preionic:build, continuing
7 info lifecycle ionic-hello-world@~ionic:build: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~ionic:build: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~ionic:build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Stephane/Downloads/MyProject/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/usr/local/git/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
10 verbose lifecycle ionic-hello-world@~ionic:build: CWD: /Users/Stephane/Downloads/MyProject
11 silly lifecycle ionic-hello-world@~ionic:build: Args: [ '-c', 'ionic-app-scripts build' ]
12 silly lifecycle ionic-hello-world@~ionic:build: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~ionic:build: Failed to exec ionic:build script
14 verbose stack Error: ionic-hello-world@ ionic:build: `ionic-app-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd /Users/Stephane/Downloads/MyProject
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error ionic-hello-world@ ionic:build: `ionic-app-scripts build`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

_Copied from original issue: driftyco/ionic#9692_

**Comment by jgw96** [comment]
_From @lufias on December 19, 2016 2:20_

Are you using ion-img? Using debugger, my indexOf error was thrown trying to load an ion-img src using a promise.. 

https://github.com/driftyco/ionic/issues/9691

**Comment by jgw96** [comment]
_From @stefdelec on December 19, 2016 12:14_

I am not using anything.
I creating a new project and then serve.

`ionic start myproject tabs --v2 --ts`


...

```
cd myproject
ionic serve
```

**Comment by jgw96** [comment]
_From @jayeshanandani on December 20, 2016 18:7_

Please try by updating ionic-app-scripts to 0.0.48 and ensure you have deleted node_modules folder and reinstalled again for safety check.

**Comment by jgw96** [comment]
_From @stefdelec on December 20, 2016 20:25_

how to update  ionic-app-scripts ?
`npm  ionic-app-scripts --update` ?

**Comment by jgw96** [comment]
_From @jayeshanandani on December 21, 2016 2:27_

You can try by `npm install @ionic/app-scripts@latest --save-dev`

**Comment by stefdelec** [comment]
I got this error:
```
"npm WARN @ionic/app-scripts@0.0.48 requires a peer of @angular/core@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of @angular/compiler@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of @angular/compiler-cli@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of @angular/tsc-wrapped@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of rxjs@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of typescript@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of zone.js@* but none was installed.
npm WARN tslint@3.15.1 requires a peer of typescript@>=1.7.3 but none was installed."
```

So I did:

`npm install -g typescript`

and again 
`npm install @ionic/app-scripts@latest --save-dev`

Still having the issue...

**Comment by jayeshanandani** [comment]
@stefdelec : what typescript version are you using?

**Comment by stefdelec** [comment]
```
tsc -v
Version 2.1.4
```

**Comment by jayeshanandani** [comment]
@stefdelec : can you please try with typescript version 2.0.9 as I have seen quite a few issues with 2.1.x in angular and other places round.

**Comment by stefdelec** [comment]
```
macbook:~ Stephane$ npm install typescript@2.0.0
/Users/Stephane
+-- UNMET PEER DEPENDENCY @angular/compiler@*
+-- UNMET PEER DEPENDENCY @angular/compiler-cli@*
+-- UNMET PEER DEPENDENCY @angular/core@*
+-- UNMET PEER DEPENDENCY @angular/tsc-wrapped@*
+-- UNMET PEER DEPENDENCY browserify@>= 6.x
+-- UNMET PEER DEPENDENCY rxjs@*
+-- typescript@2.0.0 
`-- UNMET PEER DEPENDENCY zone.js@*

npm WARN enoent ENOENT: no such file or directory, open '/Users/Stephane/package.json'
npm WARN @ionic/app-scripts@0.0.48 requires a peer of @angular/core@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of @angular/compiler@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of @angular/compiler-cli@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of @angular/tsc-wrapped@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of rxjs@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of zone.js@* but none was installed.
npm WARN tsify@2.0.2 requires a peer of browserify@>= 6.x but none was installed.
npm WARN Stephane No description
npm WARN Stephane No repository field.
npm WARN Stephane No README data
npm WARN Stephane No license field.

```

**Comment by stefdelec** [comment]
```
macbook-air-de-stephane:~ Stephane$ npm install typescript@2.0.0 -g
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
/usr/local/lib
`-- typescript@2.0.0 

macbook-air-de-stephane:~ Stephane$ npm install @ionic/app-scripts@latest --save-dev -g
/usr/local/bin/ionic-app-scripts -> /usr/local/lib/node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js
/usr/local/lib
+-- UNMET PEER DEPENDENCY @angular/compiler@*
+-- UNMET PEER DEPENDENCY @angular/compiler-cli@*
+-- UNMET PEER DEPENDENCY @angular/core@*
+-- UNMET PEER DEPENDENCY @angular/tsc-wrapped@*
+-- @ionic/app-scripts@0.0.48 
| `-- UNMET PEER DEPENDENCY typescript@>=1.7.3
+-- UNMET PEER DEPENDENCY rxjs@*
+-- UNMET PEER DEPENDENCY typescript@*
`-- UNMET PEER DEPENDENCY zone.js@*

npm WARN @ionic/app-scripts@0.0.48 requires a peer of @angular/core@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of @angular/compiler@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of @angular/compiler-cli@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of @angular/tsc-wrapped@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of rxjs@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of typescript@* but none was installed.
npm WARN @ionic/app-scripts@0.0.48 requires a peer of zone.js@* but none was installed.
npm WARN tslint@3.15.1 requires a peer of typescript@>=1.7.3 but none was installed.

```

**Comment by jayeshanandani** [comment]
@stefdelec : It seems you dont' have any angular dependencies installed. Please share you package.json file.

**Comment by stefdelec** [comment]
It is a brand new projet from 
`ionic start myproject tabs --v2 --ts`

**Comment by jayeshanandani** [comment]
@stefdelec : That's fine but from your output it seems npm is not installing all dependencies needed and hence the error.

**Comment by jayeshanandani** [comment]
@stefdelec: Please update ionic-app-scripts to 0.0.48 in package.json. Delete npm_modules, .tmp folder if any and run the application again. Ensure you don't have any errors while npm install command.

**Comment by stefdelec** [comment]
Almost there : new error

`MacBook-Air-de-Stephane:myproject Stephane$ ionic serve

> ionic-hello-world@ ionic:serve /Users/Stephane/Documents/APPs/myproject
> ionic-app-scripts serve

keywords if/then/else require v5 option
[17:27:58]  ionic-app-scripts 0.0.48 
[17:27:58]  watch started ... 
[17:27:58]  build dev started ... 
[17:27:58]  clean started ... 
[17:27:58]  clean finished in 4 ms 
[17:27:58]  copy started ... 
[17:27:58]  transpile started ... 
[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.collection.d.ts, line: 24 
            All declarations of 'size' must have identical modifiers. 

      L25:  interface WeakMapConstructor {

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.collection.d.ts, line: 30 
            All declarations of 'prototype' must have identical modifiers. 

      L30:  declare var WeakMap: WeakMapConstructor;
[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.collection.d.ts, line: 44 

            All declarations of 'prototype' must have identical modifiers. 

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.collection.d.ts, line: 54 
      L43:      new <T>(values?: T[]): Set<T>;
      L44:      readonly prototype: Set<any>;

            All declarations of 'size' must have identical modifiers. 

      L54:  interface WeakSetConstructor {
      L55:      new (): WeakSet<any>;

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.collection.d.ts, line: 60 
            All declarations of 'prototype' must have identical modifiers. 

      L59:  declare var WeakSet: WeakSetConstructor;

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.collection.d.ts, line: 73 
            All declarations of 'prototype' must have identical modifiers. 

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.core.d.ts, line: 17 

            Duplicate identifier 'PropertyKey'. 

      L16:  * Returns the index of the first element in the array where predicate is true, and undefined
      L17:  * otherwise.
      L18:  * @param predicate find calls predicate once for each element of the array, in ascending

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.core.d.ts, line: 95 
            All declarations of 'name' must have identical modifiers. 

      L94:      imul(x: number, y: number): number;

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.core.d.ts, line: 216 
[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.core.d.ts, line: 251 
            All declarations of 'EPSILON' must have identical modifiers. 

     L217:        * Returns a Boolean value that indicates whether a value is the reserved value NaN (not a

            All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers. 

     L251:    * Converts A string to an integer.
     L252:    * @param s A string to convert into a number.

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.core.d.ts, line: 258 
            All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers. 

     L257:      parseInt(string: string, radix?: number): number;

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.core.d.ts, line: 403 
            All declarations of 'flags' must have identical modifiers. 

     L402:  interface RegExpConstructor {
     L403:      new (pattern: RegExp, flags?: string): RegExp;
[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.iterable.d.ts, line: 24 
     L404:      (pattern: RegExp, flags?: string): RegExp;

            All declarations of 'iterator' must have identical modifiers. 

      L24:  interface IterableIterator<T> extends Iterator<T> {
      L25:      [Symbol.iterator](): IterableIterator<T>;

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.iterable.d.ts, line: 29 
            All declarations of 'value' must have identical modifiers. 

      L28:  interface Array<T> {
[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.promise.d.ts, line: 69 
      L29:      /** Iterator */
      L30:      [Symbol.iterator](): IterableIterator<T>;

            All declarations of 'prototype' must have identical modifiers. 

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.d.ts, line: 29 
      L69:   * Creates a Promise that is resolved with an array of results when all of the provided Promises
      L70:   * resolve, or rejected when any Promise is rejected.

            All declarations of 'prototype' must have identical modifiers. 

      L29:    * Returns a key from the global symbol registry matching the given Symbol if found. 
      L30:    * Otherwise, returns a undefined.

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 24 
            All declarations of 'hasInstance' must have identical modifiers. 

      L24:      readonly replace: symbol;
[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 30 

            All declarations of 'isConcatSpreadable' must have identical modifiers. 

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 36 
      L30:      readonly search: symbol;

            All declarations of 'match' must have identical modifiers. 

      L36:      readonly species: symbol;
[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 42 

            All declarations of 'replace' must have identical modifiers. 

      L42:      readonly split: symbol;

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 48 
            All declarations of 'search' must have identical modifiers. 

      L48:      readonly toPrimitive: symbol;

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 54 
            All declarations of 'species' must have identical modifiers. 

      L54:      readonly toStringTag: symbol;

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 60 
            All declarations of 'split' must have identical modifiers. 

      L60:      readonly unscopables: symbol;
[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 66 

            All declarations of 'toPrimitive' must have identical modifiers. 

      L67:  interface Array<T> {

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 72 
            All declarations of 'toStringTag' must have identical modifiers. 

      L72:  [Symbol.unscopables](): {
      L73:      copyWithin: boolean;

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 78 
            All declarations of 'unscopables' must have identical modifiers. 

      L77:  findIndex: boolean;
      L78:  keys: boolean;
      L79:  values: boolean;
[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 82 

            All declarations of '[Symbol.toStringTag]' must have identical modifiers. 

      L83:  interface Date {

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 142 
            All declarations of '[Symbol.toStringTag]' must have identical modifiers. 

                rface Math {
     L143:      readonly [Symbol.toStringTag]: "Math";

[17:28:04]  typescript: node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts, line: 161 
            All declarations of '[Symbol.toStringTag]' must have identical modifiers. 

     L160:      [Symbol.match](string: string): RegExpMatchArray | null;

[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 21 
            Duplicate identifier 'PropertyKey'. 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 85 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 145 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 262 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 276 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 311 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 318 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 457 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 457 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 464 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 492 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 498 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 504 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 510 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 516 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 522 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 528 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 534 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 540 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 546 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 552 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 609 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 609 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 613 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 613 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 628 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 634 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 645 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 651 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 666 

      L20:  * target object. Returns the target object.
      L21:  * @param target The target object to copy to.
      L22:  * @param source1 The first source object from which to copy properties.

            All declarations of 'name' must have identical modifiers. 

      L84:  * otherwise.
      L85:  * @param predicate find calls predicate once for each element of the array, in ascending
      L86:  * order, until it finds one where predicate returns true. If such an element is found, find

            Subsequent variable declarations must have the same type. Variable '[Symbol.unscopables]' must be of type '{ 
            copyWithin: boolean; entries: boolean; fill: boolean; find: boolean; findIndex: boolean; keys: ...', but 
            here has type 'any'. 

     L146:        * Creates an array from an array-like object.

            All declarations of 'flags' must have identical modifiers. 

     L261:  * number. Only finite values of the type number, result in true.
     L262:  * @param number A numeric value.

            All declarations of 'EPSILON' must have identical modifiers. 

     L275:  * to a number. Only values of the type number, that are also NaN, result in true.
     L276:  * @param number A numeric value.

            All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers. 

     L310:  * If this argument is not supplied, strings with a prefix of '0x' are considered hexadecimal.
     L311:  * All other strings are considered decimal.

            All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers. 

     L318:    * Returns the number of leading zero bits in the 32-bit binary representation of a number.
     L319:    * @param x A numeric expression.

            Subsequent variable declarations must have the same type. Variable '[Symbol.toStringTag]' must be of type 
            '"Symbol"', but here has type 'string'. 

     L457:      for(key: string): symbol;

            All declarations of '[Symbol.toStringTag]' must have identical modifiers. 

     L457:      for(key: string): symbol;

            All declarations of 'prototype' must have identical modifiers. 

     L464:      keyFor(sym: symbol): string;

            All declarations of 'hasInstance' must have identical modifiers. 

     L493:        * A regular expression method that replaces matched substrings of a string. Called by the

            All declarations of 'isConcatSpreadable' must have identical modifiers. 

     L499:        * A regular expression method that returns the index within a string that matches the

            All declarations of 'iterator' must have identical modifiers. 

     L505:        * A function valued property that is the constructor function that is used to create

            All declarations of 'match' must have identical modifiers. 

     L511:        * A regular expression method that splits a string at the indices that match the regular

            All declarations of 'replace' must have identical modifiers. 

     L517:        * A method that converts an object to a corresponding primitive value.Called by the ToPrimitive

            All declarations of 'search' must have identical modifiers. 

     L523:        * A String value that is used in the creation of the default string description of an object.

            All declarations of 'species' must have identical modifiers. 

     L529:        * An Object whose own property names are property names that are excluded from the with

            All declarations of 'split' must have identical modifiers. 

     L535:        * Non-standard. Use simple mode for core-js symbols. See https://github.com/zloirock/core-js/#caveats-when-using-symbol-polyfill

            All declarations of 'toPrimitive' must have identical modifiers. 

     L540:    * Non-standard. Use setter mode for core-js symbols. See https://github.com/zloirock/core-js/#caveats-when

            All declarations of 'toStringTag' must have identical modifiers. 

     L545:  declare var Symbol: SymbolConstructor;
     L547:  interface Object {

            All declarations of 'unscopables' must have identical modifiers. 

     L552:      hasOwnProperty(v: PropertyKey): boolean;

            Subsequent variable declarations must have the same type. Variable '[Symbol.toStringTag]' must be of type 
            '"Math"', but here has type 'string'. 

     L608:      size: number;

            All declarations of '[Symbol.toStringTag]' must have identical modifiers. 

     L608:      size: number;

            Subsequent variable declarations must have the same type. Variable '[Symbol.toStringTag]' must be of type 
            '"JSON"', but here has type 'string'. 

     L612:  [17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 680 
22mnew <K, V>(): Map<K, V>;
     L613:  new <K, V>(iterable: Iterable<[K, V]>): Map<K, V>;
     L614:  prototype: Map<any, any>;

            All declarations of '[Symbol.toStringTag]' must have identical modifiers. 

     L612:  new <K, V>(): Map<K, V>;
     L613:  new <K, V>(iterable: Iterable<[K, V]>): Map<K, V>;
     L614:  prototype: Map<any, any>;

            All declarations of 'size' must have identical modifiers. 

     L628:  interface SetConstructor {
     L629:      new <T>(): Set<T>;

            All declarations of 'prototype' must have identical modifiers. 

     L634:  declare var Set: SetConstructor;

            All declarations of 'size' must have identical modifiers. 

     L644:  new <K, V>(): WeakMap<K, V>;
     L645:  new <K, V>(iterable: Iterable<[K, V]>): WeakMap<K, V>;
     L646:  prototype: WeakMap<any, any>;

            All declarations of 'prototype' must have identical modifiers. 

     L651:  interface WeakSet<T> {
     L652:      add(value: T): WeakSet<T>;

            All declarations of 'prototype' must have identical modifiers. 

     L665:  // #############################################################################################
     L666:  // ECMAScript 6: Iterators
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 692 
[17:28:04]  typescript: Users/Stephane/node_modules/@types/core-js/index.d.ts, line: 804 
     L667:  // Modules: es6.string.iterator, es6.array.iterator, es6.map, es6.set, web.dom.iterable

            All declarations of 'prototype' must have identical modifiers. 

     L681:  interface Iterable<T> {

            All declarations of 'value' must have identical modifiers. 

     L691:      [Symbol.iterator](): IterableIterator<string>;

            All declarations of 'prototype' must have identical modifiers. 

     L803:  all<T1, T2, T3, T4, T5, T6, T7>(values: [T1 | PromiseLike<T1>, T2 | PromiseLike<T2>, T3 | PromiseLike<T3>, T4 | PromiseLike <T4>, T5 | PromiseLike<T5>, T6 | PromiseLike<T6>, T7 | PromiseLike<T7>]): Promise<[T1, T2, T3, T4, T5, T6, T7]>;
     L804:  all<T1, T2, T3, T4, T5, T6>(values: [T1 | PromiseLike<T1>, T2 | PromiseLike<T2>, T3 | PromiseLike<T3>, T4 | 
     L805:  all<T1, T2, T3, T4, T5>(values: [T1 | PromiseLike<T1>, T2 | PromiseLike<T2>, T3 | PromiseLike<T3>, T4 | PromiseLike <T4>, T5 | PromiseLike<T5>]): Promise<[T1, T2, T3, T4, T5]>;

[17:28:04]  transpile failed 
[17:28:04]  dev server running: http://localhost:8100/ 

[17:28:04]  copy finished in 5.67 s 
[17:28:04]  watch ready in 5.69 s 
^[^C
MacBook-Air-de-Stephane:myproject Stephane$`

**Comment by danbucholtz** [comment]
I believe this issue is resolved now.

Thanks,
Dan

**Comment by stefdelec** [comment]
Nope. It is not I am still running into the issue even after updating package.json and ionic-script 0.0.48

**Comment by danbucholtz** [comment]
@stefdelec,

Did you modify the `lib` option at all?

It should look like this:
https://github.com/driftyco/ionic2-app-base/blob/master/tsconfig.json#L7-L10

Thanks,
Dan

**Comment by stefdelec** [comment]
Nop I havn't modified anything anywhere. But if I put the provided tsconfig in the link, doesn't work. If I remove 
"    "lib": [
      "dom",
      "es2015"
    ],"

It is transpiling. And Ionic is serving.

**Comment by malinda1986** [comment]
@stefdelec I got the same error, tried few hours to figure it out, it's related to lib option . your solution work perfectly

**Comment by danbucholtz** [comment]
Ahh, It could be because `@types/core-js` which is likely providing duplicate definitions for ES2015. I recommend removing those Types. You shouldn't need them as you should never be interacting directly with the polyfills.

Thanks,
Dan
