### ISSUE TITLE
Windows path issues (directory separators)

### ISSUE THREAD

**Issue by leppie** [driftyco/ionic-app-scripts#6]
Was getting (when run from `C:\dev\ionic2`):
```
[13:13:04]  Sass Error: line: 1, column: 19
File to import not found or unreadable: C:Þvionic2src/theme/variables.scss
Parent style sheet: stdin
[13:13:04]  sass failed:  Sass compile error
```

Doing `sassFile.replace(/\\/g, "\\\\")` @ https://github.com/driftyco/ionic-app-scripts/blob/master/src/sass.ts#L93 does the trick, but I would assume there is something better.

**Comment by rob3c** [comment]
@leppie thanks for tracking down a workaround until they fix this!

**Comment by adamdbradley** [comment]
You're saying it should be:
```  const sassImports = userSassVariableFiles.concat(componentSassFiles).map(sassFile => '"' + sassFile.replace(/\\/g, "\\\\") + '"');
```

Just want to make sure I understand it. Thanks

**Comment by rob3c** [comment]
@adamdbradley that's what I changed the js-equivalent to in `node_modules\@ionic\app_scripts\dist\sass.js` on line 78, and it's building fine on my dev box.

**Comment by leppie** [comment]
@adamdbradley I did the same as @rob3c, but yes, if that is the TypeScript way.

**Comment by adamdbradley** [comment]
@rob3c Would you be able to submit a PR with your change that you know fixes the windows issue? Thanks

**Comment by rob3c** [comment]
@adamdbradley ok I added the @leppie's fix in the pull request here: https://github.com/driftyco/ionic-app-scripts/pull/12

Sorry for the added noise in the thread, but the inital attempt was on master instead of a branch (git client wasn't checking out after branch creation, and I didn't notice until pushing)
