### ISSUE TITLE
Ionic build/Serve fail

### ISSUE THREAD

**Issue by Xenofexs** [driftyco/ionic-app-scripts#600]
Hi and thank you in advance :)

#### Short description of the problem:
When I install the last version of npm, ionic and cordova, I can't use ionic build android or ionic serve.
With the previous version, I can use ionic serve but not ionic build android cause : ENOENT: no such file or directory, scandir 

**Which @ionic/app-scripts version are you using?**
Windows 10 64bits
Ionic 2.1.17
npm 4.0.3
cordova 6.4.0

Error log (npm-debug.log) : 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Xeno\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ionic:serve',
1 verbose cli   '--' ]
2 info using npm@4.0.3
3 info using node@v7.3.0
4 verbose run-script [ 'preionic:serve', 'ionic:serve', 'postionic:serve' ]
5 info lifecycle good@~preionic:serve: good@
6 silly lifecycle good@~preionic:serve: no script for preionic:serve, continuing
7 info lifecycle good@~ionic:serve: good@
8 verbose lifecycle good@~ionic:serve: unsafe-perm in lifecycle true
9 verbose lifecycle good@~ionic:serve: PATH: C:\Users\Xeno\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\good\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;D:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Skype\Phone\;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;D:\wamp64\bin\php\php7.0.4;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Xeno\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\Xeno\AppData\Local\Programs\Python\Python35-32\;D:\wamp64\bin\php\php5.6.19\php.exe;C:\Users\Xeno\AppData\Roaming\Composer\vendor\bin;C:\Users\Xeno\AppData\Local\Microsoft\WindowsApps;C:\Users\Xeno\AppData\Roaming\npm
10 verbose lifecycle good@~ionic:serve: CWD: C:\good
11 silly lifecycle good@~ionic:serve: Args: [ '/d /s /c', 'ionic-app-scripts serve' ]
12 silly lifecycle good@~ionic:serve: Returned: code: 1  signal: null
13 info lifecycle good@~ionic:serve: Failed to exec ionic:serve script
14 verbose stack Error: good@ ionic:serve: `ionic-app-scripts serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Xeno\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Xeno\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid good@
16 verbose cwd C:\good
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Xeno\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--"
19 error node v7.3.0
20 error npm  v4.0.3
21 error code ELIFECYCLE
22 error good@ ionic:serve: `ionic-app-scripts serve`
22 error Exit status 1
23 error Failed at the good@ ionic:serve script 'ionic-app-scripts serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the good package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs good
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls good
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by rapropos** [comment]
Does the problem persist when using LTS node?

**Comment by Xenofexs** [comment]
Hi and thank your
With the LTS node, I can use ionic serve but not ionic build android cause : ENOENT: no such file or directory, scandir [PATH_OF_PROJECT]

**Comment by rapropos** [comment]
Perhaps this topic is more suited for [the support forums](https://forum.ionicframework.com/).

**Comment by danbucholtz** [comment]
@Xenofexs, @rapropos is correct. Please ask the question is the forum.

Thanks,
Dan
