### ISSUE TITLE
Make Ionic App Scripts usable for Angular 2 web projects.

### ISSUE THREAD

**Issue by fifafu** [driftyco/ionic-app-scripts#602]
#### Short description of the problem:
Honestly, Ionic App Scripts are great. In my opinion the concept is so much better than e.g. angular-cli. They are clean, very configurable, understandable and work very well (most of the time ;-)).

As mobile app developers we often have to create web-apps in addition to the mobile apps. Those webapps probably don't use Ionic, but it would be really awesome to be able to use the same infrastructure and setup for them.

Actually it's already quite possible to use the Ionic App Scripts for normal Angular 2 apps, however some things are hardcoded and Ionic specific.
I think it would really help Ionic to not only provide the app-scripts as an infrastructure base for Ionic apps, but also for web-apps. Given the quality of the app scripts, I think the Angular community will really appreciate what you are doing here, especially when looking at the controversial, unconfigurable and complicated angular-cli. This could even bring more contributors here and improve the quality of the app scripts even more. 

Also I think this could add a lot of value to the Ionic platform in general.

**Comment by danbucholtz** [comment]
Thanks for the kind words, we appreciate it. What doesn't work? I would be surprised if it doesn't just work. Of course, we don't support some parts of angular decorators like styles, etc since we use sass and scoped files. We probably won't be able to add support for that stuff.

Thanks,
Dan
