### ISSUE TITLE
--appEntryPoint does not work in production

### ISSUE THREAD

**Issue by jcviau** [driftyco/ionic-app-scripts#603]
#### Short description of the problem:
When using ionic-app-scripts build --prod --appEntryPoint ./src/path_to_file.ts, an error occur when building in production (--prod).

#### What behavior are you expecting?
calling --appEntryPoint in production should work.

**Steps to reproduce:**
1. call ionic-app-scripts build --prod --appEntryPoint ./src/path_to_file.ts
2. error occur

**Which @ionic/app-scripts version are you using?**
0.48

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Here's the error I got: 
Error: Could not find entry point (bootstrap file) ./src/path_to_file.ts
  at [...]\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:82:41

Also, if I try to use {SRC} environment variable in the path (instead of specifying ./src), I get an error. It occur because it look for a file with '{SRC}' in his path instead of the value of this environment variable. Here's the error: "main.dev.ts" and "main.prod.ts" have been deprecated. Please create a new file "main.ts" containing...

**Comment by jcviau** [comment]
It works if I start my path to the entry file with ./

**Comment by jcviau** [comment]
We have a workaround by specifying the path instead of using environment variable. 

Note : It's important to start the path to your file with ./, otherwise webpack won't find the file.

**Comment by danbucholtz** [comment]
This is resolved in master and will be in the next release.

Thanks,
Dan

**Comment by jcviau** [comment]
Thanks, will use next version (49) as soon as it's released.

**Comment by danbucholtz** [comment]
We published `1.0.0` of app-scripts tonight! 🎉 

Thanks,
Dan
