### ISSUE TITLE
Custom webpack config not taken into account

### ISSUE THREAD

**Issue by Mokto** [driftyco/ionic-app-scripts#604]
Hi,

#### Short description of the problem:
My webpack config is not taken into account.

**Steps to reproduce:**
1. start a new ionic app
2. set this as webpack config : (I just remove the node_modules from modules).
```javascript
var path = require('path');
module.exports = {
  resolve: {
    extensions: ['.ts', '.js', '.json'],
    modules: [
    ]
  }
};

```
3. Transpile works (shouldn't as I removed node_modules) but when I go to localhost:8100 it doesn't :
![capture du 2016-12-23 12-46-55](https://cloud.githubusercontent.com/assets/5103928/21459634/02651384-c90e-11e6-8599-6931c6d25d1f.png)

------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------
I was just showing the issue but this is what I am trying to do : adding modules directory to webpack :
1)
```javascript
module.exports = {
  resolve: {
    extensions: ['.ts', '.js', '.json'],
    modules: [
        path.resolve('modules'),
        path.resolve('node_modules')
    ]
  }
};
```
2) `import { Logger } from 'common-frontend';`
3) When transpiling it says : `Cannot find module 'common-frontend'.` but directory exists in /modules.

**Which @ionic/app-scripts version are you using?**
0.0.48

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed

```

Thanks !

**Comment by danbucholtz** [comment]
Sorry, I cannot recreate. It could be a problem with your webpack config.

Thanks,
Dan
