### ISSUE TITLE
--ngc doesnt work

### ISSUE THREAD

**Issue by jcviau** [driftyco/ionic-app-scripts#605]
#### Short description of the problem:
When using --ngc in the build, the tsconfig file is not updated with the additional configuration specifiedby the --ngc flag.

#### What behavior are you expecting?
This was working with version 41 and it's not working with the latest version (48). We would expect that we could modify the tsconfig by specifying additonnal configuration with --ngc. In our project, we use this to ignore some files from ngc.

**Steps to reproduce:**
1. Build with --ngc, specify a config file
2. the config file specified is not used to modify the tsconfig.json when calling ngc.

**Which @ionic/app-scripts version are you using?**
48

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
When you say `--ngc`, what do you mean exactly? We deprecated the `ngc` config file and just use the `tsconfig.json` file for now. It was in the changelog as moving to in-memory ngc.

Thanks,
Dan

**Comment by jcviau** [comment]
OK, sorry I missed that changes, you can close this issue.

Did not see this breaking changes in the changelog of version 47 (version where In-memory was introduced) 

Note : --ngc should be removed from the Readme file.
