### ISSUE TITLE
Build time - webpack and white screen

### ISSUE THREAD

**Issue by jayeshanandani** [driftyco/ionic-app-scripts#606]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
The issues are as follows:

1. Ionic build takes longer time in Linux compared to MAC. Even if no file has been changed and just save is clicked, it takes 20seconds in Linux and 6 seconds in MAC to perform each build. Note this is the time taken by webpack update.
2.  Ionic build android works fine only the first time. When we remove node_modules, android platform plugins everything and add everything again by respective commands it works fine on the first load. Device ready takes around 4seconds to get fired, but if you make some change and run ionic run android or ionic build android --prod application crashes due to device ready being fired after 20 seconds.
**UPDATE:** Behavior is very uncertain. ionic run android / ionic build android takes upto 30 seconds to fire but same when done with --aot it takes only 3 seconds to fire.
3. When you close app and resume back the application we get a momentarily white screen and then it loads application.

#### What behavior are you expecting?
1. If no file contents are changed webpack updated should not happen. HTML or TS both take equal time in building which didn't use to happen earlier.
2. I don't recall this issue happening earlier. If I revert back to 0.0.45 app-scripts everything is smooth. I am debugging at my end to find a resolution of what actually caused this.
3. This is happening in all versions and seems is still unresolved.

**Steps to reproduce:**
1. Any starter app with the configuration of the system mentioned below. Can be tested on MAC/Linux.
2. Android tools installed and run steps as shown in issue.

**Which @ionic/app-scripts version are you using?**
0.0.48

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: OS X El Capitan
Node Version: v6.9.2
Xcode version: Xcode 7.3.1 Build version 7D1014

**For Linux:** 
Your system information:                                                                         
Cordova CLI: 6.4.0                                                                               
Ionic Framework Version: 2.0.0-rc.4                                                              
Ionic CLI Version: 2.1.17                                                                        
Ionic App Lib Version: 2.1.7                                                                     
Ionic App Scripts Version: 0.0.48                                                                
ios-deploy version: Not installed                                                                
ios-sim version: Not installed                                                                   
OS: Linux 4.4                                                                                    
Node Version: v4.5.0                                                                             
Xcode version: Not installed

**Comment by yasar-salim** [comment]
use 
```
ionic build android --prod
```
if it fails on terminal check whether it is node-sass issue , in that case updating node sass will fix the error

**Comment by jayeshanandani** [comment]
@yasar-salim that doesn't solves the development purpose. I have also written in above post that --prod works fine sometimes and sometimes it doesn't. --dev with aot also works fine.

**Comment by yasar-salim** [comment]
i fix the issue by updating  node, npm and app script to the latest version.
And when i run ionic 
```
ionic build android --prod
```
which fails all the time. It shows a problem with node sass in the terminal .
When i fix the node sass issue  the above command executed successfully and results a low size apk file and the white screen duration is reduced

**Comment by danbucholtz** [comment]
I'm not sure I'm following. Is this still an issue?

Thanks,
Dan
