### ISSUE TITLE
can't run service worker

### ISSUE THREAD

**Issue by MoranF** [driftyco/ionic-app-scripts#609]
#### Short description of the problem:
I updated Ionic 2, codova and the app-scripts to the latest versions and when I un-commented the service worker block in index.html file, I get this error: "Uncaught SyntaxError: Unexpected token )" on line 27 in index.html file, and right after it, this error: "Uncaught TypeError: Cannot read property 'insertBefore' of null".
It seems to me that maybe index.html and serice-worker.js aren't transpiled (when I used es5 code in index.html file, there wasn't an error in index.html file, but there was in service-worker.js file).

#### What behavior are you expecting?
That the service worker will run correctly.

**Steps to reproduce:**
1. run "ionic serve" from the project folder
2. go to the project home page in the browser

```
**Which @ionic/app-scripts version are you using?**
@ionic/app-scripts@latest

**Comment by danbucholtz** [comment]
@MoranF,

I'm not sure I'm following. Is this still an issue? I'll reopen if so.

Thanks,
Dan
