### ISSUE TITLE
Uglification : inSourceMap not working

### ISSUE THREAD

**Issue by paulpatarinski** [driftyco/ionic-app-scripts#613]
#### Short description of the problem:
inSourceMap not working

#### What behavior are you expecting?
setting the inSourceMap includes the specified source map in the outSourceMap

**Steps to reproduce:**
1. set inSourceMap 
2. uglify
3. source map is not included 

The setting is not being passed to uglify.minify

```
function runUglifyInternal(uglifyJsConfig) {
  return uglify.minify(uglifyJsConfig.sourceFile, {
    compress: uglifyJsConfig.compress,
    mangle: uglifyJsConfig.mangle,
    outSourceMap: uglifyJsConfig.outSourceMap
  });
}
```

**Which @ionic/app-scripts version are you using?**
0.0.48

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Submitting a PR with a fix....

**Comment by paulpatarinski** [comment]
PR #614

**Comment by danbucholtz** [comment]
Merged the PR.

THanks,
Dan
