### ISSUE TITLE
build folder files get deleted during ionic serve

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-app-scripts#617]
_From @MAEVE007 on December 2, 2016 5:3_

I get these error when i run my app. N these files main.css ,polyfills.css were deleted themselves. Please suggest something. 

<Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/main.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/polyfills.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://0.0.0.0:35729/livereload.js?snipver=1 Failed to load resource: net::ERR_ADDRESS_INVALID
http://localhost:8100/build/main.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/polyfills.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/main.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/main.css Failed to load resource: the server responded with a status of 404 (Not Found)

_Copied from original issue: driftyco/ionic-conference-app#326_

**Comment by danbucholtz** [comment]
A clean is executed as part of the build. It seems that something went wrong in your particular environment. I cannot recreate, so I am going to close this. If this was wide spread or a common issue, we'd hear about it more so I'm not overly concerned 🐱 

Thanks,
Dan

**Comment by ahmadalhajh** [comment]
have same issue

**Comment by mlp1802** [comment]
Same..
