### ISSUE TITLE
PWA: Splitting main.JS into 2 files - libraries & business logic

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#623]
_From @astec on January 5, 2017 13:17_

**Ionic version:**  (check one with "x")
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] feature request

**Current behavior:**

Currently when we run `ionic build browser --prod` we get 1 `main.js` file that contains both libraries (_Angular, Ionic, etc._) and application logic/UI(_AOT_).

**Expected behavior:**

Developers often update application without changing libraries. Having production bundle split in 2 (_for example libraries.js & app.js_) would allow:

- Speedup deployment as most of the time developers can upload just changed app.js part. (_for example when deploy to Google AppEngine just changed files are uploaded_).  On 2G connection few extra MB do make a difference.
- Minimize traffic & response time for clients for requests after an app updated.

An additional 1 HTTP(s) request should not be a big deal and not a problem at all for those who use HTTP2 (_you should_).

Of course a proper lazy loading with multiple modules would be a more generic and a preferable solution but splitting into 2 bundles can be a good interim or "settings free by default" alternative.

**Steps to reproduce:**
`ionic build browser --prod`

**Other information:**
```
Ionic RC4
```

_Copied from original issue: driftyco/ionic#9889_

**Comment by dorgold** [comment]
If someone is trying to pull this off until official support by ionic, this can be done using webpack CommonsChunkPlugin (shipped with webpack).

This is the changes necessary to the webpack.config.js:

`var path = require('path');
var webpack = require('webpack');
var ionicWebpackFactory = require(process.env.IONIC_WEBPACK_FACTORY);

module.exports = {
  entry: {
    app: process.env.IONIC_APP_ENTRY_POINT,
    vendor: [
      "ionic-angular",
      "ionic-native",
      "@angular/core",
      "@angular/forms",
      "@angular/common",
      "@angular/platform-browser",
      "@angular/http",
      "lodash",
      "rxjs"],
  },
  output: {
    path: '{{BUILD}}',
    filename: process.env.IONIC_OUTPUT_JS_FILE_NAME,
    devtoolModuleFilenameTemplate: ionicWebpackFactory.getSourceMapperFunction(),
    publicPath: '/build/'
  },
  devtool: process.env.IONIC_GENERATE_SOURCE_MAP ? process.env.IONIC_SOURCE_MAP_TYPE : '',

  resolve: {
    extensions: ['.ts', '.js', '.json'],
    modules: [path.resolve('node_modules')]
  },

  module: {
    loaders: [
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        //test: /\.(ts|ngfactory.js)$/,
        test: /\.ts$/,
        loader: process.env.IONIC_WEBPACK_LOADER
      }
    ]
  },

  plugins: [
    ionicWebpackFactory.getIonicEnvironmentPlugin(),
    new webpack.optimize.CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.bundle.js' })
  ],

  // Some libraries import Node modules but don't use them in the browser.
  // Tell Webpack to provide empty mocks for them so importing them works.
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
};
`

**Comment by arihantdaga** [comment]
Does not improve much in the time taken in build process when running ionic serve. 
one more thing is, total build time is much more than what it took in webpack process. 
```

[13:37:21]  build started ... 
[13:37:21]  transpile update started ... 
[13:37:21]  transpile update finished in 190 ms 
[13:37:21]  webpack update started ... 
[13:37:25]  webpack update finished in 3.57 s 
[13:37:42]  build finished in 21.22 s 

```

I don't know what's going on after webpack update finishes which is taking so much time.

**Comment by danbucholtz** [comment]
We will have to more to share on this soon. Tracking the topic here.

https://github.com/driftyco/ionic-app-scripts/issues/693

Thanks,
Dan

**Comment by awebdeveloper** [comment]
is this in ?? I don't find it even commented checked 1.3.5
