### ISSUE TITLE
Ionic Application Error 

### ISSUE THREAD

**Issue by magnusmel** [driftyco/ionic-app-scripts#624]
My system information:

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.1
Node Version: v6.9.0
Xcode version: Not installed
```
This is an Ionic 2 app, worked fine till recently. After upgrading to ionic framework Rc3 , during an 

> ionic run android

 builds it throws an Error which keeps a dialog open on the app in the mobile device with the below message. But I am able to live debug the app on the mobile using the chrome dev tools. So the app works fine, login et all. Except for the error below:-

-```
Application Error 
connection to the server was unsuccessful. File://android_asset/www/index.html
Tried reinstalling android platform and all.

```
But nothing seems to work on even a basic app.

Config.xml file contains
```

 <description>An  Ionic 2 Starter app.</description>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">

```

Any help will be appreciated.

I have tried downgrading to app-scripts 0.0.46 and 0.0.47 , still no luck.

**Comment by yasar-salim** [comment]
use 
```
<preference name="loadUrlTimeoutValue" value="700000"/>
```
inside 
```
<platform name="android">
```
in the config.xml file

**Comment by zindelluib** [comment]
I also had a problem like @magnusmel. I observed that when I turn on first the Internet Connection and then run app , this message appears : "Application Error connection to the server was unsuccessful. File://android_asset/www/index.html". But when no connection and run the app, no error prompt appears.My app in is Ionic 1

**Comment by zindelluib** [comment]
Sir @yasar-salim  do you mean "inside" or "instead"?
use

<preference name="loadUrlTimeoutValue" value="700000"/>
inside <-------This

<platform name="android">
in the config.xml file

**Comment by yasar-salim** [comment]
@zindelluib  inside

**Comment by danbucholtz** [comment]
This does not seem like a problem with the build process but a problem with your app. Please make a post in our [support forums](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA) for help.

Thanks,
Dan

**Comment by GameAppsBD** [comment]
So I added manually the following tags in config.xml right at the beginning:

```
<allow-navigation href="*" />
<content src=“index.html” />
<content original-src=“index.html” />
```

it’s working.

**Comment by adrynov** [comment]
This opens your app to the whole world:

**<allow-navigation href="*" />**

Don't...
