### ISSUE TITLE
Missing sw-toolbox peer-dependency in 1.0.0

### ISSUE THREAD

**Issue by bvx89** [driftyco/ionic-app-scripts#626]
#### Short description of the problem:
When attempting to build, a missing file reference in the copy-config error is thrown. This is due to the missing sw-toolbox dependency that should be included as a peer dependency in package.json

#### What behavior are you expecting?
The sw-toolbox dependency to be included when installing ionic-app-scripts.

**Steps to reproduce:**
1. Run `npm i --save-dev @ionic/app-scripts@1.0.0` in project
2. Run `ionic serve`
3. Get error message.

**Which @ionic/app-scripts version are you using?**
1..0.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
```
watch failed: A watch configured to watch the following paths failed to start. It likely that a file 
            referenced does not exist: /home/lasse/Development/goformtest/src/assets/**/*, 
            /home/lasse/Development/goformtest/src/index.html, /home/lasse/Development/goformtest/src/manifest.json, 
            /home/lasse/Development/goformtest/src/service-worker.js, 
            /home/lasse/Development/goformtest/node_modules/ionicons/dist/fonts/**/*, 
            /home/lasse/Development/goformtest/node_modules/ionic-angular/fonts/**/*, 
            /home/lasse/Development/goformtest/node_modules/ionic-angular/polyfills/polyfills.js, 
            /home/lasse/Development/goformtest/node_modules/sw-toolbox/sw-toolbox.js 

```

**Comment by fiznool** [comment]
A quick fix to this is to run the following in your app:

```
npm install --save-dev sw-toolbox
```

**Comment by bvx89** [comment]
@fiznool Yes, I am aware. Just notifying about the problem.

**Comment by marcradziwill** [comment]
Doesn't work for me.
I still got this problem in my vagrant setup. I've read about some linux issues. Can anybody reproduce this or relate to that as well?

I've tried it with following versions of Ionic Script: 0.0.47, 0.0.48, 1.0.0

`Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.2
Node Version: v6.8.0
Xcode version: Not installed`

**Comment by danbucholtz** [comment]
Thanks all. I will update the changelog. I did not see this is testing on Mac OS or Windows, but we are adding `sw-toolbox` so we'll go ahead and make the change.

Thanks,
Dan
