### ISSUE TITLE
1.0.0 watch issue 

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic-app-scripts#627]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
ionic watch issue after upgrading to 1.0.0, Please check screenshot.

![image](https://cloud.githubusercontent.com/assets/5780117/21713373/b48777d4-d41f-11e6-95fa-87bd8a3d2859.png)

#### What behavior are you expecting?

**Steps to reproduce:**
1.updated from 0.0.48 to 1.0.0 
2.ionic serve
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
D:\Tushar\Projects\SafetyMobileApp>ionic info

Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by fiznool** [comment]
See #626

**Comment by jtushar53** [comment]
@fiznool thanks, closing this one now
