### ISSUE TITLE
Ionic 2 Application error 

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-app-scripts#630]
_From @magnusmel on January 6, 2017 5:19_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Ionic 2 starter template cutepuppypics was generated, However on running the 
`ionic run android `

The app does get built and installed on the mobile device. 

But on launching the app in the device, it throws an Application error.
This has started to appear quite recently. 
Any help will be appreciated.

BTW I am using nvm to manage my node installations. Could this be a factor ?
 
Same issue posted in more details on 
[](http://stackoverflow.com/questions/41440866/ionic2-application-error)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	openSUSE project Description:	openSUSE Leap 42.2 
Node Version: v6.9.2
```
insert the output from ionic info here
```

_Copied from original issue: driftyco/ionic#9895_

**Comment by brandyscarney** [comment]
@magnusmel Could you paste the output from the following commands please:

```
node -v
npm -v
ionic -v
```

**Comment by brandyscarney** [comment]
@magnusmel Can you update to the latest CLI:

```
npm uninstall -g ionic
npm install -g ionic
```

Then run `ionic info` and `npm -v` and paste the output again? Thanks :)

**Comment by magnusmel** [comment]
Did the npm uninstalll/install -g ionic.
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.0
Xcode version: Not installed

 npm -v
3.10.8

OK this solves my issues with the starter template, Thank you so much, brandy.

**Comment by brandyscarney** [comment]
Glad it's working for you now! :smile:
