### ISSUE TITLE
show blank about 10s after app splash screen disapear

### ISSUE THREAD

**Issue by wolfljj** [driftyco/ionic-app-scripts#638]
this issue isn't solved after 0.0.45 version.I create new ionic project and build  with 0.0.47 0.0.48 1.0.0,app will show blank about 10s after app splash screen disapear,then homepage shown.0.0.45 is ok.Is there nobody get this problem???

**Comment by arendjantetteroo** [comment]
Are you using --prod when viewing your project? Otherwise you are getting develop mode which is optimized for debugging but not for speed.

**Comment by yasar-salim** [comment]
use 
```
ionic build android --prod
```

**Comment by danbucholtz** [comment]
Yes, use `--prod` 🐱 

Thanks,
Dan
