### ISSUE TITLE
Can build/run/serve scripts respect env variables?

### ISSUE THREAD

**Issue by josh-m-sharpe** [driftyco/ionic-app-scripts#639]
I would like to have 'ionic [serve|emulate|run|build|etc]' all respect environment variables so that I can change how my app behaves accordingly.

I've seen a lot of posts that access the current runtime env by 'process.env.VAR_NAME' but it's unclear if that's supported inside ionic's webpack process.

Thanks!

**Comment by danbucholtz** [comment]
This is a bit of a gap in our process right now that we will resolve in the coming months. For now, please use webpack or rollup's plugin for environment variables. You may also need to add `node` typings to your Ionic project.

Thanks,
Dan

**Comment by josh-m-sharpe** [comment]
Hi @danbucholtz thanks for your reply - would you mind linking me to those things?  I'm not super familiar with the ecosystem yet.

**Comment by danbucholtz** [comment]
Lets track this here. Please weigh in with your thoughts.

https://github.com/driftyco/ionic-app-scripts/issues/762

Thanks,
Dan
