### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by yasar-salim** [driftyco/ionic-app-scripts#640]
#### My system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v4.4.6
Xcode version: Xcode 7.3.1 Build version 7D1014

 I use 
```
ionic build android
```

which results an apk android-debug.apk . i can install it in my android phone...

when i use 
```
ionic build android --release
```

results an apk android-release-unsigned.apk .. but i cant install this file in my phone..

when i was trying to install it shows error "app not installed"

**Comment by yasar-salim** [comment]
fix issue using ionic build android --prod

**Comment by XcyTheR101** [comment]
Why does --release not work though? I have run into the same issue, also removing --release fixed it for me.

**Comment by yasar-salim** [comment]
@XcyTheR101 release build need to be signed before installing...

**Comment by LindokuhleProHlubi** [comment]
What is the solution for this problem? i tried ionic build android --prod --release, still not working for me?

**Comment by lperezb** [comment]
Remove the release option and you're fine.

**Comment by Dak1411** [comment]
If you use --prod it will give you debug build
