### ISSUE TITLE
Ionic 2 --prod error  with angular (>= 2.3,2.4)

### ISSUE THREAD

**Issue by Devas9** [driftyco/ionic-app-scripts#641]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I try to use angular/* "2.3.x or 2.4.x
Anyway, when using ionic build, i.e. the ngc AOT compiler, the build breaks with

**Steps to reproduce:**
1.ionic-app-scripts build "--prod"

```
[14:35:45]  ionic-app-scripts 1.0.0 
[14:35:45]  build prod started ...
[14:35:45]  clean started ...
[14:35:45]  clean finished in 9 ms
[14:35:45]  copy started ...
[14:35:45]  ngc started ...
[14:35:49]  ionic-app-script task: "build" 
[14:35:49]  TypeError: compiler_cli_1.ReflectorHost is not a constructor 
TypeError: compiler_cli_1.ReflectorHost is not a constructor
    at new AotCompiler (E:\workbench\ticketBusiness\TicketPassenger\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:31:30)
    at ngcWorker (E:\workbench\ticketBusiness\TicketPassenger\node_modules\@ionic\app-scripts\dist\ngc.js:19:20)
    at Object.ngc (E:\workbench\ticketBusiness\TicketPassenger\node_modules\@ionic\app-scripts\dist\ngc.js:9:12)
    at buildProject (E:\workbench\ticketBusiness\TicketPassenger\node_modules\@ionic\app-scripts\dist\build.js:95:51)
    at E:\workbench\ticketBusiness\TicketPassenger\node_modules\@ionic\app-scripts\dist\build.js:43:16
```

**Which @ionic/app-scripts version are you using?**
  "@ionic/app-scripts": "1.0.0",

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
My package.json is：

  "dependencies": {
    "@angular/common": "2.4.2",
    "@angular/compiler": "2.4.2",
    "@angular/compiler-cli": "2.4.2",
    "@angular/core": "2.4.2",
    "@angular/forms": "2.4.2",
    "@angular/http": "2.4.2",
    "@angular/platform-browser": "2.4.2",
    "@angular/platform-browser-dynamic": "2.4.2",
    "@angular/platform-server": "2.4.2",
    "@angular/router": "3.4.2",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.0.0-rc.4",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "sw-toolbox": "3.4.0",
    "typescript": "2.0.9"
  },

**Comment by rolandjitsu** [comment]
As far as I know, Ionic is at `2.2.1`.

**Comment by YasirPanjsheri** [comment]
"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.0.0-rc.4",
    "ionic-native": "2.2.16",
    "ionic2-custom-icons": "^0.3.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  }

**Comment by danbucholtz** [comment]
This is a known issue. The `@angular/compiler-cli` had some breaking changes in it.

It'll be fixed in the coming weeks. We're working with Angular to identify ways we can mitigate breaking changes in the build process.

Thanks,
Dan

**Comment by Devas9** [comment]
Thanks, very glad to hear the news

**Comment by hotforfeature** [comment]
You can still use Angular 2.3/2.4 with Ionic, just the AoT compiler `--prod` flag will not work. Angular 2.3 adds support for proper inheritance, which was pretty important for my use case.

@danbucholtz I've been keeping an eye out for a while now for 2.3 support. Are there any branches or forks out there attempting to fix the changes in `@angular/compiler-cli`? I would gladly help test and develop to speed up the process.

**Comment by danbucholtz** [comment]
@hotforfeature,

It will hopefully be coming soon. Next couple weeks. We are going out to visit with Google next week so it will probably be a couple weeks.

Thanks,
Dan
