### ISSUE TITLE
How to overwrite inner scripts

### ISSUE THREAD

**Issue by aszmyd** [driftyco/ionic-app-scripts#642]
#### Short description of the problem:
I want to add `pre` action to some of ionic scripts to put my own logic in the middle.
Lets say i want to overwrite `copy` task. According to readme, i'm adding
```json
"scripts": {
    "ionic:serve": "ionic-app-scripts serve",
    "ionic:copy": "echo 'my copy action'"
}
``` 

When i run the script directly like `npm run ionic:copy` it's behaving correctly but when i run `ionic serve`, the `copy` task from my package.json is ignored and default one from ionic scripts is used. 

I've tried also this syntax:
```json
"scripts": {
    "ionic:serve": "ionic-app-scripts serve",
    "copy": "echo 'my copy action'"
}
``` 

But with no luck.

All i want to achieve here is to add `precopy` or `preionic:copy` task then so it'll do something before the copy task.

Is it possible to tell app-scripts to use task defined in project level package.json ?

**Comment by danbucholtz** [comment]
You can't. We probably won't support that.

Thanks,
Dan
