### ISSUE TITLE
`ionic build` always exits with `0`

### ISSUE THREAD

**Issue by eidng8** [driftyco/ionic-app-scripts#644]
Currently, all tslint errors are treated as (kind of) warnings. I reach this conclusion by the fact that the script exits with `0` despite all those tslint errors on screen.

This way, we can't catch these in CI, because of the exit code is `0`, and there's nearly no indication of such error. We have to do a regular express grep on the complete output to determine that.

There should be an option/setting to make the script return with not zero instead.

P.S. I think this applies beyond tslint. Other compilers has command line options to treat "warnings" as "error".

**Comment by eidng8** [comment]
It's seems that app-scripts exits with '0' even when `ngc` reports error

**Comment by samyakbrimma** [comment]
I am not able to set a git ```pre-commit``` hook ( I intend to use [husky](https://github.com/typicode/husky), btw) due to the same reason. The ```pre-commit``` hook succeeds all the time, which should not be the case.

**Comment by danbucholtz** [comment]
I cannot recreate this. npm bails for me.

Thanks,
Dan
