### ISSUE TITLE
rc5: slow startup time android 

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-app-scripts#645]
_From @doender on January 12, 2017 15:54_

My Ionic2 RC5 application is loading *very* slow (20-25s) on Android 4.4.2 (Samsung Galaxy S4), whereas earlier versions were way faster. iOS startup is very fast (2-3 seconds)

I reinstalled the Android platform and made a production build:
`ionic run android --prod --device`

ionic info:
```
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

What can I do to improve this?

_Copied from original issue: driftyco/ionic#9993_

**Comment by TdyP** [comment]
Any clue about this issue? I'm experiencing the same latency at startup. Splash screen, then white screen for about 8s before the app is fully loaded
Loading is very quick on any emulator (with Genymotion), but very slow on any real device.

Build was made with `ionic build android --release`

I'm using SQLite for data storage, if that may help.

I'm keen on investigating further on my side, how can I know what's going on during this white screen?

Thanks!  

Ionic info:
```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.3.0
Xcode version: Not installed
```

**Comment by demirk4n** [comment]
A similar issue was also reported for rc.4 and closed later on. Might be a regression issue.
https://github.com/driftyco/ionic-app-scripts/issues/596

**Comment by Chris1234567899** [comment]
Same experience here on Moto G2 with Android 6. Even a blank project needs 15-20s to start.
Updated from rc2 where it was rather quick to rc5 now and facing this issue...

Not sure if it is connected to this, but I faced also a timout issue "connection to server was unsuccessful (file:///android_asset/www/index.html) as described for example here: https://forum.ionicframework.com/t/application-error-the-connection-to-the-server-was-unsuccessful/67584

I could solve that by adding 
`<preference name="loadUrlTimeoutValue" value="700000" />`

So I think it might have something to do with the long startup time.

**Comment by mhartington** [comment]
Please make sure you are running the builds with the `--prod` flag that was introduced in app-scripts 0.0.47

https://github.com/driftyco/ionic-app-scripts/releases/tag/v0.0.47

**Comment by TdyP** [comment]
I did ran the build with `--prod` flag : `ionic build android --prod --release` but I still have the slow startup.

**Comment by mhartington** [comment]
it's a bit a of  vague issue. Have you done any debugging? What part is slow? What version of android are you targeting? What version of cordova-android is being run? 

I test on a old moto phone running 4.4, and with a prod build running the conference app, I have a startup time of around 2-3 second

**Comment by TdyP** [comment]
I don't know really know how to debug this part of the app as it's the Ionic core loading.
The app is opening, the splash screen is showing for a few seconds (2-3s), and then I have a white screen for 8s before the app actually shows up.

A `cordova -v' shows me `v6.4.0`.
I tried myself on a Android 6.0 (HTC One M8 and Huawai P9 Lite). Got some feedback from users experiencing the same issue, don't know aboit their device.

I'm not blaming the Ionic team, I'm really keen on investigating further but I don't really know where to dig. If you could just give some hints on how to get more informations about what's going on during this white screen, I'll try to find out the issue.

Thanks

**Comment by Kobzol** [comment]
@mhartington could you please post accurate time that you got on the Moto? I'm getting exactly 5 seconds with the conference app on 6.0 Sony Z3 Compact.

**Comment by uj** [comment]
Similar issue here on Android.  Even going to the homescreen (with hardware home button) and then going back to the app takes significantly longer on RC5 than it does on RC4.  The only difference is the RC4/RC5, no code changes.

**Comment by 64jcl** [comment]
Same issue here with RC5. After splash screen goes away I have 6-7 seconds of white screen before the first page comes up. Previously with RC3 it took perhaps 1-2 seconds after splash screen was gone.

Btw in my **app.component.ts** I have the following:

```
    this.platform.ready().then(() => {
      StatusBar.styleDefault();
      Splashscreen.hide();
    });
```

Does the code actually reach the **Splashscreen.hide();** when the splashscreen goes away or is it the option in **config.xml** that controls the time its showing?

`<preference name="SplashScreenDelay" value="3000" />`

**Comment by TdyP** [comment]
Managed to fix issue on my case.
I realized that, even with `--prod` flag, it was actually running a dev build:
```
$ ionic build android --prod
> open_score@ ionic:build /media/data/dev/openScore
> ionic-app-scripts build

[14:53:59]  ionic-app-scripts 1.0.0 
[14:53:59]  build **dev** started ... 
```

After some investigation, I found out that the `scripts` section of my `package.json` was not good. So I copied this from the conference app:
```
  "scripts": {
    "build": "ionic-app-scripts build",
    "clean": "ionic-app-scripts clean",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  }
```

Now the `--prod` makes its job and run a prod build. I then tested it on my device and the startup is now lightning fast! :)

**So, if you're facing this issue: start by making sure you're actually running a prod build when using `--prod` flag.**

**Comment by 64jcl** [comment]
Well mine is building prod it seems, however when I migrated to RC5 and app scripts 1.0.0 I remember being told that main.dev.ts and main.prod.ts was obsolete and that I should only have one main.ts.

My main.ts looks like this:

```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';
platformBrowserDynamic().bootstrapModule(AppModule);
```

I assume that is correct? At least that is also what the ionic start test app also contains now. So I would guess that what those two ts files did before is now happening "behind the scenes" depending on build? Kinda hard to know exactly whey these platform changes happen and how to handle project upgrades to newer versions of everything. Anyone got a good source/blog for this info?

**Comment by mhartington** [comment]
Yes, the main.ts for production builds will be generated on the fly during production builds
A good source of info, is the app-scripts Changelog file, which we update every time there is a new release, and make notes of any breaking changes

**Comment by Kobzol** [comment]
@TdyP could you please measure and post the time it takes to start your app? (from clicking the icon to seeing the loaded UI of your app)

**Comment by TdyP** [comment]
It takes about 5s overall. Was more about 13s before

**Comment by Kobzol** [comment]
I'm glad to hear that it improved for you, yet 5 seconds is still eternity for an app launch :-( I hope it will improve in time.

**Comment by mhartington** [comment]
yes, we do plan on improving this. Making things load lazily, and removing excess code that is not used in an app.

**Comment by coolman7** [comment]
I have exactly same problem with 2.0.0 final version. I'm running following command to build:
`ionic build android --prod`

I used to have this as `main.ts`
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';
platformBrowserDynamic().bootstrapModule(AppModule);
```
I added modified as these:
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';
import { enableProdMode } from '@angular/core';
enableProdMode();
platformBrowserDynamic().bootstrapModule(AppModule);
```
I also have these lines at `package.json` file:
```
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
```
I still have 15-20 sec startup time and this messages at console log:
```
Native: deviceready did not fire within 5000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.
main.js:6097 DEVICE READY FIRED AFTER 8108 ms
```

What can I do more?

Thanks

**Comment by coolman7** [comment]
I think an app using cordova may not open less than 5 seconds. If an app requires 2-3 seconds of opening time, native approach might be a better solution.

**Comment by padmini-grmtech** [comment]
native approach meaning? can u explain me further please.

**Comment by coolman7** [comment]
I mean java, objective c, or any Project not using cordova such as react native.

**Comment by padmini-grmtech** [comment]
ok.You are saying that app using cordova cant be loaded less than seconds in latest versions of android.

**Comment by coolman7** [comment]
Correction: I tested with empty project with cordova with no plugins. It starts in 1 seconds. I added several plugins to cordova project but don't use these plugins. I starts in 2 seconds. So ionic or plugins should increase startup time. On the other hand I started another project with react native. it starts much faster than ionic 2.

**Comment by padmini-grmtech** [comment]
u mean my plugins are making my app slow down...

**Comment by coolman7** [comment]
blank ionic 2 project can take about 5 seconds to startup. additional plugins may increase this time.

**Comment by padmini-grmtech** [comment]
ok. once i installed the app,then i close it.When i reopen still the app is taking same time 5sec.is that correct,because it is installed it has to open in no seconds.Am i wrong here?

**Comment by coolman7** [comment]
correct

**Comment by padmini-grmtech** [comment]
what should i do for reopen app in milli seconds

**Comment by coolman7** [comment]
don't use ionic 2.

**Comment by MichaelHuy** [comment]
On android device, first time loading is too long, around 7s. Tested on my Mobistar and tablet.
Hope that we can improve it to around 3s.

**Comment by touqeeraslam** [comment]
I just created a  helloWorld release App on ionic2 using cordova 6 but its startup time is slow 5 secs and on my required app this is 8-9 seconds how can i reduce please guide.

**Comment by IgorGanapolsky** [comment]
Any solution to this?  My app uses Ionic, and the rendering of the Activity elements takes 5 seconds.
