### ISSUE TITLE
Suggestion: 'ionic compile' for compiling to www folder only

### ISSUE THREAD

**Issue by fiznool** [driftyco/ionic-app-scripts#648]
It would be really useful to have a command such as `ionic compile [--prod]`. This would execute the build process, up to the part where cordova kicks in - i.e., compile the app to the `www` folder.

This would be very useful in conjunction with `ionic upload`, which AFAICT publishes everything in the `www` folder to the Ionic cloud.

For example:

```
ionic compile && ionic upload
```

At the moment I have to use `ionic build android --prod && ionic upload` which necessitates that I have the Android SDK setup, etc.

**Comment by rapropos** [comment]
Does `npm run ionic:build` do what you want? That's what I use before dockerizing nginx to serve Ionic apps to browsers.

**Comment by danbucholtz** [comment]
`npm run ionic:build --aot` or `npm run ionic:build --prod` for a minified, distribution.

Thanks,
Dan
