### ISSUE TITLE
Upgrade tslint to v5

### ISSUE THREAD

**Issue by rolandjitsu** [driftyco/ionic-app-scripts#649]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
It would be nice to have tslint upgraded to v4. Because right now, it does not complain if I use that version, but `ionic-app-scripts lint` does nothing, just exits.

#### What behavior are you expecting?
If I use v4 it should still work and log errors. Additionally it should exit with code `1` if there was an error.

**Steps to reproduce:**
1. Install the conf app;
2. Add `"tslint": "^4.3.1"` to `package.json` dev deps;
3. Run `ionic-app-scripts lint`.

**Which @ionic/app-scripts version are you using?**
`1.0.0`

**Comment by wbhob** [comment]
The conference app is already linted, so tslint shouldn't have any errors.

**Comment by rolandjitsu** [comment]
Yes, but it should throw errors if I have any in my app. And I intentionally made some mistakes to trigger some errors.

**Comment by eampiart** [comment]
This would be nice as there are some rules which have apparently changed (e.g. arrow-parens) and so when linting is run manually, everything passes, but when ionic-app-scripts runs linting, there are issues (which should not be there).

**Comment by huerlisi** [comment]
You can now trigger a non-zero exit code when linting in versino `1.0.1`: b3bb906

**Comment by danbucholtz** [comment]
```
Update to TSLint 4.x. Do this when Ionic/Angular support TypeScript 2.1.

Thanks,
Dan
```

**Comment by rolandjitsu** [comment]
@danbucholtz does this mean that we have to wait until Ionic 2 upgrades to Angular 4+? Because they do not plan to provide support for TS 2.1+ in Angular 2.x as far as I can tell.

**Comment by wbhob** [comment]
Angular 4 is coming out in early march, as is Ionic 3, so at that time it will work with the latests deps.

Wilson Hobbs
CEO/Founder/Developer at Canal
11th Grade at The Lovett School

Personal Information
E-mail: wilsonhobbs1@gmail.com
Cell: (404) 719-3252
Website: www.wilsonhobbs.com (https://www.wilsonhobbs.com)
Twitter/Instagram/Facebook: @wbhob

Canal Information
E-mail: wilson@getcanal.com
Web: www.getcanal.com (https://www.getcanal.com/)

Twitter/Instagram/Facebook: @getcanal

**Comment by danbucholtz** [comment]
@rolandjitsu,

I looked into it and we'll probably just wait for TS Lint 4. I tried doing it now but they have some Type Definitions in there that require TS 2.1, which we can't use yet until Angular supports it. So yes, most likely when V4 ships.

Thanks,
Dan

**Comment by rolandjitsu** [comment]
@danbucholtz now that Ionic is at Angular `v4`, are there any plans to upgrade? I guess it hasn't been done as I experienced some strange behaviour as I reported in https://github.com/driftyco/ionic-app-scripts/issues/886.

**Comment by danbucholtz** [comment]
It is not a very high priority item. We'd take a well-tested PR.

Thanks,
Dan

**Comment by JustinPierce** [comment]
May as well go for TSLint 5, while you're in there. ;)

**Comment by jgw96** [comment]
Closing this issue as the above PR got merged. Thanks @rolandjitsu
