### ISSUE TITLE
IONIC_ENV is not set properly when running the build through the lib API

### ISSUE THREAD

**Issue by rolandjitsu** [driftyco/ionic-app-scripts#653]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

I made a simple script to run a build of the app, but it seems that `IONIC_ENV` is not set accordingly.

I use the script pasted below as such:
```js
// make_a_package.js
const {buildApp} = require('./build_app.js');

buildApp()
    .subscribe(() => {
        // do something else after the app is build
    });
```

Even though I send `{isProd: true}` with the context and I can see that the context is properly created, `IONIC_ENV` is not exported with the proper value.

#### What behavior are you expecting?

`IONIC_ENV` should be set.

**Steps to reproduce:**
1. Clone the conf. app;
2. Add rxjs as a dep.
3. Add the two scripts in this issue description;
4. Run `node ./make_a_package.js`.

```js
// build_app.js
const {isMaster} = require('cluster');
const {clean, build, generateContext} = require('@ionic/app-scripts');
const {Observable} = require('rxjs');


/**
 * Clean and build the app.
 * NOTE: This function will clean and build the app (in that order) using @ionic/app-scripts.
 * @param {BuildContext} context - The context of this build.
 * @returns {Observable} A stream that emits when it has completed the built.
 */
function buildApp(context = {
	isProd: true,
	runAot: true,
	runMinifyJs: true,
	runMinifyCss: true,
	optimizeJs: true
}) {
	const ctx = generateContext(null);
	Object.assign(ctx, context);
	return Observable.fromPromise(clean(ctx))
		.mergeMap(() => Observable.fromPromise(build(ctx)));
}


module.exports = {
	buildApp
};


if (isMaster) {
	process.on('message', (ctx) => {
		buildApp(ctx)
			.subscribe(() => {
				process.send(null);
			}, (err) => {
				process.send(err);
			});
	});
}
```

**Which @ionic/app-scripts version are you using?**
**1.0.0**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
I think this should be resolved.

Thanks,
Dan
