### ISSUE TITLE
The usage of parameter --prod ？

### ISSUE THREAD

**Issue by fenghonghui89** [driftyco/ionic-app-scripts#658]
Dear All：
I am a chinese ios develop.
I want to konw the usage of parameter --prod in ionic build ios script.
It is that --prod can advance the app boot speed？

I know I should ask this question to the ionic forum, but I don't know why my account can not login..so sorry
Thank you to tell me.

**Comment by alan-agius4** [comment]
The `--prod` command forces the build to be AOT which is Angular Ahead-of-time compilation. 

While it does speed up boot speed and even the site speed in general. It is not recommended to use during Development as it takes longer to compile.

**Comment by danbucholtz** [comment]
`--prod` is a build that uses `AoT` compilation and `minification`. It also runs various optimizations on the JS code.

Thanks,
Dan
