### ISSUE TITLE
Ionic2 RC.0 third party scss libraries not found after live compilation

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#66]
_From @peterpeterparker on October 2, 2016 9:33_

Hi,

I added some third party scss libraries in my application.

To accomplish that:
- "npm install" 
- override sass.config.js to include these scripts.
- add "@include" in my app.component.scss

Works fine. 

I only face one problem. When I'm running the server ("ionic serve"), if I make any changes to my scss files, the server gonna recompile the sass files but it isn't able, seems so, to find these third party scss files anymore. For example, the recompilation results could be:

    [11:26:15]  Sass Error: line: 85, column: 1
    File to import not found or unreadable: _bourbon.scss
    Parent style sheet: /Users/me/Documents/projects/myproject/src/app/app.component.scss

Therefore, each time I make a scss change I've to start my server again, which isn't really convenient.

Could that be fixed?

_Copied from original issue: driftyco/ionic#8401_

**Comment by adamdbradley** [comment]
Going to group this in with #42 

Thanks
