### ISSUE TITLE
RC5 - error "build dev failed: Cannot set property 'fileSystem' of null"

### ISSUE THREAD

**Issue by Tusharbalar** [driftyco/ionic-app-scripts#660]
Hi,
I have this error:
"build dev failed: Cannot set property 'fileSystem' of null "

when I use "ionic serve"

but if I run "ionic build browser", everything is ok.

I've removed all my node_modules and do a fresh "npm install".
I've deleted the ".tmp" & "www" dir too, but the error still displaying.

Please, can you help me? Thanks you,
best regards

This is my ionic info:

```
Your system information:

- Cordova CLI: 6.4.0 
- Ionic Framework Version: 2.0.0-rc.5
- Ionic CLI Version: 2.2.1
- Ionic App Lib Version: 2.2.0
- Ionic App Scripts Version: 0.0.45
- ios-deploy version: Not installed
- ios-sim version: Not installed
- OS: Linux 4.6
- Node Version: v4.6.0
- Xcode version: Not installed

```

and my package.json :

```
"dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "angular-calendar": "^0.4.0",
    "angular2-moment": "^1.0.0-beta.rc.1",
    "ionic-angular": "2.0.0-rc.5",
    "ionic-native": "2.2.3",
    "ionic2-rating": "0.0.10",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "underscore": "^1.8.3",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.45",
    "typescript": "2.0.6"
  },
```

**Comment by Quocnamit** [comment]
Hi,
I have this error after **run NPM INSTALL without any update**
**"build dev failed: Cannot set property 'fileSystem' of null "**

This is my ionic info
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.42
OS: Windows 7 SP1
Node Version: v6.5.0

and my package.json :
"dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "angular2-moment": "1.0.0-beta.6",
    "angular2-toaster": "1.0.2",
    "intl": "1.2.5",
    "ionic-angular": "2.0.0-rc.2",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "lodash": "4.16.4",
    "moment": "2.15.1",
    "nativescript-ng2-translate": "1.2.0",
    "ng2-pdf-viewer": "0.0.15",
    "ng2-translate": "4.0.0",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.42",
    "@types/core-js": "0.9.34",
    "@types/lodash": "4.14.37",
    "dotenv": "^2.0.0",
    "typescript": "2.0.6"
  },

**Comment by markholland** [comment]
Gulp version: CLI version 3.9.0
Ionic Framework Version: 2.0.0-rc.2
Ionic App Scripts Version: 0.0.46
OS: macOS Sierra
Node Version: v4.0.5

"dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.2",
    "ionic-native": "2.2.6",
    "ionicons": "3.0.0",
    "lodash": "4.17.0",
    "ng2-translate": "4.0.0",
    "npm": "3.10.9",
    "rxjs": "5.0.0-rc.2",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.46",
    "@types/chai": "^3.4.34",
    "@types/lodash": "^4.14.43",
    "cordova": "6.4.0",
    "ionic": "2.1.8",
    "typescript": "2.0.9"
  }

**Comment by lleevvyy** [comment]
@markholland  @Quocnamit @Tusharbalar  Guys, just switch to @ionic/app-scripts@1.0.0 - this will solve the problem :-)

**Comment by markholland** [comment]
> Guys, just switch to @ionic/app-scripts@1.0.0 - this will solve the problem :-)
"just", we stuck on 0.0.46 because of breaking changes, I'll try to resolve them again I guess..

**Comment by carstenbaumhoegger** [comment]
I also get the error after deleting my node_modules without changing anything at my package.json

Here's my Ionic Info

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.43
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

```
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "angular2-apollo": "^0.7.0",
    "apollo-client": "^0.5.6",
    "graphql-tag": "^0.1.17",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.43",
    "@types/chai": "^3.4.34",
    "@types/es6-shim": "^0.31.32",
    "typed-graphql": "^1.0.2",
    "typescript": "2.0.6",
    "typings": "^2.0.0"
  }
```

**Comment by dilipchandima** [comment]
Guys, Same issue here I deleted node_modules and reinstall node_modules by npm install this is my package.json

 `{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build",
    "test": "ng test --code-coverage",
    "e2e": "protractor",
    "postinstall": "webdriver-manager update"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.2",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "node-uuid": "^1.4.7",
    "pouchdb": "^6.1.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "@types/jasmine": "2.5.37",
    "@types/node": "^6.0.52",
    "angular-cli": "1.0.0-beta.20-1",
    "browserify": "13.0.0",
    "browserify-istanbul": "2.0.0",
    "codelyzer": "~0.0.26",
    "isparta": "4.0.0",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.7.0",
    "karma": "1.3.0",
    "karma-browserify": "5.0.5",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.0.2",
    "karma-mocha-reporter": "2.2.0",
    "karma-remap-istanbul": "0.2.1",
    "run-sequence": "1.1.5",
    "tsify": "2.0.2",
    "typescript": "2.0.6",
    "watchify": "^3.7.0"
  },
  "description": "mCrew: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": []
}`

and I got following error

> [09:52:28]  ionic-app-scripts 0.0.45 
[09:52:28]  watch started ... 
[09:52:28]  build dev started ... 
[09:52:28]  clean started ... 
[09:52:28]  clean finished in 6 ms 
[09:52:28]  copy started ... 
[09:52:28]  transpile started ... 
[09:52:32]  transpile finished in 3.94 s 
[09:52:32]  webpack started ... 
[09:52:32]  build dev failed: Cannot set property 'fileSystem' of null 
[09:52:32]  copy finished in 4.25 s 
[09:52:32]  watch ready in 4.33 s 
Proxy added: /callback => http://10.16.32.83:9097/callback
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*, !www/**/*.map
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit


after @lleevvyy 's comment I change @ionic/app-scripts version and delete node-modules and re install it now I got following issue

`
[09:59:40]  ionic-app-scripts 1.0.0 
[09:59:40]  watch started ... 
[09:59:40]  build dev started ... 
[09:59:40]  watch failed: /home/dileepa/projects/test/src/app/main.ts was not found. The 
            "main.dev.ts" and "main.prod.ts" files have been deprecated. Please create a new file "main.ts" containing 
            the content of "main.dev.ts", and then delete the deprecated files. For more information, please see the 
            default Ionic project main.ts file here: 
            https://github.com/driftyco/ionic2-app-base/tree/master/src/app/main.ts 
[09:59:40]  ionic-app-script task: "watch" 
[09:59:40]  Error: /home/dileepa/projects/test/src/app/main.ts was not found. The 
            "main.dev.ts" and "main.prod.ts" files have been deprecated. Please create a new file "main.ts" containing 
            the content of "main.dev.ts", and then delete the deprecated files. For more information, please see the 
            default Ionic project main.ts file here: 
            https://github.com/driftyco/ionic2-app-base/tree/master/src/app/main.ts 

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/home/dileepa/programs/node-v6.9.1/bin/node" "/home/dileepa/programs/node-v6.9.1/bin/npm" "run" "watch"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dileepa/projects/test/npm-debug.log
`

**Comment by dilipchandima** [comment]
@lleevvyy It's not working after change the @ionic/app-scripts@1.0.0  I got following error

```
[11:00:15]  watch failed: A watch configured to watch the following paths failed to start. It likely that a file 
            referenced does not exist: /home/dileepa/projects/test/src/assets/**/*, 
            /home/dileepa/projects/test/src/index.html, 
            /home/dileepa/projects/test/src/manifest.json, 
            /home/dileepa/projects/test/src/service-worker.js, 
            /home/dileepa/projects/test/node_modules/ionicons/dist/fonts/**/*, 
            /home/dileepa/projects/test/node_modules/ionic-angular/fonts/**/*, 
            /home/dileepa/projects/test/node_modules/ionic-angular/polyfills/polyfills.js, 
            /home/dileepa/projects/test/node_modules/sw-toolbox/sw-toolbox.js 
[11:00:15]  ionic-app-script task: "watch" 
[11:00:15]  Error: A watch configured to watch the following paths failed to start. It likely that a file referenced 
            does not exist: /home/dileepa/projects/test/src/assets/**/*, 
            /home/dileepa/projects/test/src/index.html, 
            /home/dileepa/projects/test/src/manifest.json, 
            /home/dileepa/projects/test/src/service-worker.js, 
            /home/dileepa/projects/test/node_modules/ionicons/dist/fonts/**/*, 
            /home/dileepa/projects/test/node_modules/ionic-angular/fonts/**/*, 
            /home/dileepa/projects/test/node_modules/ionic-angular/polyfills/polyfills.js, 
            /home/dileepa/projects/test/node_modules/sw-toolbox/sw-toolbox.js 

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/home/dileepa/programs/node-v6.9.1/bin/node" "/home/dileepa/programs/node-v6.9.1/bin/npm" "run" "watch"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dileepa/projects/test/npm-debug.log
```

**Comment by markholland** [comment]
@dilipchandima Did you add the sw-toolbox dependency?

**Comment by carstenbaumhoegger** [comment]
I also had this error with RC3 and app-scripts `0.0.43` and it was solved by updating to RC5 with app-scripts `1.0.0`

**Comment by Tusharbalar** [comment]
@dilipchandima @Quocnamit you need to install **sw-toolbox.**

- npm install sw-toolbox

please read this: [2.0.0-rc.5 CHANGELOG](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md)

**Comment by ebartan** [comment]
its work it to me thx guys

**Comment by Quocnamit** [comment]
Hi,

My old version is 0.0.42. Now It's 1.0.0 :+1:  . So that I need to update some file name, and update my custom configuration (sass, copy, webpack,...)

Now it works for me

Thanks guys

**Comment by mandarincreative** [comment]
This worked for me, too!  Thanks guys.

**Comment by danbucholtz** [comment]
It seems that this is user error and not app-scripts error so I'm going to close this thread.

Thanks,
Dan

**Comment by almgwary** [comment]
still not working after update

**Comment by amrayoub** [comment]
same problem with final version

**Comment by danbucholtz** [comment]
@almgwary, @amrayoub,

What version of `@ionic/app-scripts` are you running? I haven't seen this before. What OS? Can you `rm -rf node_modules` and do a fresh install? It should be `@ionic/app-scripts@1.0.0`

Thanks,
Dan

**Comment by amrayoub** [comment]
$ ionic serve

Running 'serve:before' npm script before serve

> neighbors@ watch D:\ionic 2\ionic2-neighbors
> ionic-app-scripts watch

[09:40:05]  ionic-app-scripts 1.0.0
[09:40:05]  watch started ...
[09:40:05]  build dev started ...
[09:40:05]  clean started ...
[09:40:05]  clean finished in less than 1 ms
[09:40:05]  copy started ...
[09:40:05]  transpile started ...
[09:40:11]  transpile finished in 5.18 s
[09:40:11]  webpack started ...
[09:40:11]  copy finished in 5.45 s
[09:40:22]  webpack finished in 11.62 s
[09:40:22]  sass started ...
[09:40:24]  sass finished in 1.95 s
[09:40:24]  build dev finished in 19.02 s
[09:40:27]  watch failed: A watch configured to watch the following paths failed to start. It likely that a file
            referenced does not exist: D:\ionic 2\ionic2-neighbors\src\assets\**\*, D:\ionic
            2\ionic2-neighbors\src\index.html, D:\ionic 2\ionic2-neighbors\src\manifest.json, D:\ionic
            2\ionic2-neighbors\src\service-worker.js, D:\ionic 2\ionic2-neighbors\node_modules\ionicons\dist\fonts\**\*,
            D:\ionic 2\ionic2-neighbors\node_modules\ionic-angular\fonts\**\*, D:\ionic
            2\ionic2-neighbors\node_modules\ionic-angular\polyfills\polyfills.js, D:\ionic
            2\ionic2-neighbors\node_modules\sw-toolbox\sw-toolbox.js
[09:40:27]  ionic-app-script task: "watch"
[09:40:27]  Error: A watch configured to watch the following paths failed to start. It likely that a file referenced
            does not exist: D:\ionic 2\ionic2-neighbors\src\assets\**\*, D:\ionic 2\ionic2-neighbors\src\index.html,
            D:\ionic 2\ionic2-neighbors\src\manifest.json, D:\ionic 2\ionic2-neighbors\src\service-worker.js, D:\ionic
            2\ionic2-neighbors\node_modules\ionicons\dist\fonts\**\*, D:\ionic
            2\ionic2-neighbors\node_modules\ionic-angular\fonts\**\*, D:\ionic
            2\ionic2-neighbors\node_modules\ionic-angular\polyfills\polyfills.js, D:\ionic
            2\ionic2-neighbors\node_modules\sw-toolbox\sw-toolbox.js

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! neighbors@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the neighbors@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the neighbors package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs neighbors
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls neighbors
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ionic 2\ionic2-neighbors\npm-debug.log

**Comment by amrayoub** [comment]
@danbucholtz 
npm -v
3.10.10
node -v
v6.9.3
ionic -v
2.2.1
cordova -v
6.5.0

**Comment by JayaniSumudini** [comment]
I have the same error..I followed these steps
Run this command on root directory of project: npm install @ionic/app-scripts@latest --save-dev
Rename .\src\app\main.dev.ts with .src\app\main.ts
npm rebuild node-sass

but still occur same error..what's the wrong?

**Comment by JayaniSumudini** [comment]
@amrayoub, @dilipchandima,
Hi,
My old ionic/app-scripts version is 0.0.45. Now It's 1.0.0.
Now it works for me...

I followed these steps

1) npm uninstall -g ionic
2) npm install -g ionic
3)Update my package.json

"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.0.0-rc.5",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26",
    "sw-toolbox": "3.4.0"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "typescript": "2.0.9"
  }

4) npm install
5) ionic serve

**Comment by gtzinos** [comment]
Hello guys,
Same project. Just follow these instructions:

1) npm uninstall -g ionic
2) npm install -g ionic
3) Open package.json
4) Check all of them:

"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.0.0-rc.5",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26",
    "sw-toolbox": "3.4.0"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "typescript": "2.0.9"
  }

**Comment by webberig** [comment]
ionic-app-scripts depends on webpack version `^2.1.0-beta.25` and currently installs `2.1.1` which seems to have a breaking change.

In case you can't update ionic-app-scripts yet, you can force the older version of webpack by running following command:

    npm install webpack@2.1.0-beta.25 --save

Updating ionic-app-scripts is probably the better solution, consider this as a temporary workaround...

**Comment by piyushdevapp** [comment]
everything done  JayaniSumudini and other help.....

not working error showing...

[14:16:55]  ionic-app-scripts 0.0.47
[14:16:55]  watch started ...
[14:16:55]  build dev started ...
[14:16:55]  clean started ...
[14:16:55]  clean finished in 2 ms
[14:16:55]  copy started ...
[14:16:55]  transpile started ...
[14:16:58]  transpile finished in 2.
[14:16:58]  webpack started ...
[14:16:58]  build dev failed: Cannot
[14:16:58]  dev server running: http
[14:16:58]  build dev failed: Cannot set property 'fileSystem' of null
[14:16:58]  dev server running: http://localhost:8100/

[14:16:58]  watch ready in 2.42 s
[14:16:58]  copy finished in 2.43 s

**Comment by chayankiit** [comment]
how to fix build dev failed: Cannot set property 'fileSystem' of null

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.19
Node Version: v7.7.4
Xcode version: Not installed

**Comment by danbucholtz** [comment]
@chayankiit,

Update to `@ionic/app-scripts@latest`.

Thanks,
Dan

**Comment by chayankiit** [comment]
Thank for reply @danbucholtz ...its works.
