### ISSUE TITLE
Stylelint integration

### ISSUE THREAD

**Issue by adascal** [driftyco/ionic-app-scripts#661]
Any plan to add stylelint integration for linting `.scss` files?
Ref: https://github.com/stylelint/stylelint

**Comment by huerlisi** [comment]
Related to #720 

I was thinking about integrating `sass-lint`, but `stylelint` is also a valid candidate.

@adascal could you maybe close this issue in favor of #720 as that contains more info already?

**Comment by danbucholtz** [comment]
We're probably not going to do this unless someone submits a good PR.

Thanks,
Dan
