### ISSUE TITLE
No big size difference between dev and prod build

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic-app-scripts#662]
#### Short description of the problem:
There is no big difference between dev and prod build.
Is this correct?

#### What behavior are you expecting?
A way smaller apk size on a prod build. About 30M, is this normal? Is it related to the crosswalk plugin used by conference-app?

**Steps to reproduce:**
1. dir change in actual (01/18/17) ionic-conference-app
2. ionic build android
3. ionic build android --prod

apk size of dev build: **30.509.197** bytes
apk size of prod build: **29.496.689** bytes

**Which @ionic/app-scripts version are you using?**
```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5-201701112208
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by mpaland** [comment]
Seems to be Crosswalk, which adds about 25MB to the apk.
So, the reduction between prod and dev is about 1M, is this realistic?

**Comment by mhartington** [comment]
Closing as this is not an issue but a question.

Yes, crosswalk does have a big footprint.
As for the additional file size, there is still work being done to optimize this. 
We're addressing this by making ionic tree-shakable and reduce the overall bundle size.
