### ISSUE TITLE
upgrade node-sass dependency

### ISSUE THREAD

**Issue by tycho01** [driftyco/ionic-app-scripts#663]
Windows, Node 7.x, `ionic serve`:
```
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (51)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.10.1
```
Checking there, it does seem Node 7 on Windows only got support from v3.11.

**Comment by yasar-salim** [comment]
use 
```
npm rebuild node-sass
```

**Comment by CleverWhiteWolf** [comment]
+1
The similar issue with node-sass in Alpine Linux. node-sass supports Alpine since version 4.1.0.
Version 4.5.0 is available in repositories right now.

**Comment by danbucholtz** [comment]
This is done in 1.x.

Thanks,
Dan
