### ISSUE TITLE
Overwrite variableSassFiles config

### ISSUE THREAD

**Issue by QiaoyuanMaxDeng** [driftyco/ionic-app-scripts#665]
#### Short description of the problem:
Does  not have a way to overwrite `variableSassFiles` in ionic config

#### What behavior are you expecting?
Have ability to overwrite/update current `variableSassFiles` in config file through package.json/process.env

**Steps to reproduce:**
1. moved `/src/app/variables.scss` file to another location
2. run `$ ionic serve`
3. get Error:
```
sass: stdin, line: 1
 File to import not found or unreadable: .../src/app/core/variables.scss Parent style sheet: stdin
sass failed
```

**Which @ionic/app-scripts version are you using?**
v1.0.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
suggest to add configs as other variables, such as `sourceFileName` in https://github.com/driftyco/ionic-app-scripts/blob/master/config/cleancss.config.js#L8

**Comment by danbucholtz** [comment]
Yes, you should be able to configure all paths by customizing the `scss.config.js` file.

https://github.com/driftyco/ionic-app-scripts#custom-configuration

Thanks,
Dan
