### ISSUE TITLE
Build is breaking component names in navPush 

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-app-scripts#668]
#### Short description of the problem:

Cannot use component names directly in a template.  

#### What behavior are you expecting?

Should be able to place components by name in `navPush` but [`getComponent`](https://github.com/driftyco/ionic/blob/master/src/navigation/nav-util.ts#L10) returns `null` in `nav-util`.

**Steps to reproduce:**
1. Add a button with `navPush` to another page:
      ```
      <button ion-button navPush="TabsPage">
        Continue
      </button>
      ```
2. Click on the button after running serve
3. See `nav-util.js:23 invalid page component: TabsPage`

*Note*: If you set it in the component to a property it will work, code:

```
export class TutorialPage {
  tabsPage = TabsPage;
}
```

then on the button:

```
<button ion-button [navPush]="tabsPage">
  Continue
</button>
```

**Which @ionic/app-scripts version are you using?** 1.0.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Can be reproduced in the [`nav/basic`](https://github.com/driftyco/ionic/blob/master/src/components/nav/test/basic/app.module.ts#L65) and [`tabs/advanced`](https://github.com/driftyco/ionic/blob/master/src/components/tabs/test/advanced/signIn.html#L22) e2e tests running a prod build.

When I ran the prod build with the following it worked fine:
```
ionic-app-scripts build --aot --minifyCss --optimizeJs
```

**Comment by brandyscarney** [comment]
If you need to test e2e this commit should be undone: https://github.com/driftyco/ionic/commit/ce7afd0327d1e5a6d6c7aed1d0825a75992265b3

**Comment by danbucholtz** [comment]
I'll reopen if needed.

Thanks,
Dan
