### ISSUE TITLE
Release build accessible from chrome://inspect

### ISSUE THREAD

**Issue by moldstadt** [driftyco/ionic-app-scripts#672]
#### Short description of the problem:
Release build of my Android app is accessible from chrome://inspect.  I am able to see console logs and HTTPS network traffic.

#### What behavior are you expecting?
Release build should not be accessible.

**Steps to reproduce:**
1. ionic start -v2 testblank blank
2. ionic plugin remove cordova-plugin-console
3. add some console logs and HTTPS network requests.
4. ionic build android --release --prod -- --keystore="..." --alias=...
5. install on Genymotion and inspect with Chrome

**Which @ionic/app-scripts version are you using?**
1.0.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
May be related to #671.

```
$ ionic info
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Your system information:

 You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.9.2
Xcode version: Not installed


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

$ node -v
v6.9.2

$ npm -v              **this takes about 30s**
4.0.5

$ cordova -v
You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

$ ionic platform                   **this also takes about 30s***
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

You have been opted out of telemetry. To change this, run: cordova telemetry on.

Installed platforms:
  android 6.1.0
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  webos ~3.7.0
  windows ~4.4.0
  wp8 ~3.8.2 (deprecated)

```

**Comment by danbucholtz** [comment]
As I mentioned in the other issue, it's very likely you're not doing a true `prod` build.

Thanks,
Dan

**Comment by moldstadt** [comment]
@danbucholtz, here is the output of my build:
> ionic-app-scripts build "--release" "--prod" "--" "--keystore=***" "--alias=***"

[09:12:24]  ionic-app-scripts 1.0.0
[09:12:24]  build prod started ...
[09:12:24]  clean started ...
[09:12:24]  clean finished in 47 ms
[09:12:24]  copy started ...
[09:12:24]  ngc started ...
[09:12:43]  ngc finished in 19.11 s
[09:12:43]  webpack started ...
[09:12:45]  copy finished in 21.30 s
[09:12:51]  webpack finished in 7.82 s
[09:12:51]  uglifyjs started ...
[09:12:51]  sass started ...
[09:12:55]  sass finished in 3.92 s
[09:12:55]  cleancss started ...
[09:12:57]  cleancss finished in 2.28 s
[09:13:03]  uglifyjs finished in 12.34 s
[09:13:03]  build prod finished in 39.41 s

It looks like it is at least thinks it is building prod.  Is there any other way I can confirm this?

**Comment by moldstadt** [comment]
@danbucholtz 
Like with the other issue I logged (#671), I am also able to debug the release build of the blank app using chrome://inspect, using the signed release apk that I built and ran in Genymotion **on my Mac**.

**Comment by moldstadt** [comment]
@danbucholtz This is still an issue using latest app-scripts nightly build. Please reopen.

**Comment by moldstadt** [comment]
@danbucholtz can you please reopen and have a look at this. This seems like a serious security bug. Problem wasn't resolved with changes that fixed #671

**Comment by danbucholtz** [comment]
I'm sorry, perhaps I'm not understanding this correctly. Why would you expect not to be able to see that data?

**Comment by moldstadt** [comment]
Probably because I am new to this kind of development :-) If someone
downloads my app and installs it on the simulator, they will then be able
to see my private api between the app and the server. This could open up
the server to misuse or abuse.

**Comment by jcesarmobile** [comment]
This is because of Genymotion, they do something to the apk when you install it and becomes debuggable.
