### ISSUE TITLE
scss css url path not updated on minification to reflect nesting

### ISSUE THREAD

**Issue by vinpez** [driftyco/ionic-app-scripts#674]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
**previous card:** https://github.com/driftyco/ionic/issues/10103

When the scss is minified, relative paths to images are not updated to reflect the new build path. For example if one of the css files is in /pages/login and the background-image: is "../../assets/img/picture-name.jpg", when it minifies it will still have that same path even though the minified file is one level more shallow.

#### What behavior are you expecting?
The minified css file should update that relative path depending on how nested the css file is. For example: "../assets/img/picture-name.jpg"

**Steps to reproduce:**
We are able to replicate with ionic upload

```
background-image: "../../assets/img/picture-name.jpg";
```

**Which @ionic/app-scripts version are you using?**
Ionic App Scripts Version: 0.0.45

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

We can get around this bug by assigning the image path to a variable in the theme/variables.scss file which is one level more shallow:
```$img-bkg: url("../img/background.jpg");```
then calling it on the file associated with the page /pages/login/login.scss:
```background-image: $img-bkg;```

Maybe we're not following best practices for css (not sure what they are really) but either way I think we won't be the only ones to organize our css files this way. (a main one, one for each page, and styles that will always be associated with each component on the component level)

**Comment by danbucholtz** [comment]
What would the paths be different based on minification? I don't understand this issue, and it's old, so I'm going to close it. Please let me know if you'd like me to re-open.

Thanks,
Dan
