### ISSUE TITLE
Make it easy to provide custom webpack config

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-app-scripts#682]
Look into the webpack-config-copier thing and use it rather than an `Object.assign` since Webpack has a complex data structure that makes an Object.assign not practical.

Thanks,
Dan

**Comment by seiyria** [comment]
This would be great, especially since ionic by default does not set historyApiFallback for development!

**Comment by danbucholtz** [comment]
We probably aren't going to get for this for awhile.

Thanks,
Dan
