### ISSUE TITLE
Add BuiltIns, Globals and JSON Rollup Plugins

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-app-scripts#69]
^

**Comment by pskhodad** [comment]
I tried using globals and builtins earlier but ended up with blank page and following error,

Uncaught ReferenceError: exports is not defined

This is coming from rxjs/util/root.js

root.js:10 Uncaught ReferenceError: exports is not defined
(anonymous function) @ root.js:10
(anonymous function) @ main.dev.js:3

**Comment by ckaeslin** [comment]
It depends on the order of the plugins. I also saw this error with certain order.

These two configs worked for me.

https://gist.github.com/matheusgarcez/96b1af958df0c04bc8e4651c81deaa0a
https://github.com/ckaeslin/ionic2-RC0-pouchdb/blob/master/config/rollup.config.js

**Comment by pskhodad** [comment]
Thanks @ckaeslin 
It works!

**Comment by jgw96** [comment]
This was fixed with https://github.com/driftyco/ionic-app-scripts/pull/79. Thanks everyone!
