### ISSUE TITLE
Using external typescript interfaces is strangely unreliable

### ISSUE THREAD

**Issue by Lingomat** [driftyco/ionic-app-scripts#690]
#### Short description of the problem:

Importing typescript definitions from a file appears to be strangely unreliable.

For example, make datatypes.d.ts and put it in src/app, and this file has export interface SomeThing {}
and then in some component put import SomeThing from '../relative.path/datatypes' and ... this basically works. But ... sometimes it doesn't, it will break randomly on serve watch changes and sometimes it just breaks the app completely when doing a production build with an unhelpful error along the lines of:

Uncaught Error: Cannot find module "../../app/recipe"
    at Object.<anonymous> (D:\git\zahwa\www\build\main.js:39552)

...where recipe here is recipe.d.ts and where this works just fine in ionic serve MOST of the time.

#### What behavior are you expecting?

I would like some reliable scheme to define typescript interfaces in an external file rather than putting them in providers or whatever.

I'd also expect this kind of import to work or not work rather than this strange half-way.

**Steps to reproduce:**
1. Define typescript defintions in an external d.ts file
2. Import a datatype with import { whatever } from '../relative.path/datatypes.d.ts'
3. Make changes in serve, generate production build

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

1.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

I really wish I could give you more except that in the earlier app scripts this seemed to work without issue.

**Comment by themastersoda** [comment]
This looks similar to #632 . No something must have changed between app-scripts 0.0.45 and 1.0.0 that breaks the imports for external files.

**Comment by danbucholtz** [comment]
@Lingomat,

That sounds strange to me. Can you create a minimal repository to recreate the issue and some steps on how to do it? I'll check it out then.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Due to inactivity we're going to close this issue.

Thanks,
Dan

**Comment by iget-master** [comment]
@Lingomat did you fixed it? Same issue here.

**Comment by danbucholtz** [comment]
@iget-master,

Seems strange, can you make a minimal recreation repo? Start with `ionic start showMeTheBugs blank`

Thanks,
Dan

**Comment by iget-master** [comment]
@danbucholtz Unfortunately I could not reproduce. I did removed the interface from my project and hard-coded it where needed until I find a solution.

I'll check if the issue happens with another file.
Not the same error message but looks the same issue:

Sometimes the `home` page could not be found (no link found for ...). It's lazy loaded, and also stop working until I restart ionic serve.

**Comment by Lingomat** [comment]
Apologies, I never fixed it as such, I just put the interface lines in providers. 

If and when I get frustrated with the inelegance of this solution, I'll try again and make a repo with more specific error data.

**Comment by iget-master** [comment]
Yeah, I did put the inline interfaces, but that ugly thing is making me crazy.

**Comment by Cytla24** [comment]
Still having this same issue in 2019 :D. Ionic devs what is going on?!
