### ISSUE TITLE
ionic-app-scripts lint don't see tslint.json rules

### ISSUE THREAD

**Issue by leonardobazico** [driftyco/ionic-app-scripts#691]
#### Short description of the problem:

When I execute `ionic-app-scripts lint` this done without errors or warnings.

#### What behavior are you expecting?

Load rules from tslint.json.
Execute `tslint --config tslint.json src/**/*.ts``
output:
```
no-unused-variable is deprecated. Use the tsc compiler options --noUnusedParameters and --noUnusedLocals instead.

src/app/app.component.ts[3, 10]: Named imports must be alphabetized.
src/app/app.component.ts[6, 1]: Import sources within a group must be alphabetized.
src/app/app.module.ts[1, 10]: Named imports must be alphabetized.
src/app/app.module.ts[2, 20]: Named imports must be alphabetized.
src/app/app.module.ts[8, 1]: Import sources within a group must be alphabetized.
src/app/app.module.ts[10, 1]: Import sources within a group must be alphabetized.
src/components/uploader/uploader-preview.directive.ts[1, 40]: Named imports must be alphabetized.
src/components/uploader/uploader.service.ts[7, 1]: Import sources within a group must be alphabetized.
src/declarations.d.ts[14, 20]: file should end with a newline
src/pages/auth/signup.component.ts[3, 25]: Named imports must be alphabetized.
src/pages/report/report.component.ts[2, 10]: Named imports must be alphabetized.
```

**Steps to reproduce:**
1. customize tslint.json linke: 
```
{
  "extends": "tslint-ionic-rules",
  "rules": {
    "curly": true,
    "import-spacing": true,
    "no-consecutive-blank-lines": [true, 2],
    "no-duplicate-variable": true,
    "no-unused-variable": [ true ],
    "ordered-imports": true,
    "prefer-method-signature": true,
    "space-before-function-paren": [
      true,
      {
        "anonymous": "always",
        "named": "never",
        "method": "never",
        "asyncArrow": "always",
        "constructor": "never"
      }
    ]
  }
}
```
2. execute `ionic-app-scripts lint`

**Which @ionic/app-scripts version are you using?**
1.0.0

**Comment by ramonornela** [comment]
Problem with ```tslint-ionic-rules``` in version tslint >= 4

**Comment by leonardobazico** [comment]
@ramonornela, downgrade tslint to 3.x solve the problem?

**Comment by huerlisi** [comment]
Updating to TSLint 4 is tracked in #649.

**Comment by adamdallis** [comment]
I am having the same issue is there a workaround or should we ignore for the time the linting provided by the app scripts and just use tslint directly?

**Comment by danbucholtz** [comment]
I would use TSLint directly. I tried upgrading but it is going to take a bit of time for us due to the move to TS 2.1 and Angular requiring 2.0.x.

Thanks,
Dan

**Comment by danbucholtz** [comment]
I'm going to close this and track the issue here:

https://github.com/driftyco/ionic-app-scripts/issues/649

Thanks,
Dan

**Comment by japostigo-atsistemas** [comment]
I'm facing the same problem although driftyco#649 issue has been closed.
