### ISSUE TITLE
ionic serve using active port

### ISSUE THREAD

**Issue by yasar-salim** [driftyco/ionic-app-scripts#694]
#### Short description of the problem:
I have 2 ionic projects. When i serve my first project using
```
ionic serve
```
it uses port 8100. At the same time when i serve my second project using 
```
ionic serve
```
it uses the same port(8100) and i cant access my first port

#### What behavior are you expecting?

it would be great if the second project use any open port instead of manually assigning to any open port using
```
ionic serve --port 8100



**Which @ionic/app-scripts version are you using?**
1.0.0

**Comment by danbucholtz** [comment]
@jthoms1,

Can you look into this when you get a chance?

Thanks,
Dan

**Comment by huerlisi** [comment]
@yasar-salim it works for me when using the `ionic serve` command from the Ionic CLI. This is with `ionic` version `2.2.1`.

@danbucholtz @jthoms1 When using the `ionic-app-scripts serve` command, I get `EADDRINUSE` for both the live-reload port and the web-server port.

Looking into https://github.com/driftyco/ionic-app-scripts/blob/master/src/serve.ts#L26, it seems that only the notification/logger port is dynamically assigned.

I'll try to come up with a PR that would also dynamically try ports for live-reload and web-server.

**Comment by huerlisi** [comment]
PR ready for review:-)

**Comment by danbucholtz** [comment]
PR merged.

Thanks again.

Thanks,
Dan
