### ISSUE TITLE
Update dependencies to latest, including webpack

### ISSUE THREAD

**Issue by ataraxus** [driftyco/ionic-app-scripts#695]
I've noticed that there is already support for angular cli 2.3+ in the works. 

Please consider also to update to the final version of webpack, currently we use RC3 which breaks 'barrel imports'. The final is already available and fixes this and other issues.

**Comment by JustinPierce** [comment]
For the love of all that is good in the world, _please_ do this. The bug mentioned by @ataraxus has been killing me for weeks (https://github.com/webpack/webpack/issues/3895)

**Comment by danbucholtz** [comment]
Good idea, time to update our deps.

Thanks,
Dan

**Comment by danbucholtz** [comment]
I did this. Some of the deps still need to be updated due to breaking changes. I called those out as separate issues.

This can be installed via `npm install @ionic/app-scripts@nightly`. It is not necessarily stable but should be okay more than likely.

Thanks,
Dan
