### ISSUE TITLE
[EXTEME BUG] device failing to execute as for ES6 support errors

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#697]
_From @AmitMY on January 29, 2017 15:39_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Running my app, which includes `class` and `let` in it, on many devices /emulators work, However, running it on this device fails with errors like:
![image](https://cloud.githubusercontent.com/assets/5757359/22405280/19dece8a-e649-11e6-91a2-91167318dddf.png)

Don't know what this is:
> main.js:127765 
Uncaught SyntaxError: Unexpected reserved word

This is a dependency I am using via NPM: (the class ArrayPrototypes is theirs)
> Uncaught SyntaxError: Unexpected reserved word
class ArrayPrototypes {

A config file (js) on root of the app:
> unexpected identifier for:
let _config = {

**Expected behavior:**
Full transpiling for everything the app relies on

**Steps to reproduce:**
Have a config file at the root of the app. in it, write:
```
let _config = {};
module.exports = config;
```
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

_Copied from original issue: driftyco/ionic#10231_

**Comment by jgw96** [comment]
_From @anatoly-spb on January 29, 2017 18:47_

According to https://thenextweb.com/dd/2016/03/09/6-reasons-need-learn-javascript-es6-now-not-later/

> ES6 support is coming along well in major desktop browsers, with Chrome at more than 90 percent compatibility, Edge at 80 percent and Safari at 54 percent. On mobile there’s just 31 percent of ES6 support for Android 5.1 users and 54 percent for iOS users.

More details you can find here https://kangax.github.io/compat-table/es6/

So try to switch back to the tsconfig.json supplied by ionic:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by jgw96** [comment]
_From @AmitMY on January 29, 2017 19:34_

@anatoly-spb I think I might have not explained myself correctly.

Ionic using webpack I think, transpiles all of the source files to es5, which is great. However, if you use a file outside of the src folder (for example, root folder, or node module), and that file is using es6, it will not transpile it in the bundle, and will keep it as es6. That is the problem.

When I edited the node module (it is actually my own module, so I added transpiling for it), and changed the config file to instead of having `let` have `var`, it works.

**Comment by danbucholtz** [comment]
It's been awhile since there's been any activity here, so we're considering this matter resolved.

Thanks,
Dan

**Comment by AmitMY** [comment]
@danbucholtz Incorrect. Issue is still relevant.
Also, another person had this problem just 4 days ago here https://github.com/driftyco/ionic/issues/10231

**Comment by danbucholtz** [comment]
There is an option that you can turn on to convert to bundle to es5.

`ionic_build_to_es5`

It's true by default so this should be working.

Thanks,
Dan

**Comment by AmitMY** [comment]
@danbucholtz Correct, however, this changes all of the source files to es5, not an outside file. Don't know why, it does.

**Comment by danbucholtz** [comment]
No, it transpiles the final bundle bundle from ES2015 to ES5.

Thanks,
Dan

**Comment by AmitMY** [comment]
@danbucholtz I really don't like contradicting you, but I just ran a serve, just to make sure I see everything, and it does not transpile the not-src file into ES5...
![image](https://cloud.githubusercontent.com/assets/5757359/23081823/4dacf5e6-f55f-11e6-8a48-fa09dee8cf6f.png)

**Comment by danbucholtz** [comment]
Ahh, you're correct. We're not transpiling for `ionic serve` by default. We are transpiling the bundle for `--prod` builds only right now.

**Comment by danbucholtz** [comment]
We probably aren't going to fix this for `ionic serve`. We do the transpilation to es5 in prod builds. It is too slow for dev builds.

Thank,s
Dan
