### ISSUE TITLE
target browser by default in rollup-plugin-node-resolve

### ISSUE THREAD

**Issue by shlomiassaf** [driftyco/ionic-app-scripts#7]
Currently, if a node module is targeting both browser and node, the node version is used by default.

Of course one can overwrite the config but the default should target browser version of packages.

```
nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    })
```

**Comment by adamdbradley** [comment]
Good call, thanks
