### ISSUE TITLE
Node 7 support

### ISSUE THREAD

**Issue by Zerokk** [driftyco/ionic-app-scripts#706]
I've been working in an application in Ionic 2 for the latest months, and I've been testing it with "ionic serve --lab". It always worked fine, until today, in which I installed the latest Node.js version (7.5), and now I get the following error every time I try to use the "serve" command in many ways:

> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "--v2" "--port" "8777" "--lab" "--address" "0.0.0.0" "--livereload-port" "35729"
> npm ERR! node v7.5.0
> npm ERR! npm  v4.1.2
> npm ERR! code ELIFECYCLE
> npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--v2" "--port" "8777" "--lab" "--address" "0.0.0.0" "--livereload-port" "35729"`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "--v2" "--port" "8777" "--lab" "--address" "0.0.0.0" "--livereload-port" "35729"'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ionic-app-scripts serve "--v2" "--port" "8777" "--lab" "--address" "0.0.0.0" "--livereload-port" "35729"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs ionic-hello-world
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls ionic-hello-world
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Zerok\Dev\Projects\StepApp\StepApp\npm-debug.log
> There was an error serving your Ionic application: There was an error with the spawned command: serve
> 

What's going on? I'll try now to downgrade to the LTS version, but this should be working fine.

**Comment by danbucholtz** [comment]
It is probably an issue with Node 7. We don't test on Node 7 yet. Can you try doing this for me:

```
npm install @ionic/app-scripts@nightly
```

and see if that makes a difference? It isn't necessarily stable - but it should in theory support Node 7 better as I updated several dependencies.

Thanks,
Dan

**Comment by Zerokk** [comment]
Thank you for the help, Dan. I directly tried migrating to the LTS version, and now it's working fine. Even the android build process I was trying to use before, seems to be working fine (now I'm installing the Android SDK to finally try it out).

**Comment by danbucholtz** [comment]
This is released now.

Thanks,
Dan
