### ISSUE TITLE
3rd Party Library “cordova-plugin-ms-azure-mobile-apps” not getting recognized in my Ionic 2 app

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#707]
_From @paragw09ckp on February 3, 2017 21:32_

**Ionic version:**  (check one with "x")
[X ] **2.0.0**

**I'm submitting a ...**  (check one with "x")
[X ] bug report

**Current behavior:**
I added "**cordova-plugin-ms-azure-mobile-apps**" library/module to my project and after importing "**WindowsAzure**" from it, I wrote the following line of code to connect to my Microsoft Azure Mobile Apps Backend:

**pushClient = new WindowsAzure.MobileServiceClient('https://myazuremobileapp.azurewebsites.net');**

I run my app using "ionic serve" to run it in my Chrome browser. At this point, I get a **Runtime Error** as below:

```
**
Runtime Error
Cannot find module "cordova-plugin-ms-azure-mobile-apps"
Stack
Error: Cannot find module "cordova-plugin-ms-azure-mobile-apps"
    at Object.<anonymous> (http://localhost:8100/build/main.js:114165:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:29990:72)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:114006:79)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:29966:100)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:113629:71)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
**
```

The same happens on my Android phone when run the app on phone using "**ionic run android**". I get the same exact error.

**Expected behavior:**
If all goes well, the "**client**" object/variable should have reference to my Microsoft Azure Mobile Apps Backend. Then using that reference I can register my phone for receiving Push Notifications.

**Steps to reproduce:**
1. Create a base Ionic 2 project as **ionic start azuretestapp sidemenu --v2 --ts**

2. Add the required plugin using following command: (You can use **npm install --save** also for the same)
```
        ionic plugin add cordova-plugin-ms-azure-mobile-apps --save
```
3. In the base project, in app.component.ts file, write following import statement:

        import { WindowsAzure } from 'cordova-plugin-ms-azure-mobile-apps';

4. Add a variable in MyApp class as below:

```
           pushClient: any = null;
```

5. In the base project, in app.component.ts file, add the following in **initializeApp()** method:

```
         this.pushClient = new WindowsAzure.MobileServiceClient('https://myazuremobileapp.azurewebsites.net');
```

The complete **initializeApp()** method should look like this:

```
          initializeApp() {
              this.platform.ready().then(() => {
               // Okay, so the platform is ready and our plugins are available.
               // Here you can do any higher level native things you might need.
              StatusBar.styleDefault();
              Splashscreen.hide();

              this.pushClient = new WindowsAzure.MobileServiceClient('https://myazuremobileapp.azurewebsites.net');
          });
  } 
```

6. Run command "**ionic serve**" and you will get the error in your browser window.

**Other information:**
**After trying to fix this for 2 days now, I believe this is Ionic 2 specific problem. I am saying this because I am successfully able to use the same "cordova-plugin-ms-azure-mobile-apps" from a regular HTML/JavaScrip project.**

The Stacktrace is:
```
**
Runtime Error
Cannot find module "cordova-plugin-ms-azure-mobile-apps"
Stack
Error: Cannot find module "cordova-plugin-ms-azure-mobile-apps"
    at Object.<anonymous> (http://localhost:8100/build/main.js:114165:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:29990:72)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:114006:79)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:29966:100)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:113629:71)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
**
```

I have also posted this issue on Stackoverflow, here is the link with complete description:

http://stackoverflow.com/questions/42016964/3rd-party-library-cordova-plugin-ms-azure-mobile-apps-not-getting-recognized-i

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed

```

_Copied from original issue: driftyco/ionic#10310_

**Comment by danbucholtz** [comment]
Can you verify that `cordova-plugin-ms-azure-mobile-apps` is in your `node_modules` directory? I don't see where you're doing an `npm install`.

Thanks,
Dan

**Comment by paragw09ckp** [comment]
Hi @danbucholtz - yes, it's in node_modules. I added it using `ionic plugin add --save`

**Comment by danbucholtz** [comment]
@jgw96,

Can you try to recreate this?

Thanks,
Dan

**Comment by paragw09ckp** [comment]
@danbucholtz - as a work around, I got it working by declaring "**WindowsAzure**" as a variable the old fashioned JavaScript way. Thanks for Microsoft support!

So, all I had to do was to use the "**WindowsAzure**" namespace from "**cordova-plugin-ms-azure-mobile-apps**" as a regular **plain old JavaScript variable** instead of doing an "**import**".

That is, instead of importing WindowsAzure as:

**import { WindowsAzure } from 'cordova-plugin-ms-azure-mobile-apps';**

I declared it as a regular JavaScript object after all the "**imports**" and before "**@Component**" class and/or "**@Injectable**" service/provider class, as:

```

    import { ... } from '...';

    declare var WindowsAzure: any;

    @Injectable
    export class ... {
        client: any;
        ....
        constructor or yourMethod(...) {
            this.client = new WindowsAzure.MobileServiceClient('http://YourAzureMobileApp.azurewebsites.net');
        }
        ....
        ....
        //Your logic
    }
```

So, apparently, my conclusion is, if in Ionic 2 (or is it an Angular 2 issue?) a third party library is not being recognized with regular "**import**" statement then one should try to use it in the old JavaScript way.

Do let me know your thoughts on this approach and whether there will be a fix in Ionic 2 for such scenarios.

Thanks.

**Comment by rapropos** [comment]
Does a namespaced wildcard import work?

```
import * as azure from "cordova-plugin-ms-azure-mobile-apps";
```

**Comment by paragw09ckp** [comment]
@rapropos - I had tried that before posting the issue here. It does not, I was getting the same error.

**Comment by Ross-Rawlins** [comment]
+1

**Comment by jgw96** [comment]
Hello all! After further research i am going to close this one as it seems to be an issue with that plugin. Most cordova plugins are not built with typings and are not written in es6, that is the reason we have the Ionic Native project. This means you may have to use the method that @paragw09ckp mentioned [here](https://github.com/driftyco/ionic-app-scripts/issues/707#issuecomment-277761516). I would recommend opening an issue on [the Ionic Native repo](https://github.com/driftyco/ionic-native) to get this plugin adde to Ionic Native. Thanks!

**Comment by jordanks** [comment]
this plugin will never work with ionic serve, it should run on a platform (android ios or browser), try 
`ionic cordova run browser` 

you can use a service to test 

declare var WindowsAzure: any;
@Injectable()
export class AzureService {
    public client: any;
    constructor() {
 this.client = new WindowsAzure.MobileServiceClient("http://adamomobilequickstart.azurewebsites.net");
    }
    public testTableAzure() {
        this.client = new WindowsAzure.MobileServiceClient("http://someurl");
        this.loggerService.info("");
        var table = this.client.getTable("todoitem", table);
        table.read().then((result) => {
//do something with result
        });

    }
}
