### ISSUE TITLE
Serve --prod on a clean app fails

### ISSUE THREAD

**Issue by maxflex** [driftyco/ionic-app-scripts#709]
#### Short description of the problem:
After running `ionic serve --prod` on a new clean app I get this message:

> Runtime Error
> Module build failed: Error: ENOENT: no such file or directory, open 'src/app/main.js.map' at Error (native)

**Steps to reproduce:**
1. `ionic start myapp --v2 --template blank`
2. `ionic serve --prod`

**Which @ionic/app-scripts version are you using?**
1.0.0

**Other information:** 
I've tried all the other solutions, nothing helps. `sourceMap` is set to "true" in `tsconfig.json` by default, `declaration` set to `false` – still not working.

**Comment by danbucholtz** [comment]
Sorry, we don't intend to support this until AoT is faster. It would take ~30 seconds minimum between builds right now, so it's not practical. Google internally has "incremental" AoT builds that take ~2 seconds, so it could happen in the future.

Thanks,
Dan

**Comment by miqmago** [comment]
There are some features that should be tested in production code, in fact I'm testing an app that works without minimizing and when it gets minimized it does not...

The question is here: https://github.com/ionic-team/ionic-app-scripts/blob/master/src/watch.ts#L21, I've commented these lines and I could be able to test minimized.

Couldn't it be a flag where the developer could decide if he wants to get in the heal of 30 seconds between build or not? In the way that it is right now, ionic is deciding that even if the developer executes `ionic-app-scripts serve -- --prod` it will not be in prod mode... Imo, if you say `-- --prod` I think that you should know what you're doing...

In my case that I'm testing for ios, it's better to wait 30 seconds for build than recompile the whole app to test what's going on (in fact it was a problem of mangling, so each test I had the build time and also the compiling time...)
