### ISSUE TITLE
move to app-scripts from gulp

### ISSUE THREAD

**Issue by sfabriece** [driftyco/ionic-app-scripts#71]
I have a gulp task that renames a file when releasing.

```js

var isRelease = argv.indexOf('--release') > -1;

gulp.task('config', function() {
	var options = {
		inputPath: './app/shared/config/',
		inputFile: isRelease ? 'config.release.ts' : 'config.debug.ts',
		outputPath: './app/shared/config/',
		outputFile: 'config.ts'
	};
	return gulp.src(options.inputPath + options.inputFile)
		.pipe(rename(options.outputFile))
		.pipe(gulp.dest(options.outputPath));
});
```

How can I do this with app-scripts?

Thank you 😄

**Comment by jgw96** [comment]
Hello, thanks or using Ionic! So you can still use gulp exactly as you always have with the RC.0 release of Ionic 2, but we have just moved this out of our core as we believe npm scripts are the future (:. You may have to install gulp yourself if you do not have gulp installed globally by running `npm install gulp --save-dev`. Thanks for using Ionic!

**Comment by sfabriece** [comment]
My question is if I can still do what I wanted to do without depending on gulp. Maybe by using a custom script. In that case, How do I achieve this?
