### ISSUE TITLE
Ionic Config in package.json do not work

### ISSUE THREAD

**Issue by ubaidazad** [driftyco/ionic-app-scripts#710]
#### Short description of the problem:
custom configuration settings do not work.

#### What behavior are you expecting?
using custom **ionic_app_ng_module_path** and **ionic_app_ng_module_class** does nothing in package.json but **ionic_app_entry_point** works. when changing values in the **ionic_app_ng_module_path**  or **ionic_app_ng_module_class**  app still compiles, even though the path is incorrect, even changing from **'/app.module'** in **main.ts** to anything also compiles successfully, how is that possible?

`
import { WebAppModule } from './anything';
`

```
"config": {
    "ionic_app_ng_module_path": "src/app/app.web.module.ts",
    "ionic_app_ng_module_class": "WebModule",
    "ionic_app_entry_point": "src/app/main.web.ts"
  }
```

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

**Comment by danbucholtz** [comment]
There's a good chance those properties are not in `1.0.0`. `master` is ahead of `1.0.0`. You could clone and build from `master` if you'd like. Clone, `npm install`, run `npm run build`.

Thanks,
Dan
