### ISSUE TITLE
use of Angular 2 Hot Module Replacement: @angularclass/hmr instead of refreshing browser

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#711]
_From @almothafar on February 5, 2017 15:14_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
Each change made to project files, it refresh the page and lost any changes and focus on the page, especially for forms and sometimes it is simply annoying getting page refresh for every change, especially if you are using WebStorm or InjelliJ, when you switch between windows, you will get the page refreshed directly, because those IDEs save when you lose focus.

**Expected behavior:**
Hot Module Reloading, no more need to refresh a page, and see changes instantly, this could really helpful to notice changes especially the really small changes and compare the previous state with new stat.!

**Other information:**
Angular 2 Hot Module Replacement: https://github.com/AngularClass/angular2-hmr

_Copied from original issue: driftyco/ionic#10318_

**Comment by danbucholtz** [comment]
Sorry, that's outside of the current scope of Ionic. Maybe some day but we're focused on other things now.

Thanks,
Dan

**Comment by nicolas-albert** [comment]
Do you find a workaround @jgw96 or @almothafar to enable HMR with a ionic project ?

**Comment by almothafar** [comment]
@nicolas-albert  no, sadly, ionic2 is a jail especially with `ionic-app-scripts` you can't move like what you want, I'm not wasting time to try this.

And don't expect so much from ionic2, their job is press close button not solve issues!.

**Comment by danbucholtz** [comment]
@almothafar,

You don't need to use app-scripts. You can design and implement your own build process if you'd like. Heck, you could even use the angular-cli if you felt so inclined.

We support multiple bundlers beyond Webpack so using webpack HMR is not plausible right now or on our road map.

Thanks,
Dan
