### ISSUE TITLE
1.0.1 Deeplinks

### ISSUE THREAD

**Issue by theomathieubhvr** [driftyco/ionic-app-scripts#714]
#### Short description of the problem:
Since 1.0.1 I cannot use deeplinks.

#### What behavior are you expecting?
Preprocess should not failed. I worked in 1.0.0

**Steps to reproduce:**
This is my IonicModule config.

```javascript
IonicModule.forRoot(AppComponent, {
			locationStrategy: true ? 'hash' : 'path',
			pageTransition: 'ios',
		}, {
			links: [
				{ component: TabsPage, name: 'Tabs', segment: 'tabs' },
				{ component: HomePage, name: 'Home', segment: 'home' },
				{ component: AboutPage, name: 'About', segment: 'about' },

				...playerRouting,
				...userRouting,
			],
		})
```
2. ionic serve
3.
```bash
[12:42:48]  preprocess failed: Expected 0 names in deep link config, found the following: Tabs,Home,About
[12:42:48]  ionic-app-script task: "serve"
[12:42:48]  Error: Expected 0 names in deep link config, found the following: Tabs,Home,About
```

**Which @ionic/app-scripts version are you using?**
1.0.1

NOTE : It doesn't detect other links from other modules (playerRouting, userRouting)

Thanks !

**Comment by danbucholtz** [comment]
Sorry, use `1.0.0` now. A breaking API change may have slipped through the cracks here.

Thanks,
Dan

**Comment by theomathieubhvr** [comment]
Ok thanks for the explanation.

Maybe you should explain this in your release notes ?

**Comment by theomathieubhvr** [comment]
And I honestly think this should not be a minor release.

Thanks !

**Comment by danbucholtz** [comment]
Yeah, since the API broke we should have did a major release. Sorry about that, we did not realize we broke the API. We have tests but the tests are using the new API. We didn't plan to cut the release - we needed to do another for beta testing a different Ionic functionality.

Thanks,
Dan

**Comment by ncapito** [comment]
This is really bad and scary as a developer using this product.  We just got bit by this as well.  We are rolling back to 1.0.0

**Comment by danbucholtz** [comment]
@ncapito,

Yeah, it was a mistake. We're sorry about that. It's behind a flag in `1.1.0`. I would use that.

Thanks,
Dan
