### ISSUE TITLE
serve gets stuck every now and then

### ISSUE THREAD

**Issue by Isigiel** [driftyco/ionic-app-scripts#715]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
It seems like ionic serve gteyx stuck for me when using it with webstorm.
I'd assume that is due to some file changes in a short ammount of time and scrupts not handling them very well.

#### What behavior are you expecting?
Either killing the current update and starting over or just finishing all of them.

**Steps to reproduce:**
1. have project
2. wildly save and edit files
3. see `serve` stopping

I waited 2 mins before taking this screenshot
http://i.imgur.com/qXsWVAy.png

_EDIT: this is what happens when more file changes occur ten minutes later http://i.imgur.com/GN7KYIU.png_

_EDIT2: sometimes it seems like webpack just gets stuck without many file changes_

**Which @ionic/app-scripts version are you using?**
```
$ ionic info

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.4.0
Xcode version: Not installed
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Link to my project https://gitlab.com/pikandpeople/mobile-next

**Comment by tweetgeek** [comment]
+1

**Comment by megobyte** [comment]
I observe this issue to with my html files. When I updating html files I need to restart `ionic serve` to get updates

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.4
```

(same thing with Ionic App Scripts Version: 1.0.1)

**Comment by BradyLiles** [comment]
I was getting the same errors as megobyte. I just downgraded to 1.0.0 for active development when using `ionic serve`.

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by EbilPanda** [comment]
same thing as here [Webpack frequently freezes when started](https://forum.ionicframework.com/t/webpack-frequently-freezes-when-started/74226)?

what solved it for me: downgrade node to 6.9.5 (LTS)

my info:

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.1
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by cmaart** [comment]
Can still confirm. Hangs when doing changes while another change is still ongoing (being compiled).

```
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.5.0
Xcode version: Not installed
```

**Comment by danbucholtz** [comment]
Due to inactivity and inability to recreate, we're closing this issue.

Thanks,
Dan
