### ISSUE TITLE
tslint is printing out wild stuff

### ISSUE THREAD

**Issue by Isigiel** [driftyco/ionic-app-scripts#716]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When I run tslint from my node scripts it has a bunch of things and then stops complaining.
Whn I then run `ionic:lint` I get a massive strangely formatted list of things that seem to be wrong but don't show up in my tslint run.

#### What behavior are you expecting?
The same output for both versions of linting

**Steps to reproduce:**
1. Run the tslint script 
2. Run ionic:lint script
3. compare results

I get this on https://gitlab.com/pikandpeople/mobile-next

**Which @ionic/app-scripts version are you using?**
```
$ ionic info

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.4.0
Xcode version: Not installed
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
@Isigiel,

I am far from a TSLint expert, but this looks like our behavior is correct and your scripts version is not. The output does seem to match the rules configured, and when I look at a few of them the output does seem correct.

Please let me know if I am mistaken and I'll re-open the issue.

Thanks,
Dan
