### ISSUE TITLE
Introduce SASS linting

### ISSUE THREAD

**Issue by huerlisi** [driftyco/ionic-app-scripts#720]
#### Short description of the problem:
There is nice support for TypeScript linting, but there are also other file formats to lint, especially SASS. 

#### What behavior are you expecting?
I understand that due to the nice re-formatting and watching support, integrating more linters is quite some work.

Given the 1. class support for SASS during build, it would be great if SASS linting could be integrated. 

**Which @ionic/app-scripts version are you using?**
1.0.1

**Comment by huerlisi** [comment]
I took a quick look at the linting support in the sources.

My understanding is that the following would be needed:
* split `lint.ts` into generic stuff like `lintUpdate`, `lintApp`... and TSLint specific functions
* implement support for `sass-lint`
** calling with a wrapper
** config file support
* add `sass-lint` to `package.json`
* implement a `logger-sass-lint` diagnostics class
* ensure changes not only for `.ts` but also `.scss` and `.sass` trigger re-linting
* update documentation

Is that about right?

**Comment by danbucholtz** [comment]
@huerlisi,

It sounds about right. You wanna take a crack at the PR? I can help. Otherwise we can do this but it'll be a few months at the least.

Thanks,
Dan

**Comment by huerlisi** [comment]
@danbucholtz maybe:-) Won't commit doing it, but we need this, so it's on my backlog:-)

**Comment by awebdeveloper** [comment]
@danbuchoits if you can help I can give a shot

**Comment by danbucholtz** [comment]
@awebdeveloper,

Sure! are you on Ionic Worldwide slack? Send me a DM on there. I think my handle is dan.b or danb.

Thanks,
Dan

**Comment by danbucholtz** [comment]
PR welcome.

Thanks,
Dan
