### ISSUE TITLE
Optimize font files copy process

### ISSUE THREAD

**Issue by tanzl88** [driftyco/ionic-app-scripts#722]
#### Short description of the problem:
Font files take up a significant portion of production apk file size (about 1MB). To my knowledge, some file types are for backward compatibility purpose and some file types are for different platform.

![screen-shot-2017-02-04-at-11 14 52-am](https://cloud.githubusercontent.com/assets/4703671/22716104/2dc42ce6-edcf-11e6-8ed2-6f870360734c.jpg)

#### What behavior are you expecting?
Would it be a good idea to optimize app script copy process for different platform? For example, android build would not copy noto-sans and non .woff ionicons file which could save about 700kB.

**Steps to reproduce:**
1. Build any project

**Which @ionic/app-scripts version are you using?**
1.0.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
N/A

**Comment by danbucholtz** [comment]
This is in `master` now, it will require an update to our CLI so expect to hear some news on this in the coming weeks.

Thanks,
Dan
