### ISSUE TITLE
fonts not added

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#73]
_From @ThorConzales on October 3, 2016 13:17_

Many times in my upgrade path to RC0 I encountered an error when all the ionicon fonts were missing. They were just not included in www/assets/fonts folder. Though nothing was outputted to console it seemed to be related to messing up styles. For example when I used "ion-button" together with "icon-right" class when actually I didn't have an icon inside the button element.

_Copied from original issue: driftyco/ionic#8433_

**Comment by joshgarwood** [comment]
This also seems to be a problem with the "Roboto" font when running in `md` mode.  It doesn't get copied.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately I am not able to reproduce this issue. Can you all run `npm install` in your app to install the latest version of `ionic-app-scripts` and try again? Thanks!

**Comment by joshgarwood** [comment]
This is happening with the ionic-conference-app and ionic-app-scripts v. 0.0.28 (make sure you clone ionic-conference-app into a brand new directory, not an existing clone).  

I also noticed that with ionic-app-scripts .28, that I'm getting permission errors (it at least looks like it's trying to copy the ionicons... but still no Roboto :)

`[18:22:43]  copy failed:  Error copying "src/assets/" to "www/assets/": Error: EPERM: operation not permitted, open 'C:\Users\josh\Source\Repos\ionic-help\ionic-conference-app\www\assets\fonts\ionicons.svg',Error: EPERM: operation not permitted, open 'C:\Users\josh\Source\Repos\ionic-help\ionic-conference-app\www\assets\fonts\ionicons.eot',Error: EPERM: operation not permitted, open 'C:\Users\josh\Source\Repos\ionic-help\ionic-conference-app\www\assets\fonts\ionicons.ttf',Error: EPERM: operation not permitted, open 'C:\Users\josh\Source\Repos\ionic-help\ionic-conference-app\www\assets\fonts\ionicons.woff',Error: EPERM: operation not permitted, open 'C:\Users\josh\Source\Repos\ionic-help\ionic-conference-app\www\assets\fonts\ionicons.woff2'
`

**Comment by Chris1308** [comment]
I had the same problem here.

If you delete the src/app/assets/fonts-folder, everything is working.
With the old 0.0.23-app-scripts, i had the problem that the fonts were often not copied, so i created a new folder in assets like in the conference app.

But with 0.0.28 it's no longer necessary because the fonts are now copied from node_modules. So just detele the folder and it works.

**Comment by ThorConzales** [comment]
I still managed to reproduce it with 0.0.28 version but the second run fixed it.

**Comment by jgw96** [comment]
Thanks for the info everyone! So just to be clear, with app-scripts 0.0.28 and a fresh starter is this still reproducible?

**Comment by daniel7912** [comment]
Roboto still isn't loading for me with 0.0.28. I did the following:

```
ionic start test --v2 --ts
cd test
ionic serve
```

Ionicons work OK but not Roboto.

**Comment by jgw96** [comment]
Thanks for all the info everyone. I can confirm that Roboto is definitely not being loaded, although ionicons are working great for me.

**Comment by sveinl** [comment]
It happens from time to time here too. Deleting the .tmp folder and then rerun `ionic serve` solves the problem.

**Comment by savanvadalia** [comment]
Agree with @sveinl, it happens intermittently. Haven't tried deleting the .tmp folder. But i experienced this problem twice.

**Comment by wwallace** [comment]
Tried deleting the .tmp folder, deleting assets/*, changing to Read/Write/Execute permissions for "Everyone", still having the same issue.

**Comment by math10** [comment]
I also face the same problem. 
In copy.config.js in app-sctipt I found this,
`{
      src: 'src/assets/',
      dest: 'www/assets/'
    }`
`{
      src: 'node_modules/ionicons/dist/fonts/',
      dest: 'www/assets/fonts/'
    }`
In `src/assets/fonts/` and `node_modules/ionicons/dist/fonts/` both contain same files for ionicons fonts. I just remove ionicons fonts form src/assets/fonts/ and then rerun `ionic serve` solves the problem. I also use custom fonts in `src/assets/fonts/` which also go to `www/assets/fonts` without any error.

That's why, I think the main problem is the same name file found in a different place for copying.

**Comment by gigocabrera** [comment]
@jgw96 This is also happening on a Windows 10 environment. Please see below
https://forum.ionicframework.com/t/2-0-0-rc0-error-copying-src-assets-to-www-assets/65542

**Comment by joshgarwood** [comment]
Is there a workaround for this in the meantime so that I can get the Roboto font included in my `ionic package` build?  We really need it in order to release our app :)

Thanks!

**Comment by lygstate** [comment]
Too often on my computer. the previous version doesn't has this problem.

**Comment by lygstate** [comment]
I am using Windows 10.

**Comment by zhang5690889** [comment]
Had the same problem. Second run fixed it.

**Comment by joshgarwood** [comment]
Roboto still isn't copied over at all... ionicons are most of the time though.

**Comment by lleevvyy** [comment]
@jgw96 that issue is still not fixed - if you look at copy and sass config files, there is no reference to node_modules/ionic-angular/fonts/... Roboto and other fonts are not copied...

**Comment by ataraxus** [comment]
getting also these copy errors, every time i start the app-scripts and didn't deleted the contents of www by hand 
```
[09:11:20]  copy: Error copying "C:\Users\PROJECT\src\assets"
            to "C:\Users\PROJECT\www\assets"
[09:11:20]  copy: Error copying
            "C:\Users\PROJECT\node_modules\ionicons\dist\fonts"
            to "C:\Users\PROJECT\www\assets\fonts
```

```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.42
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by gabriele-v** [comment]
Still have problems with Roboto and Noto Sans not copied, do I need to check something on my side or it's an app-scripts problem?

I haven't any error in cli after ionic serve.


```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.44
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.7.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Going to close this for now. This will be fixed in the next release of Ionic 2. Thanks!

**Comment by neculaionutni** [comment]
Close but I'm using version 3 of Ionic and still having the same problem. Any fix please?

**Comment by risen85** [comment]
I am having the same issue as neculaionutni too.
When copying files, i can see roboto fonts but when the script runs ionic cordova prepare, all the fonts were deleted and not copying over.

When copying files
![image](https://user-images.githubusercontent.com/31330114/29696007-8e0a6b84-8978-11e7-9b80-6170de4dbb21.png)

When preparing cordova
![image](https://user-images.githubusercontent.com/31330114/29696025-ae5e6412-8978-11e7-9504-8f366f962f74.png)

**Comment by mflmartin** [comment]
Same issue with latest ionic CLI, today.

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.3.0

System:

    Node : v6.10.3
    npm  : 4.2.0
    OS   : Windows 10

**Comment by RafaelSNascimento** [comment]
same problem here!

**Comment by MWNemesis** [comment]
I have the same issue, there is a workaround?

**Comment by shogunfighter** [comment]
Something is overwriting this folder everytime i build...

<app>/src/asset/fonts/

What i did was not use that damn folder, instead create my own and store my fonts and etc.

<app>/src/custom/fonts/<your fonts and scss font imports are here>

I override my own copy.config.js to copy the files we placed in our newly created custom folder into the www folder when building.
e.g., after build will be like this 

<app>/www/custom/fonts/<your custom files copied when building using copy.config.js>

Update the $file_path to use the custom folder path: 

<app>/src/theme/variable.scss
 
E.g, scss variable assignment
$file_path : "../custom/fonts/";

Try building again. I'll edit this comment if i can later, hopefully I'll remember. (Im using my phone typing this whole thing)

**Comment by Raghu-Rocks** [comment]
1. "ionic build" is copying all the fonts(ionicons and roboto) correctly.
2. it works partially fine with : 
                   (a) "ionic cordova build android"
                   (b) "ionic cordova run android".
          while running this command fonts are present in folders
              (platform/android/assets/WWW/assets/fonts  and  WWW/assets/fonts) for few seconds.

     I guess it removes the fonts when it starts running :  "cordova run android"

**Comment by marcRDZ** [comment]
Same problem, here is my environment info:

    @ionic/cli-plugin-proxy : 1.4.8
    @ionic/cli-utils        : 1.10.1
    ionic (Ionic CLI)       : 3.10.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.3.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 3.10.10
    OS                : Windows 7

**Comment by shogunfighter** [comment]
There was actually a [bug](https://github.com/ionic-team/ionic-cli/issues/2675#issuecomment-327580475) that happened. Then, my previous answer wasn't that clear... So if you still get error try this instead.

My Method involves overriding the `copy.config.js`. Well, you can try this and create a `custom` folder, away from that buggy `assets` folder:

First of all:
Check if you have files in your `<APP>/src/assets`, if yes, just put it over to `<APP>/src/custom`.
Adjust your codes accordingly to point to `custom`.

1. Copy this file:

`<APP>/node_modules/@ionic/app-scripts/config/copy.config.js`

2. Place the file in here:

`<APP>/overrides/copy.config.js`

3. Adjust the `<APP>/package.json` 

```
{
    "scripts": {...},
    "dependencies": {...},
    "devDependencies": {...},
    "x----x----x": "ADD THE CONFIG BELOW SINCE YOU WANT TO OVERWRITE THE COPY CONFIG",
    "config": {
        "ionic_copy": "./overrides/copy.config.js"
    }
}
```

4. Modify the file `<APP>/overrides/copy.config.js`

From:

```
module.exports = {
  copyAssets: {
    src: ['{{SRC}}/assets/**/*'],
    dest: '{{WWW}}/assets'
  },
  copyIndexContent: {
    src: ['{{SRC}}/index.html', '{{SRC}}/manifest.json', '{{SRC}}/service-worker.js'],
    dest: '{{WWW}}'
  },
  copyFonts: {
    src: ['{{ROOT}}/node_modules/ionicons/dist/fonts/**/*', '{{ROOT}}/node_modules/ionic-angular/fonts/**/*'],
    dest: '{{WWW}}/assets/fonts'
  },
  copyPolyfills: {
    src: [`{{ROOT}}/node_modules/ionic-angular/polyfills/${process.env.IONIC_POLYFILL_FILE_NAME}`],
    dest: '{{BUILD}}'
  },
  copySwToolbox: {
    src: ['{{ROOT}}/node_modules/sw-toolbox/sw-toolbox.js'],
    dest: '{{BUILD}}'
  }
}
```

To:

```
module.exports = {
  //copyAssets: {			//commented
  //  src: ['{{SRC}}/assets/**/*'],	//commented
  //  dest: '{{WWW}}/assets'		//commented
  //},					//commented
  copyCustom: {				//new
    src: ['{{SRC}}/custom/**/*'],	//new
    dest: '{{WWW}}/custom'		//new
  },
  copyIndexContent: {
    src: ['{{SRC}}/index.html', '{{SRC}}/manifest.json', '{{SRC}}/service-worker.js'],
    dest: '{{WWW}}'
  },
  copyFonts: {
    src: ['{{ROOT}}/node_modules/ionicons/dist/fonts/**/*', '{{ROOT}}/node_modules/ionic-angular/fonts/**/*'],
    dest: '{{WWW}}/custom/fonts'	//new - these are the fonts, ionicon/roboto/noto-sans
  },
  copyPolyfills: {
    src: [`{{ROOT}}/node_modules/ionic-angular/polyfills/${process.env.IONIC_POLYFILL_FILE_NAME}`],
    dest: '{{BUILD}}'
  },
  copySwToolbox: {
    src: ['{{ROOT}}/node_modules/sw-toolbox/sw-toolbox.js'],
    dest: '{{BUILD}}'
  }
}
```


5. Modify the `$font-path` in the scss to load the font from our custom folder 

`<APP>/src/theme/variables.scss`


From:

`$font-path: "../assets/fonts";`

To:

`$font-path: "../custom/fonts";`



6. ENJOY!

```
$ ionic cordova run <platform>
```

**Comment by marcRDZ** [comment]
Thanks for your quick reply, I´ll give a try
I've found another workaroud using the deprecated appcache as I was using this feature previously.

**Comment by Raghu-Rocks** [comment]
@marcRDZ  once you test these steps please share the result, because I followed the @shogunfighter's
steps but producing the same error.

![image](https://user-images.githubusercontent.com/16892603/30476991-61389902-9a29-11e7-9c66-aa3fa8df1a18.png)

The custom fonts are getting copied in
    1.  www/custom/fonts
    2.  platform/android/assets/www/custom

but it still giving the 404 error for me.
and when I change the variable.scss : 

   From:
    $font-path: "../assets/fonts";

   To:
  $font-path: "../custom/fonts";

It doesn't load even ionicons. 

![image](https://user-images.githubusercontent.com/16892603/30477532-184a745c-9a2b-11e7-9f7d-e35e76c86f23.png)

**Comment by shogunfighter** [comment]
@Raghu-Rocks Somewhere you did not follow instructions, 
I created a blank repo for you. [link](https://github.com/shogunfighter/testfont)


HTML changes: [link](https://github.com/shogunfighter/testfont/blob/master/src/pages/home/home.html)

Result test ionicon: [link](https://github.com/shogunfighter/testfont/blob/master/testfont.png)

**Comment by Raghu-Rocks** [comment]
Thanks @shogunfighter it works for me. I think I missed "npm install" last time. feeling very happy.
Many many thanks for the solution.👌👌👌😊😊😊
