### ISSUE TITLE
Enable CI checks in PR

### ISSUE THREAD

**Issue by huerlisi** [driftyco/ionic-app-scripts#730]
#### Short description of the problem:
I just noticed one of my PRs broke the builds on Circle-CI. I noticed because I look through the commits and saw the red cross.

#### What behavior are you expecting?
Circle-CI has some nice integration with GitHub showing the test results in the context of the PRs.

Could you give the service integration a try? Would be nice to catch such issues before the merge:-)

**Comment by danbucholtz** [comment]
I think these are in place, I just merged too quickly.

Thanks,
Dan

**Comment by huerlisi** [comment]
They are partially in place: while PRs from branches in this project are using the CI integration, it seems not enabled for PRs from forks. So external guys like me have more power to break your builds without noticing:-)

See https://circleci.com/docs/fork-pr-builds/ on how PRs from forks could be tested. It's more or less one setting, but should only be done if you don't use any (deployment/API...) secrets in your builds.
