### ISSUE TITLE
1.1.0 optimizations - messed up CSS?

### ISSUE THREAD

**Issue by zarko-tg** [driftyco/ionic-app-scripts#739]
#### Short description of the problem:
Building/running (with --prod) on a device (Nexus 5 in this test) seems to mess up the CSS while the two new flags (ionic_experimental_manual_treeshaking and ionic_experimental_purge_decorators) are enabled.

#### What behavior are you expecting?

No visual differences while using the optimizations.

**Steps to reproduce:**
1. Set ionic_experimental_manual_treeshaking and ionic_experimental_purge_decorators to true in the "config" section of package.json
2. ionic prepare
3. ionic run android --prod

**Which @ionic/app-scripts version are you using?**
1.1.0

**Screenshots - without (normal) and with flags**
<img src="https://cloud.githubusercontent.com/assets/6142411/22876958/69d1a620-f1d3-11e6-8f3d-6d1dd435c18d.png" width="256"> <img src="https://cloud.githubusercontent.com/assets/6142411/22876944/56bca01c-f1d3-11e6-9f92-f25191970074.png" width="256">

**My system information**
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.1 Build version 8B62

**Comment by FdezRomero** [comment]
I had exactly the same problem, but wasn't sure if it was due to this. Seems like the root font size is increased.

**Comment by brandyscarney** [comment]
Can either of you please open the built css file and see if the following rule is being included:

```
html {
  font-size: 62.5%;
}
```

Thanks :)

**Comment by zarko-tg** [comment]
These are the only occurrences I found in the built main.css:
html{width:100%}
html{-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;text-size-adjust:100%}

So no, nothing like font-size:62.5%

**Comment by gregavola** [comment]
Also seeing this problem... any ideas on how to fix?

**Comment by gregavola** [comment]
My solution so far:

Add the following to `global.scss` and it appears to work well.

```
html {
  font-size: 62.5% !important;
}

[text-center] {
  text-align: center;
}
```

**Comment by brandyscarney** [comment]
It should be fixed in the framework in the next release, to try out the nightly:

```
npm install ionic-angular@nightly
```

**Comment by danbucholtz** [comment]
This should be fixed in Ionic 3. We restructured some CSS.

Thanks,
Dan
