### ISSUE TITLE
JS output file name build fails with --prod flag

### ISSUE THREAD

**Issue by superkew** [driftyco/ionic-app-scripts#741]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When using a js file name anything other than main.js, the --prod build will fail with a "ENOENT: no such file or directory" error. This happens in the uglify phase.

#### What behavior are you expecting?
Prod build to succeed

**Steps to reproduce:**
1. create new blank ionic template
2. run: ionic build ios --prod --outputJsFileName main.foo.js

**Which @ionic/app-scripts version are you using?**
1.1.0 (also fails on 1.0.0, 1.0.1)

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
This is fixed now. Expect to to be in `1.1.3`.

Thanks,
Dan
