### ISSUE TITLE
Build fails when specifying css file name with --outputCssFileName

### ISSUE THREAD

**Issue by superkew** [driftyco/ionic-app-scripts#742]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Build does not finish when specifying the css file name. Error: Unknown platforms: main.foo.css

#### What behavior are you expecting?
Build to succeed.

**Steps to reproduce:**
1. Install blank ionic template
2. run: ionic build ios --prod --outputCssFileName main.foo.css

**Which @ionic/app-scripts version are you using?**
1.1.0

On previous versions a different error occurs - will log separate issue.

**Comment by superkew** [comment]
Same issue on 1.0.1

**Comment by superkew** [comment]
1.0.0 has Error: ENOENT: no such file or directory, open '/.../www/build/main.css'

**Comment by danbucholtz** [comment]
Also happens with `--webpack`, this is Cordova not being able to find the platform.

Thanks,
Dan

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1925
