### ISSUE TITLE
"Cannot find name Buffer" - only on Windows, not on Mac.

### ISSUE THREAD

**Issue by larssn** [driftyco/ionic-app-scripts#744]
#### Short description of the problem:
The build fails with the error in the topic.

Now this only happens on a colleague's Windows 10 machine for some reason. It has everything freshly installed to debug this. Node 7.5.0, Typescript 2.0.9, Ionic 2.2.1, Cordova 6.5.0.

**Now we finally found a solution, which is inserting `typeRoots: [ "./node_modules/@types" ]` in `tsconfig.json` under `compilerOptions`**

Not sure why this is only required on his Win10 machine, and not my OSX Sierra.

#### What behavior are you expecting?

Was a git project, so was expecting that the same `package.json`/`tsconfig.json` would work universally.

**Steps to reproduce:**
1. `ionic start buffer_test blank --v2`
2. `npm install @types/node --save-dev`
3. Insert `bf: Buffer` as a field in app.component.ts
4. `ionic serve` (on Win10)

**Which @ionic/app-scripts version are you using?**
1.1.0

**Comment by danbucholtz** [comment]
`Buffer` is a node type. That does not mean it's available on the browser. `@types` are just interfaces, interfaces are not there at runtime. When you reference `Buffer`, if the browser doesn't know about it (I'm not sure if it does or not), it will error out on that unknown Symbol.

Thanks,
Dan

**Comment by larssn** [comment]
Thanks for the reply, but why would it work on mac then, without the typeRoots?

**Comment by danbucholtz** [comment]
You shouldn't need `typeRoots`. I don't know why you do. Seems odd. BTW, it's best to use Node 6 LTS since I know some of our dependencies can be wonky with Node 7.

Thanks,
Dan

**Comment by larssn** [comment]
Maybe a node 7 problem yeah. Best to write this behind one's ear methinks.

**Comment by FelschR** [comment]
I'm having the exact same issue.
Adding `./node_modules/@types` to `typeRoots` fixed it.

**Comment by rob3c** [comment]
Requiring a `typeRoots` entry just to see typings in `node_modules/@types` on Windows is still an issue as of ionic-app-scripts 2.1.4 9 months later! The same tsconfig without it works fine on my mac. This is with either of the current node LTS versions, 6 or 8.
