### ISSUE TITLE
Validation check on build.ts throws error on valid tsconfig.json

### ISSUE THREAD

**Issue by robrohan** [driftyco/ionic-app-scripts#745]
#### Short description of the problem:

tsconfig.json allows for the 'extends' property to be used to help with the build pipeline.  It's used to support different tsconfigs for dev, test, production, etc etc.

The current code in the file `ionic-app-scripts/src/build.ts` on line 76 checks to see if the compilerOptions.sourceMap property is set, and uses that as a validity check.  However, this is also a valid tsconfig file:

```
{
  "extends": "./config/base"
}
```

According to the tsconfig documentation: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends

#### What behavior are you expecting?

Valid tsconfig.json files to get passed through to tsc.

**Steps to reproduce:**
1. Rename _tsconfig.json_ to _base.json_ and move it  a sub folder named 'config'
2. Create a new file in the root named _tsconfig.json_
3. Add the following to the _tsconfig.json_ file
```
{
  "extends": "./config/base"
}
```
4. Try to run _ionic serve_

The code will error.  Then comment out the code starting at line 76 and the code will work properly.

**Which @ionic/app-scripts version are you using?**

 @ionic/app-scripts@1.0.0

**Other information:** 

It seems to me like ionic shouldn't do a validity check of that file, and just let _tsc_ say if the file is valid or not.

** Workaround **

Add those properties to the tsconfig.json file:

```
{
  "extends": "./config/base.json",
   "compilerOptions": {
    "sourceMap": true
  }
}
```

**Comment by danbucholtz** [comment]
Sorry, that's outside of the scope of Ionic at this time. There are too many higher priority items for us. While it is technically a supported option, there simply isn't enough interest in us for it to be worth the cost of implementation. We'll take a well-tested PR if you're open to it.

Thanks,
Dan

**Comment by robrohan** [comment]
This is removing code not adding code.
