### ISSUE TITLE
Production build does not work with multiple-outputs

### ISSUE THREAD

**Issue by Nilos** [driftyco/ionic-app-scripts#746]
#### Short description of the problem:

If I use multiple output targets in my webpack config, production builds do not work because one of them has not been compiled using ngc.

My webpack config contains this part:
```
module.exports = {
  entry: {
    login: path.resolve("src/login/login.ts"),
    main: path.resolve("src/app/main.ts"),
  }
}
```
#### What behavior are you expecting?
NGC should be able to pick up multiple entry points.

**Steps to reproduce:**
1. Choose a webpack config with multiple output targets
2. Run build --prod
3. One of the compiled files does not work

**Which @ionic/app-scripts version are you using?**
1.0.0

**Comment by danbucholtz** [comment]
Sorry, we don't support multiple entry points right now. We may get to it at some point but it won't be for a bit.

Thanks,
Dan

**Comment by Nilos** [comment]
I might have a Pull Request in the future is there interest in getting this to work one way or another?

**Comment by Nilos** [comment]
I at least have a working version for myself right now but the code is really unclean

**Comment by danbucholtz** [comment]
We'd take a well-tested PR, sure.

Thanks,
Dan
