### ISSUE TITLE
1.1.0 now ok with deep linking?

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#748]
Hi,

The CHANGELOG of 1.0.1 clearly displayed, that this version of ionic-app-scripts wasn't suitable for people using deep linking. 

The CHANGELOG of 1.1.0 doesn't mention anything about that. Do that mean "now it's ok for deep linking user too" or does that mean "nope, still not good, otherwise we would have said something"?

Thx in advance for clarifying the situation

**Comment by danbucholtz** [comment]
Yes, it's behind a flag now.

Thanks,
Dan

**Comment by peterpeterparker** [comment]
cool thx for the feedback @danbucholtz ... I gonna try this version then ;)
