### ISSUE TITLE
Which version of rxjs should be use?

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#749]
Hi,

ionic-app-scripts (and ionic-native) use rxjs@5.0.1
ionic-angular@2.0.1 still use rxjs@5.0.0-beta.12

which version should be use then?

best regards

p.s.: right now I've got rxjs@5.0.0-beta.12 in my package.json, when I install the last version of ionic-app-scripts I get:

UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12

npm WARN @ionic-native/camera@3.0.0-alpha.1 requires a peer of rxjs@^5.0.1 but none was installed.

**Comment by danbucholtz** [comment]
Hi @peterpeterparker,

Sit tight on this one. I _think_ you could update to rxjs 5.0.1 without issue. We are about to update the dependencies across the board in `ionic-angular 2.1.0` next week.

Thanks,
Dan
