### ISSUE TITLE
rollup.config.js changes on updates

### ISSUE THREAD

**Issue by javebratt** [driftyco/ionic-app-scripts#75]
Based on a conversation with @jgw96 we noticed that when updating `npm install --save @ionic/app-scripts@latest` all the changes made to the `rollup.config.js` disappear and we get the factory file again.

Since the only way to get 3rd party libraries like Firebase working is updating this file it will be better if the file didn't have to change.

Don't know if this is a bug or it is the intended behavior because you are working on fixing the compatibility issues in a different way.

On a side note, I do understand the decision to go with Rollup, I've experienced first hand the speed improvements :smile:

**Comment by jgw96** [comment]
Hey! So here is a [link](https://github.com/driftyco/ionic-app-scripts#npm-config) that goes over how to add a custom rollup.config to your app that will not get overwritten when updating app-scripts. We are planning on making some docs to make this easier to find and a little less low level. Thanks!
