### ISSUE TITLE
failed with overriding the 'ionic_node_modules_dir' in package.json 

### ISSUE THREAD

**Issue by GuoLunHao** [driftyco/ionic-app-scripts#751]
I wanna custom the node_modules path in my ionic project, so that several ionic projects can use the same node_modules folder. I edit the package.json file as follow

`  "config": {
    "ionic_node_modules_dir": "another_node_modules"
  },`

and another_node_modules is a folder renamed from origin node_modules.  After that, I run the script 'ionic serve', it shows the warnning that "No node_modules directory found, do you need to run npm install?". And it says cannot find the ionic-app-scripts . If I run the script "npm install", it'll generate another node_modules folder. It seems the overriding has no effect.  

I use the 1.1.0 version on windows.

**Comment by danbucholtz** [comment]
This won't work because the Ionic CLI needs to know where to look to launch app-scripts. This value shouldn't be configurable. I'm going to change that in the next release.

Thanks,
Dan

**Comment by GuoLunHao** [comment]
Thanks for reply, Dan.  Do you mean that I shouldn't change the node_modules path by by custom configuration in  package.json  file?  Is there other way I can do to change the path?

**Comment by danbucholtz** [comment]
I don't think setting that value is the best way to do it. I took it out in the most recent version of @ionic/app-scripts. I think (maybe) what you're looking for is [NPM link](https://docs.npmjs.com/cli/link).

Thanks,
Dan
