### ISSUE TITLE
ionic_experimental_manual_treeshaking and ionic_experimental_purge_decorators always performed?

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#752]
Hi,

I tried ionic-app-scripts 1.1.0. I build (ionic build iOS --prod) my app using the three following config in package.js and the resulting main.js always reached the same size, 4,4 Mo, even when I didn't specify that I wanted to try tree shaking and purge decorator.

Ok it's 200ko less than before (with 1.0.0), but since these operations should had been optional, I'm a little bit confuse.  Were these operations performed or not?

    "config": {
    "ionic_sass": "./scripts/sass.config.js",
    "ionic_copy": "./scripts/copy.config.js",
    "ionic_source_map_type": "source-map"
     }

    "config": {
    "ionic_sass": "./scripts/sass.config.js",
    "ionic_copy": "./scripts/copy.config.js",
    "ionic_source_map_type": "source-map",
    "ionic_experimental_manual_treeshaking": true,
    "ionic_experimental_purge_decorators": true
    }

    "config": {
    "ionic_sass": "./scripts/sass.config.js",
    "ionic_copy": "./scripts/copy.config.js",
    "ionic_source_map_type": "source-map",
    "ionic_experimental_manual_treeshaking": "true",
    "ionic_experimental_purge_decorators": "true"
     }

**Comment by danbucholtz** [comment]
No, the logic behind the flags should not run unless the flag is set. Eventually it will be automatic but we're still testing/validating right now.

We updated to newer dependencies which may result in improved tree shaking.

Thanks,
Dan

**Comment by peterpeterparker** [comment]
@danbucholtz thx for the answer, but it isn't strange that with or without the flag my bundle size at the end was the same?

**Comment by danbucholtz** [comment]
@peterpeterparker,

It is a little strange I guess. Can you dive in and see if they're running when they shouldn't be? Is it a large app that uses most components? Or is it pretty much an empty app?

We use `source-map-explorer` to troubleshoot. It lets you inspect the bundle easily and see what it's composed of.

Thanks,
Dan

**Comment by peterpeterparker** [comment]
@danbucholtz it's kind of a large app, at least in number of pages.  I gonna try to do my best to dig a little bit more for sure, thx.

p.s.: Justin and Mike just played a little bit with my app, because my build is huge (4.6 Mb). If you want to have fun with too, drop me an email ;)

**Comment by peterpeterparker** [comment]
@danbucholtz I tried with 1.1.2 and here's my result running "ionic build iOS --prod"

mains.js size / app-script version / experimental flags 

4.6 mb / 1.1.0 / false
4.4 mb / 1.1.2 / false
4.3 mb / 1.1.2 / true

seems that the flags are correctly interpreted then
