### ISSUE TITLE
blank template - large main.s

### ISSUE THREAD

**Issue by philrob** [driftyco/ionic-app-scripts#753]
Hi Dan,

Did...
ionic build android --prod
... with ionic-app-scripts 1.1.0 and main.js is still over 1Mb (1087Kb to be exact) which seems excessive?
Is that what you expect with new optimizations as 'blank' template is only a single page with a tiny bit of text or, will this be improved as more optimizations are added. Splash screen fades after 3 secs (default) to black screen with ui appearing about 1 sec later. Total launch time Nexus 7 (2013) running Android 6.0.1 is therefore ~4 secs.
Cheers Phil Rob

**Comment by danbucholtz** [comment]
As I've mentioned to you specifically numerous times, we're well aware this is an issue and we're working on it. Please stop creating issues about it. We use issues to track the work that we're doing. There is no action to take on this ticket.

The blank starter _should_ be much smaller. There are several factors contributing to why it's not. We're resolving these factors one at a time. This is our highest priority item. That has not changed.

Thanks,
Dan
