### ISSUE TITLE
Version 1.0.0: own copy font doesn't copy directory anymore

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#755]
I'm using ionic-app-scripts 1.0.0

#### Short description of the problem:
I didn't played with my fonts for a while I've to say. 

First I noticed that starting the build (ionic build iOS --prod) didn't cleared the www/build/assets/fonts folder, but that's probably normal with my config I guess.

Then I deleted the files by myself and noticed that the font-awesome fonts weren't copied anymore.

#### What behavior are you expecting?

When providing an own ionic_copy scripts, the copy of directory should be possible too (as it used to be).

**Steps to reproduce:**
1. in package.json providing own copy, for example

    "config": {
        ionic_copy": "./scripts/copy.config.js"
     }

2. then in script try to set a copy of the font-awesome fonts folder

       copyFonts: {
           src: ['{{ROOT}}/node_modules/ionicons/dist/fonts/**/*', '{{ROOT}}/node_modules/ionic-angular/fonts/**/*', '{{ROOT}}/node_modules/font-awesome/fonts/'],
           dest: '{{WWW}}/assets/fonts'
      }

=> not gonna work. no font-awesome fonts gonna be copied in www/build/assets/fonts

but if I add a * to {{ROOT}}/node_modules/font-awesome/fonts/, the font-awesome fonts gonna be flat copied (without their directories font-awesome/fonts/)

    copyFonts: {
        src: ['{{ROOT}}/node_modules/ionicons/dist/fonts/**/*', '{{ROOT}}/node_modules/ionic-angular/fonts/**/*', '{{ROOT}}/node_modules/font-awesome/fonts/**/*'],
        dest: '{{WWW}}/assets/fonts'
    }

**Comment by danbucholtz** [comment]
This is not a bug, this is how globs work. The `'{{ROOT}}/node_modules/font-awesome/fonts/**/*'` is the correct syntax you want.

Thanks,
Dan

**Comment by peterpeterparker** [comment]
ok @danbucholtz, plz excuse myself then for having opening that issue

**Comment by danbucholtz** [comment]
😸  no worries!

Thanks,
Dan
