### ISSUE TITLE
About the --aot option

### ISSUE THREAD

**Issue by andrevcf** [driftyco/ionic-app-scripts#756]
Sorry if this is off-topic but I searched and not find a answer.
What is the difference between --aot and --prod?

**Comment by danbucholtz** [comment]
`--aot` only does `--aot` and does not do optimizations or minification.

Prod does AoT, minification, and optimizations.

When I want to debug optimizations, I use `npm run ionic:build --aot --optimizejs`

Thanks,
Dan
