### ISSUE TITLE
Components not rendering when running `--prod` flag

### ISSUE THREAD

**Issue by eafif** [driftyco/ionic-app-scripts#757]
#### Short description of the problem:
[Here a simple repo](https://github.com/eafif/ionic-aot-bug) that could be used to replicate the issue. In this case, I am using the `Ng2HighchartsModule` to render a simple chart on the main page.

![img_1848 2](https://cloud.githubusercontent.com/assets/4964765/23005391/4996c5fe-f3ca-11e6-8e21-b6afde310077.PNG)

When generating a build without the `--prod` flag, the chart is displayed on an iOS device (iPhone 6 or Emulator). 
When generating the build  with the `--prod` flag, the chart is not displayed (on the same iOS devices). 
No errors are raised in both cases.

#### What behavior are you expecting?
The chart should display in both cases.

**Steps to reproduce:**
[You can use this repo for code base](https://github.com/eafif/ionic-aot-bug).

Steps that will show the chart:
1. `npm run ionic:build` (in dev mode)
2. `ionic build ios`
3. Open the Xcode project and launch on iOS device - The chart will load

Steps that will not show the chart:
1. `npm run ionic:build --prod`
2. `ionic build ios`
3. Open the Xcode project and launch on iOS device - The chart will not load and no errors are reported

**Which @ionic/app-scripts version are you using?**
Happens with both 1.0.0 and 1.1.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

```
ionic info
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v7.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002 
```

**Comment by danbucholtz** [comment]
Thank you for the detailed issue. I'll take a look.

Thanks,
Dan

**Comment by danbucholtz** [comment]
This has to do with the `ngc` metadata changing in angular 2.3. Try running Angular 2.4.8. We are releasing Ionic 2.1 with a default of 2.4.8 this week. It should be a drop in replacement.

Thanks,
Dan

**Comment by eafif** [comment]
Thanks @danbucholtz. However 2.4.8 seems to break some components of Ionic as [per here](https://github.com/driftyco/ionic/commit/98e8158b9c03e142a50e79b6e754f9f0fa2a0233).

Any other suggestions that come to mind or should I just wait for Ionic compatibility with 2.4.8?

**Comment by danbucholtz** [comment]
@eafif, more than likely it will be fine. We are going to ship 2.4.8 support this week or next. The only reason it missed the last release is we needed to do testing. `@ionic/storage` was broken due to changes in the dependency injection system. We published a beta version of those changes and will make them widely available soon.

Thanks,
Dan
