### ISSUE TITLE
Proxy urls are being ignored

### ISSUE THREAD

**Issue by Ladeiras** [driftyco/ionic-app-scripts#759]
#### Short description of the problem:
Since 1.1.1 "proxies" urls, in ionic.config.json, are not set on build

#### What behavior are you expecting?
![appscripts](https://cloud.githubusercontent.com/assets/5716992/23028477/601ce674-f45f-11e6-971e-40e72ce870d1.png)

This is used to bypass CORS problem by setting a proxy to localhost (dev server).

**Steps to reproduce:**
1. Go to [http://blog.ionic.io/handling-cors-issues-in-ionic/](http://blog.ionic.io/handling-cors-issues-in-ionic/)
2. "Setting up the proxy urls" section

```
{
  "name": "proxy-example",
  "app_id": "",
  "proxies": [
    {
      "path": "/api",
      "proxyUrl": "http://cors.api.com/api"
    }
  ]
}
```

**Which @ionic/app-scripts version are you using?**
1.1.2

**Other information:**
I'm using 1.1.0 until this issue gets resolved

**Comment by danbucholtz** [comment]
Fixed in `nightly`, will likely publish an official version tomorrow. Sorry about that.

Thanks,
Dan
