### ISSUE TITLE
Built-in support for Android multiple APK (crosswalk)?

### ISSUE THREAD

**Issue by astec** [driftyco/ionic-app-scripts#76]
Is there exist support for [multiple APK](https://developer.android.com/google/play/publishing/multiple-apks.html) on Android?

People use it with [Crosswalk](https://crosswalk-project.org) to [target old Android devices](https://github.com/angular/material/issues/5900#issuecomment-160193882) with version <= 4.3.

Currently there are roughly [15% of Android users with "Jelly Bean"](https://developer.android.com/about/dashboards/index.html) platform version.

If it's not supported any plans to support it "out of the box" in nearest future?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! You can definitely use Crosswalk with Ionic 2. To install Crosswalk you can follow their docs [here](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview). Thanks!

**Comment by astec** [comment]
@jgw96 thanks for prompt reply, though the question not about using Crosswalk, but about possibility easily to generate multiple APKs. Especially using https://docs.ionic.io/services/package/
