### ISSUE TITLE
ionic_experimental treeshaking/decorator flags: promise error while using xcode simulator

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#763]
#### Short description of the problem:

When I try to open the menu (click on the "hamburger" icon top left corner), an exception is thrown

#### What behavior are you expecting?

No error should be thrown

**Steps to reproduce:**

1. Build app "ionic build ios --prod" with experimental flags ionic_experimental_manual_treeshaking and ionic_experimental_purge_decorators set to true
2. Open Xcode and debug the app in simulator
3. Open the menu

**Which @ionic/app-scripts version are you using?**

1.1.2 (nightly 1.1.2-201702170425)

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

- Debugging with "ionic serve" or with Xcode simulator but without the experimental flags doesn't throw any error, everything goes fine

- Xcode stacktrace:

2017-02-17 10:58:01.634 MyApp[6532:255896] ERROR: Unhandled Promise rejection: undefined is not a constructor (evaluating 'new s[t](e,n)') ; Zone: angular ; Task: HTMLButtonElement.addEventListener:click ; Value: TypeError: undefined is not a constructor (evaluating 'new s[t](e,n)') create@file:///Users/me/Library/Developer/CoreSimulator/Devices/.../MyApp.app/www/build/main.js:7:8387

- Ionic info:

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.2
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by ghenry22** [comment]
This is very similar to what I see in #770

**Comment by danbucholtz** [comment]
Tracking in 770 as a dupe.

https://github.com/driftyco/ionic-app-scripts/issues/770

Thanks,
Dan
