### ISSUE TITLE
File watching doesn't work on a virtual machine

### ISSUE THREAD

**Issue by alexander-alzate** [driftyco/ionic-app-scripts#769]
The system doesn't watch for changes on file being edited on a virtual machine in a shared folder.

I use vagrant and virtualbox to simulate the development environment and I edit the files from the host machine, the changes are not reported and I have to restart the server (`ionic serve`).
I tried to `touch` the files being edited from guest and it works once, when I fire the command again the changes are not reported.

- Host: Archlinux
- Guest: Archlinux
- $ `ionic info`:
~~~
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.9
Node Version: v7.5.0
Xcode version: Not installed
~~~
- Vagrantfile:
~~~{.rb}
# Most comments are droped
Vagrant.configure("2") do |config|
  config.vm.box = "ogarcia/archlinux-x64"
  # Ionic 2 Development Server
  config.vm.network "forwarded_port", guest: 8100, host: 8100

  # Ionic 2 Live Reload Server
  config.vm.network "forwarded_port", guest: 35729, host: 35729

  # Dev Logger Port
  config.vm.network "forwarded_port", guest: 53703, host: 53703

  # Karma Test Server
  config.vm.network "forwarded_port", guest: 9876, host: 9876

  # System upgrade
  config.vm.provision "Update System", type: "shell", inline: "pacman -Syu --noconfirm --force"

  # Install Ionic 2 required dependencies
  config.vm.provision "Install dependencies", type: "shell", inline: <<-SHELL
	pacman -S nodejs npm --noconfirm --force
	npm install -g typescript typings
  SHELL

  # Install Ionic 2
  config.vm.provision "Install Ionic 2", type: "shell", inline: "npm install -g cordova ionic "
end
~~~

**Comment by danbucholtz** [comment]
Hi @alexander-alzate,

Sorry, this is likely outside of the scope of app-scripts. We use `Chokidar` for watching files, and if that doesn't report a change, there isn't much we can do. It's the best file watching library available for Node. We'd be open to a well-tester PR but it doesn't seem like this would be an easy fix.

Thanks,
Dan
