### ISSUE TITLE
Kinvey / rollup - could not resolve error

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic-app-scripts#77]
I *think* this is rollup related, or it could be rollup AND Typings

Getting

> Error: Could not resolve 'kinvey-angular2-sdk' from

When using Kinvey's Angular 2 SDK library - on ionic serve - in the rollup phase

Written a forum post with more info
https://forum.ionicframework.com/t/kinvey-backend-rc0-typings-or-rollup-issue-help/65573

Includes a link to a fork of the ionic conference app, with the changes I have made to (unsuccessfully) make this work

There was an issue in ionic about this and a similar error on Pouch DB (closed) but I see you want build issues here now......

Thanks!

(Side note, keep going through the pain - Loving the look of RC0 - but its certainly a jump from Beta 11!)

**Comment by danbucholtz** [comment]
@alexbainbridge,

I don't think it's a typings issue.  What does your import statement look like?

How are you using the lib?

Thanks,
Dan

**Comment by alexbainbridge** [comment]
Hi @danbucholtz 

I put it up here
https://github.com/alexbainbridge/ionic-conference-app/

Specifically these 3 file changes are the only changes I am made
https://github.com/alexbainbridge/ionic-conference-app/commit/e781252521230c822e587f79f90d8ef43ecea4f1

or more specifically
import Kinvey from 'kinvey-angular2-sdk';

I am not clear whether what I did with declarations is right.... 

Their typings file is 
https://github.com/Kinvey/angular2-sdk/blob/master/kinvey.d.ts 
Which I am not sure about either..... 

Yes I was pretty convinced that there IS a rollup issue. It may not be the only issue however

Thank you for looking at this. 

Alex

cc @ThomasConner the Kinvey library author

**Comment by ThomasConner** [comment]
I should have more time later in the week to commit at trying to resolve these issues. I am currently tied up working on some other libraries we support at Kinvey. Just wanted to give a heads up.

**Comment by alexbainbridge** [comment]
Thanks @ThomasConner - sorry for copying you in - knew you and I were looking at it already - If Dan gets to something that needs tweaking your end - I wanted you to see how we got to that point

Thanks Thomas and Dan!

**Comment by danbucholtz** [comment]
All,

We've posted some docs on the subject. Note: They match a version of `@ionic/app-scripts` that will be dropped in the next day or so. 95% of the concepts still apply.

http://ionicframework.com/docs/v2/resources/third-party-libs/
http://ionicframework.com/docs/v2/resources/app-scripts/

[Here's](https://github.com/danbucholtz/ionic-rollup-angularfire2) an example with AngularFire2.
[Here](https://github.com/danbucholtz/ionic-third-party-lib-mega-test/blob/master/package.json) is a project I implemented that has every library in it that Ionic users have reported trouble with. Most of the libraries worked, but a couple did not. [Here](https://docs.google.com/spreadsheets/d/124VhzYm5gHrBowWAUolfOsVBNTcxTELWauAjKKWAUBQ/edit?usp=sharing) is the summary of the findings.

Please let me know how everything goes. Since we shipped the documentation, we are going to close this issue now.

Thanks,
Dan

**Comment by alexbainbridge** [comment]
Hi @danbucholtz 

Thanks for testing the Kinvey Library (results linked on "here" - in note above) 

I see Kinvey was works by default: no - workaround: no 

"Super expression must either be null or a function, not undefined" exception" 

Sadly I don't understand that what that means. Is that an action for Kinvey to change their library?

Thanks
Alex

**Comment by danbucholtz** [comment]
That was a runtime exception that I received when bundling the kinvey library. I am not sure how to get around it. It may be a bug in Kinvey, it may not be. The best bet is to probably do a script tag include (old school 😄 ) as described [here](http://ionicframework.com/docs/v2/resources/app-scripts/) in the `script tag include` section.

Thanks,
Dan

**Comment by alexbainbridge** [comment]
Hi Dan
I never got that error - I was blocked at Rollup. Any hints as to where you saw that error message? 

I will give the script direct call concept a go.....  might need Thomas's help on this as there are multiple JS files, not quite sure which are key

**Comment by danbucholtz** [comment]
You should be able to roll it up.

http://ionicframework.com/docs/v2/resources/app-scripts/

Sorry, we need a link to the exact section, but search for "Task Details" and read the bundle section.

Thanks,
Dan

**Comment by alexbainbridge** [comment]
@danbucholtz the other thing is I was very specific that need to test the Kinvey library from GITHUB not from NPM

i.e. this in package.json
"kinvey-angular2-sdk": "https://github.com/Kinvey/angular2-sdk.git"

not
"kinvey-angular2-sdk": "^3.1.0",

If you have a couple of minutes - could you try with that - rather than NPM - and see if you have the same outcome?

Probably explains why I didn't get the same error as you :)

Thanks

**Comment by alexbainbridge** [comment]
@danbucholtz I have "solved" this by using another Kinvey library - their HTML 5 library - and a direct script import. Means I have to call zone.run when I want to update the UI, but I can handle that, and at at least unblocks me.

Will come back to this problem later! (as would be great to use via NPM, and without zone.run) 

I think its now something to do with Kinvey using webpack to create a bundle..... so rollup is missing their webpack configuration.... maybe
