### ISSUE TITLE
ionic_experimental_treeshaking error with sidemenu

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic-app-scripts#770]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
enabled experimental treeshaking & purge decorators.
build is successful & app launches fine
when clicking on the hamburger icon to open the side menu an error is thrown in the javascript console (see screenshot attached for exact error)
this is a --prod build so there is also an error thrown about no js.map file present in chrome but I believe that is expected with a prod build?

#### What behavior are you expecting?
clicking the hamburger opens the side menu without throwing exceptions as usual.

**Which @ionic/app-scripts version are you using?**
appscripts 1.1.3
ionic 2.0.1

side menu handling is basically the same as the base sidemenu template (as that is where I started from long ago...) but I have a couple of ngIf's in there to display different menu items based on some user settings.  All works perfectly once I disable these new experimental settings.

I am using the ionic wkwebview plugin on ios 10
also tested with android device and the error and behaviour is the same so doesn't appear to be platform dependant.

**Comment by ghenry22** [comment]
![2017-02-21 09_06_38-os x 10 11 - vmware workstation](https://cloud.githubusercontent.com/assets/7463213/23146911/f5aab018-f815-11e6-8f52-a6efbfebbf69.png)

**Comment by danbucholtz** [comment]
Thanks for the feedback. I am digging into some issues with these flags today to smooth them out and remove them from the experimental stage.

Thanks,
Dan

**Comment by ghenry22** [comment]
@danbucholtz just let me know once you're ready and I'll gladly run some builds and report the results

Other than this the app seemed to be working normally (the bits I could get to without the sidemenu) and the filesize was reduced.

**Comment by ghenry22** [comment]
I still see the exact same issue with ionic v3.0 and appscripts 1.3.0 with these flags enabled.  Everything else seems to work fine.  Would be cool if there was a solution as shrinking the final bundle size definitely makes a difference.

**Comment by ghenry22** [comment]
This is resolved with latest ionic and app-scripts
