### ISSUE TITLE
cannot install app

### ISSUE THREAD

**Issue by yasar-salim** [driftyco/ionic-app-scripts#771]
#### cannot install app while building for publishing

```
ionic build android --prod --release
```

**Which @ionic/app-scripts version are you using?1.0.0**

**Comment by ghenry22** [comment]
Does it work without the --release flag?

When using --release you still have to sign and zipalign the generated apk before it can be installed on a real device.  These are additional manual steps outside of the ionic build process that just generates the base apk file.

**Comment by yasar-salim** [comment]
@ghenry22  the above command works for previous versions. Let me check it

**Comment by yasar-salim** [comment]
@ghenry22 works for me . thanks
