### ISSUE TITLE
Increase timeout for startWatcher

### ISSUE THREAD

**Issue by Ritzlgrmft** [driftyco/ionic-app-scripts#772]
#### Short description of the problem:
Currently my machine is too slow to start the watching of my app in 3 seconds. Therefore `ionic serve` produces:

```
...
[10:28:18]  build dev finished in 52.67 s
[10:28:22]  watch failed: A watch configured to watch the following paths failed to start. It likely that a file
            referenced does not exist:
            ...\src\**\*.(ts|html|s(c|a)ss)
```

#### What behavior are you expecting?
It should be possible to use `ionic serve` also if the start of watching needs longer than 3 seconds.

I changed the timeout in `node_modules\@ionic\app-scripts\dist\watch.js` to 30 seconds. 
Then everything worked as expected.

**Which @ionic/app-scripts version are you using?**
1.1.3

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
Fixed in 1.1.4, it's now configurable. See the readme for `IONIC_START_WATCH_TIMEOUT` property.

Thanks,
Dan
