### ISSUE TITLE
[Feature Request] allow tsConfig 'excludes' to be extended for builds to easily support unit testing

### ISSUE THREAD

**Issue by Barryrowe** [driftyco/ionic-app-scripts#774]
#### Short description of the problem:

When ionic-app-scripts builds the ts configuration and runs the transpile task, it just reads the project level tsconfig.json.  This is fine if you only have source files you want to bundle, but many teams keep their *spec files as siblings to the files they test.

Adding '*spect.ts' to the main tsconfig.json file is not an answer, because most editors will read this and not provide Typescript help in those files as you're working in them.

#### What behavior are you expecting?

When running a build, a set of tsconfigExcludes would be pushed onto the ```tsConfigFile.config.exclude``` array in the transpile task.

**Steps to reproduce:**
1. Create a project with unit test setup (this is a complicated process, but there are examples around)
2. Add a something.spec.ts file with a unit test in the src directory
3. Attempt to build/serve

**Which @ionic/app-scripts version are you using?**

ionic-app-scripts 1.1.3

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

We are working around this right now by inserting the following code at line 284 of node_modules/@ionic/app-scripts/dist/transpile.js (254 prior to v1.1.3 of ionic app scripts):

```Javascript
  if(tsConfigFile.config){
        var excludePatterns = ["**/*spec.ts", "mocks"];
        if(tsConfigFile.config.exclude){
          tsConfigFile.config.exclude.push(...excludePatterns);                    
        }else{
          tsConfigFile.config.exclude = excludePatterns;
        }
    }
```

This could be pretty easily modified to pull the exclude patterns from the ```config``` options in package.json like 

```
"config":{
    "ionic_compile_excludes":["*spec.ts", "mocks"]
}
```

The solution in bug #157 will get past this compile issue, but from what I can tell just allows the spec files to be bundled into the resulting compiled JS.

**Comment by danbucholtz** [comment]
You can pass in a separate tsconfig.json if you'd like. I believe it is configurable.

Thanks,
Dan

**Comment by Barryrowe** [comment]
@danbucholtz  Thanks for that. I have been keeping an eye on the table above that long list and waiting for it to show the tsconfig file as overrideable, and missed the addition in the longer table. That looks like what I was looking for just missed it

The reason I want to exclude the spec files from the ionic build process is because I don't want them involved in the ionic bundling process (until maybe a test runner is built into app-scripts down the road). We have karma or wallaby running our specs as we develop, and there's not a need for the ionic scripts to manage them at all. 

I don't want to introduce types and dependencies for unit tests into the build transpile process. Basically, since ionic app-scripts "hides" the webpacking and bundling, I don't want there to be any chance our spec files end up as just dead code in the output bundles.

**Comment by danbucholtz** [comment]
Understood. They shouldn't be but I do see your point. The bundlers only know about the entry point.

The table is huge now 😹 . We're going to redo the docs in the coming weeks. It's just a medium priority in a world of high priorities.

Thanks,
Dan

**Comment by Barryrowe** [comment]
Good point about the webpack entry point. As long as it's pointed to main.ts always, I guess there's not a big danger of specs getting bundled in.

This gives us the tools we need to make the right decisions for us though, so thanks for the info.

-Barry
