### ISSUE TITLE
main.js size should be reduced for PWA

### ISSUE THREAD

**Issue by itrethan** [driftyco/ionic-app-scripts#776]
#### Short description of the problem:

I have a reasonable small app build for PWA, but the main.js file is 2.5M when build in prod. It's too large to load in browser and take long time.

#### What behavior are you expecting?

main.js should not include everything, it should be modulized and load on demand.

**Comment by LarsSaalbach** [comment]
@itrethan That is already an big task on ionic with tree shaking etc.
So this issue was already created 10-20 times. I don't think a topic 21 will help more.

**Comment by danbucholtz** [comment]
This is our #1 priority and we're working on it. We'll have more to share soon.

Thanks,
Dan
