### ISSUE TITLE
Watch issue

### ISSUE THREAD

**Issue by michaelgeorgeattard** [driftyco/ionic-app-scripts#778]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

Watch is not working.

#### What behavior are you expecting?

**Steps to reproduce:**
1. npm run watch

```
[17:05:51]  watch failed: A watch configured to watch the following paths failed to start. It likely that a file
            referenced does not exist: xxx\src\**\*.(ts|html|scss)
[17:05:51]  ionic-app-script task: "watch"
[17:05:51]  Error: A watch configured to watch the following paths failed to start. It likely that a file referenced
            does not exist: xxx\src\**\*.(ts|html|scss)
```

**Which @ionic/app-scripts version are you using?**

1.1.3

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

![untitled](https://cloud.githubusercontent.com/assets/5755302/23267146/25a6aa08-f9ea-11e6-96bd-8ecd2dda56a4.png)

Increasing timeout in watch.js to 10000 fixes the issue for me.

**Comment by danbucholtz** [comment]
Fixed in 1.1.4, it's now configurable. See the readme for `IONIC_START_WATCH_TIMEOUT` property.

Thanks,
Dan
