### ISSUE TITLE
Can't copy custom files to same destination

### ISSUE THREAD

**Issue by jabas06** [driftyco/ionic-app-scripts#78]
I've an issue setting a custom config file for the Copy task. If I add a new source entry with the same destination than a previous one, the content of the second source is not copied. Example, I'm want to add the font-awesome fonts like this, but doesn't work.

```javascript
module.exports = {
    include: [
       // Other sources
        {
            src: 'node_modules/ionicons/dist/fonts/',
            dest: 'www/assets/fonts/'
        },
        {
            src: 'node_modules/font-awesome/fonts/',
            dest: 'www/assets/fonts/' 
        },
    ]
};
```

Changing the destination folder for font-awesome works, but I want all the fonts in the same folder.

This works.
```javascript
module.exports = {
    include: [
       // Other sources
        {
            src: 'node_modules/ionicons/dist/fonts/',
            dest: 'www/assets/fonts/'
        },
        {
            src: 'node_modules/font-awesome/fonts/',
            dest: 'www/assets/fonts2/' 
        },
    ]
};
```

My environment:
Ionic Framework Version: 2.0.0-rc.0                                                                                                                
Ionic CLI Version: 2.1.0                                                                                                                           
Ionic App Lib Version: 2.1.0-beta.1                                                                                                                
OS: Windows 10                                                                                                                                   
Node Version: v6.6.0

**Comment by appdezign** [comment]
Since this fix, my updates of json files (like /src/assets/data/data.json), are not being copied to /www/assets/.
I don't understand why you would set clobber to false. Now it will only copy new files, which is fine for images and icons, but with text files it doesn't make sense.

**Comment by mg1075** [comment]
Is this issue really closed?

I just pulled down the conference app, ran npm install, then ionic serve.

During ionic serve, a message comes back about "**copy: Error copying**...\ionic-angular\fonts to ...\www\assets\fonts", and then the app gives an error about '**Cannot find module "localforage"**'.

Environment:
Ionic Framework Version: 2.0.0-rc.3-201612081620
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v4.4.3
Xcode version: Not installed

**Comment by Langstra** [comment]
@mg1075 I have the same issue as you are referring to, but without the error about cannot find module localforage. @danbucholtz Maybe worth to reopen this one?

**Comment by danbucholtz** [comment]
We made a bunch of changes to the copy task that are available in `0.0.47`.

Thanks,
Dan

**Comment by mg1075** [comment]
@danbucholtz - And now I can't build after doing 0.0.47 and npm install. Had to revert to 0.0.45.

![image](https://cloud.githubusercontent.com/assets/2031435/21115821/9278074a-c078-11e6-9966-51a109bb1edf.png)

**Comment by danbucholtz** [comment]
@mg1075, Can you give some more info? Did you follow the instructions? Can you run `ionic serve --debug` and then `npm run ionic:build --debug`?

Thanks,
Dan
