### ISSUE TITLE
sh: ionic-app-scripts: command not found

### ISSUE THREAD

**Issue by mehrad-rafigh** [driftyco/ionic-app-scripts#782]
#### Short description of the problem:
Hello ionic community. I am experiencing a strange issue which I cannot resolve. 
When I use `ionic build android --prod --release` on my local Macbook Pro, an APK gets spit out.

This is the output of `ionic info` of my local MBP:
```
Your system information:

Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.6.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

When I run the same command on our my MacMini which is supposed to build the apks in release mode and sign them, I got an error. 

First of `ionic info` of the MacMini:
```
Your system information:

Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.6.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

The error I get is:
```
sh: ionic-app-scripts: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build "--prod" "--release"`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build "--prod" "--release"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build "--prod" "--release"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/iosdeploy/.npm/_logs/2017-02-25T12_21_45_016Z-debug.log
```

The npm log states:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'ionic:build',
1 verbose cli   '--',
1 verbose cli   '--prod',
1 verbose cli   '--release' ]
2 info using npm@4.4.0
3 info using node@v7.6.0
4 verbose run-script [ 'preionic:build', 'ionic:build', 'postionic:build' ]
5 info lifecycle ionic-hello-world@~preionic:build: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~preionic:build: no script for preionic:build, continuing
7 info lifecycle ionic-hello-world@~ionic:build: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~ionic:build: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~ionic:build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/iosdeploy/garcon-mobile-apps/bestellbar-debug-2017-02-25-13:19:33/bestellbar-hybrid/current-version/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle ionic-hello-world@~ionic:build: CWD: /Users/iosdeploy/garcon-mobile-apps/bestellbar-debug-2017-02-25-13:19:33/bestellbar-hybrid/current-version
11 silly lifecycle ionic-hello-world@~ionic:build: Args: [ '-c', 'ionic-app-scripts build "--prod" "--release"' ]
12 info lifecycle ionic-hello-world@~ionic:build: Failed to exec ionic:build script
13 verbose stack Error: ionic-hello-world@ ionic:build: `ionic-app-scripts build "--prod" "--release"`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:192:7)
13 verbose stack     at maybeClose (internal/child_process.js:890:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid ionic-hello-world@
15 verbose cwd /Users/iosdeploy/garcon-mobile-apps/bestellbar-debug-2017-02-25-13:19:33/bestellbar-hybrid/current-version
16 verbose Darwin 16.4.0
17 verbose argv "/usr/local/Cellar/node/7.6.0/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--" "--prod" "--release"
18 verbose node v7.6.0
19 verbose npm  v4.4.0
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error ionic-hello-world@ ionic:build: `ionic-app-scripts build "--prod" "--release"`
24 error spawn ENOENT
25 error Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build "--prod" "--release"'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the ionic-hello-world package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     ionic-app-scripts build "--prod" "--release"
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs ionic-hello-world
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls ionic-hello-world
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

Unfortunately no ionic command works on the MacMini

I have searched and founded similar issues here on github like  https://github.com/driftyco/ionic-cli/issues/1480 but no luck until now.

#### What behavior are you expecting?
When I run `ionic build android --prod --release` an APK gets build.

**Which @ionic/app-scripts version are you using?**
`cat package.json | grep @ionic/app-scripts
    "@ionic/app-scripts": "1.1.4"`

Thanks in advance

**Comment by mehrad-rafigh** [comment]
Solved my problem by just calling `node_modules/.bin/ionic-app-scripts build android --prod --release`

**Comment by DumildeMatos** [comment]
It can't start th server

dumildematos@dumildematos:~/Documents/Intel XDK App/myAppO$ ionic serve
WARN: No node_modules directory found, do you need to run npm install?

> ionic-app-base@ ionic:serve /home/dumildematos/Documents/Intel XDK App/myAppO
> ionic-app-scripts serve

sh: 1: ionic-app-scripts: not found

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:serve" "--"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ionic-app-base@ ionic:serve: `ionic-app-scripts serve`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ionic-app-base@ ionic:serve script 'ionic-app-scripts serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-app-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-app-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-app-base
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dumildematos/.npm/_logs/2017-04-05T11_03_13_207Z-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve

**Comment by danbucholtz** [comment]
This is likely user error. I'm not sure. Sorry.

Thanks,
Dan
