### ISSUE TITLE
localhost 8100 opens same file always while ionic serve command is applied for another file

### ISSUE THREAD

**Issue by skjainlky** [driftyco/ionic-app-scripts#785]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
Due to inactivity, we're closing this issue.

Thanks,
Dan
