### ISSUE TITLE
Could not resolve entry \.tmp\app\main.prod.ts

### ISSUE THREAD

**Issue by speedfl** [driftyco/ionic-app-scripts#789]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

ionic run android --prod make my builld failed with error:

```
    [10:16:37]  rollup started ...
  [10:16:37]  rollup failed: Could not resolve entry (D:\xx\git\pr\application\xx\.tmp\app\main.prod.ts)
  [10:16:37]  ionic-app-script task: "build"
  [10:16:37]  Error: Could not resolve entry (D:\xx\git\pr\application\xx\.tmp\app\main.prod.ts)
  Error: Could not resolve entry (D:\xx\git\pr\application\xx\.tmp\app\main.prod.ts)
      at error (D:\xx\git\pr\application\xx\node_modules\@ionic\app-  scripts\node_modules\rollup\dist\rollup.js:170:12)
      at D:\xx\git\pr\application\xx\node_modules\@ionic\app-scripts\node_modules\rollup\dist\rollup.js:9284:5

```

#### What behavior are you expecting?

The build should work

**Steps to reproduce:**
1.
2.
3.
```
package.json
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.6",
    "@types/cropperjs": "0.0.22",
    "cropperjs": "^1.0.0-alpha",
    "ionic-angular": "2.0.1",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "ng2-translate": "^5.0.0",
    "ng2-ui-auth": "^6.0.0",
    "pouchdb": "^6.0.6",
    "pouchdb-upsert": "^2.0.2",
    "qrcode-generator": "^1.0.7",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^1.1.4",
    "rollup-plugin-commonjs": "^6.0.0",
    "typescript": "^2.1.5"
  },
  "description": "xx: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "config": {
    "ionic_rollup": "./script/rollup.config.js",
    "ionic_sass": "./script/sass.config.js"
  }
}
```

**Which @ionic/app-scripts version are you using?**

latest

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

I went from app script 0.47 to 1.1.4 so maybe I forgot something. I added:

To go to 1.0.0 I added first 
npm install sw-toolbox --save --save-exact

Then I did
npm install @ionic/app-scripts@latest --save-dev

I looked at: 
https://github.com/driftyco/ionic/issues/8312

So message for ng2-translate has been done
The advice to go to last version (i am on it)
The advice to go to more recent typescript version (2.0.9) already done as I am in 2.1.5

I think I am no more in link with this issue has I removed the app.prod.ts app.dev.ts and created the app.main.ts like it was mentionned in the changelog of the 0.0.47

Here is the content:
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app.module';

platformBrowserDynamic().bootstrapModule(AppModule);
```

My tsconfig.json is exactly the same as the one mentionned in the changelog 0.0.47

I did not touched to ionic_source_map 

Do you maybe have an idea?

For information I also tried to downgrade all angular version to 2.1.0 and also to 2.0.1 (cli to 2.1.0) and I am getting same issue

my npm version 4.0.2
my node version 4.6.0

I created a startapp copied all my files did a npm install but still same issue

I created a startapp and just run ionic run android --prod and everything is working.
From what I can see the version of angular is the same. 

So I suspect a code issuue (or maybe a version of typescript 2.1.x vs 2.0.x in the startapp) but I have no logs....

**Comment by speedfl** [comment]
Found the issue!!!!

I overriden the rollup-config.js to handle pouchDB. However it was an old version (before app-script 0.0.47) But as I will remove it to use ionic storage I won't have problem anymore 

You can close the issue.

By the way the --prod is wonderfull. Only 5 secondes to start an app with more than 60 pages

Thanks continue like this (3 secondes would be perfect :p)

**Comment by danbucholtz** [comment]
Please update to a newer version of app-scripts. The .tmp folder went away.

Thanks,
Dan
