### ISSUE TITLE
Failed to load config.xml on production build for browser

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic-app-scripts#791]
#### Short description of the problem:
We build our app for browser and production doing this `ionic build browser --prod` we copy the files from `platforms/browser/www` to our webserver. We mapp the webserver app not to the root but to a subfolder.
So the app is deployed something like that:

> http://192.168.8.1/subfolder/index.html

On open the app from browser we got this error:
Failed to load resource: the server responded with a status of 404 (Not Found)
http://192.168.8.1/config.xml

![image](https://cloud.githubusercontent.com/assets/3778892/23556501/28044ea6-002d-11e7-8f7a-069d92915952.png)

#### What behavior are you expecting?
The app is searching the config.xml file from root but this is not this case, it is deployed under **subfolder** where the whole app is.

I think it could also be possible the config.xml should not be included and also not be loaded? It does not make sense have a file with `<allow-navigation href="http://192.168.8.121:8100" />` Could this be a potentially security problem?

**Which @ionic/app-scripts version are you using?**
1.1.4

**Comment by danbucholtz** [comment]
We don't support the browser platform currently.

Thanks,
Dan

**Comment by bruno-barros** [comment]
Hooo man, very bad to know that. What about that blog post about PWA?

**Comment by mburger81** [comment]
I'm intersted in  it too

**Comment by danbucholtz** [comment]
@bruno-barros,

We'll have a better PWA story soon.

Thanks,
Dan
