### ISSUE TITLE
Make linting an isolated step?

### ISSUE THREAD

**Issue by jthoms1** [driftyco/ionic-app-scripts#798]
_From @AlQuraian on March 7, 2017 15:27_

I was thinking if the linting process was out of the 'serve' process, for 2 reasons:
- Speed up the live-reloading
- Avoid having linting issues cluttering the terminal

Just a suggestion, Thanks!

_Copied from original issue: driftyco/ionic-cli#1955_

**Comment by danbucholtz** [comment]
You can already do this. Make a new `npm script` called `lint` to run `lint` just like serve. You can also disable `lint` in `serve`. Set `ionic_enable_lint` to `false` in package.json config.

Thanks,
Dan

**Comment by danbucholtz** [comment]
I need to update docs, then close this.

**Comment by danbucholtz** [comment]
I think I did this.

Thanks,
Dan
