### ISSUE TITLE
Automate Changelog

### ISSUE THREAD

**Issue by shlomiassaf** [driftyco/ionic-app-scripts#8]
The commits are already in the angular change log format.

It quite trivial to add it to the release process.

Since this is a beta project and internal to the IONIC cli its hard to keep track what changes and doc's are limited, so a change log can help a lot.

Thanks!

**Comment by adamdbradley** [comment]
If you're willing to contribute we'd love to get your help adding that. Right now we're just trying to get beta12 shipped so this is lower priority for us.

**Comment by ramonornela** [comment]
@adamdbradley added CHANGELOG.md see https://github.com/driftyco/ionic-app-scripts/commit/1fb2aa7d40e45812ef67fb9795c6c60858bd7bee in 0.0.29

Thanks
