### ISSUE TITLE
Cordova browser target on serve

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-app-scripts#80]
One thing that would better blend the world of native cordova plugins and ionic serve/PWAs, is starting to incorporate the cordova browser target for our testing. This would make it possible to use real or mocked cordova plugins that have browser fallbacks in the web.

I know there was some hesitation about this due to the browser target supposedly being focused on development, but having tested it myself I'm confident we could use it. One added benefit would be no more 404 on cordova.js, we'd always have it and it would always run and be available. We can start to push Cordova into the PWA world as not just a native solution, but a cross-platform plugin API perfect for native apps as well as PWAs.

**Comment by danbucholtz** [comment]
We have had internal discussions about what we want to do here, so with that in mind I'm going to close this issue.

Thanks,
Dan
