### ISSUE TITLE
my ionic app is too much slow and it takes long time for booting 

### ISSUE THREAD

**Issue by abmnukmr** [driftyco/ionic-app-scripts#801]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by mhartington** [comment]
Hi there! I'm going to be closing this issue as you have not provided any information asked by the issue template.

If your app is slow to boot, make sure you are using the `--prod` flag, as documented [here](http://ionicframework.com/docs/v2/intro/deploying/)

If you are still experiencing other issue, please open a new issue and completely fill out the issue template.
