### ISSUE TITLE
Uncaught Error: Cannot find module "./app.module.ngfactory

### ISSUE THREAD

**Issue by abmnukmr** [driftyco/ionic-app-scripts#803]
When i build my apk. with
 ionic build android --prod >
run apk in my phone 
and debug with google chrome://inspect/#devices

I got this  error
uncought Error: Cannot find module 'ng-factory'

[ts] Cannot find module ‘./app.module.ngfactory’

my ionic info :+1: 

onic info
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Your system information:

 You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.5.0

Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.4.5
Xcode version: Not installed

******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

**Comment by danbucholtz** [comment]
Due to inactivit,y I am going to close this issue. Please make a post on our Ionic Framework forum about it. This is likely user error.

Thanks,
Dan
