### ISSUE TITLE
ionic serve command doesn't detect changes.

### ISSUE THREAD

**Issue by masteruser20** [driftyco/ionic-app-scripts#804]
Ionic 2(newest build)

I started new ionic project with updated cordova, ionic, npm, node by command 'ionic start ... --v2'.
When project has been created I run npm install and everything was alright.
And now when I execute 'ionic serve --lab' started watch task do nothing when Im making some changes in html files. 
It stucks at last line on attached screen

http://i.imgur.com/AxIKRxY.png

--
When I remove scripts tag from package.json:
```
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
```
and run ionic serve --lab, watch detects changes but he doesn't rebuild solution

**Comment by pacMakaveli** [comment]
Have you tried `ionic serve -c -l` ?

**Comment by masteruser20** [comment]
I tried this but this command gives me only logs in terminal. So serv still doesn't work properly

**Comment by masteruser20** [comment]
Anyone have similiar problem?

**Comment by Mili1984** [comment]
I have the same problem!
OS: Windows 8.1 `64bit`
I tried both latest LTS Version: v6.10.0 (includes npm 3.10.10) 32bit and 64bit.

> My system information via `ionic info`:
 ordova CLI: 6.5.0
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.10.0
Xcode version: Not installed


```
C:\Program Files (x86)\somewhere>ionic serve -l

> ionic-hello-world@ ionic:serve C:\Program Files (x86)\somewhere
> ionic-app-scripts serve "--v2" "--lab" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"

[13:13:04]  ionic-app-scripts 1.1.4
[13:13:05]  watch started ...
[13:13:05]  build dev started ...
[13:13:05]  clean started ...
[13:13:05]  clean finished in 293 ms
[13:13:05]  copy started ...
[13:13:05]  transpile started ...
[13:13:26]  transpile finished in 20.78 s
[13:13:26]  preprocess started ...
[13:13:26]  preprocess finished in 1 ms
[13:13:26]  webpack started ...
[13:13:28]  copy finished in 23.04 s
[13:13:56]  webpack finished in 29.79 s
[13:13:56]  sass started ...
[13:14:06]  sass finished in 10.81 s
[13:14:06]  postprocess started ...
[13:14:06]  postprocess finished in 1 ms
[13:14:06]  lint started ...
[13:14:07]  build dev finished in 62.50 s
[13:14:09]  watch ready in 64.48 s
[13:14:09]  dev server running: http://localhost:8100/

[13:14:32]  lint finished in 25.91 s
```

**Comment by Mili1984** [comment]
Just move your project outside the `C:\Program Files (x86)\` folder, and it will work like a charm!

**Comment by rashnk** [comment]
@masteruser20 , yes same problem, sometimes it showing the previous version of file, 
to reproduce,  keep multiple files opened ,make some changes (not adding or removing space) then ctrl+s from all files, it will start build, opens the page in browser, but the changes not reflected in browser, instead it shows old page (previous change)..

**Comment by masteruser20** [comment]
@Mili1984  solution works, thank's for help but I think that it needs fix.

**Comment by adjmb** [comment]
This issue is because the path has a space character in Windows. `ionic serve` (especifically app-scripts) does not track when there is a space in the path.

**Comment by mptorrejon** [comment]
I have the same issue. ionic serve only runs the app and whenever I make a change in my editor, my browser does not reload. This is my ionic info. 

global packages:

    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Ionic Framework                 : ionic-angular 2.0.0-rc.2

System:

    Node       : v8.0.0
    OS         : OS X Yosemite
    Xcode      : Xcode 7.0 Build version 7A220
    ios-deploy : not installed
    ios-sim    : 5.0.8
    npm        : 5.0.0

**Comment by davidpestana** [comment]
I have the same issie


´cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node : v7.10.0
    npm  : 5.4.2
    OS   : Linux 4.10

Misc:

    backend : pro´

**Comment by corysmc** [comment]
Same thing happened for me. Once i downgraded to 3.6.0 (team member was using 3.6.0) everything started working again
`npm uninstall ionic`
`npm install ionic@3.6.0`

**Comment by davidpestana** [comment]
@corysmc thanks ... downgrade to 3.6.0 doesnt  work in my case

**Comment by AlperMulayim** [comment]
This happened for me also at Ubuntu 18.04
My ionic settings : 

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/home/alpermulayim/npm/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v8.10.0 (/usr/bin/node)
   npm    : 3.5.2
   OS     : Linux 4.15
