### ISSUE TITLE
Build mode is not being toggled correctly when using custom rollup config

### ISSUE THREAD

**Issue by cubicleWar** [driftyco/ionic-app-scripts#81]
When using a custom rollup config file I get the error `Error: Could not resolve entry (./.tmp/app/main.dev.js)`. It appears that when specifying a custom config file switching of the entry point never executes:

    if (process.env.IONIC_ENV == 'prod') {
      // production mode
      rollupConfig.entry = '.tmp/app/main.prod.js';
      rollupConfig.sourceMap = false;
    } 

If I make identical config changes in `node_modules/@ionic/app-scripts/config/rollup.config.js` everything works, alternatively if I change the entry point to `entry: './.tmp/app/main.prod.js'` everything works fine.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. Unfortunately I cannot seem to reproduce this issue. Would you mind posting your custom `rollup.config`?

**Comment by cubicleWar** [comment]
I thought that may be the case given I couldn't find anyone else with the issue. My rollup config is as follows, I have tried a few different versions but all end with the same result.

./config/rollup.config.js:

    var ngTemplate = require('@ionic/app-scripts/dist/plugins/ng-template').ngTemplate;
    var nodeResolve = require('rollup-plugin-node-resolve');
    var commonjs = require('rollup-plugin-commonjs');
    var globals = require('rollup-plugin-node-globals');
    var builtins = require('rollup-plugin-node-builtins');
    var json = require('rollup-plugin-json');

    // https://github.com/rollup/rollup/wiki/JavaScript-API

    var rollupConfig = {
      /**
       * entry: The bundle's starting point. This file will
       * be included, along with the minimum necessary code
       * from its dependencies
       */
      entry: './.tmp/app/main.dev.js',

      /**
       * sourceMap: If true, a separate sourcemap file will
       * be created.
       */
      sourceMap: true,

      /**
       * format: The format of the generated bundle
       */
      format: 'iife',

      /**
       * dest: the output filename for the bundle in the buildDir
       */
      dest: 'main.js',

      /**
       * plugins: Array of plugin objects, or a single plugin object.
      * See https://github.com/rollup/rollup/wiki/Plugins for more info.
       */
      plugins: [
        ngTemplate(),
        builtins(),
        commonjs({
            namedExports: {
                'node_modules/js-extend/extend.js': ['extend']
            }
        }),
        nodeResolve({
          module: true,
          jsnext: true,
          main: true,
          browser: true,
          extensions: ['.js']
        }),
        globals(),
        json()
      ]
    };

    if (process.env.IONIC_ENV == 'prod') {
      // production mode
      rollupConfig.entry = '.tmp/app/main.prod.js';
      rollupConfig.sourceMap = false;
    }

    module.exports = rollupConfig;

When I npm run build I get:

    [06:14:50]  Error: Could not resolve entry (./.tmp/app/main.dev.js)

If I paste the same config into `node_modules/@ionic/app-scripts/config/rollup.config.js`, change the ngTemplates path and remove `"ionic_rollup": "./config/rollup.config.js"` from package.json everything works fine.

It seems the problem is that either main.dev.js is not being generated or the entry point is not being switched to main.prod.js. I believe npm run build uses the production mode so It's probably the latter.

**Comment by jgw96** [comment]
Ahh, thanks for the extra info! I can now reliably reproduce this issue with a custom config. So this is definitely caused by the entry point not being switched to `main.prod.js`.  `main.dev.js` does not get built when doing a prod build, so it should not be looking for that file anyways.

**Comment by jgw96** [comment]
Hello @cubicleWar can you confirm the version of @ionic-app-scripts you are running?

**Comment by cubicleWar** [comment]
Hi @jgw96 the version of @ionic-app-scripts I am currently running is 0.0.28

**Comment by jgw96** [comment]
Unfortunately I cannot reproduce this issue with app-scripts version 0.0.28. Could you provide a repo that i can use to reproduce this issue? Thanks!

**Comment by cubicleWar** [comment]
@jgw96 after explicitly setting the version as 0.0.28 and running npm update I no longer have the issue. Everything seems to be building fine.

**Comment by jgw96** [comment]
Awesome! Glad to hear!
