### ISSUE TITLE
.d.ts, .js and .js.map files in src.

### ISSUE THREAD

**Issue by shaneparsons** [driftyco/ionic-app-scripts#813]
#### Short description of the problem:

My src directory is randomly flooded with **.d.ts**, **.js** and **.js.map** files.

#### What behaviour are you expecting?

For these unnecessary files not to be there.

**Steps to reproduce:**

There isn't really any steps to re-produce this as I wasn't really doing anything out of the ordinary... The last thing I did before I noticed this was creating some promises and observers for geolocation data.

**Which @ionic/app-scripts version are you using?**

1.0.0

**Other information:**

This issue seems related: https://github.com/driftyco/ionic-app-scripts/issues/136... though I have no idea what angular barrels are.

**Comment by shaneparsons** [comment]
I decided to delete all the garbage files and they haven't come back yet. I'll re-open this if it happens again.

**Comment by danbucholtz** [comment]
It is likely the IDE that is generating these. We only write files to memory.

Thanks,
Dan

**Comment by shaneparsons** [comment]
I use sublime text though, which doesn't do anything in terms of writing files. I'm pretty sure it's an ionic serve / webpack issue.

**Comment by danbucholtz** [comment]
Hmm, it does seem weird. I think we'd hear about this is a lot if it was a common thing. Hmmm. I'm not sure where to go.

**Comment by shaneparsons** [comment]
Weird indeed. I'll keep an eye out for if it happens again (it hasn't in a while) and update this with any findings.

**Comment by louisdoe** [comment]
same error here ! my directory src/providers just got flooded with .js an .map files. I don't how !

**Comment by kernwig** [comment]
Just happened to me. Ionic v2.4.8. IntelliJ Ultimate 2017. IDE is set to _not_ compile Typescript.

**Comment by g1bbzy** [comment]
Same here sublime text 3

**Comment by davincif** [comment]
Same to be, also sublime text 3... perhaps sublime does has something to do with it...

**Comment by sangwin** [comment]
Same thing happened to me as well. Sublime text 3.

**Comment by shaneparsons** [comment]
@sangwin From what I remember deleting them is fine.

I haven't had this problem since I switched to VS Code, which is a much better development experience anyways. I'd definitely recommend it to anybody who hasn't tried it yet.

**Comment by thierce** [comment]
I have had this happen multiple times with VS code.

**Comment by adamjcasey** [comment]
Same here, Sublime Text 3.  First time and have built hundreds of times

**Comment by davincif** [comment]
@shaneparsons, I have had! ^^" and also friends of mine. so...

**Comment by jyprksh001** [comment]
you can use git clean -fd if u havent tracked those files
https://stackoverflow.com/questions/40349369/sublime-how-to-remove-js-map-js-files-of-ts-files-in-sublime-text

**Comment by dhistira** [comment]
this just happen to me, because accidentally click ctrl + b to make typescript plugin on sublime text 3 compile all ts to js. To remove all unnecessary js and map file, try this on your src folder (with cmd)
**Windows**
`del /s *.js
del /s *.map`

**Mac**
`find . -name '*.js' -delete`
`find . -name '*.map' -delete`
