### ISSUE TITLE
Command "ionic build browser" missed "img/logo.png" for SplashScreen

### ISSUE THREAD

**Issue by zGwit** [driftyco/ionic-app-scripts#820]
As title.

**Comment by zGwit** [comment]
@danbucholtz

**Comment by danbucholtz** [comment]
Hi @zGwit,

We don't formally support the browser target. I'm not sure what's going on there, but it is likely a cordova issue. Can you open an issue with them?

Thanks,
Dan

**Comment by zGwit** [comment]
@danbucholtz

Thanks
