### ISSUE TITLE
v1.1.X removes -webkit-box-orient from the css

### ISSUE THREAD

**Issue by albert-gonzalez** [driftyco/ionic-app-scripts#821]
Hi!

#### Short description of the problem:
If you use the CSS property -webkit-box-orient, it is removed in the build. It worked well in v1.0.x

#### What behavior are you expecting?
The build should have this property.

```
.three_lines {
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
}
```

**Which @ionic/app-scripts version are you using?**
v1.1.4

The same issue was rejected in ionic repository: https://github.com/driftyco/ionic/issues/10723

Thank you very much!

**Comment by aspidvip** [comment]
Yes? i'm not work to scss
```
  .pod_c {
    white-space: pre-line;
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
   -webkit-box-orient: vertical;
   vertical-align: middle;
   font-size: 0.7em;
  }
```

**Comment by ceeliro** [comment]
Same here. And can't find another solution to have same behaviour other than wrapping text previously  to be shown what i am not confortable with

**Comment by awebdeveloper** [comment]
another duplicate https://github.com/driftyco/ionic-app-scripts/issues/869

**Comment by vhinic** [comment]
+1 one for this - it simply removes "-webkit-box-orient: vertical;" from css

**Comment by vhinic** [comment]
I was able to properly fix this by specifying my own css.config.js:

```
module.exports = {

  autoprefixer: {
    remove: false
  },
};
```

And pointing to it in package.json:

```
  "config": {
    "ionic_sass": ".sass.config.js"
  },
```

See [this](https://github.com/driftyco/ionic-app-scripts) and [this](https://www.npmjs.com/package/autoprefixer#outdated-prefixes) for more details

**Comment by aspidvip** [comment]
thansk )))

**Comment by aspidvip** [comment]
close team please

**Comment by albert-gonzalez** [comment]
Nice workaround @aspidvip ! Thanks!

**Comment by jerryyan1990** [comment]
@vhinic thanks for u ,solve my problem 👍
