### ISSUE TITLE
Reduce boot time in ionic-2 app

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-app-scripts#828]
_From @dominicg666 on March 21, 2017 11:13_

[ ] **2.x**

I am new to ionic-2 project.I just want to know how to reduce boot time of app.Because after 3 sec of splash screen , it shows white screen and takes 16 sec to start.

_Copied from original issue: driftyco/ionic#10858_

**Comment by brandyscarney** [comment]
_From @AmitMY on March 21, 2017 11:18_

compile for aot (using --prod) and other modifications can help.
This is a support request, which you should ask in the forums.

**Comment by brandyscarney** [comment]
_From @dominicg666 on March 21, 2017 11:23_

please give for example?

**Comment by brandyscarney** [comment]
_From @AmitMY on March 21, 2017 11:38_

https://forum.ionicframework.com/

**Comment by brandyscarney** [comment]
_From @mburger81 on March 21, 2017 16:40_

@dominicg666 
ionic build android --prod

**Comment by danbucholtz** [comment]
Using a prod build is the way to go. In a few weeks, we're going to ship Ionic 3 which will support lazy loading which will speed this up tremendously.

Thanks,
Dan

**Comment by niravparsana94** [comment]
Any updates on this?
My Application still takes 8-9 seconds to start.

**Comment by AmitMY** [comment]
@niravparsana94 The unofficial update is that it is now faster with webpack 3, and optimizations are always being made. The next major update will have a much much faster boot time thanks to new technologies being implemented. And of course, make sure your build is built with `--prod`

**Comment by niravparsana94** [comment]
@AmitMY What do you mean by unofficial updates? Do have any idea about when they will release those updates? I'm building my application using production, still it takes 8-9 seconds.

**Comment by AmitMY** [comment]
Unofficial update - While it says I am a "member" of Ionic, I am actually not, so I don't want to be quoted on this as an official source.
No idea when they release those changes, I am waiting too :)

**Comment by niravparsana94** [comment]
Thanks for quick reply, btw. :)

**Comment by mburger81** [comment]
Angular 4 will use WebComponents which are by design lazy loaded. 
But are you using Ionic3 and his lazy loaded IonicPage and using --prod build? If yes it should not take so much time! We have several pages and components which works very fast no

**Comment by mburger81** [comment]
....now not No

**Comment by niravparsana94** [comment]
@mburger81 I'm using Angular 4 with Ionic 3. but there is no lazy loading. What i'm saying, when i launch application in android device, it takes 8-9 seconds for appering first screen.
