### ISSUE TITLE
Feature: Add Test Execution to ionic serve with configuration similar to Lint

### ISSUE THREAD

**Issue by Chowarmaan** [driftyco/ionic-app-scripts#830]
#### Short description of the problem:
I would like to be able to run my test scripts each time I make code changes to better reflect TDD development.  It would be nice to have the ability to configure the unit test (using Karma, mocha, etc...) and possibly even the e2e testing (using protractor, ...) as part of the normal ionic serve build process.

#### What behavior are you expecting?
Similar to the ionic_enable_lint, you would be able to ionic_enable_test/ionic_enable_e2e and have a configuration section as needed. Defaults should be disabled for the current build speeds to be maintained.

**Steps to reproduce:**
1. N/A
2.
3.

**Which @ionic/app-scripts version are you using?**
1.0.0

**Comment by danbucholtz** [comment]
@Chowarmaan,

Sorry, this is something that will likely be out of scope for awhile. Karma is too slow to do this efficiently.

Thanks,
Dan
