### ISSUE TITLE
Lint errors on Production build for 1.2.0

### ISSUE THREAD

**Issue by dmastag** [driftyco/ionic-app-scripts#837]
#### Short description of the problem:
After upgrading to ionic-app-script 1.2.0 I am getting a lot of Lint issues saying [The following file has multiple class declarations in it](https://github.com/driftyco/ionic-app-scripts/blob/master/src/util/typescript-utils.ts#L166). The file mentiond is the ngFactory file which I believe is made by ionic-app-scripts

#### What behavior are you expecting?
No linting errors

**Steps to reproduce:**
1. Update ionic-app-scripts to 1.2.0
2. ionic build ios --prod --release

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
1.2.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
We may just remove this warning. I'll revisit next week. For now, ignore!

Thanks,
Da

**Comment by danbucholtz** [comment]
Going to close as a duplicate. We'll track it here:

https://github.com/driftyco/ionic-app-scripts/issues/842
