### ISSUE TITLE
Rollup config does not use ionic_tmp_dir config value.

### ISSUE THREAD

**Issue by mnasyrov** [driftyco/ionic-app-scripts#84]
#### Short description of the problem:
Rollup cannot find an entry file (e.g. main.dev.js) in case a temp directory is changed via 'ionic_tmp_dir' npm option ('config' section) because a default '.tmp' directory is hardcoded.

#### What behavior are you expecting?
Ability to change a temp directory via 'ionic_tmp_dir' config value.

**Which @ionic/app-scripts version are you using?**
0.0.28

**Comment by jgw96** [comment]
Hello @mnasyrov , is this still an issue with the latest release? v0.0.33

**Comment by mnasyrov** [comment]
@jgw96, I can't test it right now, but it seems like a following commit fixed it: # [556d2e3](https://github.com/driftyco/ionic-app-scripts/commit/556d2e37dd6b84154b224592751e5f50f9e2a309#diff-a2f217adb8d48f171e50d566a73143bc).

**Comment by jgw96** [comment]
Hello all! I am going to close this issue for now as it is fixed in the latest version of app-scripts. Thanks!
