### ISSUE TITLE
[app-script 1.2.0] Build --prod broken, result build weight only 228 kb!!!

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#841]
#### Short description of the problem:

After upgrading to ionic-app-scripts 1.2.0, when I build my app with the --prod option, the result build make no sense. My app (main.js) weight 228kb where without --prod it weight 7.7mb. 

Of course the result isn't a valid app. When I test it, cordova start and then nothing, no stacktrace, nothing, it hang on the splash screen.

#### What behavior are you expecting?

A valid app build.

**Which @ionic/app-scripts version are you using?**

1.2.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

I still have got warnings because of my abstract classes (see other tickets, https://github.com/driftyco/ionic-app-scripts/issues/842) but my app is still fully functional when I run ionic serve

I also upgrade typescript to 2.2.1 and I also spent one hour extracting the classes I would have had in single ts files.

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by danbucholtz** [comment]
Fixed in `1.2.1`. Thanks and sorry for the bug.

Note: If you're using Angular 2.x still requires TS 2.0.x and won't work with TS 2.2.x.

Thanks,
Dan

**Comment by peterpeterparker** [comment]
@danbucholtz Thx for your comment about TS. 

What do you recommend then, sticking to Typescript 2.0.9 and Angular 2.x or upgrading to Typescript 2.2.1 and Angular 4.0.0? What is the most compatible with Ionic 2.3.0 and Ionic-app-scripts 1.2.1?

**Comment by peterpeterparker** [comment]
@danbucholtz your fix works like a charm, thx a lot

**Comment by hkfoxok** [comment]
I am testing the native mock in broswer and i have install camera plugins,  but in app script v1.1.4,  it is always give me msg as dollowing: Native: tried calling Camera.getPicture, but the Camera plugin is not installed.

**Comment by Sh1d0w** [comment]
@danbucholtz Do you know any know issues with Angular 2.x and Typescript 2.2? I've been using latest version of ionic + ionic app scripts + Typescript 2.2.1 for almost two months and there are not any problems so far and the app is pretty big.

Please let us know what do you mean, so I can review the app code in case there are any known issues?

**Comment by danbucholtz** [comment]
@peterpeterparker, I would personally try Angular 4 and only go back if you have issues. I don't anticipate you having any issues.

Thanks,
Dan

**Comment by danbucholtz** [comment]
@Sh1d0w,

`ngc`, the ahead-of-time compiler with Angular, did not work with TS 2.1 or greater until Angular 4. You should definitely use AoT for production builds.

Thanks,
Dan

**Comment by Sh1d0w** [comment]
@danbucholtz Hm strange then, I am successfully compiling my app with `--prod` flag without any errors

**Comment by peterpeterparker** [comment]
@danbucholtz  I will, thx a lot for the feedback!
