### ISSUE TITLE
build --prod never seems to finish.

### ISSUE THREAD

**Issue by seiyria** [driftyco/ionic-app-scripts#844]
#### Short description of the problem:
`build --prod` never finishes.

#### What behavior are you expecting?
A prod build to finish.

**Steps to reproduce:**
1. Grab [this particular version](https://github.com/IdleLands/Play/commit/4aef345d8647bd71a019d70385300bf75f9a698b) of my project.
2. `npm install`
3. `npm run ionic:build:prod`

**Which @ionic/app-scripts version are you using?**
1.2.1

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
package.json:

```
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "angular-svg-round-progressbar": "^1.0.6",
    "angular2-jwt": "^0.1.28",
    "angular2-moment": "^1.3.0",
    "auth0-lock": "^10.13.0",
    "clipboard": "^1.6.1",
    "gameicons-font": "github:idlelands/gameicons-font",
    "ionic-angular": "2.3.0",
    "ionic-native": "^2.9.0",
    "ionicons": "3.0.0",
    "linkifyjs": "^2.1.4",
    "lodash": "^4.17.4",
    "ng2-webstorage": "^1.5.1",
    "phaser": "^2.6.2",
    "primus": "^6.1.0",
    "reddit.js": "^0.1.3",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "tinycon": "github:tommoor/tinycon",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.2.1",
    "@ionic/cli-plugin-cordova": "0.0.8",
    "@ionic/cli-plugin-core": "0.0.7",
    "@types/node": "^7.0.5",
    "css-loader": "^0.26.4",
    "file-loader": "^0.10.1",
    "gh-pages": "^0.12.0",
    "git-revision-webpack-plugin": "^2.4.1",
    "ionic": "^2.2.1",
    "script-loader": "^0.7.0",
    "standard-version": "^4.0.0",
    "style-loader": "^0.13.2",
    "typescript": "^2.2.1"
  },
  "config": {
    "ionic_webpack": "./webpack.config.js"
  }
```
(my webpack config doesn't deviate too much from the base, just adds a few defineplugins and some external modules)

sample run:
```
> ionic-app-scripts build --prod

[17:36:58]  ionic-app-scripts 1.2.1 
[17:36:58]  build prod started ... 
[17:36:58]  clean started ... 
[17:36:58]  clean finished in 5 ms 
[17:36:58]  copy started ... 
[17:36:58]  ngc started ... 
[17:37:17]  ngc finished in 19.81 s 
[17:37:17]  preprocess started ... 
[17:37:17]  deeplinks started ... 
<< lots of spam about multi class files >>
[17:37:19]  deeplinks finished in 1.49 s 
[17:37:19]  optimization started ... 
[17:37:19]  optimization finished in 12 ms 
[17:37:19]  preprocess finished in 1.50 s 
[17:37:19]  webpack started ... 
[17:37:19]  copy finished in 21.72 s 
[17:38:20]  webpack finished in 60.60 s 
[17:38:20]  sass started ... 
[17:38:20]  transpile bundle started ... 
```

ionic info:
```
  Your system information:

    Cordova CLI: 4.3.0 
    Ionic Framework Version: 2.3.0
    Ionic CLI Version: 3.0.0-beta.2
    ios-deploy version: Not installed
    ios-sim version: 3.1.1 
    OS: OS X El Capitan
    Node Version: v7.6.0
    Xcode version: Xcode 7.3.1 Build version 7D1014
```

Additionally, I see the same issue as #701 when I try to build sass independently.

**Comment by sfaizanh** [comment]
`ionic build ios` works fine but with --prod flag this error occurs

```
ionic-app-script task: "build" 
RangeError: Maximum call stack size exceeded 
RangeError: Maximum call stack size exceeded
    at getTypeAtFlowNode (/Users/me/Documents/v2/node_modules/typescript/lib/typescript.js:33799:39)
```

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.1
ios-deploy version: 1.9.1 
ios-sim version: 5.0.6 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by danbucholtz** [comment]
Angular 2.x does not support TypeScript 2.2.x. Please revert to TS ~2.0.x.

Thanks,
Dan

**Comment by sfaizanh** [comment]
@danbucholtz Thanks for replying but mine seem to work with 2.2.2.
i was able to get rid of maximum stack error by switching to webpack from rollup

@seiyria backup your **package.json** and remove these line from your **package.json** and try to build your app with --prod flag.
```
  "config": {
    "ionic_webpack": "./webpack.config.js"
  }
```

**Comment by seiyria** [comment]
@sfaizanh I need my webpack config, is the problem, as I stated it adds some variables via define.
@danbucholtz I tried this on an earlier TS and I get the same error. I'll try again but I suspect it'll end the same way.

**Comment by sfaizanh** [comment]
@seiyria i was saying try this method if you get success then backup your webpack.config.ts file and go to `node_modules/@ionic/app-scripts/config/webpack.config.ts` copy it **webpack.config.js** and paste into your root folder and update your **webpack.config.js** with your changes

**Comment by seiyria** [comment]
@sfaizanh I have done that already.

**Comment by seiyria** [comment]
Hm. Amongst all of the other package.json updates I made, it looks like the typescript one updated, but didn't stick when I tried to downgrade it. It appears to work now.

Hopefully this will get changed in the future to at least spit out an error so users don't spin their wheels for hours.
