### ISSUE TITLE
Ionic scripts unit tests

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic-app-scripts#852]
It's impossible to run unit tests on Windows. it will result in a lot of errors due to the fact that paths are not normalized, example

```
expect(received).toEqual(expected)

    Expected value to equal:
      "/some/src/**/*.spec.ts"
    Received:
      "\\some\\src\\**\\*.spec.ts"
```

**Comment by danbucholtz** [comment]
@alan-agius4,

Our tests? We should never hit an actual path so that is surprising. I can fix.

Thanks,
Dan

**Comment by alan-agius4** [comment]
Yep thats from your test.

AFAIK, mockFs (I saw your are using it) does normalize the paths.

**Comment by danbucholtz** [comment]
I am confused though, we never do iOS so I am unsure why this would be a thing. It's treated as just a string for the sake of testing.

Thanks,
Dan

**Comment by alan-agius4** [comment]
I didn't dig into this that much to be honest.

But mockFs create a sort of new file system, example /src/text.txt, which
in linux and unix like OS are fine however on Windows these are normalized
like \\src\\text.txt when retrieved via and an node method.

Easiest way would be to normalize all file paths within the test. Bit of a
bummer I know.

If you have a Windows machine you can try it out easily.

**Comment by danbucholtz** [comment]
I have fixed all of the tests.

Thanks,
Dan

**Comment by alan-agius4** [comment]
Thanks
