### ISSUE TITLE
feat: cordova resources create just for current orientation

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic-app-scripts#855]
#### Short description of the problem:
`ionic cordova:resources` creates resources for all of the current platforms. for all device types, and for all orientations.

#### What behavior are you expecting?
First, I expect it to create resources only for the specified `config.xml` orientation. If specified `portrait`, no reason to make a `landscape` one.
Second, I expect a some sort of ability to disable tablets, such as ipad.

**Which @ionic/app-scripts version are you using?** `1.2.2`

**Comment by danbucholtz** [comment]
Sorry, this is not something on our short-term roadmap.

Thanks,
Dan

**Comment by AmitMY** [comment]
@danbucholtz So perhaps leave this issue open, with a `priority: low` tag? closing it is assuring no regard to it even it the future.
