### ISSUE TITLE
Prod builds do not successfully load (Module parse failed)

### ISSUE THREAD

**Issue by seiyria** [driftyco/ionic-app-scripts#857]
#### Short description of the problem:
My prod builds fail with an error that seems to imply that `ionic-angular` isn't being compiled correctly.

#### What behavior are you expecting?
A working prod build.

**Steps to reproduce:**
1. Check out my project at [this commit](https://github.com/IdleLands/Play/tree/2a733e60fe611377dfe29a341c3947756e771665). 
2. `npm install && npm run ionic:build:prod`
3. Serve the `www` directory in a web browser (I used `npm install -g http-server`).
4. Observe the error in the console (stack trace below).

**Which @ionic/app-scripts version are you using?**
Tried with 1.1.4, 1.2.0, 1.2.1, 1.2.2

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Here's the stack trace:
```
Uncaught Error: Module parse failed: /Users/seiyria/GitHub/Play/node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory.ts Unexpected token (40:27)
You may need an appropriate loader to handle this file type.
| import * as import30 from '@angular/common/src/directives/ng_for';
| export class Wrapper_ActionSheetCmp {
|   /*private*/ _eventHandler:Function;
|   context:import0.ActionSheetCmp;
|   /*private*/ _changed:boolean;
    at v (polyfills.js:3)
    at Object.<anonymous> (main.js:94)
    at e (main.js:1)
    at Object.<anonymous> (main.js:51)
    at e (main.js:1)
    at Object.<anonymous> (main.js:134)
    at e (main.js:1)
    at main.js:1
    at main.js:1
```

**Comment by danbucholtz** [comment]
Do you have any of our experimental options can? Can you do the following build:

`npm run ionic:build --aot` and then serve it up and see if you still get the error.

Thanks,
Dan

**Comment by seiyria** [comment]
Running that command, I still get the same error. I do not have any experimental options on, either.

**Comment by rashnk** [comment]
--prod build not working, found this issue today, the change i did was added a plugin camera

**Comment by kamok** [comment]
Try reverting back to `1.2.4`. It fixed the issue for me. I couldn't build after adding the barcode plugin, so I did a hard reset and it still didn't let me build. Further debugging led me to the app scripts which was updating automatically to the latest version.

**Comment by seiyria** [comment]
If you mean 1.1.4, I've tried that. No version works correctly.

**Comment by kamok** [comment]
No, I mean `"@ionic/app-scripts": "1.2.4",`

**Comment by seiyria** [comment]
Not sure where the comment went, but I've also tried this on 1.2.5.

**Comment by danbucholtz** [comment]
@seiyria,

Can you provide a repo that can reproduce the issue?

Thanks,
Dan

**Comment by seiyria** [comment]
Dan,

Please see the link in the issue. It links to the specific commit for when
I posted this.

**Comment by danbucholtz** [comment]
Is this still an issue? I have not looked into it but it seems strange. Haven't seen this from anyone else.

Thanks,
Dan

**Comment by seiyria** [comment]
Yes, this is still an issue. Still cannot get a successful prod build for my application.

**Comment by danbucholtz** [comment]
Are you on Ionic 3? Are you using Angular 4? What TS version? Sorry, this seems like a misconfiguration somewhere in the dependencies.

Thanks,
Dan

**Comment by seiyria** [comment]
[here is my package.json](https://github.com/IdleLands/Play/blob/2a733e60fe611377dfe29a341c3947756e771665/package.json).

I was using angular 2.4.8, ionic-angular 2.3.0, typescript 2.0.9. I have tried other versions. I have tried using ionic 2 and ionic 3 for the CLI. I've tried changing those dependency versions over and over, which is what led me to post an issue - after several hours of trying to change some versions around and see if it would work, then reinstalling everything every time, it got frustrating.

**Comment by danbucholtz** [comment]
Could it be the custom webpack config?

Thanks,
Dan

**Comment by seiyria** [comment]
The webpack config does not deviate very much - it adds a few defines and a processor for fonts. I don't think that would stop a prod build, as it doesn't for vanilla angular2 apps.

**Comment by seiyria** [comment]
Just to follow up, I have updated to angular 4, typescript 2.1, ionic-angular 3.0.1 and this error is still happening.

**Comment by kamok** [comment]
Upgrade ionic app scripts

**Comment by seiyria** [comment]
I am using 1.3.3 (or whatever the latest is).

**Comment by seiyria** [comment]
One deviation of note that I didn't note earlier (I just diff'd the configs again): I exclude `.ts` with my ts loader, but the default ionic webpack script includes them. This was because it freezes if I do `ionic:build --prod` when it gets to `webpack started...`. That's probably why it's not correctly transpiling anything in ionic (because it's ts), but it works in dev, just not when doing a prod build.

**Comment by danbucholtz** [comment]
I remember looking at this issue in detail but I don't remember what I concluded, fwiw.

Thanks,
Dan

**Comment by seiyria** [comment]
What part of it? Has webpack freezing when compiling prod builds for others as well?

**Comment by danbucholtz** [comment]
No, this is the only one. Darn it, I should have taken some notes when I looked at your app.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Just looked at it again. Sorry, I cannot troubleshoot all of the issues with a custom webpack config. If you can recreate on a vanilla Ionic project, I can look into it.

Thanks,
Dan
