### ISSUE TITLE
No --prod or --release build on linux

### ISSUE THREAD

**Issue by sridher** [driftyco/ionic-app-scripts#868]
when `$> ionic build --prod --release android` command executed giving error
`✗ You cannot run iOS unless you are on Mac OSX.`
 

#### What behavior are you expecting?
on linux there is no way to compile in production or release mode

**Steps to reproduce:**
1. $> `ionic build --prod --release android`
2. $> `ionic build --prod  android`
3. $> `ionic build --release android`

**Which @ionic/app-scripts version are you using?**

> `ionic info`

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.2.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.10
Node Version: v6.10.1
Xcode version: Not installed

**Comment by kamok** [comment]
Try `ionic build android --prod --release`

**Comment by sridher** [comment]
that works; thanks.
