### ISSUE TITLE
ionic Serve not working properly with ionic2 app  in RC0

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#87]
_From @sriteja09 on October 3, 2016 18:21_

Issue with ionic2

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 7.3 Build version 7D175

this is my system configuration.i am using mac book . In my macbook when i am using ionic serve it works. when i write error in the code then ionic serve working fine in that case after that if i change code and run application its not working.

_Copied from original issue: driftyco/ionic#8447_

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind providing some more info please? Could you post the exact errors you are getting? Thanks!

**Comment by Vanclief** [comment]
Having the same error: 

npm version
3.10.7           
node version
v6.7.0                   
                                                                     
---Ionic Info ---
Ionic Framework Version: 2.0.0-rc.0                                                           
Ionic CLI Version: 2.1.0                                                                     
Ionic App Lib Version: 2.1.0-beta.1                                                          
ios-deploy version: Not installed                                                             
OS: Mac OS X El Capitan                                                                       
Node Version: v6.7.0                                                                          
Xcode version: Not installed


---Error ---

Running 'serve:before' npm script before serve                                                
> reu@ watch /Users/J/Desktop/ITESM_ISC/Semestre7/LDAW : AMSS/Progra/Proyect/reuapp           
> ionic-app-scripts watch                                                                     
sh: ionic-app-scripts: command not found                                                      
npm                                                                                           
 ERR! Darwin 16.0.0                                                                           
npm ERR!                                                                                      
argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "run" "watch"               
npm ERR!                                                                                      
node v6.7.0                                                                                   
npm ERR! npm  v3.10.7                                                                         
npm ERR! file sh                                                                              
npm ERR! code ELIFECYCLE                                                                      
npm                                                                                           
ERR! errno ENOENT                                                                             
npm ERR! syscall                                                                              
 spawn                                                                                        
npm ERR! reu@ watch: `ionic-app-scripts watch`                                                
npm ERR! spawn ENOENT                                                                         
npm                                                                                           
ERR!                                                                                          
npm ERR!                                                                                      
 Failed at the reu@ watch script 'ionic-app-scripts watch'.                                   
npm ERR! Make sure you have the latest version of node.js and npm installed.                  
npm                                                                                           
 ERR! If you do, this is most likely a problem with the reu package,                          
npm ERR! not with npm itself.                                                                 
npm ERR! Tell the author that this fails on your system:                                      
npm ERR!                                                                                      
     ionic-app-scripts watch                                                                  
npm ERR! You can get information on how to open an issue for this project with:               
npm ERR!                                                                                      
     npm bugs reu                                                                             
npm ERR! Or if that isn't available, you can get their info via:                              
"debug.txt" 53L, 1311C


-----
Tried: Deleting node modules and npm install. Deleted repo and made git clone. Reinstailled npm and node. Reinstalled ionic cli.

The same project works on two different OSX computers. Only difference is this one has the latest MacOS (Sierra)

Probably related: https://github.com/driftyco/ionic-cli/issues/1448

**Comment by haydenJogs92** [comment]
Same issue here I think
`
Haydens-MacBook-Pro:testApp haydenbrown$ ionic info

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a 


Haydens-MacBook-Pro:testApp haydenbrown$ ionic serve

Running 'serve:before' npm script before serve
> ionic-hello-world@ watch /Users/haydenbrown/Desktop/ionicProject/CabinsUSA/testApp
> ionic-app-scripts watch
sh: ionic-app-scripts: command not found



npm
 ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch"
npm
 ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm 
ERR! file sh
npm ERR! code ELIFECYCLE
npm
 ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! ionic-hello-world@ watch: `ionic-app-scripts watch`
npm ERR!
 spawn ENOENT
npm ERR! 
npm 
ERR! Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm 
ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm 
ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts watch
npm ERR!
 You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR!
 Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR!
 There is likely additional logging output above.



npm ERR! Please include the following file with any support request:
npm ERR!     /Users/haydenbrown/Desktop/ionicProject/CabinsUSA/testApp/npm-debug.log

Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
`


I uninstalled npm and node before reinstalling ionic and cordova - still having this issue.
Haydens-MacBook-Pro:testApp haydenbrown$ npm -v
3.10.3
Haydens-MacBook-Pro:testApp haydenbrown$ node -v
v6.7.0
Haydens-MacBook-Pro:testApp haydenbrown$

**Comment by haydenJogs92** [comment]
I'm having the same issue.

Unless I'm mistaken - the first time I saw this issue was after uninstalling and reinstalling node, npm, ionic, and cordova today. I followed the instillation steps and it produced this error.

Here's my system info:
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a 

first few lines of the error are:
> ionic-hello-world@ watch /Users/haydenbrown/Desktop/ionicProject/CabinsUSA/test
> ionic-app-scripts watch
sh: ionic-app-scripts: command not found
npm
 ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch"
npm

**Comment by Vanclief** [comment]
Heads up, we solved it by doing a global install of npm @ionic/app-scripts. Seems this was not installed when we did the global ionic install.

**Comment by haydenJogs92** [comment]
Awesome - running 
npm install -g @ionic/app-scripts 

Got the app to build. It seems tslint isn't working still though:
[17:14:19]  lint failed:  Unable to find "tslint" command: null

[17:14:19]  Error: Unable to find "tslint" command: null
    at /usr/local/lib/node_modules/@ionic/app-scripts/dist/lint.js:38:20
    at runTsLint (/usr/local/lib/node_modules/@ionic/app-scripts/dist/lint.js:35:12)
    at /usr/local/lib/node_modules/@ionic/app-scripts/dist/lint.js:22:13
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by haydenJogs92** [comment]
Nevermind - I was able to get rid of the app scripts not found error and cannot find typescript, and tslint problems by uninstalling, ionic, cordova, npm, and node then deleting node_modules folder in usr/lib and deleting .cordova, .npm, .ionic.

I then went through the installation process, ionic asked for sudo installs. Brew doctor told me I was missing xcode clt. Then Ionic info mentioned that I needed ios-deploy. I'm not sure which of these steps fixed my problem, but cleaning my machine of node, npm, cordova, and ionic and checking instillation steps seemed to do the trick.

**Comment by jgw96** [comment]
Hello all! @sriteja09 are you still having this issue?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by pankajkumar6401** [comment]
Having same issue while release command

--Ionic Info--
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v4.4.0

--Error--

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Pankaj\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.9
3 info using node@v4.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle softwareforcleaners3@~prebuild: softwareforcleaners3@
6 silly lifecycle softwareforcleaners3@~prebuild: no script for prebuild, continuing
7 info lifecycle softwareforcleaners3@~build: softwareforcleaners3@
8 verbose lifecycle softwareforcleaners3@~build: unsafe-perm in lifecycle true
9 verbose lifecycle softwareforcleaners3@~build: PATH: C:\Users\Pankaj\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Pankaj\Documents\GitHub\softwareforcleaners3\node_modules\.bin;F:\cmder\bin;C:\Program Files\Git\bin;C:\Program Files\Git\share\vim\vim74;F:\cmder\vendor\conemu-maximus5\ConEmu\Scripts;F:\cmder\vendor\conemu-maximus5;F:\cmder\vendor\conemu-maximus5\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;F:\Server\PHP;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\QuickTime\QTSystem\;C:\ProgramData\ComposerSetup\bin;C:\PHPUnit;C:\Program Files (x86)\Skype\Phone\;C:\Users\Pankaj\AppData\Roaming\Composer\vendor\bin;C:\Program Files (x86)\nodejs\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Ruby22-x64\bin;C:\Users\Pankaj\AppData\Roaming\npm;C:\Program Files\Java\jdk1.7.0_79\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;;F:\cmder
10 verbose lifecycle softwareforcleaners3@~build: CWD: C:\Users\Pankaj\Documents\GitHub\softwareforcleaners3
11 silly lifecycle softwareforcleaners3@~build: Args: [ '/d /s /c', 'ionic-app-scripts build' ]
12 silly lifecycle softwareforcleaners3@~build: Returned: code: 1  signal: null
13 info lifecycle softwareforcleaners3@~build: Failed to exec build script
14 verbose stack Error: softwareforcleaners3@ build: `ionic-app-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Pankaj\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Pankaj\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid softwareforcleaners3@
16 verbose cwd C:\Users\Pankaj\Documents\GitHub\softwareforcleaners3
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Pankaj\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v4.4.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error softwareforcleaners3@ build: `ionic-app-scripts build`
22 error Exit status 1
23 error Failed at the softwareforcleaners3@ build script 'ionic-app-scripts build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the softwareforcleaners3 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs softwareforcleaners3
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls softwareforcleaners3
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
