### ISSUE TITLE
ionic package build android fails with "Error opening android-debug.apk"

### ISSUE THREAD

**Issue by luckylooke** [driftyco/ionic-app-scripts#876]
Building via `ionic build android` successfully build apk and can be installed on device and tested - OK

Building using ionic cloud `ionic package build android`, build FAILS with log: `Error opening android-debug.sdk`

Building for iOS via `ionic package build ios` is OK, build finish successfully

ionic version 2.2.2

I dont know what info to provide for solving this issue, maybe you could tell me what can I try... some debug procedure in steps or so... thanks

**Comment by danbucholtz** [comment]
@dwieeb,

Can you take a look at this one?

Thanks,
Dan

**Comment by arendjantetteroo** [comment]
I've got the same issue for more than a month now, Would be great to get some feedback on steps to take to debug this.

**Comment by luckylooke** [comment]
Seems to be same issue here: https://github.com/driftyco/ionic-cloud/issues/196

**Comment by luckylooke** [comment]
And also here: https://github.com/driftyco/ionic-cloud-angular/issues/26

**Comment by luckylooke** [comment]
Seems to be cordova-custom-config and ionic cloud build problem. But locally build is OK

**Comment by luckylooke** [comment]
As diskused with plugin author, plugin doesnt work because of hooks dependencies https://github.com/dpa99c/cordova-custom-config/issues/112#issuecomment-297147332
