### ISSUE TITLE
with 1.3.0 ngrx/effects stops working in AOT mode

### ISSUE THREAD

**Issue by metzc** [driftyco/ionic-app-scripts#880]
- downgrading to 1.2.5 solves the issue (works with AOT)
- building in dev mode solves the issue (works in 1.3.0)
- ngrx effects are not started/triggered/subscribed to
- i'm running angular 4.0.0 and ionic 3.0.0

So seemingly there are some changes to the way the ngc compiler is called that cause ngrx-effects to break. 

Any ideas?

**Comment by danbucholtz** [comment]
Duplicate: https://github.com/driftyco/ionic-app-scripts/issues/879

Can you please follow the steps I outlined in the last post so I can fix the issue?

Thanks,
Dan

**Comment by metzc** [comment]
thanks, 1.3.1 fixes the issues for me
