### ISSUE TITLE
TypeError: _angular_core.ɵmerge is not a function

### ISSUE THREAD

**Issue by tobiasmuecksch** [driftyco/ionic-app-scripts#881]
#### Short description of the problem:
Running `npm run ionic:build --prod` aborts with the following error:
`TypeError: _angular_core.ɵmerge is not a function`

#### What behavior are you expecting?
Well, it should build a --prod version without exiting with an error.

**Which @ionic/app-scripts version are you using?**
1.3.1

(After downgrading to 1.2.4, it fails with the same error too)

**Other information:**
This is my `package.json`:
```
{
  "name": "App_v2",
  "author": "Tobias Mücksch",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "config": {
    "ionic_sass": "./scripts/sass.config.js"
  },
  "dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@ionic-native/core": "3.4.2",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "2.0.1",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.2",
    "@ngrx/store": "^2.2.1",
    "@ngrx/store-devtools": "^3.2.4",
    "angular2-swing": "^0.11.0",
    "bourbon": "^4.2.7",
    "immutable": "^3.8.1",
    "ionic-angular": "3.0.1",
    "ionicons": "3.0.0",
    "lodash": "^4.17.3",
    "moment": "^2.18.1",
    "rxjs": "5.1.1",
    "sw-toolbox": "^3.4.0",
    "zone.js": "0.8.4"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.1",
    "typescript": "2.2.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "myApp: An Ionic project"
}

```

This is the full stack trace:

![bildschirmfoto 2017-04-07 um 08 19 01](https://cloud.githubusercontent.com/assets/1294854/24787971/6d059e66-1b6b-11e7-896d-1d7e66699c5e.png)

**Comment by tobiasmuecksch** [comment]
`ionic serve` throws and similar error.

![bildschirmfoto 2017-04-07 um 09 23 37](https://cloud.githubusercontent.com/assets/1294854/24789576/fb77f254-1b73-11e7-8a92-c049e54fb667.png)

**Comment by tobiasmuecksch** [comment]
If you ionic guys wish to have access to my repo in order to reproduce, please leave a bitbucket username, and I will grant you private access.

**Comment by tobiasmuecksch** [comment]
Some times the devil is in the details...
I finally fixed it. The problem was this entry in the package.json:

`"@angular/core": "^4.0.0",`

After removing the **^** it worked....

So the correct line should be:
`"@angular/core": "^4.0.0"`

**Comment by Cinemacloud** [comment]
Tobias.. those two lines look exactly the same to me ;)

**Comment by tobiasmuecksch** [comment]
@Cinemacloud thank you for the hint. I've updated that comment accordingly.
