### ISSUE TITLE
Error: The "tsconfig.json" file contains malformed JSON. 

### ISSUE THREAD

**Issue by abf7d** [driftyco/ionic-app-scripts#883]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

I am working on an Ionic [example](https://github.com/driftyco/ionic-conference-app) in Visual Studio.  When I try to build the app it fails validating the tsconfig.  I get the error: The "tsconfig.json" file contains malformed JSON.

#### What behavior are you expecting?

To me, my tsconfig.json looks fine.  Maybe I'm missing something. 

**Steps to reproduce:**
1. Go to Task Runner Explorer in Visual Studio 2017
2. Execute the build task for the app. (from package.json)
3.

```
insert any relevant code between the above and below backticks
tsconfig.json:

{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```
build.js:

function validateTsConfigSettings(tsConfigFileContents) {
       return new Promise(function(resolve, reject) {
		try {
            console.log(tsConfigFileContents);
			
	    var tsConfigJson = JSON.parse(tsConfigFileContents);
            
            var isValid = tsConfigJson.hasOwnProperty('compilerOptions') &&
                tsConfigJson.compilerOptions.hasOwnProperty('sourceMap') &&
				tsConfigJson.compilerOptions.sourceMap === true;
            
            if (!isValid) {
                var error = new errors_1.BuildError(['The "tsconfig.json" file must have compilerOptions.sourceMap set to true.',
                    'For more information please see the default Ionic project tsconfig.json file here:',
                    'https://github.com/driftyco/ionic2-app-base/blob/master/tsconfig.json'].join('\n'));
                error.isFatal = true;
                return reject(error);
			}
            
			resolve();
        }
        catch (e) {
            var error = new errors_1.BuildError('The "tsconfig.json" file contains malformed JSON.');
            error.isFatal = true;
            return reject(error);
        }
    });
}
**Which @ionic/app-scripts version are you using?**
ionic-app-scripts 1.2.4 

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

The stack trace when build the build fails:

[13:50:35]  ionic-app-script task: "build" 
[13:50:35]  Error: The "tsconfig.json" file contains malformed JSON. 
Error: The "tsconfig.json" file contains malformed JSON.
at BuildError.Error (native)
    at new BuildError (C:\Users\Dell\Documents\Visual Studio 2017\Projects\IonicTest\ConferenceApp\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at C:\Users\Dell\Documents\Visual Studio 2017\Projects\IonicTest\ConferenceApp\node_modules\@ionic\app-scripts\dist\build.js:110:25
    at validateTsConfigSettings (C:\Users\Dell\Documents\Visual Studio 2017\Projects\IonicTest\ConferenceApp\node_modules\@ionic\app-scripts\dist\build.js:72:9)
    at C:\Users\Dell\Documents\Visual Studio 2017\Projects\IonicTest\ConferenceApp\node_modules\@ionic\app-scripts\dist\build.js:43:16

I went to the offending line mentioned in the stack trace which was inside the node_modules\@ionic\app-scripts\dist\build.js file in the validateTsConfigSettings function.  I debugged and found that the build fails at:
var tsConfigJson = JSON.parse(tsConfigFileContents);
It looks like the JSON.parse function does not exist.  I commented that line out and the build runs, but it hangs.  I put the following line of code in its place and it fails:
JSON.parse("{a:true, b:false}");

**Comment by Rainson12** [comment]
Hey,
i got the same issue using visual studio 2017 however when creating a new  template for ionic 2 using 
"ionic start tutorial --template blank --v2 --ts --skip-npm" and copying over the tsconfig.ts into your project it will work. I assume its because of the formating of the file, originaly when opening it with nodepad.exe it is just a single line. When opening and "resaving" it with visual studio it seems to change to change the format of the file and that way it wont work anymore.

**Comment by danbucholtz** [comment]
How can I recreate the issue? I don't have access to visual studio.

Thanks,
Dan

**Comment by Rainson12** [comment]
Hey dan,
this can be recreated by saving the tsconfig file using utf8 with a bom (byte order mark). As soon as the file has a BOM it doesnt work anymore. Sadly VS Studio saves all files including a BOM by default. I attached you 2 diffrent files, the original one without a BOM and the VS saved one with a BOM

**Comment by abf7d** [comment]
This absolutely worked. I am very grateful. Thank you Rainson12 .
