### ISSUE TITLE
Encountered undefined provider! Usually this means you have a circular dependencies

### ISSUE THREAD

**Issue by awebdeveloper** [driftyco/ionic-app-scripts#885]
#### Short description of the problem:
I am migrating to ionic 3 and i get the above error. I followed the instructions in this link
https://github.com/driftyco/ionic/releases and now i get this error.

I ran `npm run ionic:build --prod` it gives the below error but `npm run ionic:build` works perfectly fine

**Which @ionic/app-scripts version are you using?**
1.3,0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

```
[00:10:06]  ngc started ...
[00:10:08]  ionic-app-script task: "build"
[00:10:08]  Error: Encountered undefined provider! Usually this means you have a circular dependencies (might be caused

            by using 'barrel' index.ts files.
Error: Encountered undefined provider! Usually this means you have a circular dependencies (might be caused by using 'b
arrel' index.ts files.
    at syntaxError (/Users/pr/workspace/ui/node_modules/@angular/compiler/bundles/compiler.umd.js:1513:3
4)
    at /Users/pr/workspace/ui/node_modules/@angular/compiler/bundles/compiler.umd.js:14398:40
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (/Users/pr/workspace/ui/node_modules/@angular/compi
ler/bundles/compiler.umd.js:14383:19)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/pr/workspace/ui/node_modules/@angular/compile
r/bundles/compiler.umd.js:14039:50)
    at addNgModule (/Users/pr/workspace/ui/node_modules/@angular/compiler/bundles/compiler.umd.js:22526:
58)
    at /Users/pr/workspace/ui/node_modules/@angular/compiler/bundles/compiler.umd.js:22537:14
    at Array.forEach (native)
    at _createNgModules (/Users/pr/workspace/ui/node_modules/@angular/compiler/bundles/compiler.umd.js:2
2536:26)
    at analyzeNgModules (/Users/pr/workspace/ui/node_modules/@angular/compiler/bundles/compiler.umd.js:2
2411:14)
```

**Comment by jrierab** [comment]
Same here. `ionic build android --prod --release` fails to build with above mentioned error.

Note, however, that a debug build with `ionic build android` works as expected.

Package.json dependencies are the same as in a new project (which builds ok in prod).

**Comment by ThorConzales** [comment]
Same here. Is there a way to get more detailed error message, for example in which file the compiler failed or which dependency it didn't find. It probably is related to some Angular service that is no longer out of the box included and have to be included manually in app.modules. But now the question is which one.

**Comment by Kr0n092** [comment]
Same problem here after upgrading to Ionic 3 as suggested at [https://github.com/driftyco/ionic/releases](url).

**Comment by awebdeveloper** [comment]
@ThorConzales where you able to find out the missing dependency

**Comment by ThorConzales** [comment]
@awebdeveloper I haven't tried to find out just yet, my project is pretty huge, hoping that someone else will stumble upon the solution.

**Comment by RomeoDenis** [comment]
I had the same issue, but on my case i removed "storage" from providers
@NgModule({
providers: [ storage, ... ] 
})
in app.module.ts
since @ionic/storage 2.x.x
we import instead of storage

**Comment by jrierab** [comment]
Yes! This was also my case. Many thanks @RomeoDenis !!

So, this was an issue on our code after all. Probably, this thread can be closed.

**Comment by seedgabo** [comment]
agree, remove Storage from providers resolve this issue for me

**Comment by Kr0n092** [comment]
Same, removed Storage from providers and it worked! Thanks guys

**Comment by chacariel** [comment]
thanks @RomeoDenis .. funciona!!!

**Comment by smubarak-ali** [comment]
@RomeDenise 
Right on points, thanks a lot!!

**Comment by mah14** [comment]
@RomeoDenis thanks, but it isn't work for me in ionic3.

**Comment by luizmendesalmeida** [comment]
@RomeoDenis you are the MVP. Thank you!

**Comment by Kshitiz294** [comment]
@RomeoDenis  I don't have storage included in my providers, still I am getting this issue. Can you Help?

**Comment by Grigss** [comment]
I don't have storage included in my providers either, I'm still getting this error as well.

**Comment by uttarwarsandesh33** [comment]
Uncaught Error: Encountered undefined provider! Usually this means you have a circular dependencies (might be caused by using 'barrel' index.ts files.
    at syntaxError (vendor.js:95008)
    at vendor.js:109288
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (vendor.js:109273)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (vendor.js:108689)
    at CompileMetadataResolver._getEntryComponentMetadata (vendor.js:109361)
    at vendor.js:108932
    at Array.map (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (vendor.js:108932)
    at JitCompiler._loadModules (vendor.js:120272)

**Comment by romain10009** [comment]
@RomeoDenis thank you man!

**Comment by alltej** [comment]
I am getting this error. It is kinda hard to figure what provider is having circular dependency. The error is already telling me it an undefined provider: `Error: Encountered undefined provider!...`

**Comment by MarcoDoell** [comment]
Still having this Issue after removing Storagemodule! does someone have an idea how to detect this circular dependency issue?

**Comment by rajureddy2010** [comment]
iam getting this issue only in component level service.

**Comment by Batur24** [comment]
after I move my provider at the end of the import, the problem is solved, not sure why it is

**Comment by jmmaguigad** [comment]
yay! Removing Storage fixed my issue when using `ionic cordova build --prod --release android`

**Comment by danroot** [comment]
This occurred to me when I switched from the "mock" item provider in the super template to a "real" item provider working against HTTP.  There were a number of issues, but in this case one was that the real item provider didn't have "defaultItem", but item-detail expected it.  The error was non-intuitive, but when I completely stopped ionic serve and re-ran I got a more useful error that pointed to this.  In my case I removed ||items.defaultItem from item-detail.ts and it worked.

**Comment by armin37** [comment]
in my case it was a rebuild problem
i changed rootPage in app.component file and my app and ran into this error
after stoping ionic and serving again the problem was gone
just to be sure i did the same thing again and exact same scenario happened

**Comment by stillatmylinux** [comment]
In my case, I had a method marked as private.  The error went away once I made it public.

**Comment by amitgandole** [comment]
I am still getting this error. my provider is like : 
providers: [
    ReduxStore,
    FileChooserOriginal,
    FilePathOriginal,
    ExtractFileDataService,
    AscendingSortPipe,
    SearchFilterPipe,
    TestOrderPipe,
    ZoneFilter,
    CSVToJSONService,
    XMLToJSONService,
    fetchEventLogs,
    FileOriginal,
    FileOpenerOriginal,
    FileTransferOriginal,
    FileTransferObject,
    TXTToJSONService,
    GroupbyattProvider,
    updateStatistics,
    consistencyCheckService,
    SpeechRecognitionOriginal,
    AppGlobals,
    AlertService,
    DatePickerOriginal,
    SerialOriginal,
    AppPreferencesOriginal,
    ApploggerService,
    AnimationService,
    MergePreviousDataService,
    BrowseFromMobileService,
    ParseSiteInfoService,
    IconAlert,
    NetworkOriginal,
    NetworkCheck,
    Storage,
    GetFileCreationDateService,
    GetDirectoryStructureService,
    AppService,
    GetPdfData,
    UploadJSON,
    VisualPlanning,
    POSTPDFFile
  ]

**Comment by JoanJosep33** [comment]
> I am still getting this error. my provider is like :
> providers: [
> ReduxStore,
> FileChooserOriginal,
> FilePathOriginal,
> ExtractFileDataService,
> AscendingSortPipe,
> SearchFilterPipe,
> TestOrderPipe,
> ZoneFilter,
> CSVToJSONService,
> XMLToJSONService,
> fetchEventLogs,
> FileOriginal,
> FileOpenerOriginal,
> FileTransferOriginal,
> FileTransferObject,
> TXTToJSONService,
> GroupbyattProvider,
> updateStatistics,
> consistencyCheckService,
> SpeechRecognitionOriginal,
> AppGlobals,
> AlertService,
> DatePickerOriginal,
> SerialOriginal,
> AppPreferencesOriginal,
> ApploggerService,
> AnimationService,
> MergePreviousDataService,
> BrowseFromMobileService,
> ParseSiteInfoService,
> IconAlert,
> NetworkOriginal,
> NetworkCheck,
> Storage,
> GetFileCreationDateService,
> GetDirectoryStructureService,
> AppService,
> GetPdfData,
> UploadJSON,
> VisualPlanning,
> POSTPDFFile
> ]

Remove your `Storage` entry and I supose it will work.

**Comment by davidalisson** [comment]
> Eu tive o mesmo problema, mas, no meu caso, removi o "armazenamento" dos provedores
> @NgModule ({
> provider: [storage, ...]
> })
> no app.module.ts
> desde que o @ ionic / storage 2.xx
> importamos o IonicStorageModule de armazenamento

Thanks!!!!

**Comment by davidalisson** [comment]
> I had the same issue, but on my case i removed "storage" from providers
> @NgModule({
> providers: [ storage, ... ]
> })
> in app.module.ts
> since @ionic/storage 2.x.x
> we import IonicStorageModule instead of storage

Thanks!!
