### ISSUE TITLE
Error: Unexpected token: name (DEFAULT_LOG_LEVEL)

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic-app-scripts#898]
#### Short description of the problem:
Today I upgraded to `ionic@beta7` and `app-scripts@1.3.2` and running commands like `npm run build --prod` or `ionic cordova:build android --prod` is breaking:

This is the error:

```
ionic-app-script task: "build" 
Error: Unexpected token: name (DEFAULT_LOG_LEVEL) in 
/abc/www/build/5.main.js at line 8805, col 6, pos 750274 
Error: Unexpected token: name (DEFAULT_LOG_LEVEL) in /abc/www/build/5.main.js at line 8805, col 6, pos 750274
    at BuildError.Error (native)
    at new BuildError (/abc/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at taskReject (/abc/node_modules/@ionic/app-scripts/dist/worker-process.js:36:22)
    at /abc/node_modules/@ionic/app-scripts/dist/worker-process.js:14:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

#### What behavior are you expecting?
It should work :+1: :smile: 

**Which @ionic/app-scripts version are you using?**
**1.3.1**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
```
ionic info

  Your system information:

    Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.8
    Node Version: v6.10.2
    Xcode version: Not installed

```

**Comment by danbucholtz** [comment]
Can you provide a repository that I can reproduce the issue?

Thanks,
Dan

**Comment by mburger81** [comment]
I think not before next week Tuesday :cry:

**Comment by mburger81** [comment]
@danbucholtz okay, I think the problem is also having external JS libs included in the app.

We are loading a JS lib where the first rows are this:

```
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (factory());
}(this, function () { 'use strict';

  // ERROR=0, WARN=1, LOG=2, DEBUG=3
  const LogLevel = {
      Error: 0,
      Warn: 1,
      Log: 2,
      Debug: 3
  };

  let DEFAULT_LOG_LEVEL = LogLevel.Debug;

  function setDefaultLogLevel(level) {
      DEFAULT_LOG_LEVEL = level;
  }
...
...
...
```
and we load the javascript file in this way from our component
`import WSPlayer from './assets/js/rtsp_player';`

I think this should be an error for ES2015 code like an older bug of mine: #877

**Comment by mburger81** [comment]
If I convert my JS lib with babel manually on https://babeljs.io/repl/ and paste the transpiled code instead of the js code, it works, I'm able run production build for our app.

**Comment by samastur** [comment]
I also get unexpected token error on production build.

Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.10.1
Xcode version: Xcode 8.3.1 Build version 8E1000a

**Comment by mburger81** [comment]
@samastur can you test if you can confert the file online? This was a workaround for me.

**Comment by samastur** [comment]
No, because the file in question actually is an angular service written in Typescript.

There are two other external dependencies which aren't (zxcvbn and Intercom's integration lib), but it is not complaining about them.

**Comment by samastur** [comment]
It's even worse as production build built with 1.3.1 (the only one that succeeds) doesn't start properly. The only error in console I can see is missing sourcemap file.

**Comment by mburger81** [comment]
Transpiling the code online resolves me the build error, but when we release a production build, (--prod) the library is not working and gives no error message, it is just not working.

**Comment by samastur** [comment]
I also noticed that zxcvbn functionality is not working on dev build either. Intercom is, but unlike zxcvbn it is not loaded locally (in node_modules), instead link to script is added directly to index.html.

Therefore I am reasonably certain that problem lies in handling external non-Typescript libraries.

**Comment by samastur** [comment]
I started a new v2 app and added zxcvbn and intercom to it. Worked fine with --prod setting so I was not able to create a test repo and have even less of an idea of what is wrong.

**Comment by danbucholtz** [comment]
App-scripts 1.3.4 should transpile 3rd party libs, etc for prod builds. It's too slow to do it for dev builds.

Please let me know if this issue persists.

Thanks,
Da

**Comment by mburger81** [comment]
Hi, as we wrote in our post. The problem persist on 1.3.4 for some libs.

**Comment by mburger81** [comment]
@danbucholtz & @samastur I created a github example where you can simulate this ISSUE and also another issue from ionic 
https://github.com/driftyco/ionic/issues/11184

What to do, do simulate this bug. Nothing magically, clone this repro (https://github.com/mburger81/ionic3-app-scripts-bug.git) install npm packages and try a production build spricpt


`npm install`
```
npm run build --prod
or
ionic cordova:build android --prod

```
At the end you will get this two errors, first for first build script and second error for second build script
```
[12:10:48]  uglifyjs started ... 
[12:10:48]  ionic-app-script task: "build" 
[12:10:48]  Error: Unexpected token: name (DEFAULT_LOG_LEVEL) in 
            /bugs/ionic3-app-scripts-bug/www/build/0.main.js at line 1027, col 6, pos 
            66404 
Error: Unexpected token: name (DEFAULT_LOG_LEVEL) in /bugs/ionic3-app-scripts-bug/www/build/0.main.js at line 1027, col 6, pos 66404
    at BuildError.Error (native)
    at new BuildError (/bugs/ionic3-app-scripts-bug/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at taskReject (/bugs/ionic3-app-scripts-bug/node_modules/@ionic/app-scripts/dist/worker-process.js:36:22)
    at /bugs/ionic3-app-scripts-bug/node_modules/@ionic/app-scripts/dist/worker-process.js:14:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

```
[12:17:59]  uglifyjs started ... 
{ Error: Unexpected token: name (DEFAULT_LOG_LEVEL) in /bugs/ionic3-app-scripts-bug/www/build/0.main.js at line 1027, col 6, pos 66404
    at BuildError.Error (native)
    at new BuildError (/bugs/ionic3-app-scripts-bug/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at taskReject (/bugs/ionic3-app-scripts-bug/node_modules/@ionic/app-scripts/dist/worker-process.js:36:22)
    at /bugs/ionic3-app-scripts-bug/node_modules/@ionic/app-scripts/dist/worker-process.js:14:13
    at process._tickCallback (internal/process/next_tick.js:109:7) hasBeenLogged: false, isFatal: false, name: 'Error' }
```

Don't forget If you play around with the html pages and get the error `Links of null`, it is the other issue :)

**Comment by danbucholtz** [comment]
@mburger81,

The reason your file is not being transpiled is because you are inserting a .js file into the `src` directory. We strongly suggest you use npm, or if you must include .js source in your `src` directory, make sure they're ES5.

The issue is uglify-js, our dependency, cannot handle all of ES2015.

This is a highly unusual edge case, so we're not going to make a change here. I _think_ you should just be able to change the extension from `.js` to `.ts` and it will likely work.

In general, if you're interacting with `.js`, we expect them to be in `node_modules`, not `src`.

Thanks,
Dan
