### ISSUE TITLE
add TSC build step when in DEV mode

### ISSUE THREAD

**Issue by shlomiassaf** [driftyco/ionic-app-scripts#9]
@brandyscarney Hi,

With the latest change supporting prod/dev modes the new dev mode does not work.

Looking the the [change](https://github.com/driftyco/ionic-app-scripts/blob/master/src/build.ts#L45-L51) I see that if `isProd` you use `ngc` to compile TS to JS.

If not `isProd` you just bundle.

Since `ngc` wraps `tsc` if we omit it we need to use `tsc` instead otherwise `bundle` will use rollup on nothings... no JS output from TS files.

The reason you might missed it might be since the `.tmp` directory was still in place from a previous run with `isProd` true.

It's also an issue/feature to add: delete `.tmp` before a run.

**Comment by adamdbradley** [comment]
Yup we'll get adding that in, just haven't gotten to it yet. Thanks
