### ISSUE TITLE
1.3.2 messed up sth for --prod (Uncaught Error: Cannot resolve all parameters for 'e'(?))

### ISSUE THREAD

**Issue by zarko-tg** [driftyco/ionic-app-scripts#900]
#### Short description of the problem:
A simple app build with "--prod" errors when launched on an Android device (white screen with cryptic error in Chrome the DevTools inspector)

#### What behavior are you expecting?
No such error / normal execution.

**Which @ionic/app-scripts version are you using?**
1.3.2

Not using --prod doesn't yield such error.

1.3.1 is just fine in any case.

![error](https://cloud.githubusercontent.com/assets/6142411/25023164/15e43bdc-2099-11e7-8dd7-4a48b5bb45e9.png)

System information:
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.2
Xcode version: Not installed

**Comment by themastersoda** [comment]
Can confirm. Building with 1.3.0 works just fine, 1.3.1 introduced errors that prevented from building, and with 1.3.2 build succeeds, however, same error occurs as stated in this report.

**Comment by danbucholtz** [comment]
It's weird, I never saw this error until a couple days ago. The Angular team isn't exactly sure what is causing it and their suggestions fixed it for our test apps but clearly not all apps. I'll release a new `nightly` soon that I'm hoping you can test.

Thanks,
Dan

**Comment by themastersoda** [comment]
Could it have something to do with Angular 4.0.2? Didn't see this issue with 4.0.0. Could be just the timing though.

**Comment by zarko-tg** [comment]
Yeah, forgot to say that my report was about app with exact dependency on Angular 4.0.0 and Ionic 3.0.1.
To repeat, there is no problem with app scripts 1.3.1

**Comment by danbucholtz** [comment]
Can you try

```
npm install @ionic/app-scripts@nightly
```

I reverted the code the angular team suggested we add.

Thanks,
Dan

**Comment by oxydeon** [comment]
it's work for me with nightly

**Comment by zarko-tg** [comment]
@danbucholtz Just tried with the nightly, it's all good.

**Comment by vkniazeu** [comment]
I started https://forum.ionicframework.com/t/uncaught-error-cannot-resolve-all-parameters-for-platformref-/86520 earlier today - couldn't find this issue as it was hard to narrow down the culprit.

This problem applies to browser as well.
Going from `"@ionic/app-scripts": "1.3.0"` to `"@ionic/app-scripts": "1.3.2"` results in a run-time error `Uncaught Error: Cannot resolve all parameters for 'e'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'e' is decorated with Injectable.`, where 'e' is 'PlatformRef_' if you disable obfuscation.

`ionic cordova build browser --prod' completes without errors or warnings; the error appears at run-time.

Reverting to '1.3.0' or using the @nightly build removes the problem.

**Comment by danbucholtz** [comment]
K, I'll publish a short-term fix for now. Sorry, this issue seems intermittent as 1.3.2 fixed it on my end. We're working with the angular team to identify where we cannot purge certain annotations that are increasing file size.

`1.3.3` will be out in 10 minutes.

Thanks,
Dan

**Comment by alex-okrushko** [comment]
Was the issue identified? I'm having the same error in my project (which is large) and trying to figure out the root cause.

**Comment by danbucholtz** [comment]
@alex-okrushko,

You can run the latest app-scripts `1.3.8`. That should fix it.

Thanks,
Dan
