### ISSUE TITLE
ionic serve shows --v2 for v3 upgrade

### ISSUE THREAD

**Issue by peterennis** [driftyco/ionic-app-scripts#901]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
ionic serve shows "--v2" but upgrade is to v3

#### What behavior are you expecting?

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

C:\ae\aedh>ionic info

Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

![capture055](https://cloud.githubusercontent.com/assets/140737/25031393/7c72b328-2081-11e7-9f8a-5f573dd49c18.png)

**Comment by danbucholtz** [comment]
This is by design for now.

Thanks,
Dan
