### ISSUE TITLE
webpack watcher not picking up js file changes

### ISSUE THREAD

**Issue by Nilos** [driftyco/ionic-app-scripts#908]
#### Short description of the problem:
I have some pure js files in my ionic app. Importing them works but any update to them does not trigger a reload / webpack update

#### What behavior are you expecting?
Webpack should rebuild on js changes

**Steps to reproduce:**
1. Clone https://github.com/Nilos/cutePuppyPics
2. Run ionic serve. See alert of "test2"
3. Change src/pages/home/test.js to a different alert
4. No recompile

**Which @ionic/app-scripts version are you using?**
1.3.3

**Comment by Nilos** [comment]
I was able to fix this by rolling my own watch.config which also includes js files. Not sure why ionic does not do this by default.

**Comment by danbucholtz** [comment]
@Nilos,

Glad you resolved it. It's something we could consider in the future. If you'd like to submit a well-tested PR, we'd probably accept it.

Thanks,
Dan

**Comment by mburger81** [comment]
@Nilos I like the feature
