### ISSUE TITLE
Build too rigid in general: example with --livereload option

### ISSUE THREAD

**Issue by jdat82** [driftyco/ionic-app-scripts#92]
#### Short description of the problem:

With default configuration after a fresh `ionic start` for instance, the following command will not work as expected: `ionic emulate ios -l`.
1. First, you will always bundle code in production mode.
2. Secondly, source code inside `src` will not be watched for changes, thus the livereload option being useless
#### What behavior are you expecting?

I'm inclined to think that `ionic run|emulate` should not imply dev or prod bundling. They should take what is given to them. They should not imply a build step neither. What if we want to redeploy several times without rebuilding web code ? What if we want to deploy in alternance dev code and production code ?

We may need more flexibility in order to mix high level ionic commands with any npm script in order to adapt to complex situations. For instance, like I explained in issue #91, separating the fact of launching a watcher and the fact of building could allow us to use tools like `concurrently` in order to start in parallel a watcher and an ionic command like `ionic serve`or `ionic run` or even a karma watcher.

**Steps to reproduce:**
1. ionic start --v2 demo 
2. ionic emulate ios -l

**Which @ionic/app-scripts version are you using?**

0.0.28

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
#91

https://github.com/driftyco/ionic-cli/issues/1465

**Comment by jthoms1** [comment]
This will be resolved with the next release of the CLI.

**Comment by jthoms1** [comment]
@jdat82 We released a more recent CLI that fixes these issues.  Please ensure to install 2.1.12.
We are still debating how to resolve the dev vs prod issues with emulate and run.  I know that cordova currently has a `--release` flag that can be passed for production ready testing.  I think we might end up going this direction.
