### ISSUE TITLE
Can't watch for changes of `src/index.html`

### ISSUE THREAD

**Issue by jdat82** [driftyco/ionic-app-scripts#93]
#### Short description of the problem:

When source code is watched, you can edit sass files, ts files, html templates but not index.html. It will not be detected by the watcher and thus not trigger a livereload event.

#### What behavior are you expecting?

Everything inside `src` should be editable and "livereloadable".

**Steps to reproduce:**
1. ionic serve
3. Edit index.html inside src folder

Tried to add a `watch.config.js` file inside my project referenced inside `package.json` by the config property `ionic_watch`, did not work:

_./package.json_

```json
"config":{
      "ionic_sass": "./config/sass.config.js",
      "ionic_watch": "./config/watch.config.js"
  },
```

_./config/watch.config.js_
```js
var buildUpdate = require('@ionic/app-scripts/dist/build').buildUpdate;
var templateUpdate = require('@ionic/app-scripts/dist/template').templateUpdate;
var copyUpdate = require('@ionic/app-scripts/dist/copy').copyUpdate;
var sassUpdate = require('@ionic/app-scripts/dist/sass').sassUpdate;

// https://www.npmjs.com/package/chokidar

module.exports = {

  watchers: [

    {
      paths: [
        '{{TMP}}/**/*.js'
      ],
      callback: buildUpdate
    },

    {
      paths: [
        '{{SRC}}/**/*.html'
      ],
      options: { ignored: /(index.html$)/ },
      callback: templateUpdate
    },

    {
      paths: [
        '{{SRC}}/**/*.scss'
      ],
      callback: sassUpdate
    },

    {
      paths: [
        '{{SRC}}/assets',
        **'{{SRC}}/index.html'**
      ],
      callback: copyUpdate
    }

  ]

};
```

**Which @ionic/app-scripts version are you using?**

0.0.28

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has been fixed in the latest beta release of app-scripts by [this commit](https://github.com/driftyco/ionic-app-scripts/commit/f4930f339f050fc4d09d8985639e98cbb3042d9e) and some changes that were done to the watch script.
