### ISSUE TITLE
Not emitting JS bundle - Webpack

### ISSUE THREAD

**Issue by michaelgeorgeattard** [driftyco/ionic-app-scripts#932]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

`ionic-app-scripts build`

Latest versions are not emitting JS bundle (no errors).
Debug shows the following warning 

`Error loading core compiler: 
xxx\node_modules\ionic-angular\compiler, Error: Cannot find module xxx\node_modules\ionic-angular\compiler'`

Ionic angular is version 2.0.0.

**Which @ionic/app-scripts version are you using?**

Bug introduced in 1.2.0 and is present in 1.3.5.

**Comment by danbucholtz** [comment]
Try `npm install @ionic/app-scripts@nightly`. I'll push a fix for this today. Sorry and thank you.

Thanks,
Dan

**Comment by michaelgeorgeattard** [comment]
Latest nightly still shows "error loading core compiler" warning, and does not emit JS bundle :-(

**Comment by michaelgeorgeattard** [comment]
Bug seems to be in `src/webpack.ts`:

`
const bundledFilesToWrite = context.fileCache.getAll().filter(file => {
    return dirname(file.path) === context.buildDir && (file.path.endsWith('.js') || file.path.endsWith('.js.map'));
});
`

dirname(file.path) = xxx\www\js 
context.buildDir =xxx\www

**Comment by danbucholtz** [comment]
This should be fixed in `1.3.6`. `npm install @ionic/app-scripts@latest`

Thanks,
Dan

**Comment by michaelgeorgeattard** [comment]
Not fixed, can you kindly reopen please?
