### ISSUE TITLE
Not emitting JS bundle - Webpack

### ISSUE THREAD

**Issue by michaelgeorgeattard** [driftyco/ionic-app-scripts#939]
Note: for support questions, please use one of these channels:

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

Short description of the problem:

ionic-app-scripts build

Latest versions are not emitting JS bundle (no errors).
Debug shows the following warning

Error loading core compiler: xxx\node_modules\ionic-angular\compiler, Error: Cannot find module xxx\node_modules\ionic-angular\compiler'

Ionic angular is version 2.0.0.

Which @ionic/app-scripts version are you using?

Bug introduced in 1.2.0 and is present in 1.3.6.

Bug seems to be in src/webpack.ts:

```
const bundledFilesToWrite = context.fileCache.getAll().filter(file => {
    return dirname(file.path) === context.buildDir && (file.path.endsWith('.js') || file.path.endsWith('.js.map'));
});
```

dirname(file.path) = xxx\www\js
context.buildDir =xxx\www

Thus files are not emitted.

**Comment by danbucholtz** [comment]
I cannot recreate this.

Can you please create a repository on github where I can recreate it?

Thanks,
Dan

**Comment by michaelgeorgeattard** [comment]
Issue has been fixed in https://github.com/driftyco/ionic-app-scripts/pull/938.

Can you please release a package including the merged commits?

**Comment by danbucholtz** [comment]
@michaelgeorgeattard,

Yes, I will do it today/tonight.

Thanks,
Dan

**Comment by danbucholtz** [comment]
This is fxied in 1.3.7.

Thanks,
Dan
