### ISSUE TITLE
Disabling manual tree shaking generates a smaller build

### ISSUE THREAD

**Issue by FdezRomero** [driftyco/ionic-app-scripts#940]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Disabling manual tree shaking generates **smaller** bundle chunks than having this option enabled (the default). I'm not sure if this is specific to our app (Savelist), if something is preventing the manual tree shaking or if the normal one just works better with our code. I think this is interesting enough to investigate:

PWA build size with lazy-loading and manual tree shaking:
- Enabled: 5.1 MB
- Disabled: 4.7 MB

Any help is greatly appreciated.

#### What behavior are you expecting?
The manual tree shaking to generate a smaller build than having it disabled.

**Steps to reproduce:**
1. Set `ionic_manual_treeshaking` to `true` in package.json.
2. Add custom NPM script in package.json: `"pwa": "ionic-app-scripts build --prod --generateSourceMap false"` (to exclude source maps size).
3. Build with `npm run pwa` and check the `www/build` folder size (CMD+I in macOS).
4. Set `ionic_manual_treeshaking` to `false` in package.json.
5. Build with `npm run pwa` and the `www/build` folder size is bigger (in our case).

**Which @ionic/app-scripts version are you using?**
1.3.6

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
```
npm (global):

    @ionic/cli-utils : 1.0.0-beta1
    cordova          : 6.5.0
    ionic            : 3.0.0-beta10

npm (local):

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-beta1
    @ionic/cli-plugin-ionic-angular : 1.0.0-beta1
    Ionic Framework                 : ionic-angular 3.1.0

System:

    Node       : v6.10.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Comment by danbucholtz** [comment]
I'll check it out, it seems odd. Thanks for letting me know!

Thanks,
Dan

**Comment by FdezRomero** [comment]
Thanks Dan! Let me know if I can be of any help or you need samples.

**Comment by rapropos** [comment]
Can you try to isolate the effect of lazy loading from that of treeshaking? In my experience, it's quite common for lazy loading to increase overall app binary size.

**Comment by FdezRomero** [comment]
@rapropos Sure, I understand but please note that I'm using lazy loading in both cases: with and without manual tree shaking. The comparison should be valid as all other variables are equal (ceteris paribus).

**Comment by danbucholtz** [comment]
This should be fixed in 1.3.7.

Thanks,
Dan

**Comment by FdezRomero** [comment]
Thanks @danbucholtz, it's at 4.6 MB now :)

**Comment by aabi0044** [comment]
i dont know what tree shaking is but i visit package.jason file there i got some thing true and i did it false then my problem is resolved .
Thanks,
Aabi
