### ISSUE TITLE
Watch script stops working when using custom rollup.config.js

### ISSUE THREAD

**Issue by Will-Tian** [driftyco/ionic-app-scripts#95]
#### Short description of the problem:
When using a custom rollup.config file, after running ionic serve, watch script stops at ' typescript compilation started ...'  

My custom rollup.config file:
```
var ngTemplate = require('../node_modules/@ionic/app-scripts/dist/plugins/ng-template').ngTemplate;
var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var globals = require('rollup-plugin-node-globals');
var builtins = require('rollup-plugin-node-builtins');
var json = require('rollup-plugin-json');

// https://github.com/rollup/rollup/wiki/JavaScript-API

var rollupConfig = {
  /**
   * entry: The bundle's starting point. This file will
   * be included, along with the minimum necessary code
   * from its dependencies
   */
  entry: './.tmp/app/main.dev.js',

  /**
   * sourceMap: If true, a separate sourcemap file will
   * be created.
   */
  sourceMap: true,

  /**
   * format: The format of the generated bundle
   */
  format: 'iife',

  /**
   * dest: the output filename for the bundle in the buildDir
   */
  dest: 'main.js',

  /**
   * plugins: Array of plugin objects, or a single plugin object.
   * See https://github.com/rollup/rollup/wiki/Plugins for more info.
   */
  plugins: [
    ngTemplate(),
    builtins(),
    commonjs({
      include: [
        'node_modules/ionic-native/dist/**',
        'node_modules/rxjs/**',
        'node_modules/localforage/**',
        'node_modules/immutable/dist/**'
      ],
      namedExports: {
        'node_modules/ionic-native/dist/index.js': ['Facebook'],
        'node_modules/immutable/dist/immutable.js': ["Iterable", "Seq", "Collection", "Map", "OrderedMap", "List", "Stack", "Set", "OrderedSet", "Record", "Range", "Repeat", "is", "fromJS"]
      }
    }),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    }),
    globals(),
    json()
  ]

};


if (process.env.IONIC_ENV == 'prod') {
  // production mode
  rollupConfig.entry = '.tmp/app/main.prod.js';
  rollupConfig.sourceMap = false;
}


module.exports = rollupConfig;
```

I am adding NPM Config
  "config": {
    "ionic_rollup": "./config/rollup.config.js"
  }

#### What behavior are you expecting?
Watch task should continue to work

**Steps to reproduce:**
1. add a custom rollup.config file
2. add NPM Config or Command-line Flags for the watch script
3. run ionic serve
4. make a change to a .ts file and save.

**Which @ionic/app-scripts version are you using?**
"latest"

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind trying adding `useStrict: false` to your `rollup.config` above the plugins entry? Also, could you share a link to a repo I could use to reproduce this. Thanks!

**Comment by adamdbradley** [comment]
Would you be able to try out the latest version and see if it fixes your problem? Thanks

**Comment by danbucholtz** [comment]
@Will-Tian, with the latest version you'll want to remove the first line of the file with `ngTemplate` as well as the entry in the plugins section for `ngTemplate`.  The entry point has changed to `src/app/main.dev.js` too.

Thanks,
Dan

**Comment by smkamranqadri** [comment]
in my case, i got...

Config file "/Volumes/data/securityapp/rollup.config.js" not found. Using defaults instead.

**Comment by agustinhaller** [comment]
Seems to me that something similar is happening when using custom rollup `sass.config.js`.

In my case I used custom `sass.config.js` to include bourbon sass library path to the `includePaths` array:
```
...
includePaths: [
    'node_modules/ionic-angular/themes',
    'node_modules/ionicons/dist/scss',
    'node_modules/bourbon/app/assets/stylesheets'
  ]
...
```

I noticed the solution works fine the first time I run `ionic serve`:
```
[20:35:10]  sass started ...
[20:35:13]  sass finished in 3.04 s
[20:35:13]  build dev finished in 24.39 s
[20:35:13]  watch ready in 24.66 s
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*
√ Running dev server:  http://localhost:8100
```

But then when I change some random scss file it throws:
```
ionic $ [20:38:21]  sass started ...
[20:38:22]  Sass Error: line: 26, column: 1
File to import not found or unreadable: _bourbon
Parent style sheet: /Users/agustinhaller/ion2-Test/src/app/app.scss

[20:38:22]  sass failed:  Sass compile error
```

It's weird. It seems that the second time it runs the sass task it misses the references to the `includePaths` defined in the custom `sass.config.js`.

Any idea what may be happening here?

From: https://forum.ionicframework.com/t/mixin-like-compass/54703/6

**Comment by agustinhaller** [comment]
`npm install @ionic/app-scripts@latest` fixed my issue

**Comment by jgw96** [comment]
@Will-Tian @smkamranqadri are you all still getting an issue with the latest ionic-app-scripts? v0.0.30?

**Comment by Will-Tian** [comment]
@jgw96 @danbucholtz  Hey, updating to the latest version seems to have fixed my issue. I've noticed some performance increases as well. Thanks for the hard work. Will continue to update should I run into any future bugs.

**Comment by danbucholtz** [comment]
@Will-Tian, w00t, glad to hear it!

Thanks,
Dan

**Comment by smkamranqadri** [comment]
@jgw96 what fix my problem was the path error of ngtemplate, it was absolute path.

also the latest version removed this so update your custom rollup config will fix it.
