### ISSUE TITLE
Error because `fileCache` is not defined

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic-app-scripts#952]
#### Short description of the problem:
If I use `generateContext` from your API and pass an argument example, `{isProd: true}`

I will get an error because `fileCache` is required example in https://github.com/driftyco/ionic-app-scripts/blob/73a744b2b8cc5dbd515264c253f6682b9fafa029/src/aot/aot-compiler.ts#L78

#### What behavior are you expecting?
No errors and don't need to workaround it like

```
const tempContext = generateContext();
tempContext.isProd = args.isProd;
const buildContext = generateContext(tempContext);
```

Issues
```
import { build, generateContext } from "@ionic/app-scripts";
const buildContext = generateContext({
	isProd: true
});

build(buildContext);
```
**Which @ionic/app-scripts version are you using?**
1.3.6

**Comment by danbucholtz** [comment]
Fixed.

Thanks,
Dan

**Comment by alan-agius4** [comment]
@danbucholtz how was this fixed? I dont see any code changes?

**Comment by danbucholtz** [comment]
I didn't push yet. I'll publish 1.3.7 today.

Thanks,
Dan

**Comment by alan-agius4** [comment]
Um okay, cause I did clone and linked this morning and the issue was still there.

Thanks
