### ISSUE TITLE
ion-select with action-sheet interface won't open with prod build

### ISSUE THREAD

**Issue by cocowalla** [driftyco/ionic-app-scripts#959]
#### Short description of the problem:
When doing a `--prod` build with a signed APK, `ion-select` components won't open when tapped if they use `interface="action-sheet"`. If I remove the interface attribute, it opens in the normal popup style. it also works fine in `--dev` builds

#### What behavior are you expecting?
The action sheet style interface to open as normal.

**Steps to reproduce:**
1. Create a project with an `ion-select` that uses `interface="action-sheet"`
2. Build with `ionic build android --release --prod`
3. Sign the APK
4. Run the app and tap the `ion-select` - the action sheet interface is not displayed

**Which @ionic/app-scripts version are you using?**
1.3.6

**Comment by danbucholtz** [comment]
Can you test `nightly`?

```
npm install @ionic/app-scripts@nightly
```

Hopefully that resolves the issue.

Thanks,
Dan

**Comment by cocowalla** [comment]
I just gave this a try, but get the same result.

**Comment by WangRongda** [comment]
+1.
And `interface="popover" `not work too with prod build

**Comment by cocowalla** [comment]
@WangRongda you mean in the page component?

**Comment by WangRongda** [comment]
@cocowalla 
Yes.

**Comment by danbucholtz** [comment]
This is fixed in 1.3.7.

Thanks,
Dan
