### ISSUE TITLE
--nolivereload not working

### ISSUE THREAD

**Issue by rashnk** [driftyco/ionic-app-scripts#962]
**Short description of the problem:**

I tried this, `ionic serve --nolivereload` but it does not seem to be working, it still detects changes and reloads the browser.

 
**What behavior are you expecting?**

when file change is detected, do not build and do not reload
 
**Steps to reproduce:**

1. run` ionic serve --nolivereload`
1. Make changes in some .ts or .html file

**Ionic Info**

Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v7.7.4
Xcode version: Not installed

**Comment by rashnk** [comment]
how to disable live reload when run ionic serve ? i hope someone in ionic team will look into this issue

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2288

**Comment by rashnk** [comment]
Please make a decision between you which repo is responsible for this, i'm attaching the screenshot here, check the red circle in the image
![no1](https://cloud.githubusercontent.com/assets/12730428/26087342/da240f76-3a0d-11e7-9257-e3d57fce49ed.PNG)
![no2](https://cloud.githubusercontent.com/assets/12730428/26087343/da2557a0-3a0d-11e7-9c0e-b8a6c14b881e.PNG)
![no3](https://cloud.githubusercontent.com/assets/12730428/26087344/da286aa8-3a0d-11e7-800d-7c2159ca8694.PNG)

**Comment by jguitar** [comment]
I'd like to reopen the issue. It doesn't work yet

**Comment by dhasilva** [comment]
It does not work here too.

**Ionic Info**

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.2

System:

    Node       : v7.10.0
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.2.0

**Comment by ufolux** [comment]
I think this is a ion-app-script issue and I create a pull request to resolve this problem.
see  [#1200fix --nolivereload flag not work bug](https://github.com/ionic-team/ionic-app-scripts/pull/1200)
