### ISSUE TITLE
Using rollup will not generate js for deeplinks pages

### ISSUE THREAD

**Issue by iron9light** [driftyco/ionic-app-scripts#965]
#### What behavior are you expecting?

bundler with rollup only generate main.js, but with webpack will generate main.js and n.main.js (n is number).
And the size of generated css file are different (rollup's is larger)

**Steps to reproduce:**
1. ionic-app-scripts build --prod --bundler rollup
2. ionic-app-scripts build --prod
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
1.3.7

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 ordova CLI: 6.5.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.1
Xcode version: Not installed

**Comment by danbucholtz** [comment]
Rollup doesn't support code splitting so there isn't anything we can do here.

Thanks,
Dan

**Comment by iron9light** [comment]
Got it.
You guys should mention it in the doc.
