### ISSUE TITLE
annoying issue : Uncaught (in promise): invalid link: TabsPage

### ISSUE THREAD

**Issue by rashnk** [driftyco/ionic-app-scripts#973]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

ionic serve loading old version
every time it shows the error Uncaught (in promise): invalid link: TabsPage, i have to stop serve and rerun ionic serve, this is really annoying

#### What behavior are you expecting?
Build the latest chnages in pages, do not load old vesion of page

**Steps to reproduce:**
1. create ionic 3 tab project
2. ionic serve
3.  sometime it shows this error when building changes

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

1.3.4

**Comment by rashnk** [comment]
I just upgraded app-script to 1.3.7 , checking now

**Comment by danbucholtz** [comment]
Please provide a set of actions to recreate this issue. I cannot recreate with the latest app-scripts.

Thanks,
Dan

**Comment by matomesc** [comment]
I had this issue with `ionic-app-scripts@1.3.4` and upgrading to `ionic-app-scripts@1.3.7` resolved it.

**Comment by jgfet** [comment]
Have issue intermittently too 
@ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.2.1
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b

**Comment by muhammadumerfarooq** [comment]
i am sharing my experience as in my case i had declared class like this

   

    @IonicPage()
    @Component({
    selector: 'page-login',
    templateUrl: 'login.html',
    })

    export class logininfo {
     name: string;
    }

    export class loginPage {
      // code
    }

as seen here the declared class is before the declaration of page class that's why it was saying invalid error, but after remiving the logininfo class the link was working
