### ISSUE TITLE
Execlude SASS Files?

### ISSUE THREAD

**Issue by dertuerke** [driftyco/ionic-app-scripts#979]
Hi, how i can exceclude sass file in the theme folder (ionic-angular) that i dont use????
The main.css after building the app are 150kb!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
