### ISSUE TITLE
Cannot import TypeScript files from `node_modules`

### ISSUE THREAD

**Issue by aszmyd** [driftyco/ionic-app-scripts#98]
#### Short description of the problem:
App build breaks when trying to import TypeScript source files from `node_modules`

#### What behavior are you expecting?
App build should just work and give ability to import source TS files from npm.

**Steps to reproduce:**
1. Import some TypeScript source file from npm
2. Run `ionic serve`

```
import { Foo } from 'example-ts-module/src/foo'
```

**Which @ionic/app-scripts version are you using?**
"latest"

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

The issue is that when we try to import such TS source file from npm, `tsc` compilator creates files structure under `.tmp/src/**` folder instead of `.tmp/**`. Because of that, rollup cannot localize entry point which (for dev) should be under `.tmp/app/main.dev.js`.

Here is basic ionic2 sidemenu app that breaks when using such scenario: https://github.com/aszmyd/ionic2-import-ts-from-node-modules
The import is made here: https://github.com/aszmyd/ionic2-import-ts-from-node-modules/blob/master/src/app/app.component.ts#L10 and without it everything works as expected.

Stacktrace of broken build:
```bash
[aszmyd@localhost ionic2-import-ts-from-node-modules]$ ionic serve

Running 'serve:before' npm script before serve
> ionic-hello-world@ watch /home/aszmyd/tmp/ionic2-import-ts-from-node-modules
> ionic-app-scripts watch
[12:04:01]  ionic-app-scripts 0.0.28
[12:04:01]  watch started ...
[12:04:01]  build dev started ...
[12:04:01]  clean started ...
[12:04:01]  clean finished in 6 ms
[12:04:01]  copy started ...
[12:04:01]  typescript compiler started ...
[12:04:01]  lint started ...
[12:04:01]  copy finished in 28 ms
[12:04:01]  tslint: /home/aszmyd/tmp/ionic2-import-ts-from-node-modules/src/app/app.component.ts[10, 10]: Unused import: 'Foo'


[12:04:01]  lint finished in 370 ms
[12:04:03]  typescript compiler ready in 1.83 s
[12:04:03]  bundle dev started ...
[12:04:03]  bundle dev failed:  Could not resolve entry (./.tmp/app/main.dev.js)
[12:04:03]  bundle dev failed:  Could not resolve entry (./.tmp/app/main.dev.js)

[12:04:03]  Error: Could not resolve entry (./.tmp/app/main.dev.js)
    at /home/aszmyd/tmp/ionic2-import-ts-from-node-modules/node_modules/rollup/dist/rollup.js:8635:28
    at process._tickCallback (node.js:369:9)
```

File structures looks like that:
![image](https://cloud.githubusercontent.com/assets/3050805/19109406/9554152a-8af5-11e6-99c7-4021fff54171.png)

**Comment by adamdbradley** [comment]
One thing that's currently in master, but hasn't been released yet is that the dev builds no longer use the `.tmp` directory, and instead uses a typescript rollup plugin. We'll do some more testing today but hope to release it soon, which hopefully solves your issues. cc @jgw96

**Comment by danbucholtz** [comment]
@aszmyd,

Why would you want to import a `TS` file from `node_modules`? I am struggling to see the use case? If it's a project written in `Typescript`, it should be distributed as a `.js` file with `.d.ts` type definitions.

Thanks,
Dan

**Comment by aszmyd** [comment]
@adamdbradley thanks. @danbucholtz maybe its not the right approach but we have kind of "core" source code used between may smaller projects and i want to include those sources and make use of them.

**Comment by jgw96** [comment]
@aszmyd would you mind trying this with the latest version of app-scripts? v0.0.29. You can update to them by just running `npm install` in your app. Thanks!

**Comment by danbucholtz** [comment]
@aszmyd,

Unless I am misunderstanding you, what you're doing is against the best practices in place. The `.ts` files in node_modules aren't in the build path, so they won't be compiled.

Are you sure they're not `.js` files?

Thanks,
Dan

**Comment by aszmyd** [comment]
@jgw96 i've installed `0.0.30` and it works! thanks. @danbucholtz also thanks, i'll try to improve our approach as You've suggested.
