### ISSUE TITLE
Build fails due to errors in node_modules/@types/lodash-es/index.d.ts

### ISSUE THREAD

**Issue by grapemix** [driftyco/ionic-app-scripts#981]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Unable to run serve. This problem is almost identical to #700, except the problem is because of lodash-es instead of lodash. The solution of #700 is not working. Running `npm install @types/lodash-es@ts2.0 --save-dev --save-exact` still yield the same problem.

#### What behavior are you expecting?
Able to run serve. We tried to replace "@types/lodash-es" to "@types", but still not working. We also tried to remove "@types/lodash-es", typescript and typings, and still not working.

**Steps to reproduce:**
1. ionic run serve
2.
3.

```
insert any relevant code between the above and below backticks
```
Part of the package.json
```
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic-native/camera": "^3.7.0",
    "@ionic-native/core": "^3.7.0",
    "@ionic-native/deeplinks": "^3.7.0",
    "@ionic-native/device": "^3.7.0",
    "@ionic-native/file": "^3.7.0",
    "@ionic-native/geolocation": "^3.7.0",
    "@ionic-native/google-maps": "^3.7.0",
    "@ionic-native/push": "^3.7.0",
    "@ionic-native/social-sharing": "^3.7.0",
    "@ionic-native/splash-screen": "^3.7.0",
    "@ionic-native/status-bar": "^3.7.0",
    "@ionic-native/transfer": "^3.7.0",
    "cordova": "^6.2.0",
    "ionic-angular": "2.2.0",
    "ionicons": "^3.0.0",
    "lodash-es": "^4.17.4",
    "rxjs": "5.0.1",
    "sw-toolbox": "^3.4.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^1.1.4",
    "@types/lodash-es": "4.14.2",
    "install": "0.10.1",
    "npm": "4.5.0",
    "rollup-plugin-commonjs": "^7.0.0",
    "rollup-plugin-replace": "^1.1.1",
    "typescript": "2.0.9",
    "typings": "^1.4.0"
  },

```
**Which @ionic/app-scripts version are you using?**
We have tried 1.2.4, 1.3.2, 1.3.7

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

> ionic-app-scripts build

ESC[2m[12:22:39]ESC[22mESC[36m  ionic-app-scripts 1.3.7 ESC[39m
ESC[2m[12:22:39]ESC[22m  build dev started ESC[2m...ESC[22m 
ESC[2m[12:22:39]ESC[22m  clean started ESC[2m...ESC[22m 
ESC[2m[12:22:39]ESC[22m  clean finished ESC[2min 1 msESC[22m 
ESC[2m[12:22:39]ESC[22m  copy started ESC[2m...ESC[22m 
ESC[2m[12:22:39]ESC[22m  transpile started ESC[2m...ESC[22m 
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8446 ESC[39m
            ',' expected. 
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8449 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8449 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8452 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8452 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8452 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8452 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8454 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8454 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8455 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8455 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8456 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8457 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8457 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8460 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8460 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8460 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8460 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8460 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8460 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8460 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8466 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8466 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8466 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8466 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8467 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8468 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8468 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8473 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8473 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8474 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8474 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8474 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8474 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8475 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8476 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8476 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8493 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8493 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8493 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8493 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8493 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8499 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8500 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8500 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8505 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8505 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8506 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8507 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8507 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8507 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8508 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8519 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8519 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8519 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8519 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8519 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8522 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8522 ESC[39m
ESC[31m[12:25:09]  typescript: node_modules/@types/lodash/index.d.ts, line: 8522 ESC[39m

ESC[2m    L8446:  ESC[22mpartition(^MESC[41m ESC[49m
ESC[2m    L8447:  ESC[22m    callback: ListIterator<T, boolean>): LoDashImplicitArrayWrapper<T[]>;

            ']' expected. 

ESC[2m    L8449:  ESC[22m * @sESC[41meESC[49me _.partition

            ';' expected. 

ESC[2m    L8449:  ESC[22m * @seESC[41meESC[49m _.partition

            ',' expected. 

ESC[2m    L8451:  ESC[22mpartition<W>(
ESC[2m    L8452:  ESC[22m    whereValue: WESC[41m)ESC[49m: LoDashImplicitArrayWrapper<T[]>;

            '(' expected. 

ESC[2m    L8451:  ESC[22mpartition<W>(
.
.
.
.
.
BTW, does anyone any how to turn off the stdout/stderr color from ionic-cli?

**Comment by arendjantetteroo** [comment]
Update to ionic 3 which has angular 4 based on typescript 2.2 might fix the problem?

**Comment by grapemix** [comment]
We will update to ionic 3 as the last solution. We heard lots of stuff broke when updating to ionic 3. We ran into this build problem because we want to try out ionic native plugin 3. BTW, the google map in the ionic native is still broken. It is pretty common to fix one bug which led to another bug. And we are trying to avoid that cycle if possible. Anyway, thanks for your advice.

**Comment by arendjantetteroo** [comment]
I've avoided the Lazy load stuff, and then a upgrade was pretty easy. But can relate to your hesitation.

**Comment by rapropos** [comment]
I don't think you would need to upgrade anything more than TypeScript itself (to >=2.1) to resolve this.

**Comment by grapemix** [comment]
After deciding to give a try on upgrading to ionic3, we spend less than 3 min for the upgrade excluding the downloading and compiling time. Good job, ionic team. Now we can focus on fixing the bug from ionic-native3 + google map plug in. Thanks.
