### ISSUE TITLE
How do ionic-app-scripts use   [chunkhash]?

### ISSUE THREAD

**Issue by 791060555** [driftyco/ionic-app-scripts#986]
How do ionic-app-scripts use   [chunkhash]?
css and js  Cache

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
