### ISSUE TITLE
ionic cordova build android error

### ISSUE THREAD

**Issue by djtrav** [driftyco/ionic-app-scripts#997]
ionic cordova build android

Running app-scripts build: --iscordovaserve --externalIpRequired --nobrowser

[10:40:57]  build dev started ...
[10:40:57]  clean started ...
[10:40:57]  clean finished in 4 ms
[10:40:57]  copy started ...
[10:40:57]  transpile started ...
[10:41:04]  transpile finished in 6.54 s
[10:41:04]  preprocess started ...
[10:41:04]  deeplinks started ...
[10:41:04]  deeplinks finished in 215 ms
[10:41:04]  preprocess finished in 227 ms
[10:41:04]  webpack started ...
[10:41:05]  copy finished in 7.88 s
[10:42:24]  webpack finished in 80.43 s
[10:42:24]  sass started ...
WARNING: First value in `$grid-breakpoints` must start at 0, but starts at 320px.
Backtrace:
        node_modules/ionic-angular/themes/ionic.mixins.scss:67, in mixin `assert-starts-at-zero`
        node_modules/ionic-angular/components/grid/grid.scss:62

[10:42:27]  sass finished in 2.45 s
[10:42:27]  postprocess started ...
[10:42:27]  postprocess finished in 323 ms
[10:42:27]  lint started ...
[10:42:27]  build dev finished in 90.14 s
> cordova build android
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova build android (exit code 1):

        ANDROID_HOME=/Users/Library/Android/sdk
        JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home
        Error: spawn EACCES

Ionic info:
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 2.2.0

System:

    Node       : v6.9.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.0
    ios-sim    : 5.0.4

**Comment by juanesrios** [comment]
Hello, 

What was the solution?

**Comment by djtrav** [comment]
for quick solution, i get back to an older versions.

ionic info:
global packages:


    @ionic/cli-utils : 1.1.1
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.1.1

local packages:

    @ionic/app-scripts              : 1.1.4
    @ionic/cli-plugin-cordova       : 1.1.1
    @ionic/cli-plugin-ionic-angular : 1.1.1
    Ionic Framework                 : ionic-angular 2.2.0

System:

    Node       : v6.9.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.0
    ios-sim    : 5.0.4

**Comment by thorizer** [comment]
@djtrav this should not be closed. downgrading is not a real fix. I'm encountering the same issue.

**Comment by Naitore** [comment]
I am experiencing the same issue. Did anyone get the solution?

**Comment by piyanatn** [comment]
I am got the same issue

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.1
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.1 Build version 8E1000a 
    ios-deploy : 1.9.1 
    ios-sim    : not installed
    npm        : 5.2.0

**Comment by hamzox** [comment]
Downgrading is not a valid answer. I am facing the same issue when upgrading to new ionic version.

**Comment by karansharma27** [comment]
Did you find any solution to it? I am facing the same issue

**Comment by hamzox** [comment]
No. I end up downgrading the ionic version.

**Comment by yizhak0342** [comment]
so what i can do to solve this problem?

**Comment by jayzzz00** [comment]
hamzox is right i am also facing same issue to new ionic version

**Comment by drquochoai** [comment]
any solution please?!

**Comment by hamzox** [comment]
Downgrade cordova to 6 if you are using higher version. 
Might help you.

**Comment by cesarmarinhorj** [comment]
yes | sdkmanager --licenses
