### ISSUE TITLE
Can't get custom watch config to run

### ISSUE THREAD

**Issue by AlexandruCiobanu** [driftyco/ionic-app-scripts#998]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I created a custom watch.config.js just like the default config , added it in package.json in config as ionic-watch when running ionic serve for example the config file is not loaded. Other configs do get loaed. For example I customized the copy.config and it worked beautifully. Even running with the --watch flag I could not get it to load that config

#### What behavior are you expecting?
I would expect for the config to be picked up. Maybe I am doing something wrong?

**Steps to reproduce:**
1. Create a custom watch.config file. Eventually prepend a console log to see it in the console
2. Alter package.json and add ionic_watch in config
3. Run ionic serve

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by AlexandruCiobanu** [comment]
Seems to work fine now. I did a reinstall and apparently that helped

**Comment by westphalen** [comment]
How did you fix this exactly? My `ionic_watch` config is not being picked up either.

**Comment by Juanpam** [comment]
@AlexandruCiobanu What do you mean by reinstall? I'm also having this problem.
